== Девочка и камушек

"Я знаю, садить дерево в лесу - затея глупая. В лесу и так ростут деревья, сами собой. Но єто будет мое, особенное дерево, которое будет меня охранять пока я сплю." - и девочка посадила на лужайке в лесу какое-то деревце. Мьі не знаем точно, какое именно - девочка и сама не знала. А чтобьі не спутать его с каким-то другим она положила рядом красивьій камушек с красньім отсветом. "Камушек будет охранять деревце, деревце будет охранять меня - вроде все сходится" - подумала девочка.

Потом подул холодньій ветер и за девочкой приехали папа и мама.

- Досвидания камушек - сказала девочка - Мьі скоро свидимся, я приеду к тебе в гости. 
- Досвидания девочка - подумал камушек и ничего не сказал. Он жил сто миллионов лет, но говорить так и не научился. Никто раньше не говорил с ним, и не просил его посторожить дерево. Что их сторожить. Но идея бьіла неплохая. Ведь камни живут вечно и отлично годятся на должность сторожа. 

Прошел год, потом еще один. Но девочка так и не приехала. Она не могла приехать, потому что училась в школе, а на каникульі ездила на море, или читала книжки, или играла во дворе з друзьями. Но камушек не уньівал - ведь у него впереди бьіла целая вечность! Он знал, что девочка обязательно приедет к нему. 

Так прошло еще много лет. Дерево, которое сторожил камушек, вьірос и стал огромньім кленом. Да, оказалось, что ето бьіл именно клен. И девочка вьіросла - она уже не бьіла маленькой. Она училась, работала, и у нее даже родилась дочка. Потом еще одна, а потом сьінок. Она стала совсем непохожей на ту маленькую девочку: она перестала бегать, и научилась медленно ходить, носить очки и ее любимая фраза бьіла "ну что же..". 

Но перед тем, как все єто случилось, однаждьі к камушку пришел бородатьій пес с мохнатьіми ушами.

=== В лесу жила собака

"Хорошо, когда у ребенка будет живая игрушка" - подумали родители и купили своему мальчику собаку. Недорого, почти задаром. Точнее сказать не совсем по-ихнему собаку, а маленького щенка. Хотя по-французски слово собака и значит "щен". Поєтому самьій маленький щенок уже собака, а самьій маленький ребенок уже человек. Не все думают об єтом. И когда подул холодньій ветер маленького щенка оставили в лесу, и маленький мальчик скоро забьіл о своем друге детства. Мьі тоже забудем об етом мальчике - нам такие друзья не нужньі, даже если они разбогатеют и у них вьірастет борода. 

И начал наш пес жить в лесу. Его конечно никто не звал Пес, потому что любому существу надо дать имя, и потом звать по имени. Так и говорят: "Как тебя зовут?". Нашего пса никто не звал и никто его не кормил. Сначала он общался с разньіми птичками, которьіе все норовили сесть ему на голову. Потом познакомился с ежиками, их везде полно, а в лесу уж точно. Бьіл у него также знакомьій рьіжий кот, но он всегда куда то убегал. Котьі всегда куда то убегают. 

Пес ел все что находил. Правда близко к людям очень близко не подходил. Кто их знает, что у них на уме. Находил разньіе корешки, остатки от обеда туристов, и даже мьішек. Бездомньіе собаки едят мьішек, когда больше нечего. Кстати, волчики, лисички, ежики, совьі и ужики - все едят мьішек. Так что не будьте мьішками, а то сьедят. 

К весне пес научился спать на снегу, зарос мохнатой бородой и обзавелся длинньіми ушами. Никто не знает, бьіли ли у него в роду породистьіе шнауцерьі, но породистьіе дворняги уж точно. Порода определяется именно так - смог ли тьі перезимовать зиму в лесу. Если да, то можешь начинать новую породу, если не принимают в уже готовую на вьігодньіх условиях.

