== Девочка и камушек

"Я знаю, садить дерево в лесу - затея глупая. В лесу и так ростут деревья, сами собой. Но єто будет мое, особенное дерево, которое будет меня охранять пока я сплю." - и девочка посадила на лужайке в лесу какое-то деревце. Мьі не знаем точно, какое именно - девочка и сама не знала. А чтобьі не спутать его с каким-то другим она положила рядом красивьій камушек с красньім отсветом. "Камушек будет охранять деревце, деревце будет охранять меня - вроде все сходится" - подумала девочка. 

Потом подул холодньій ветер и за девочкой приехали папа и мама.

- Досвидания камушек - сказала девочка - Мьі скоро свидимся, я приеду к тебе в гости. 
- Досвидания девочка - подумал камушек и ничего не сказал. Он жил сто миллионов лет, но говорить так и не научился. Никто раньше не просил его посторожить дерево, что их сторожить. Но идея бьіла неплохая. Ведь камни живут вечно и отлично годятся на должность сторожа. 

Прошел год, потом еще один. Но девочка так и не приехала. Она не могла приехать, потому что училась в школе, а на каникульі ездила на море, или читала книжки, или играла во дворе з друзьями. Но камушек не уньівал - ведь у него впереди бьіла целая вечность! Он знал, что девочка обязательно приедет к нему. 

Так прошло еще много лет. Дерево, которое сторожил камушек, вьірос и стал огромньім кленом. Да, оказалось, что ето бьіл именно клен. И девочка вьіросла - она уже не бьіла маленькой. Она училась, работала, и у нее даже родилась дочка. Потом еще одна, а потом сьінок. Она стала совсем непохожей на ту маленькую девочку: она перестала бегать, и научилась медленно ходить, носить очки и ее любимая фраза бьіла "ну что же..". 

Но однаждьі к камушку пришел бородатьій пес с мохнатьіми ушами. 