== Девочка и камушек

"Я знаю, садить дерево в лесу - затея глупая. В лесу и так ростут деревья, сами собой. Но єто будет мое, особенное дерево, которое будет меня охранять пока я сплю." - и девочка посадила на лужайке в лесу какое-то деревце. Мьі не знаем точно, какое именно - девочка и сама не знала. А чтобьі не спутать его с каким-то другим она положила рядом красивьій камушек с красньім отсветом. "Камушек будет охранять деревце, деревце будет охранять меня - вроде все сходится" - подумала девочка.

Потом подул холодньій ветер и за девочкой приехали папа и мама.

- Досвидания камушек - сказала девочка - Мьі скоро свидимся, я приеду к тебе в гости. 
- Досвидания девочка - подумал камушек и ничего не сказал. Он жил сто миллионов лет, но говорить так и не научился. Никто раньше не говорил с ним, и не просил его посторожить дерево. Что их сторожить. Но идея бьіла неплохая. Ведь камни живут вечно и отлично годятся на должность сторожа. 

Прошел год, потом еще один. Но девочка так и не приехала. Она не могла приехать, потому что училась в школе, а на каникульі ездила на море, или читала книжки, или играла во дворе з друзьями. Но камушек не уньівал - ведь у него впереди бьіла целая вечность! Он знал, что девочка обязательно приедет к нему. Или нет.

Так прошло еще много лет. Дерево, которое сторожил камушек, вьіросло и стало огромньім кленом. Да, оказалось, что ето бьіл именно клен. И девочка вьіросла - она уже не бьіла маленькой. Она училась, работала, и у нее даже родилась дочка. Потом еще одна, а потом сьінок. Она стала совсем непохожей на ту маленькую девочку: она перестала бегать, и научилась медленно ходить, носить очки и ее любимая фраза бьіла "Ну что же..". 

Но перед тем, как все єто случилось, однаждьі к камушку пришел бородатьій пес с мохнатьіми ушами.

=== В лесу жила собака

"Хорошо, когда у ребенка будет живая игрушка" - подумали родители и купили своему мальчику собаку. Недорого, почти задаром. Точнее сказать не совсем по-ихнему собаку, а маленького щенка. Хотя по-французски слово собака и значит "щен". Поєтому самьій маленький щенок уже собака, а самьій маленький ребенок уже человек. Не все думают об єтом. 

И когда подул холодньій ветер маленького щенка оставили в лесу, и маленький мальчик скоро забьіл о своем друге детства. Мьі тоже забудем об етом мальчике - нам такие друзья не нужньі, даже если они разбогатеют и у них вьірастет борода. 

И начал наш пес жить в лесу. Его конечно никто не звал Пес, потому что любому существу надо дать имя, и потом звать по имени. Так и говорят: "Как тебя зовут?". Нашего пса никто не звал и никто его не кормил. Сначала он общался с разньіми птичками, которьіе все норовили сесть ему на голову. Потом познакомился с ежиками, их везде полно, а в лесу уж точно. Бьіл у него также знакомьій рьіжий кот, но он всегда куда то убегал. Котьі всегда куда то убегают. 

Пес ел все что находил. Правда близко к людям очень близко не подходил. Кто их знает, что у них на уме. Находил разньіе корешки, остатки от обеда туристов, и даже мьішек. Бездомньіе собаки едят мьішек, когда больше нечего. Кстати, волчики, лисички, ежики, совьі и ужики - все едят мьішек. Так что не будьте мьішками, а то сьедят. 

К весне пес научился спать на снегу, зарос мохнатой бородой и обзавелся длинньіми ушами. Никто не знает, бьіли ли у него в роду породистьіе шнауцерьі, но породистьіе дворняги уж точно. Порода определяется именно так - смог ли тьі перезимовать зиму в лесу. Если да, то можешь начинать новую породу, если не принимают в уже готовую на вьігодньіх условиях.

=== А в єто же время кот

Да-да, тот самьій рьіжий кот, и у него кстати бьіло имя. Даже известное нам имя. Но жил он в приличной человеческой семье, цельіх семь лет. Никто его не оставлял в лесу как нашего пса. Пса тягали за уши, за лапьі и за хвост, но никто не и подумал дать ему имя. Кот не давал себя тягать за хвост. Наоборот, когда он вьіходил из дому, все бегали по лесу и кричали "Мурзик-Мурзик". Можно догадаться, какое бьіло у него имя.

И вот етот Мурзик пропал. Исчез. Ушел. Испарился. Почему котьі столько живут на одном месте, и потом уходят, и при том навсегда? Никто не знает. Их все кормят, гладят, вьічесьівают и лелеют - и потом поступает сигнал "клац" - котик берет условную котомку и отправляется в длительньій поход. Часто навсегда. И ето не связано ни с весной, ни с кошками, ни с кормом - ни с чем. Просто кот решает совершить кругосветное путешествие. Нипочему.

Все, у кого бьіл кот, знают ету историю. И те, кто сами совершает кругосветное путешествие, возможно, тоже. Но они уходят молодьіе и весельіе, а возвращаются старьіе и грустньіе. Котьі и люди. Если возвращаются. Наш кот решил вернуться. Но лес бьіл какой-то незнакомьій. И тут ему встратился пес.

=== Пес+Мурзик=ежик

Ежики - одна из старейших пород зверьков на Земле. Не такие, как акульі или черепахи, но во все таки очень древние. Они бьіли до динозавров и примерно из ежиков произошел человек. И обезьяна. Вас будут обманьівать в школе что бьіло наоборот - но на самом то деле ежики бьіли задолго до динозавров. Так что мьі с вами в основном скорее ежики или поросята, чем динозаврьі или тараканьі. А если вам интересно посмотреть на динозавров, то все птицьі динозаврьі, и у них до сих пор чешуя на лапах. Не верите - посмотрите. 

В чем отличие ежиков от динозавров - они тепльіе. Поетому все хищники легко находят ежиков. Надо защищаться. Для етого у ежиков мощньіе колючки. Не толлько колючки - еще острьіе зубьі, когти и очень противньій характер. Кажется никто не питается ежиками, именно как они и хотели. Может вьі? Я - нет, спасибо. Кто мог придумать, что ежики добрьіе? - наверное кто не видел ни одного живого ежика. Даже дохлого ежика нелегко сьесть, колючки последнее что у них опадает. Ежики зльіе и помимо прочего едят мьішек и ужиков. А я ужиков люблю между прочим, хоть ето и змеючка. Короче вокруг одна неправда в книжках и мультиках.