[dedication]
Подяки за ранішні редакції Програмування на Scala
-------------------------------------------------

[quote,Ken Egervari,Chief Software Architect]
Програмування на Scala є, можливо, одною з кращих книжок з програмування, що я будь-коли читав. Мені подобається стиль написання, краткість та глибина викладення. Книжка, здається, відповідає на кожне запитання, як тілько воно спадає мені на думку - вона завжди на крок попереду мене. Автори не тільки надають деякий код та викладають речі як належне. Вони дають вам саму суть, так що ви дійсно розумієте що відбувається. Мені це дійсно подобається.

[quote,Larry Morroni,власник Morroni Technologies Inc.]
Програмування на Scala написано ясно, глибоко, та їй легко слідувати. Вона має чудові приклади та сповнена чудовими підказками. Вона дозволила нашій організації опанувати мову Scala швидко та ефективно. Ця книжка чудова для кожного програміста, хто намагається налаштувати свою голову на гнучкість та елегантність мови Scala.

[quote,Matthew Todd]
Книжка Програмування на Scala служить як чудовий туторіал по мові Scala. Просування по книзі іде гладко, де кожна глава будується на концепціях та прикладах, описаних в попередніх главах. Книга турбується про глибоке пояснення конструкцій мови, часто провадячи приклади того, як мова відрізняється від Java. Так само, як і головна мова, також є деяке покриття бібліотек, як контейнери та актори. Я знайшов книгу простою до проробки, і це, можливо, одна з кращих написаних технічних книжок, що я читав останні часом. Я справді можу рекомендувати цю книжку любому програмісту, що бажає знайти більше щодо мови Scala.

[quote,Christos KK Loverdos,Software Consultant & Researcher]
Я здивований зусиллями, здісненими авторами Програмування на Scala. Ця книга є неоціненним керівництвом до того, що я називаю платформою Scala: рушій до кращого кодування, постійне натхнення до розробки та реалізації маштабованого програмного забезпечення. Якби я тільки мав Scala в її сучасному зрілому стані, та цю книжку в далекому 2003му році, коли я спів-розробляв та реалізував частини інфраструктури порталу Олімпійськіх Ігор 2004 в Афінах! Всім читачам: не важливо, який ваш програмістській бекграунд, я відчуваю ви знайдете програмування на Scala вивільняючим, та ця книга буде вірним другом в цій подорожі.

[quote,Brian Clapper,президент ArdenTex, Inc.]
Програмування на Scala є довершеним глибинним вступом до Scala,та це також чудове посилання. Я хочу сказати, що вона займає видатне місце на моїй книжній полиці, і крім цього я все ще ношу її з собою майже будь-де, куди я іду.

[quote,Howard Lovatt]
Чудова книга, гарно написана з осмисленими прикладами. Я можу рекомендувати її як для досвідчених програмістів, так і для початківців.

[quote,Dr. Ervin Varga,CEO/засновник EXPRO I.T. & консультант]
Книга Програмування на Scala не тільки про те, як, але, більш важливо, чому слід розробляти програми на цій новій мові програмування. Прагматичний підхід в введені до потужності комбінування об'єктно-орієнтовного та функціонального програмування, залишає читача без жодних сумнівів, чим насправді є Scala.

[quote,Jeff Heon,Programmer Analyst]
Це чудове введення до функціонального програмування для ОО програмістів. Навчання щодо ФП було моєю головною ціллю, але я також познайомився з деякими милими сюрпризами Scala, як кейс класи та порівняння шаблонів. Scala є інтригуючою мовою, та ця книжка гарно розмовідає про це. Завжди є гарна лінія, вздовж якої треба іти в книжці вступу до мови, між надання дуже багато, та нестачею достатньої інформації. Я знайшов, що Програмування на Scala досягла ідеального балансу.

[quote,Dianne Marsh,засновник/консультант SRT Solutions]
Я придбав ранішню електронну версію книжки Програмування на Scala від Odersky, Spoon та Venners, та безпосередньо став фанатом. На додаток до факту, що вона містить найбільш всеосяжну інформацію щодо мови, існує декілька ключових особливостей електронного формату, що вразили мене. Я ніколи не бачив посилань в PDF, що служать не тільки для закладок, але також провадять активні посилання з таблиці змісту та індексів. Я не знаю, чому більше авторів не використовують цю можливість, оскільки це дійсно радість для читача. Інша можливість, якою я був вражений, були посилання на форуми ("Discuss"), та спосіб надсилати коментарі ("Suggest") до авторів по електронній пошті. Можливість коментувати сама по собі не є незвичною, але проста вставка номера сторінки, що генерується для надсилання авторам, є важливою для обох, авторів та читачів. Я доклав більше коментарів, ніж я мав би, якби процес був би більш важкий. Читайте Програмування на Scala заради вмісту, але якщо ви читаєте електронну версію, обов'язково отримайте переваги від цифрових можливостей, які автори подбали вбудувати в книжку!

[quote,Jagan Nambi,Enterprise Architecture & GMAC Financial Services]
Ясність та технічна повнота є відзнакою любої гарно написаної книжки, та я вітаю Martin
Odersky, Lex Spoon та Bill Venners з тим, що вони зробили цю роботу дуже гарно! Книжка Programming in Scala починається з встановлення гарного фундаменту з базовими концепціями,та просуває користувача на середній рівень, та далі. Ця книга беззаперечно обов'язкова для придбання для кожного, що прагне вивчити Scala.

[quote,Igor Khlystov, Software Architect/Lead Programmer @ Greystone Inc.]
Програмування на Scala приємно читається. Це одна з тих гарно написаних технічних книжок, що провадять глибоке та повне покриття предмету в екстремально стислій та елегантній манері. Книга організована в дуже природний та логічний спосіб. Вона однаково гарно пристосована для зацікавлених технологістів, які просто бажають залишатись на піці поточних трендів, та професіоналів, що шукають глибокого розуміння основних можливостей  мови, та обгрунтувань її дизайну. Я дуже рекомендую її всім зацікавленим в фіункціональному програмуванні взагалі. Для розробників Scala ця книга безумовно є обов'язковою для читання.

[quote,Gerald Loeffler,Enterprise Java Architect]
Книжка Програмування на Scala прямо точиться кількістю важкої роботи, що пішла до неї. Я ніколи до цього не читав книжку в стилі туторіала, що виконує роль вступу, і при цьому є повною: в їх (помилковій) спробі бути доступними, та не "засмучувати" читача, більшість туторіалів замовчують аспекти предмета, що дуже просунутий для поточного обговорення. Це залишає дуже поганий присмак, бо ніхто не може бути впевнений, якого розуміння ви вже досягли. Завжди існує деяка залишкова "магія", що не була пояснена, та  взагалі не може бути зрозумілою читачеві. Ця книжка нуколи не робить цього, вона нічого не приймає на віру: кожна деталь або достатньо пояснена, або надається посилання на подальше пояснення. Дійсно, текст екстенсивно посилається на себе та індексований, так що формує повну картину складної теми відносно просто.

[quote,Christian Neukirchen]
Програмування на Scala від Martin Odersky, Lex Spoon та Bill Venners: в часи, коли гарні книжкі є рідкістю, це чудове введення для програмістів середнього рівня дійсно є винятнковим. Ви знайдете тут все, щоб вивчити цю мову програмування.

 Programmmin in Scala, Third Edition
 Martin Odersky, Lex Spoon, Bill Venners
 Artima Press
 Walnut Creek, California
    Martin Odersky є створювачем мови Scala та професором EPFL in Lausanne, Switzerland.
    Lex Spoon робив над Scala протягом двох років разом з Martin Odersky. 
    Bill Venners є президентом Artima, Inc.

[preface]
Передмова
---------
Ви обрали чудовий час взяти до рук цю книгу! Сприйняття Scala продовжує пришвидшуватись, наша спільнота вирує, та навкола пропозиції роботи. Чи ви програмуєте для розваги чи для прибутку (або обоє), обіцяна Scala радість та продуктивність робить супротив складним. Щодо мене, дійсна радість програмування походить від протистояння цікавим викликам, за допомогою простих, витончених рішень. Місія Scala не тільки в тому, щоб зробити це можливим, але приємним, і ця книга покаже вам як.

Зпочатку я експериментував з Scala 2.5, та миттєво був втугнутий в її синтаксичну та концептуальну впорядкованість. Коли я натрапив на нерегулярність, що параметри типів самі не можуть мати параметри типів, я (боязко) підійшов до Martin Odersky на конференції в 2006, та запронував стажування, щоб позбутись цього обмеження. Моя контриб'юція була сприйнята, що привнесло підтримку поліморфізм конструкторів типів в Scala 2.7 та вище. З тих пір я робив над більшістю інших частин компілятора. В 2012 я пішов з пост-докторської практики в лабораторії Martin на керівника команди Scala в Typesafe, по мірі того, як Scala, з версією 2.10, подорослішала від своїх прагматичних академічних коренів до надійної мови рівня корпорації.

Scala 2.10 була поворотною точкою від швидко розвинених, багатих можливостями релізів, базованих на академічних дослідах, в напрямку фокусування на спрощенні та збільшенні прийняття адаптації підприємствами. Ми змістили нашу увагу на проблеми, які неможливо описати в дисертаціях, такі, як бінарна сумісність між головними релізами. Щоб збалансувати стабільність з нашим бажанням продовжувати розробку та покращення платформи Scala, ми робимо в напрямку меньшої головної бібліотеки, яку ми збираємось стабілізувати, при цьому розвиваючи платформу як ціле. Щоб зробити це можливим, мій перший проект в якості технічного керівника Scala був початок модулярізації стандартної бібліотеки Scala в 2.11.

Щоб зменшити частоту змін, Typesafe також вирішила поперемінно змінювати бібліоттеку та компілятор. Ця редакція Програмування на Scala відноситься до Scala 2.12, що буде релізом компілятора, який матиме новий бек-енд та оптимізатор, щоб отримати більше від нових можливостей Java 8. Для взаємодії з Java, та насолодження тими ж перевагами від оптимізації JVM, Scala компілює функції в той самий байткод, що і компілятор Java 8. Подібно, трейти Scala тепер компілюються в інтерфейси Java з методами по замовчанню. Обоє схеми компіляції зменшують магію, яку мали виконувати старіші компілятори Scala, більш тісно наближаючи нас до платформи Java, при цьому покращуючи обоє, час компіляції та продуктивність часу виконання, з гладшою бінарною сумісністю!

Це покращення до платформи Java 8 дуже захоалююче для Scala, та це дуже приємно бачити, що Java рівняється на тренд, який Scala встановлювала протягом дисятиріччя! Без жодного сумніву, що Scala провадить значно більш функціональний досвід програмування, з незмінністю по замовчанню, уніформним трактуванням виразів (навряд чи в цій книзі можливо побачити твердження return), співпадіння шаблонів, варіативність в місці визначення (варіативність в місці використання Java робить створення субтипів функції незграбним), і так далі! Кажучи прямо, існує дещо в функціональному програмуванні, ніж милий синтаксис для лямбди.

В якості розпорядників мови, наша ціль є розробляти основу мови, так само, як зрощувати екосистему. Scala є успішною, оскільки вона має багато чудових бібліотек, видатні IDE та інструменти, та дружніх і завжди готових допомогти членів нашої спільноти. Я глибоко насолоджуюсь своєю першою декадою зі Scala — як реалізатор мови, це є великим збудженням і натхненням бачити стільки програмістів, що насолоджуються Scala в безлічі напрямків.

Я люблю програмувати на Scala, і маю надію ви полюбите також. Від імені спільноти Scala вітаю вас!

  Adriaan Moors
  San Francisco, CA
  January 14, 2016

[dedication]
Подяки
~~~~~~
Багато людей доклали до цієї книги, та до матеріалів, які вона розкриває. Ми вдячні всім їм.

Scala сама по собі була колективним зусиллям багатьох людей. Розробці та реалізації версії 1.0 допомагали Philippe Altherr, Vincent Cremet, Gilles Dubochet, Burak Emir, Stéphane Micheloud, Nikolay Mihaylov, Michel Schinz, Erik Stenman та Matthias Zenger. Phil Bagwell, Antonio Cunei, Iulian Dragos, Gilles Dubochet, Miguel Garcia, Philipp Haller, Sean McDirmid, Ingo Maier, Donna Malayeri, Adriaan Moors, Hubert Plociniczak, Paul Phillips, Aleksandar Prokopec, Tiark Rompf, Lukas Rytz та Geoffrey Washburn приєднали зусилля для розробки другої та поточної версії мови та інструментів.

Gilad Bracha, Nathan Bronson, Caoyuan, Aemon Cannon, Craig Chambers, Chris Conrad, Erik Ernst, Matthias Felleisen, Mark Harrah, Shriram Krishnamurti, Gary Leavens, David MacIver, Sebastian Maneth, Rickard Nilsson, Erik Meijer, Lalit Pant, David Pollak, Jon Pretty, Klaus Ostermann, Jorge Ortiz, Didier Rémy, Miles Sabin, Vijay Saraswat, Daniel Spiewak, James Strachan, Don Syme, Erik Torreborre, Mads Torgersen, Philip Wadler, Jamie Webb, John Williams, Kevin Wright та Jason Zaugg окреслили дизайн мови, щедро подоілившись своїми ідеями з нами в живих та надихаючих дискусіях, через контриб'юцію важливих частин коду до зусиль відкритого коду, так само, як і через коментарі до попередніх версій цього документу. Дописувачі в список розсилки Scala також надали дуже корисний зворотній зв'язок, що допоміг нам покращити мову та інструменти.

George Berger працював наполегливо, щоб зробити процес побудови та веб присутність книги роблячими гладко. Як результат, цей проект був чудово вільний від технічних непередбачуваностей.

Багато людей надали нам цінний зворотній зв'язок щодо ранішніх версій цього тексту. Подяки надходять до Eric Armstrong, George Berger, Alex Blewitt, Gilad Bracha, William Cook, Bruce Eckel, Stéphane Micheloud, Todd Millstein, David Pollak, Frank Sommers, Philip Wadler, and Matthias Zenger. Також дякуємо до групи Silicon Valley Patterns, за їх дуже корисний огляд: Dave Astels, Tracy Bialik, John Brewer, Andrew Chase, Bradford Cross, Raoul Duke, John P. Eurich, Steven Ganz, Phil Goodwin, Ralph Jocham, Yan-Fa Li, Tao Ma, Jeffery Miller, Suresh Pai, Russ Rufer, Dave W. Smith, Scott Turnquest, Walter Vannini, Darlene Wallach та Jonathan Andrew Wolter. Та нам приємно подякувати Dewayne
Johnson та Kim Leedy за їх допомогу з оформленням обкладинки, та Frank Sommers за його роботу з індексом.

Нам також приємно поширити особливі подяки всім нашим читачам, що надали коментарі. Ваші коментарі дуже корисні для нас в окресленні цієї, навіть кращої книжки. Ми не можемо надрукувати імена всіх, хто надіслав коментарі. але ось імена тих читачів, які надіслали щонайменьше п'ять коментарів на протязі стадії eBook PrePrint®, через клацання на посиланні Suggest, впорядковані від найбільшого загального числа надісланих коментарів, та потім за алфавітом. Подякі до: David Biesack, Donn Stephan, Mats Henricson, Rob Dickens, Blair Zajac, Tony Sloane, Nigel Harrison, Javier Diaz Soto, William Heelan, Justin Forder, Gregor Purdy, Colin Perkins, Bjarte S. Karlsen, Ervin Varga, Eric
Willigers, Mark Hayes, Martin Elwin, Calum MacLean, Jonathan Wolter, Les Pruszynski, Seth Tisue, Andrei Formiga, Dmitry Grigoriev, George Berger, Howard Lovatt, John P. Eurich, Marius Scurtescu,Jeff Ervin, Jamie Webb, Kurt Zoglmann, Dean Wampler, Nikolaj Lindberg, Peter McLain, Arkadiusz Stryjski, Shanky Surana, Craig Bordelon, Alexandre Patry, Filip Moens, Fred Janon, Jeff Heon, Boris Lorbeer, Jim Menard, Tim Azzopardi, Thomas Jung, Walter Chang, Jeroen Dijkmeijer, Casey Bowman, Martin Smith, Richard Dallaway, Antony Stubbs, Lars Westergren, Maarten Hazewinkel, Matt Russell, Remigiusz Michalowski, Andrew Tolopko, Curtis Stanford, Joshua Cough, Zemian Deng, Christopher Rodrigues Macias, Juan Miguel Garcia Lopez, Michel Schinz, Peter Moore, Randolph Kahle, Vladimir Kelman, Daniel Gronau, Dirk Detering, Hiroaki Nakamura, Ole Hougaard, Bhaskar Maddala, David Bernard, Derek Mahar, George Kollias, Kristian Nordal, Normen Mueller, Rafael Ferreira, Binil
Thomas, John Nilsson, Jorge Ortiz, Marcus Schulte, Vadim Gerassimov, Cameron Taggart, Jon-Anders Teigen, Silvestre Zabala, Will McQueen та Sam Owen.

Ми також бажаемо подякувати тим, хто надіслав коментарі та помилки після друку перших двох видань, включаючи Felix Siegrist, Lothar Meyer-Lerbs, Diethard Michaelis, Roshan Dawrani, Donn Stephan, William Uther, Francisco Reverbel, Jim Balter, and Freek de Bruijn, Ambrose Laing, Sekhar Prabhala, Levon Saldamli, Andrew Bursavich, Hjalmar Peters, Thomas Fehr, Alain O'Dea, Rob Dickens, Tim Taylor, Christian Sternagel, Michel Parisien, Joel Neely, Brian McKeon, Thomas Fehr, Joseph Elliott, Gabriel da Silva Ribeiro, Thomas Fehr, Pablo Ripolles, Douglas Gaylor, Kevin Squire, Harry-Anton Talvik, Christopher Simpkins, Martin Witmann-Funk, Jim Balter, Peter Foster, Craig Bordelon, Heinz-Peter Gumm, Peter Chapin, Kevin Wright, Ananthan Srinivasan, Omar Kilani, Donn Stephan, Guenther Waffler.
Lex would like to thank Aaron Abrams, Jason Adams, Henry and Emily Crutcher, Joey Gibson, Gunnar Hillert, Matthew Link, Toby Reyelts, Jason Snape, John та Melinda Weathers, та всім членам Atlanta Scala Enthusiasts за багато корисних дискусій щодо розробки мови, її матеатичних засадах, та як презентувати Scala працюючим інженерам.

Спеціальна подяка для Dave Briccetti та Adriaan Moors за огляд третього видання, та до Marconi Lanna за не тільки огляд, але за надання мотивації для третього видання, надаючи розмову, озаглавлену "Що нового з часів Програмування на Scala."

Bill має подякувати Gary Cornell, Greg Doench, Andy Hunt, Mike Leonard, Tyler Ortman, Bill
Pollock, Dave Thomas та Adam Wright за провадження розуміння та поради по друку книжки. Bill також дякує Dick Wall за взаємодію над курсом Escalate Stairway to Scala, що значною частиною базується на цій книжці. Наші багато років досвіду викладання Stairway to Scala допомогло зробити цю книжку краще. Нарешті, Bill має подякувати Darlene Gruendl та Samantha Woolf за їх допомогу в тому, щоб третє видання було закінчене.

