:source-highlighter: pygments
Вступ
-----
Ця книжка є туторіалом по мові програмування Scala, написану людьми, напряму причетними до розробки Scala. Наша ціль полягає в тому, щоб читаючи цю книжку ви могли навчитись всьому, що треба, щоб бути продуктивним Scala програмістом. Всі приклади в цій книжці компілюються за допомогою Scala версії 2.11.7, за винятком тих, що відмічені 2.12, що компілюються за допомогою 2.12.0-M3.

Кому слідує читати цю книжку
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Головна цільова аудієнція для цієї книжки є програмісти, які бажають навчитись програмуванню на Scala. Якщо ви бажаєте робити ваш наступний проект на Scala, тоді ця книжка для вас. На додаток, книжка має бути цікавою для програмістів, що бажають розширити свої горизонти через навчання нових концепцій. Наприклад, якщо ви Java програміст, читання цієї книжки відкриє вас до багатьох концепцій з функціонального програмування, так само, як просунутих об'єктно-орієнтовних ідей. Ми віримо, що навчання  Scala, та стоячих за нею ідей, може допомогти стати кращим програмістом, загалом.

Передбачається загальне знання програмування. Хоча Scala є гарною першою мовою програмування, це не книжка для навчання програмуванню.

З іншого боку, ніякого спеціального знання мов програмування не потрібне. Навіть якщо більшість людей використовують Scala на платформі Java, ця книга не очікує, що ви знаєте щось про Java. Однак ми очікуємо, що багато читачів будуть знайомі з Java, так що часом порівнюємо Scala з Java, щоб допомогти таким читачам розуміти відмінності.

Як використовувати цю книгу
~~~~~~~~~~~~~~~~~~~~~~~~~~~
Оскільки головне призначення цієї книжки служити туторіалом, рекомендований спосіб читати цю книгу в порядку глав, зпочатку до кінця. Ми дуже намагались викладати одну тему за раз, та пояснюємо нові теми тільки в термінах тем, що ми вже розглянули. Таким чином, якщо ви пересунетесь в кінець, що скоріше підхопити щось, ви можете винайти, що це пояснено в термінах концепцій, що ви не зовсім розумієте. Доки ви читаєте глави по порядку, ми вважаємо, що ви знайдете досить прямолінійним отримати знання в Scala, по одному кроку за раз.

Якщо ви бачите невідомий вам термін, будьте певні, що перевірили глосарій та індекс. Багато читачів будуть швидко переглядати частини книжки, і це непогано. Глосарій та індекс можуть допомогти вам надолужити, якщо ви проскочили щось дуже швидко.

Після того, як ви прочитали книжку один раз, вона може також служити посиланням мови. Існує формальна специфікація мови Scala, але специфікація мови намагається бути точною, ціною читабельності. Хоча ця книга не покриває кожної деталі Scala, вона досить повна, та може служити як доступне посилання до мови, по мірі як ви ставатимете більш адаптованим в програмуванні Scala.

Як навчатись Scala
~~~~~~~~~~~~~~~~~~
Ви можете багато чому навчитись про Scala, просто читаючи цю книжку від корки до корки. Однак, ви можете навчитись Scala швидше та більш глибоко, якщо зробите декілька додаткових речей.

Зпершу, ви можете отримати вигоду від багатьох прикладів програм, включених в цю книжку. Набираючи їх самотужки є шляхом змісити ваші думки проходити через кожний рядок коду. Пробуючи варіації є шляхом зробити це більш веселим, та переконатись, що ви дійсно розумієте, як вони працюють.

Друге, пристаньте до багатьох онлайн форумів. Таким чином ви та інші інтузіасти Scala можете допомагати один одному. Є багато списків розсилки, дискусійних форумів, чат кімнат, wiki, та декілька Scala-специфічних фідів статей. Витратьте деякий час для пошуку такого, що задовільняє вашим інформаційним потребам. Ви будете витрачати значно меньше часу за вирішенням простих проблем, так що ви зможете витрачати час на глибші, більш важливі питання.

Нарешті, коли ви прочитаєте досить, оберіть собі власний програмний проект. Робіть над малою програмою від початку, або розробляйте додаток до більшої програми. Ви можете зайти тільки так далеко, читаючи.

Можливості eBook
~~~~~~~~~~~~~~~~
Ця книжка доступна в обох, паперовій формі та PDF eBook. eBook не просто електронна копія паперової версії книжки. Хоча вміст той самий, що і в паперовій версії, eBook була прискіпливо розроблена та оптимізована для читання на комп'ютерному екрані.

Перша річ, що треба зауважити, це що більшість посилань в eBook і гіперпосиланнями. Якщо ви виберете главу, малюнок, або елемент глосарію, ваш PDF переглядач  повинене перенести вас прямо до обраного елементу, так що вам не знадобиться гортати, щоб знайти його.

Додатково, знизу кожної сторінки в eBook є декілька навігаційних посилань. Посилання Обкладинка, Огляд та Вміст перенесуть вас на вступні сторінки книжки. Глосарій та Індекс посилаються на частини посилань книжки. Нарешті, посилання Обговорення перенесе вас до онлайн форуму, де ви обговорюєте питання з другими читачами, авторами та ширшою спільнотою Scala. Якщо ви знайдете помилку друку, або щось, що ви вважаєте має пояснюватись краще, будь ласка клацніть на посилання Зауваження, що перенесе вас до онлайн веб застосування, де ви можете надати зворотній зв'язок авторам.

Хоча та сама сторінка з'являється в eBook як і в друкованій книжці, порожні сторінки видалені, та залишені сторінки перенумеровані. Сторінки пронумеровані по-різному, так що вам простіше визначати номери сторінок PDF при друці тільки частини eBook. Таким чином, сторінки в eBook є нумеровані саме так, як їх нумероватиме PDF переглядач.

Типографічні домовленості
~~~~~~~~~~~~~~~~~~~~~~~~~
Перший раз, коли визначається _термін_, він виділяється прописом. Малий приклад коду як  `x + 1`, записується інлайн моноширинним шрифтом. Більші приклади коду покладаються в моноширинні блоки запозичень, як цей:
[source,scala]
----
def hello() = {
  println("Hello, world!")
}
----
Коли показується інтерактивна оболонка, відповіді від оболонки показуються легшим шрифтом:
[source,bash]
----
scala> 3 + 4
res0: Int = 7
----

Огляд вмісту
------------
* Глава 1 "Маштабована мова", надає вам огляд дизайну Scala, разом з міркуваннями, історією, що стоять за нею.
* Глава 2 "Перші кроки в Scala", показує вам, як робити декілька базових завдань програмування в Scala, не вдаючись в великі деталі щодо того, як воно робить. Ціль цієї глави є змусити ваші пальці почати друкувати та виконувати код Scala.
* Глава 3 "Наступні кроки в Scala", показує вам декілька більш базових програмних завдань,  що будуть допомагати вам швидко набрати темп в Scala. Після завершення цієї глави, ви повинні бути в змозі почати використовувати Scala для простих скриптових задач.
* Глава 4 "Класи та об'єкти", розпочинає глибинне покриття Scala з визначення його базових об'єктно-орієнтованих будівельних блоків та інструкцій щодо того, як компілювати та виконувати застосування Scala.
* Глава 5 "Базові типи та операції", розкриває базові типи Scala, їх літерали, операції, що ви можете виконувати з ними, як роблять преоритети та асоційованість, та що таке збагачені обертки.
* Глава 6 "Функціональні об'єкти", занурюється більш глибоко в об'єктно-орієнтовні можливості Scala, використовуючи функціональні (тобто незмінні) раціональні числа в якості приклада.
* Глава 7 "Вбудовані керівні структури", показує вам, як використовувати вбудовані структури керування Scala: if, while, for, try, та match.
* Глава 8 "Функції та замикання", провадить глибинне пояснення функцій, базових будівельних блоків функціональних мов.
* Глава 9 "Абстракції керування", показує, як розширювати базові керуючі структури Scala через визначення ваших власних керівних абстракцій.
* Глава 10 "Композиція та наслідування", обговорює більше з підтримки Scala об'єктно-орієнтовного програмування. Теми не такі фундаментальні, як ті що в Главі 4, але вони часто постають на практиці.
* Глава 11 "Ієрархія Scala", пояснює ієрархію наслідування Scala, та обговорює її універсальні методи та нижні типи.
* Глава 12 "Трейти", розказує про механізм Scala для міксін композиції. Глава показує, як роблять трейти, описує загальні використання, та пояснює, як трейти покращують традиційне множинне наслідування.
* Глава 13 "Пакунки та імпорти", обговорює проблеми програмування в широкому сенсі, включаючи пакунки вищого рівня, твердження імпорту, та модифікатори контроля доступа, як `protected` та `private`.
* Глава 14 "Твердження та тести", показує механізм тверджень Scala, та надає тур по декількох інструментах для написання тестів в Scala, зокрема фокусуючись на ScalaTest.
* Глава 15 "Кейс класи та співпадіння шаблонів", вводять конструкції-близьнюки, що підтримують вас при написанні регулярних, неінкапсульованих структур даних. Кейс класи та співпадіння шаблонів зокрема корисні для дерево-подібних рекурсивних даних.
* Глава 16 "Робота зі списками", пояснює в деталях списки, що, можливо, найбільш загально уживані структури даних в програмах Scala.
* Глава 17 "Робота з іншими колекціями", показує вам, як використовувати базові колекції Scala, такі як списки, масиси, кортежі, множини та мапи.
* Глава 18 "Змінні об'єкти", пояснює змінні об'єкти, та синтаксис, що провадить Scala для їх вираження. Глава завершується практичним заняттям на симуляцію дискретних подій, що показує деякі змінні об'єкти в дії.
* Глава 19 "Типова параметризація", пояснює деякі з прийомів для приховування інформації, введеної в Главі 13 з допомогою конкретного прикладу: розробкою класу для чисто функціональних черг. Глава будується до визначення варіантності типових параметрів, та як це взаємодіє з приховуванням інформації.
* Глава 20 "Абстрактні члени", описує всі типи абстрактних членів, як підтримує Scala; не тільки методи, але також поля та типи, можуть бути декларовані як абстрактні.
* Глава 21 "Неявні переткорення та параметри", розкриває дві конструкції, що можуть допомогти вам оминути нудних деталей джерельного коду, та дозволяючи компілятору надати їх замість цього.
* Глава 22 "Реалізація списків", описує реалізацію класу List. Важливо розуміти, як списки роблять в Scala, і більше того, реалізація демонструє використання деяких можливостей Scala.
* Глава 23 "Переосмислені вирази for", показує як вирази for транслюються на виклики map, flatMap, filter та foreach.
* Глава 24 "Колекції поглиблено", Надає детальний тур по бібліотеці колекцій.
* Глава 25 "Архитектура колекцій Scala", показує як побудована бібліотека колекцій, та як ви можете реалізувати свої власні колекції.
* Глава 26 "Екстрактори", показує, як робити співпадіння шаблонів з довільними класами, не тільки з кейс класами.
* Глава 27 "Анотації", показує, як робити з розширенням мови через анотації. Глава описує декілька стандартних анотацій, та показує, як робити ваші власні. 
* Глава 28 "Робота з XML", пояснює, як обробляти XML в Scala. Глава показує вам ідіоми генерації XML, його розбір, та обробку, коли він вже розібраний.
* Глава 29 "Модулярне програмування з використанням об'єктів", показує, як ви можете використовувати об'єкти Scala як модульну систему.
* Глава 30 "Еквівалентність об'єктів", вказує на деякі проблеми, які треба розглядати, коли пишете метод `equals`. Є декільки ловушок, що треба уникнути.
* Глава 31 "Комбінація Scala та Java", обговорює проблеми, що постають, коли комбінуєте Scala та Java разом в одному проекті, та рекомендовані методи щодо їх подолання.
* Глава 32 "Ф'ючерси та конкурентність", показує вам, як використовувати Scala Future. Хоча ви можете використовувати примітиви конкуренції платформи Java для Scala програм, ф'ючерси можуть допомогти вам уникнути мертвого блокування та стану гонок, що зачумлюють традиційний підхід "потоки та блокування" до конкуренції.
* Глава 33 "Комбінаторний розібр", показує, як побудувати парсери з використанням бібліотеки Scala парсерних комбінаторів.
* Глава 34 "Програмування користувацького інтерфейсу", надає швидкий тур бібліотеки Scala, що спрощує програмування GUI за допомогою Swing.
* Глава 35 "Електронна таблиця SCells", зв'язує все разом, показуючи повне застосування електронної таблиці, написане на Scala.

Ресурси
~~~~~~~
На http://www.scala-lang.org, головному веб ресурсі для Scala, ви знайдете останній реліз Scala та посилання на документацію та ресурси спільноти. Для більш стиснутої сторінки з посиланнями навідайтесь на сайт книжки: http://booksites.artima.com/programming_in_scala_3ed. Щоб поспілкуватись з іншими читачами цієї книжки, перевірте форум Programming in Scala Forum,
за адресою: http://www.artima.com/forums/forum.jsp?forum=282.

Джерельний код
~~~~~~~~~~~~~~
Ви можете завантажити ZIP файл, що містить джерельний код цієї книги, що випущений пді відкритою ліцензією Apache 2.0, с зайта книжки: http://booksites.artima.com/programming_in_scala_3ed.

Помилки
~~~~~~~
Хоча ця книжки була щільно переглянута та перевірена, помилки всеж-таки неодмінно будуть прослизати. Для (надіємось, короткого) списку помилок друку для цієї книжки навідайтесь на http://booksites.artima.com/programming_in_scala_3ed/errata. Якщо ви знайшли помилку, будь ласка повідомьте про неї за носиланням нижче URL, так що ми виправимо її при наступному друці або виданні цієї книжки.
