:ascii-ids:
:doctype: book
:source-highlighter: pygments
:icons: font

Глава 3
-------

Наступні кроки в Scala
======================
Ця глава продовжує вступ до Scala з попередньої глави. В цій главі ми введемо декілька більш складних можливостей. Коли ви скінчите цю главу, ви будете мати досить знань, щоб почати писати корисні скрипти на Scala. Як і з попередньою главою, ми рекомендуємо вам спробувати ці приклади, по мірі проходження. Кращий спосіб отримати відчуття Scala є почати писати Scala код.

Крок 7. Параметризація масивів за допомогою типів
-------------------------------------------------
В Scala ви можете створити примірники об'єктів або примірники класів, використовуючи `new`. Коли ви створюєте примірник об'єкту в Scala, ви можете параметризувати його за допомогою значень або типів. Параметризація означає "конфігурація" примірника, коли ви створюєте його. Ви параметризуєте примірник значеннями, через передачу об'єктів до конструктора в дужках. Наприклад, наступний код Scala створює нового `java.math.BigInteger`, та параметризує його значенням "12345":
----
val big = new java.math.BigInteger("12345")
----
Ви параметризуєте примірник типами, коли вказуєте один або більше типів в прямокутних дужках. Приклад показаний в Лістингу 3.1. В цьому прикладі `greetStrings` є значенням типу `Array[String]`("масив рядків"), що ініціалізований довжиною 3 через його параметризацію значенням 3 в першому рядку кода. Якщо ви запустите код з Лістинга 3.1 як скрипт, ви побачите ще одне привітання `Hello, world!`. Зауважте, що коли ви параметризуєте примірник обома, типом та значенням, тип іде першим в своїх прямокутних дужках, за якими іде значення в дужках.
[source,scala]
----
val greetStrings = new Array[String](3)
greetStrings(0) = "Hello"
greetStrings(1) = ", "
greetStrings(2) = "world!\n"
for (i <- 0 to 2)
  print(greetStrings(i))
----
Лістинг 3.1 - Параметризація масива за допомогою типа.

NOTE: Хоча код в Лістингу 3.1 демонструє важливі концепції, він не показує рекомендований спосіб створювання та ініціалізації масивів в Scala. Ви побачите кращий спосіб в Лістингу 3.2 далі.

Якщо ви знаходитесь в більш явному настрої, ви можете вказати тип `greetStrings` явно:
[source,scala]
----
val greetStrings: Array[String] = new Array[String](3)
----
Беручи до уваги вивід типів Scala, цей рядок кода семантично еквівалнтний до першого дійсного рядка Лістинга 3.1. Але ця форма демонструє, що хоча частина параметризації типа (імена типів в прямокутних дужках) формує частину типу примірника, частина параметризації значенням (значення в дужках) - ні. Тип `greetStrings` є `Array[String]`, не Array[String](3).

Наступні три рядка кода з Лістинга 3.1 ініціалізують кожний елемент масиву `greetStrings`:
[source,scala]
----
greetStrings(0) = "Hello"
greetStrings(1) = ", "
greetStrings(2) = "world!\n"
----
Як зазначалось раніше, масиви в Scala отримують доступ покладанням індексу в дужках, не прямокутних дужках, як в Java. Таким чином нульовий елемент масива є `isgreetStrings(0)`, та не `greetStrings[0]`.

Ці три рядка кода ілюструють важливу концепцію для розуміння того, як Scala розглядає визначення `val`. Коли ви визначаєте змінну за допомогою `val`, змінна не може бути переприсвоєна, але об'єкт, на який вона посилається, потенційно все ще може бути змінений. Як в цьому випадку, ви не можете переприсвоїти `greetStrings` на інший масив; `greetStrings` буде завжди вказувати на той самий примірник `Array[String]`, яким він був ініціалізований. Але ви можете змінити елементи цього `Array[String]` з часом, так що сам масив є змінним.

Два заключні рядка в Лістингу 3.1 містять вираз `for`, що друкує кожний елемент `greetStringsarray` по черзі:
[source,scala]
----
for (i <- 0 to 2)
  print(greetStrings(i))
----
Перший рядок коду в цьому виразі `for` ілюструє інше загальне правило Scala: якщо метод приймає тільки один параметр, ви можете викликати його без крапки або дужок. В цбому прикладі `to` насправді є методом, що приймає один аргумент Int. Код `0 to 2` трансформується в виклик метода `(0).to(2)`. footnote:[Цей метод to насправді повертає не масив, але інший різновид послідовності, що містить значення 0, 1 та 2, по якому ітерує for. Послідовності та інші колекції будуть описані в Главі 17.] Зауважте, що цей синтаксис робить, тільки якщо ви явно вказуєте отримувача виклику метода. Ви не можете написати `println 10`, але ви можете написати `Console println 10`.

Scala технічно не має перевантаження операторів, оскільки вона насправді не має операторів в традиційному сенсі. Замість цього, такі символи, як +, -, * та / можуть бути використані в іменах методів. Таким чином, коли ви друкуєте `1 + 2` в Scala інтерпретаторі на Кроці 1, ви насправді викликаєте метод з назвою `+` на `Int` об'єкті `1`, передаючи `2` як параметр. Як ілюстровано на Малюнку 3.1, ви можете альтернативно записати `1 + 2`, використовуючи традиційний синтаксис виклику метода, `(1).+(2)`.

Малюнок 3.1 - В Scala всі операції є викликами методів.

Інша важлива ідея, ілюстрована цім прикладом, це надати вам розуміння того, чому масиви надають доступ через дужки в Scala. Scala має меньше особливих випадків, ніж Java. Масиви є простими примірниками класів, як любі інші класи в Scala. Коли ви застосовуєте дужки, що оточують одне або більше значень до змінної, Scala буде трансформувати код в виклик методу з назвою `apply` на цій змінній. Так що `greetStrings(i)` перетвориться на `greetStrings.apply(i)`. Таким чином, доступ до елемент масива в Scala є простим викликом метода, як любий інший. Цей принцип не ообмежуєть до масивів: любе застосування об'єктів до деяких аргументів в дужках буде трпнсформоване в виклик метода `apply`. Звичайно, це буде компілюватись, тільки якщо цей тип об'єкта дійсно визначає метод `apply`. Так що це не особливий випадок; це загальне правило.

Подібним чином, коли робиться просвоєння до змінної, до якої застовані дужки з одним або більше аргументом, компілятор буде трансформувати це в виклик метода `update`, що приймає аргументи в дужках, а такж об'єкт з правого боку від знака рівності. Наприклад:
----
greetStrings(0) = "Hello"
----
буде трансформовано на:
----
greetStrings.update(0, "Hello")
----
Таким чином, наступне симантично еквівалентне до коду з лістинга 3.1:
[source,scala]
----
val greetStrings = new Array[String](3)
greetStrings.update(0, "Hello")
greetStrings.update(1, ", ")
greetStrings.update(2, "world!\n")
for (i <- 0.to(2))
  print(greetStrings.apply(i))
----
Scala досягає концептуальної простоти, трактуючи все, від масивів та виразів, як об'єкти з методами. Ви не маєте пам'ятати особливі випадки, такі, як розбіжності в Java між примітивами та їх відповідними огортаючими типами, або між масивами та звичайними об'єктаи. Більше того, ця одноманітність не накладає значних витрат продуктивності. Компілятор Scala використовує в скомпільованому коді масиви Java, примітивні типи, та природну арифметику, де це можливо.

Хоча приклади, що ви бачили на цей момент в цьому кроці, компілюються та виконуються досить гано, Scala провадить більш стислий спосіб для створення та ініціалізації масивів, який в будете звичайно використовувати (Лістинг 3.2). Цей код створює новий масив довжиною три, ініціалізований переданими рядками, `"zero"`, `"one"`, `"two"`. Компілятор виводить тип масива, як `Array[String]`, оскільки ви передали йому рядки.
[source,scala]
----
val numNames = Array("zero", "one", "two")
----
Лістинг 3.2 - Створення та ініціалізація масиву.

Що ви насправді робите в Лістингу 3.2, це виклик методу фабрики, під назвою `apply`, що створює та повертає новий масив. Цей метод `apply` приймає змінне число аргументів,footnote:[Список аргументів змінної довжини, або повторювані параметри, описані в Розділі 8.8.] та визначений на об'єкті компанйоні Array. Ви навчитесь більше щодо об'єктов компанйонів в Розділі 4.3. Якщо ви Java програміт, ви можете думати про це, як про виклик статичного методу на ім'я `apply` на класі `Array`. Більш балакучий шлях викликати той самий метод `apply`:
[source,scala]
----
val numNames2 = Array.apply("zero", "one", "two")
----

Крок 8. Використання списків
----------------------------
Одна з виликих ідей функціонального стилю програмування є методи, що не мають побічних ефектів. Єдиною дією метода повинне бути обчислення та повернення значення. Деякі переваги, що будуть отримані коли ви приймете цей підхід, в тому, що методи стають менш  заплутаними, і таким чином, більш надійні та використовувані. Інша перевага (в статично типізованій мові) в тому, що все, що входить і виходить з метода перевіряється контролем типів, так що логічні помилки більш вірогідно проявлять себе як помилки типів. Застосування цієї функціональної філософії до світу об'єктів означає зробити об'єкти незмінними.

Як ви бачили, масиви Scala є змінними послідовностями об'єктів, що всі поділяють той самий тип. Наприклад, `Array[String]` містить тільки рядки. Хоча ви не можете змінити довжину масива, після того, як був створений екземпляр, ви можете змінити значення його елементів. Таким чином, масиви є змінні об'єкти.

Для незмінних послідовностей об'єктів, що поділяють той самий тип, ви можете використати клас Scala `List`. Так само, як і з масивами, `List[String]` містить тільки рядки. Список Scala `List`, `scala.List`, відрізняється від типу Java `java.util.List` в тому, що списки Scala `List` завжди незмінні (тоді як списки Java `List` можуть бути змінні). Більш загально, Scala `List` розроблений дозволити функціональний стиль програмування. Створити список просто, та Лістинг 3.3 показує як:
[source,scala]
----
val oneTwoThree = List(1, 2, 3)
----
Лістинг 3.3 - Створення та ініціалізація списку.

Код в Лістингу 3.3 встановлює нову `val` на ім'я `oneTwoThree`, ініціалізовану як `new List[Int]` з цілими елементами 1, 2 та 3.footnote:[Вам не треба казати new List, оскільки "List.apply()" визначений як метод фабрика на об'єкті компанйоні scala.List. Ви будете читати більше про об'єкти компанйони в Розділі 4.3.] Оскільки `List` незмінні, вони поводяться трохи подібно до рядків в Java: коли ви викликаєте метод на списку, з імені якого випливає, що список буде змінений, він замість цього створює та повертає нове значення. Наприклад, `List` має метод на ім'я `:::` для конкатенації списків. Ось як ви використовуєте його:
[source,scala]
----
val oneTwo = List(1, 2)
val threeFour = List(3, 4)
val oneTwoThreeFour = oneTwo ::: threeFour
println(oneTwo + " and " + threeFour + " were not mutated.")
println("Thus, " + oneTwoThreeFour + " is a new list.")
----
If you run this script, you'll see:
----
List(1, 2) and List(3, 4) were not mutated.
Thus, List(1, 2, 3, 4) is a new list.
----
Можливо найбільш загальний оператор, якім ви будете користатись зі списками, є `::`, що вимовляється як "cons". Cons ставить новий елемент до початку існуючого списку, та повертає отриманий список. Наприклад, якщо ви викличете цей скрипт:
[source,scala]
----
val twoThree = List(2, 3)
val oneTwoThree = 1 :: twoThree
println(oneTwoThree)
----
Ви побачите:
----
List(1, 2, 3)
----
NOTE: В виразі 1 `::` twoThree, `::` є методом свого правого операну, списку `twoThree`. Ви можете запідозрити, що щось не так з асоціативністю метода `::`, але насправді є просте правило, що треба пам'ятати: якщо метод використовується в операторній нотації, такі, як `a * b`, метод викликається на лівому операнді, як `a.*(b)` — за винятком, коли метод закінчується на двокрапку. Якщо ім'я метода закінчується на двокрапку, метод викликається на правому операнді. Таким чином, в 1 `::` twoThree, метод `::` викликається на `twoThree`, передаючи 1: `twoThree.::(1)`. Асоціативність операторів буде детально дискутована в Розділі 5.9.

Приймаючи, що скороченим шляхом вказати порожній список є `Nil`, одним з методів ініціалізувати нові списки є поєднання разом елементів за допомогою оператора `cons`, з Nil в якості останнього елемента. Причина, з якої вам треба Nil в кінці полягає в тому, що `::` визначене для класа List. Якщо ви намагатиметесь просто сказати 1 `::` 2 `::` 3, це не буде компілюватись, оскільки 3 є Int, що не має метода `::`. Наприклад, наступний скрипт буде продукувати той самий вихід, що і попередній, `List(1, 2, 3)`:
[source,scala]
----
val oneTwoThree = 1 :: 2 :: 3 :: Nil
println(oneTwoThree)
----
Scala List напакований корисними методами, багато з яких показані в Таблиці 3.1. Повна потужність списків буде розкрита в Главі 16.

Чому не додавати до списків?
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Клас List пропонує операцію `append` — вона записується як `:+` та пояснена в Главі  24 — але ця операція рідко використовується, оскільки час, що займає додати до списку зростає лінійно з розміром списку, тоді як постановка в початок за допомогою `::` займає сталий час. Якщо ви бажаєте побудувати список ефективно через додавання елементів, ви можете додавати їх в початок, то коли все буде зроблене зробити реверс (обертання) списку. Або ви можете використовувати `ListBuffer`, змінний список, що пропонує операцію `append`, та потім, коли все зроблено, викликати `toList`. `ListBuffer` буде описаний в Розділі  22.2.


[caption="Таблиця: "]
.Деякі методи та використання List
[cols="1,2",options="header"]
|===
^| Що таке        ^| Що робить

a|[source,scala]
----
List() або Nil 
----
| Порожній List

a|[source,scala]
----
List("Cool", "tools", "rule")
----
| Створює новий List[String] з трьома значеннями, "Cool", "tools", "rule"

a|[source,scala]
----
val thrill = "Will" :: "fill" :: "until" :: Nil
----
| Створює новий List[String] з трьома значеннями, "Will", "fill", "until"

a|[source,scala]
----
List("a", "b") ::: List("c", "d")
----
| Конкатенує два списки (повертає новий List[String] зі значеннями "a", "b", "c", "d")

a|[source,scala]
----
thrill(2)
----
| Повертає елемент з індексом 2 (від нуля) списку thethrill (повертає "until")

a|[source,scala]
----
thrill.count(s => s.length == 4)
----
| Рахує число число рядків-елементів в thrill, чия довжина 4 (повертає 2)

a|[source,scala]
----
thrill.drop(2)
----
| Повертає список thrill без перших двох елементів (повертає List("until"))


a|[source,scala]
----
thrill.dropRight(2)
----
| Повертає список thrill без двох правих елементів (повертає List("Will"))


a|[source,scala]
----
thrill.exists(s => s == "until")
----
| Визначає, чи існує елемент-рядок в thrill, що має значення "until" (повертає true)

a|[source,scala]
----
thrill.filter(s => s.length == 4)
----
| Повертає список з усіх елементів thrill, по порядку, що мають довжину 4 (повертає List("Will", "fill"))

a|[source,scala]
----
thrill.forall(s => s.endsWith("l"))
----
| Вказує, чи всі елементи в списку thrill закінчуються на літеру "l" (повертає true)

a|[source,scala]
----
thrill.foreach(s => print(s))
----
| Виконує твердження print на кожному рядку в списку thrill (друкує "Willfilluntil")

a|[source,scala]
----
thrill.foreach(print)
----
| Те саме що і попередньє, але стисліше (також друкує "Willfilluntil")

a|[source,scala]
----
thrill.head
----
| Повертає перший елемент в списку thrill (повертає "Will")

a|[source,scala]
----
thrill.init
----
| Повертає з усіх, крім останнього, елементів в списку thrill (повертає List("Will", "fill"))

a|[source,scala]
----
thrill.isEmpty
----
| Вказує, чи є список thrill (повертає false)

a|[source,scala]
----
thrill.last
----
| Повертає останній елемент в списку thrill (повертає "until")

a|[source,scala]
----
thrill.length
----
| Повертає число елементів в списку thrill (повертає 3)

a|[source,scala]
----
thrill.map(s => s + "y")
----
| Повертає список, отриманий від додавання "y" до кожного елемента-рядка в списку thrill (повертаєList ("Willy", "filly", "untily"))

a|[source,scala]
----
thrill.mkString(", ")
----
| Робить рядок з усіх елементів списку (повертає "Will, fill, until")

a|[source,scala]
----
thrill.filterNot(s => s.length == 4)
----
| Повертає список з усіх елементів списку thrill, по порядку, крім тих, що мають довжину 4 (повертає List("until"))

a|[source,scala]
----
thrill.reverse
----
| Повертає список, що складається з усіх елеменітв списку thrill в зворотньому порядку (повертає List("until", "fill", "Will"))

a|[source,scala]
----
thrill.sort((s, t) => s.charAt(0).toLower < t.charAt(0).toLower)
----
| Повертає список, що містить всі елементи thrill в алфавітному порядку по першій літері, переведеній в нижній реєстр (повертає List("fill", "until", "Will"))

a|[source,scala]
----
thrill.tail
----
| Повертає список thrill мінус перший елемент (повертає List("fill", "until"))
|===

Крок 9. Використання таплів
---------------------------
Інший корисний контейнерний об'єкт є тапл. Як списки, тапли є нехмінними, але на відміну від списків, тапли можуть містити різні типи елементів. Коли список може бути List[Int] або aList[String], тапл може містити обоє, ціле та рядок, одночасно. Тапли дуже корисні, наприклад, коли ви повертаєте декілька об'єктів з метода. В той час, коли в Java ви будете часто створювати JavaBean-подібний клас, що міститиме декілька повертаємих значень, в Scala ви можете просто повернути тапл. Та це просто: щоб ініціалізувати тапл, що містить деякий об'єкти, просто покладіть об'єкти в дужки, розділені комами. Як тільки ви маєте примірник таплу, ви можете отримати доступ до його індивідуальних об'єктів через крапку, підкреслення, та 1-базований індекс елементів. Приклад показаний на Лістингу 3.4:
[source,scala]
----
val pair = (99, "Luftballons")
println(pair._1)
println(pair._2)
----
Лістинг 3.4 - Creating and using a tuple.

В першому рядку Лістинга 3.4 ви створюєте новий тапл, що містить ціле 99 як перший елемент, та рядок "Luftballons" як другий елемент. Scala виводить тип тапла як `Tuple2[Int, String]`, та надає цей тип до змінної `pair`, також. В другому рядку ви отримуєте доступ до поля _1, що буде продукувати перший елемент, `99`. "." в другому рядку є та сама крапка, яку ви використовуєте для доступу до поля або для виклику метода. В цьому випадку ви отримуєте доступ до поля на ім'я _1. Якщо ви виконаєте скрипт, ви побачите:
----
99
Luftballons
-----
Справжній тип тапла залежить від числа елементів, яке він містить, та від типів ціх елементів. Таким чином, тип `(99, "Luftballons")` є `Tuple2[Int, String]`. Тип `('u', 'r', "the", 1, 4, "me")` є `Tuple6[Char, Char, String, Int, Int, String]`.footnote:[Хоча концептуально ви можете створити тапли любої довжини, наразі бібліотека Scala визначає їх до Tuple22.]

Доступ до елементів тапла
~~~~~~~~~~~~~~~~~~~~~~~~~
Ви можете здивуватись, чому ви не можете отримати доступ до елементів тапла як до елементів списку, наприклад, як `pair(0)`. Причина є в тому, що для списка метод `apply` завжди повертає той самий тип, але кожний елемент тапла може бути різного типу: _1 може мати одит тип результату, _2 інший, і так далі. Ці числа _N базуються не одиниці, замість нуля, оскільки починати з 1 є традицією, встановленою іншими мовами зі статичними типизованими таплами, як Haskell та ML.

Крок 10. Використання множин та мап
-----------------------------------
Оскільки Scala націлена допомогти вам отриати переваги від обох, функціонального та імперативного стилів, її бібліотеки колекцій наголошують на різниці між змінними та незмінними колекціями. Наприклад, масиви завжди змінні; списки завжди незмінні. Scala також провадить змінні та незмінні альтернативи для множин та мап, але використовує ті ж самі прості імена для обої версій. Для множин та мап Scala моделює змінність в ієрархії класів.

Наприклад, Scala API містить базовий трейт для множин, де трейт схожий на Java інтерфейс. (Ви знайдете більше щодо трейтів в Главі 12). Потім Scala провадить два субтрейти, один для змінних множин, та інший для незмінних множин.

Як ви можете бачити на Малюнку 3.2, ці три трейти всі поділяють те саме просте ім'я, `Set`. Однак їх повністю кваліфіковані імена відрізняються, оскільки кожний знаходиться в окремому пакунку. Конкретні класи множин в Scala API, такі як класи `HashSet`, показані на Малюнку 3.2, розширюють або змінний, або незмінний трейт Set. (Хоча в Java ви "реалізуєте" інтерфейси, в Scala ви "розширюєте" або "міксуєте" трейти). Таким чином, якщо ви бажаєте використати HashSet, ви маєте обрати між змінним та незмінним варіаціями, в залежності від ваших потреб. Спосіб по замовчанню створити множину показаний на Лістингу 3.5:
[source,scala]
----
var jetSet = Set("Boeing", "Airbus")
jetSet += "Lear"
println(jetSet.contains("Cessna"))
----
Лістинг 3.5 - Створення, ініціалізація та використання незмінної множини.

Малюнок 3.2 - Ієрархія класів для множин Scala.

В першому рядук кода в Лістингу 3.5 ви визначаєте нову `var` на ім'я `jetSet`, та ініціалізуєте її незмінною множиною, що має два рядка, "Boeing" та "Airbus". Як показує приклад, ви можете створити множини в Scala подібно до того, як ви створюєте списки та масиви: через виклик метода фабрики з назвою `apply` на об'єкті компанйоні Set. В Лістингу 3.5 ви визиваєте `apply` на об'єкті компанйоні для  `scala.collection.immutable.Set`, що повертає примірник по замовчанню, незмінний `Set`. Компілятор Scala виводить тип `jetSet` як незмінний `Set[String]`.

Щоб додати новий елемент до множини ви застосовуєте виклик + на множині, передаючи новий елемент. На обох, змінній та незмінній множині метод + буде створювати та поверне нову множину з доданим елементом. В Лістингу 3.5 ви робите з незмінною множиною. Хоча змінні множини пропонують справжній метод `+=`, незмінні множини ні.

В цьому випадку другий рядок коду, `jetSet += "Lear`, в основному є скороченням для:
[source,scala]
----
jetSet = jetSet + "Lear"
----
Таким чином, в другому рядку Лістингу 3.5 ви переприсвоююте `jetSet var` новою множиною, що містить "Boeing", "Airbus", та "Lear". Нарешіт, в останньому рядку Лістингу 3.5 іде друк того, чи містить або ні множина рядок "Cessna". (Як ви і очікували, друкується false).

Якщо ви бажаєте змінну множину, вам треба використовувати імпорт, як показано в Лістингу 3.6:
[source,scala]
----
import scala.collection.mutable
val movieSet = mutable.Set("Hitch", "Poltergeist")
movieSet += "Shrek"
println(movieSet)
----
Лістинг 3.6 - Створення, ініціалізація та використання змінної множини.

В першому рядку Лістингу 3.6 ви імпортуєте `Set`. Як і з Java, твердження `import` дозволяє вам використовувати просте ім'я, таке як  `Set`, замість довшого, повністю кваліфікованого імені. Як результат, коли ви кажете Set в третьому рядку, компілятор знає, що ви маєте на увазі `scala.collection.mutable.Set`. В цьому рядку ви ініціалізуєте `movieSet` новою змінною, що містить рядки "Hitch" та "Poltergeist". Наступний рядок додає "Shrek" до змінної множини, викликаючи метод `+=` до множини, передаючи йому рядок "Shrek". Як зазначалось раніше, `+=` насправді є методом, визначеним на змінній множині. За вашим бажанням, замість `writingmovieSet += "Shrek"`, ви можете написати `movieSet.+=("Shrek")`.footnote:[Оскільки множина в Лістингу 3.6 змінна, немає потреби переприсвоювати movieSet, ось чому вона може бути встановлена в val. До контрасту, використання += з незмінною множиною в Лістингу 3.5 потребує переприсвоєння jetSet, ось чому воно має бути var.]

Хоча реалізація множин по замовчанню, спродукована змінною та незмінною методами фабриками `Set`, буде достатньою в багатьох ситуаціях, часом ви можете побажати явно задати клас. Нащастя, синтаксис є подібним. Просто імпортуйте потрібний вам клас, та використовуйте метод фабрику на його об'єкті компанйоні. Наприклад, якщо вам треба незмінний `HashSet`, ви можете зробити таке:
[source,scala]
----
import scala.collection.immutable.HashSet
val hashSet = HashSet("Tomatoes", "Chilies")
println(hashSet + "Coriander")
----
Інший корисний клас колекції в Scala є `Map`. Як і з множинами, Scala провадить змінну та незмінну версії `Map`, використовуючи ієрархію класів. Як ви можете побачити на Малюнку 3.3, ієрархія класів для мап виглядає мажйе так, як така для множин. Існує базовий трейт `Map` в пакунку `packagescala.collection`, і два субтрейти Maps: змінний Map в `scala.collection.mutable` та незмінний в `scala.collection.immutable`.

Малюнок 3.3 - Ієрархія класів для Scala мап.

Реалізації Map, такі як `HashMaps`, показані в ієрархії на Малюнку 3.3, розширюють або змінний, або незмінний трейт. Ви можете створити та ініціалізувати мапи, використовуючи метди фабрики, подібні до таких для масивів, списків та множин.
[source,scala]
----
import scala.collection.mutable
val treasureMap = mutable.Map[Int, String]()
treasureMap += (1 -> "Go to island.")
treasureMap += (2 -> "Find big X on ground.")
treasureMap += (3 -> "Dig.")
println(treasureMap(2))
----
Лістинг 3.7 - Створення, ініціалізація та використання змінної мапи.

Наприклад, Лістинг 3.7 показує змінну мапу в дії. On the first line of Лістинг 3.7, you import the mutable Map. You then define a val named treasureMap, and initialize it with an empty mutable Map that has integer keys and string values. The map is empty because you pass nothing to the factory method (the parentheses in "Map[Int, String]()" are empty).footnote:[Явна параметризація типу, "[Int, String\]", є необхідною в Лістингу 3.7, оскільки без любих значень, переданих в метод фабрику компілятор не здатний вивести тип параметрів мапи. Для контрасту, компілятор може вивести тип параметрів зі значень, переданих до фабрики мапи, показаної в Лістингу 3.8, так що явних параметрів типу не треба.] На наступних трьох рядках ви додаєте до мапи пари ключ/значення, використовуючи методи `->` та `+=`. Як вже було проілюстровано, компілятор Scala трансформує двомісні вирази операцій, як `1 -> "Go to island."` на `(1).->("Go to island.")`. Таким чином, коли ви кажете `1 -> "Go to island."`, ви насправді викликаєте метод на ім'я `->` на цілому зі значенням `1`, передаючи йому рядок зі значенням "Go to island." Цей метод `->`, який ви можете викликати на об'єкті в програмі Scala, повертає дво-елементний тапл, що містить ключ та значення.footnote:[Механізм Scala, що дозволяє вам викликати  -> на любому об'єкті, неявне перетворення, буде розкрите в Главі 21.] Потім ви можете передати тапл до метода `+=` об'єкта мапи, на який посилається `treasureMap`. Нарешті, останній рядок друкує значення, що відповідає ключу 2 treasureMap.

Якщо ви виконаєте цей код, він надрукує:
----
Find big X on ground.
----
Якщо ви обираєте незмінну мапу, імпорт непотрібний, бо незмінна є мапою по замовчанню. Приклад показаний в Лістингу 3.8:
[source,scala]
----
val romanNumeral = Map(
  1 -> "I", 2 -> "II", 3 -> "III", 4 -> "IV", 5 -> "V"
)
println(romanNumeral(4))
----
Лістинг 3.8 - Створення, ініціалізація та використання незмінної мапи.

Зважаючи на те, що тут немає імпортів, ви можете сказати, що `Map` в першому рядку Лістинга 3.8 ви отримаєте замовчання, `scala.collection.immutable.Map`. Ви передаєте п'ять таплів ключ/значення до метода фабрики мапи, що повертає незмінну `Map`, яка містить передані пари ключ/значення. Якщо ви виконаєте код в Лістингу 3.8, він надрукує "IV".

Крок 11. Вчимсоь розпізнавати функціональний стиль
--------------------------------------------------
Як зазначалось в Главі 1, Scala дозволяє вам програмувати в імперативному стилі, але заохочує вас адоптувати більш функціональний стиль. Якщо ви прийшли в Scala з імперативного бекграунда, наприклад, якщо ви Java програміст, одним з головних викликів, з яким ви стикаєтесь при вивченні Scala є зрозуміти, як програмувати в функціональному стилі. Ми розуміємо, що цей стиль зпочатку може бути незвичним, але в цій книзі ми намагаємось направляти вас в цьому переході. Це буде потребувати деякої роботи з вашого боку, і ми закликаємо докласти зусиль. Якщо ви прийшли з імперативного бекграунду, ми віримо, що вивчення програмування в функціональному стилі не тільки зробить вам кращим програмістом Scala, але також розширить ваші горизонти, та зробить кращим програмістом взагалі.

Перший крок це розпізнати різницю між двома стилями в коді. Один промовистий знак - це якщо код містить любі `var`, вірогідно що він в імперативному стилі. Якщо код взагалі не містить — тобто, він містить тільки `val` — вірогідно він в функціональному стилі. Таким чином, одним шляхом рухатись в функціональному стилі є спробувати програмувати без `var`.

Якщо ви походите з імперативного бекграунда, як Java, C++ або C#, ви можете думати про `var` як про звичану змінну, та про `val` як про спеціальний різновид змінних. З іншого боку, якщо ви походите з функціонального бекграунда, як Haskell, OCaml або Erlang, ви можете думати про `val` як про звичану змінну, та `var` як спробу святотацтва. Однак перспектива Scala полягає в тому, що `val` та `var`є просто два різні інструменти в вашому наборі, обоє корисні, та жодний не є втілення зла. Scala заохочує вас вивчати щодо `val`, але кінець кінцем отримати кращий інструмент, що знадобиться для вашої роботи. Однак навіть якщо ви згодні з цією збалансованою філософією, ви все одно можете на початку знайти складним, як позбавитись від `var` в своєму коді.

Як приклад, розглянемо наступний цикл `while`, адаптований з Глави 2, що використовує `var`, та є, таким чином, в імперативному стилі:
[source,scala]
----
def printArgs(args: Array[String]): Unit = {
var i = 0
while (i < args.length) {
  println(args(i))
  i += 1}
}
----
Ви можете трансформувати цей шматок коду в більш функціональний стиль, поклавши край `var`, наприклад, так:
[source,scala]
----
def printArgs(args: Array[String]): Unit = {
  for (arg <- args)
    println(arg)
}
----
або так:
[source,scala]
----
def printArgs(args: Array[String]): Unit = {
  args.foreach(println)
}
----
Цей приклад ілюструє одну перевагу від програмування з меншою кількістю `var`. Рефактований (більш функціональний) код є чистіший, більш стислий, та менш схильний до помилок, ніж оригінальний (більш імперативний) код. Причина, з якої Scala заохочує до функціонального стилю, в тому, що він може допомогти вам писати більш зрозумілий, менш схильний до помилок код.

Але ви можете пійти навіть далі. Рефакторений метод `printArgs` не є повністю функціональним, бо він має побічні ефекти — в цьому випадку цей побічний ефект є друк у стандартний вихідний потік. Промовистий знак що функція має побічні ефекти, це коли тип її результата Unit. Якщо функція не повертає жодного цікавого значення, що і означає тип результата Unit, єдиним шляхом, яким функція може зробити зміни в світі, че через деякий різновид побічного ефекту. Більше функціональний підхід може бути в визначенні метода, що форматує передані `args` для друку, але тільки повертає форматований рядок, як показано в Лістингу 3.9:
[source,scala]
----
def formatArgs(args: Array[String]) = args.mkString("\n")
----
Лістинг 3.9 - A function without side effects or vars.

Тепер ви дійсно функціональні: немає ні побічних ефектів, ні `var` в полі зору. Метод `mkString`, який ви можете викликати на любій ітерабельній колекції (включаючи масиви, списки, множини та мапи), повкртає рядок, що складається з викликів `toString` на кожному елементі, розділені переданим рядком. Таким чином, якщо аргументи складаються з трьох аргументів, "zero", "one", "two", `formatArgs` буде повертати `"zero\none\ntwo"`. Звичайно, ця функція насправді не друкує нічого назовні, як робив метод `printArgs`, але ви можете просто передати його результат до `println`, щоб досягти цього:
[source,scala]
----
println(formatArgs(args))
----
Кожна корисна програма, вірогідно, буде мати побічні ефекти в деякій формі; інакше, буде неможливо провадити значення до зовнішнього світу. Схильність до методів без побічних ефектів заохочує вас розробляти програми, де код з побічними ефектами мінімізований. Одна з переваг цього підходу в тому, щоце може допомогти вашим програмам простіше тестуватись.

Наприклад, щоб протестувати любий з трьох методів `printArgs`, показаних раніше в цьому розділі, вам треба перевизначити `println`, перехопити переданий йому вивід, та переконатись, що там те, що ви очікуєте. Для контрасту, ви можете тестувати функцію `formatArgs`, просто перевіряючи її результат:
[source,scala]
----
val res = formatArgs(Array("zero", "one", "two"))
assert(res == "zero\none\ntwo")
----
Метод Scala `assert` перевіряє переданий їй `Boolean`, та якщо воно `false`, підіймає `AssertionError`. Якщо передане `Boolean` є `true`, `assert` просто повертає керування. Ви навчитесь більше щодо тверджень в тестах в Главі 14.

Кажучи це, майте на увазі, що ні `var`, ні побічні ефекти не є природним злом. Scala не є чисто функціональною мовою, що змушує вас програмувати все в функціональному стилі. Scala є гібридною, імперативно/функціональною мовою. Ви можете винайти, що в деяких ситуаціях імперативний стиль краще підходить до вирішуваної проблеми, і в таких випадках вам не треба боятись використовувати його. Однак щоб допомогти вам навчитись, як програмувати без `var`, ми покажемо вам багато специфічних прикладів коду з `var`, та як трансформувати ці `val` в Главі 7.

Збалансоване ставлення для Scala програмістів
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Схиляйтесь до `val`, незмінних об'єктів та методів без побічних ефектів. Спочатку розпочніть з них. Використовуйте `var`, змінні об'єкти та методи з побочними ефектами, коли ви маєте специфічні потреби, та обгрунтування для них.

Крок 12. Читання рядків з файла
-------------------------------
Scripts that perform small, everyday tasks often need to process lines in files. In this section, you'll build a script that reads lines from a file and prints them out prepended with the number of characters in each line. The first version is shown in Лістинг 3.10:
[source,scala]
----
import scala.io.Source
if (args.length > 0) {
  for (line <- Source.fromFile(args(0)).getLines())
    println(line.length + " " + line)
}
else
  Console.err.println("Please enter filename")
----
Лістинг 3.10 - Reading lines from a file.

This script starts with an import of a class named Source from package scala.io. It then checks to see if at least one argument was specified on the command line. If so, the first argument is interpreted as a filename to open and process. The expression Source.fromFile(args(0))attempts to open the specified file and returns a Source object, on which you call getLines. ThegetLines method returns an Iterator[String], which provides one line on each iteration, excluding the end-of-line character. The for expression iterates through these lines and prints for each the length of the line, a space, and the line itself. If there were no arguments supplied on the command line, the final else clause will print amessage to the standard error stream. If you place this code in a file named countchars1.scala, and run it on itself with:
----
$ scala countchars1.scala countchars1.scala
----
You should see:
----
22 import scala.io.Source
0
22 if (args.length > 0) {
0
51
for (line <- Source.fromFile(args(0)).getLines())
37
println(line.length + " " + line)
1 }
4 else
46
Console.err.println("Please enter filename")
----
Although the script in its current form prints out the needed information, you may wish to line up the numbers, right adjusted, and add a pipe character, so that the output looks instead like:
----
22 | import scala.io.Source
0  | 
22 | if (args.length > 0) {
0  |
51 |   for (line <- Source.fromFile(args(0)).getLines())
37 |     println(line.length + " " + line)
1  | }
4  | else
46 |   Console.err.println("Please enter filename")
----
To accomplish this, you can iterate through the lines twice. The first time through you'll determine the maximum width required by any line's character count. The second time through you'll print the output, using the maximum width calculated previously. Because you'll be iterating through the lines twice, you may as well assign them to a variable:
[source,scala]
----
val lines = Source.fromFile(args(0)).getLines().toList
----
The final toList is required because the getLines method returns an iterator. Once you've iterated through an iterator, it is spent. By transforming it into a list via the toList call, you gain the ability to iterate as many times as you wish, at the cost of storing all lines from the file in memory at once. The lines variable, therefore, references a list of strings that contains the contents of the file specified on the command line. Next, because you'll be calculating the width of each line's character count twice, once per iteration, you might factor that expression out into a small function, which calculates the character width of the passed string's length:
[source,scala]
----
def widthOfLength(s: String) = s.length.toString.length
----
With this function, you could calculate the maximum width like this:
[source,scala]
----
var maxWidth = 0
for (line <- lines)
  maxWidth = maxWidth.max(widthOfLength(line))
----
Here you iterate through each line with a for expression, calculate the character width of that line's length, and, if it is larger than the current maximum, assign it to maxWidth, a var that was initialized to 0. (The max method, which you can invoke on any Int, returns the greater of the value on which it was invoked and the value passed to it). Alternatively, if you prefer to find the maximum without vars, you could first find the longest line like this:
[source,scala]
----
val longestLine = lines.reduceLeft(
  (a, b) => if (a.length > b.length) a else b
)
----
The reduceLeft method applies the passed function to the first two elements in lines, then applies it to the result of the first application and the next element in lines, and so on, all the way through the list. On each such application, the result will be the longest line encountered so far because the passed function, (a, b) => if (a.length > b.length) a else b, returns the longest of the two passed strings. "reduceLeft" will return the result of the last application of the function, which in this case will be the longest string element contained in lines.

Given this result, you can calculate the maximum width by passing the longest line towidthOfLength:
[source,scala]
----
val maxWidth = widthOfLength(longestLine)
----
All that remains is to print out the lines with proper formatting. You can do that like this:
[source,scala]
----
for (line <- lines) {
val numSpaces = maxWidth - widthOfLength(line)
val padding = " " * numSpaces
println(padding + line.length + " | " + line)
}
----
In this for expression, you once again iterate through the lines. For each line, you first calculate the number of spaces required before the line length and assign it to numSpaces. Then you create a string containing numSpaces spaces with the expression " " * numSpaces. Finally, you print out the information with the desired formatting. The entire script looks as shown in Лістинг 3.11:
[source,scala]
----
import scala.io.Source
def widthOfLength(s: String) = s.length.toString.length
if (args.length > 0) {
  val lines = Source.fromFile(args(0)).getLines().toList
  val longestLine = lines.reduceLeft(
    (a, b) => if (a.length > b.length) a else b
  )
  val maxWidth = widthOfLength(longestLine)

  for (line <- lines) {
    val numSpaces = maxWidth - widthOfLength(line)
    val padding = " " * numSpaces
    println(padding + line.length + " | " + line)
  }
} 
else
  Console.err.println("Please enter filename")
----
Лістинг 3.11 - Printing formatted character counts for the lines of a file.

CONCLUSION
----------
With the knowledge you've gained in this chapter, you should be able to start using Scala for small tasks, especially scripts. In later chapters, we will dive further into these topics and introduce other topics that weren't even hinted at here.
