include::headers.adoc[]

Глава 12
--------

Трейти
======

Трейти є фундаментальною одиницею повторного використання коду в Scala. Трейт енкапсулює визначення методів та полів, що потім може бути використані через його міксування з полями. На відміну від наслідування класів, в якому кожний клас має наслідувати від тільки одного суперкласу, клас може міксувати любе число трейтів. Ця глава показує вам, як роблять трейти, та показує два з найбільш загальних шляхів, як вони можуть бути корисні: розширення інтерфейсів до багатих, та визначення накладуваних модифікацій. Вона також показує, як використовувати трейти `Ordered` та `compares` як множинного наслідування в інших мовах.

12.1 Як роблять трейти
----------------------
Визначення трейта виглядає так само, як визначення класу, з тією різницею, що він використовує ключове слово `trait`. Приклад показаний в Лістингу 12.1:
[source,scala]
----
trait Philosophical {
  def philosophize() = {
    println("I consume memory, therefore I am!")
  }
}
----
Лістинг 12.1 - Визначення трейта `Philosophical`.

Цей трейт з назвою `Philosophical`. Він не декларує суперкласа, так що як в класи, він має суперклас по замовчанню, `AnyRef`. Він визначає один метод, названий `philosophize`, що є суцільним. Це простий трейт, але достатній для того, як роблять трейти.

Коли трейт визначений, він може бути зміксований з класом, використовуючи ключові слова `extends`, або `with`. Програмісти Scala "міксують" трейти, скоріше ніж наслідують від них, оскільки міксування трейту має важливі відмінності від множинного наслідування, яке можна знайти в інших мовах. Цей момент дискутується в Розділі 12.6. Наприклад, Лістинг 12.2 показує клас, що міксує трейт `Philosophical` з використанням `extends`:
[source,scala]
----
class Frog extends Philosophical {
  override def toString = "green"
}
----
Лістинг 12.2 - Міксування трейту використовуючи `extends`.

Ви можете використовувати ключове слово `extends` для міксування трейта; в цьому випадку ви неявно наслідуєте від суперкласа трейта. Наприклад, в Лістингу 12.2 клас `Frog` є субкласом `AnyRef` (суперклас `Philosophical`), та міксує `Philosophical`. Методи, наслідувані від трейта, можуть бути використані так само, як і методи, наслідувані від суперкласа. Ось приклад:
[source,scala]
----
scala> val frog = new Frog
frog: Frog = green

scala> frog.philosophize()
I consume memory, therefore I am!
----
Трейт також визначає тип. Ось приклад, в якому `Philosophical` використовується як тип:
[source,scala]
----
scala> val phil: Philosophical = frog
phil: Philosophical = green

scala> phil.philosophize()
I consume memory, therefore I am!
----
Тип `phil` є трейт `Philosophical`. Таким чином, змінна `phil` може бути ініціалізована любим об'єктом, чий клас міксує `Philosophical`.

Якщо ви бажаєте міксувати трейт в клас, що явно розширює суперклас, ви використовуєте  `extends` для вказання суперкласа, та `mix` для підмішування трейта. Лістинг 12.3 показує приклад. Якщо ви бажаєте зміксувати декілька трейтів, ви додаєте більше тверджень `with`. Наприклад, маючи трейт `HasLegs`, ви можете міксувати обоє, `Philosophical` та `HasLegs` у `Frog`, як показане в Лістингу 12.4.
[source,scala]
----
class Animal

class Frog extends Animal with Philosophical {
  override def toString = "green"
}
----
Лістинг 12.3 - Mixing in a trait using with.

[source,scala]
----
class Animal
trait HasLegs

class Frog extends Animal with Philosophical with HasLegs {
  override def toString = "green"
}
----
Лістинг 12.4 - Міксування декількох трейтів.

В прикладі, що ви бачили дотепер, клас `Frog` наслідував реалізацію `philosophize` від трейта `Philosophical`. Альтернативно, `Frog` може перекривати `philosophize`. Синтаксис виглядає так, як і перекриття метода, декларованого в суперкласі. Ось приклад:
[source,scala]
----
class Animal

class Frog extends Animal with Philosophical {
  override def toString = "green"
  override def philosophize() = {
    println("It ain't easy being " + toString + "!")
  }
}
----
Оскільки це нове визначення `Frog` все ще міксує трейт `Philosophical`, ви можете використовувати його зі змінними цього типу. Але оскільки `Frog` перекриває реалізацію `Philosophical` для `philosophize`, ви отримаєте нову поведінку при його виклику:
[source,scala]
----
scala> val phrog: Philosophical = new Frog
phrog: Philosophical = greenscala> phrog.philosophize()
It ain't easy being green!
----
В цій точці ви можете _philosophize_ що трейти подібні до Java інтерфейсів з суцільними методами, але насправді вони можуть значно більше. Наприклад, трейти можуть декларувати поля та підтримувати стан. Фактично, ви можете робити будь-що в визначенні трейта, що ви можете робити в визначенні класу, та синтаксис виглядає так само, з двома виключеннями.

Перше, трейт не може мати жодних параметрів "класу" (тобто параметрів, що передаються до первинного конструктора класу). Іншими словами, хоча ви можете визначити клас таким чином:
[source,scala]
----
class Point(x: Int, y: Int)
----
Наступна спроба визначити трейт не буде компілюватись:
[source,scala]
----
trait NoPoint(x: Int, y: Int) // Не компілюється
----
Ви побачите в Розділі 20.5, як обійти це обмеження.

Інша різниця між класами та трейтами в тому, що в класах супер виклики статично прив'язані, в трейтах вони прив'язані динамічно. Якщо ви напишете `super.toString` в класі, ви точно знаєте, який метод реалізації буде викликаний. Однак коли ви пишете те саме в трейті, метод реалізації, що буде викликаний для `super` виклику невизначений на час визначення трейта. Скоріше реалізація для виклику буде визначена по новій кожного разу, коли трейт підміксовується в суцільний клас. Ця цікава поведінка `super` є ключем для можливості трейтів робити як накладувані модифікації, що будуть описані в Розділі 12.5. Правила для розрішення супер викликів будуть надані в Розділі 12.6.

12.2 Тонкі інтерфейси проти багатих інтерфейсів
-----------------------------------------------
Одне головне використання трейтів є автоматичне додавання методів до класу в термінах методів, що клас вже має. Тобто трейти можуть збагатити тонкий інтерфейс, перетворяючи його на багатий інтерфейс.

Тонкі інтерфейси проти багатих інтерфейсів представляє загально зустріваний компроміс в об'єктно-орієнтовній розробці. Компроміс між реалізаторами та клієнтами інтерфейсу. Багатий інтерфейс має багато методів, що робить його зручним для викликаючого. Клієнти можуть обрати метод, що точно співпадає з потрібною їм функціональністю. З іншого боку, тонкий інтерфейс має меньше методів, і, таким чином, легше для реалізації. Однак клієнти, що викликають тонкий інтерфейс, мають писати більше коду. Маючи менший вибір методів, що можна викликати, вони мають менший за ідеальний вибір для своїх потреб, та пишуть додатковий код, щоб використати його.

Інтерфейси Java більш часто тонкі, ніж багаті. Наприклад, `CharSequence`, що був введений в Java 1.4, є тонким інтерфейсом, загальним для всіх рядок-подібних класів, що містить послідовність символів. Ось його визначення, якщо дивитись на нього як на Scala трейт:
[source,scala]
----
trait CharSequence {
  def charAt(index: Int): Char
  def length: Int
  def subSequence(start: Int, end: Int): CharSequence
  def toString(): String
}
----
Хоча більшість з дюжин методів в класі `String` можна застосувати до любого `CharSequence`, інтерфейс Java `CharSequence` декларує тільки чотири методи. Якщо б `CharSequence` замість цього включав повний інтерфейс `String`, це б наклало великий безлад на реалізаторів `CharSequence`. Кожний програміст, що реалізує `CharSequence` в Java, мав би перевизначати дюжини методів. Оскільки трейти Scala можуть суцільні методи, вони роблять багаті інтерфейси значно більш зручними.

Додавання суцільного метода до трейта схиляє компроміс тонкий-багатий в напрямку багатих інтерфейсів. На відміну від Java, додавання суцільного метода до трейта Scala є одноразовим зусиллям. Вам треба тільки реалізовати метод один раз, в самому трейті, замість потреби повторно реалізовувати його для кожного класу, що міксується з цім трейтом. Таким чином, багаті інтерфейси вимагають меньшої роботи в Scala, ніж в мові без трейтів.

Щоб збагатити інтерфейс з використанням трейтів, просто визначте трейт з малим числом абстрактних методів — тонку частину інтерфейса трейта — та потенційно велике число конкретних методів, всі реалізовані в термінах абстрактних методів. Потім ви можете міксувати збагачений трейт в клас, реалізувати тонку частину інтерфейсу, та опинитись з класом з цілим багатим інтерфейсом.

12.3 Приклад: прямокутні об'єкти
--------------------------------
Графічні біблиотеки часто мають багато різних класів, що представляють дещо прямокутне. Деякими прикладами є вікна, бітові зображення, та регіони, обрані мишею. Щоб зробити ці прямокутні об'єкти зручними для використання, було б гарним, щоб бібліотека провадила геометричні запити, такі як `width`, `height`, `left`, `right`, `topLeft`, і так далі. Однак, існує багато таких методів, які було б добре мати, так що дописувачі бібліотеки мають великий безлад, провадячи їх до всіх прямокутних об'єктів в Java бібліотеці. Якщо така бібліотека була б написана на Scala, для контрасту, дописувач бібліотеки міг би використовувати трейти, щоб з легкістю запропонувати всі ці зручні методи для всіх класів, до яких побажає.

Щоб побачити як це буде, спершу уявімо, як мав би виглядати код без трейтів. Мали б бути базові геометричні класи, як `Point` та `Rectangle`:
[source,scala]
----
class Point(val x: Int, val y: Int)

class Rectangle(val topLeft: Point, val bottomRight: Point) {
  def left = topLeft.x
  def right = bottomRight.x
  def width = right - left
// та більше інших графічних методів...
}
----
Цей клас `Rectangle` приймає дві точки в його первинному конструкторі: координати верхнього-лівого та нижнього-правого кутів. Потім він реалізує багато зручних методів, такі як `left`, `right` та `width`, через виконання простих обчислень на ціх двох точках.

Інший клас графічної бібліотеки може мати 2-D графічний віджет:
[source,scala]
----
abstract class Component {
  def topLeft: Pointdef 
  вуа bottomRight: Point
  def left = topLeft.x
  def right = bottomRight.x
  def width = right - left
// та більше інших графічних методів...
}
----
Зауважте, що визначення `left`, `right` та `width` в точності такі самі в двох класів. Вони також будуть ті самі, крім декількох малих варіацій, в любих інших класах для прямокутних об'єктів.

Ця репрезентація може бути усунута за допомогою збагаючуючого трейта. Трейт буде мати два абстрактні метода: один що повертатиме верхню-ліву координату об'єкта, та інший, що повертає нижню-праву координату. Потім він може надати суцільні реалізації всіх інших геометричних запитів. Лістинг 12.5 показує, як це буде виглядати:
[source,scala]
----
trait Rectangular {
  def topLeft: Point
  def bottomRight: Point
  def left = topLeft.x
  def right = bottomRight.x
  def width = right - left
// та більше інших графічних методів...
}
----
Лістинг 12.5 - Визначення покращеного трейта.

Клас `Component` може зміксувати трейт, щоб отримати всі геометричні методи, що провадить `Rectangular`:
[source,scala]
----
abstract class Component extends Rectangular {
// інші методи...
}
----
Подібно до цього, сам `Rectangle` може міксувати трейт:
[source,scala]
----
class Rectangle(val topLeft: Point, val bottomRight: Point)
  extends Rectangular {
}
// інші методи...
----
Маючи ці визначення, ви можете створити `Rectangle`, та викликати геометричні методи, такі як `width` та `left` на ньому:
[source,scala]
----
scala> val rect = new Rectangle(new Point(1, 1),
           new Point(10, 10))
rect: Rectangle = Rectangle@5f5da68c

scala> rect.left
res2: Int = 1

scala> rect.right
res3: Int = 10

scala> rect.width
res4: Int = 9
----
12.4 Впорядкований трейт
------------------------
Порівняння є інша галузь, де багаті інтерфейси є зручними. Коли ви порівнюєте два об'єкти, що є впорядкованими, зручно, якщо ви використовуєте простий виклик метода, щоб запитати щодо точного порівняння, яке ви бажаєте. Якщо ви бажаєте "менше ніж", ви можете викликати `<`, та якщо ви бажаєте "меньше або рівне", ви бажаєте викликати `<=`. З тонким інтерфейсом порівняння, ви можете мати лише метод `<`, та ви можете іноді писати речі як `(x < y) || (x == y)`. Багаті інтерфейси будуть провадити всі зі звичайних операторів порівняння, таким чином дозволяючи вам писати речі, як `x <= y`.

Перед поглядом на `Ordered`, уявімо, що б ви могли робити без нього. Уявімо, що ви взяли клас `Rational` з Глави 6, та додали до нього операції порівняння:footnote:[Цей приклад базується на класі `Rational`, показаному в Лістингу 6.5, з доданими `equals`, `hashCode` та модифікаціями, що запевняють в позитивному займеннику.]
[source,scala]
----
class Rational(n: Int, d: Int) {
// ...
  def < (that: Rational) =
    this.numer * that.denom < that.numer * this.denom
  def > (that: Rational) = that < this
  def <= (that: Rational) = (this < that) || (this == that)
  def >= (that: Rational) = (this > that) || (this == that)
}
----
Цей клас визначає чотири оператора порівняння (`<`, `>`, `<=`, та `>=`), та це класична демонстрація ціни визначення багатого інтерфейсу. Перше, зауважте, що три оператора порівнянь визначені в термінах першого. Наприклад, `>` визначений як зворотній до `<`, та `<=` визначений буквально як "менше ніж або дорівнює". Далі, зауважте, що всі три з ціх методів будуть ті самі для любого іншого класу, який підтримує порівняння. Немає нічого особливого щодо раціональних чисел відносно `<=`. В контексті порівняння `<=` завжди використовується для позначення "меньше ніж або дорівнює". Загалом, присутнє багато шаблонного коду в цьому класі, який буде тим самим в іншому класі, що реалізує операції порівняння.

Ця проблема така загальна, що Scala провадить трейт щоб допомогти вам з цім. Трейт має назву `Ordered`. Щоб використати його, ви заміняєте всі індивідуальні методи порівняння на єдиний метод `compare`. Потім трейт `Ordered` визначає `<`, `>`, `<=`, та `>=` за вас в термінах цього одного метода. Таким чином, трейт `Ordered` дозволяє вам збагатити клас за допомогою методів порівнянь, через реалізацію тільки одного метода `compare`.

Ось як тепер це виглядає, якщо ви визначите операції порівняння в `Rational` через використання трейта `Ordered`:
[source,scala]
----
class Rational(n: Int, d: Int) extends Ordered[Rational] {
// ...
  def compare(that: Rational) =
    (this.numer * that.denom) - (that.numer * this.denom)
}
----
Існує тільки дві речі, що залишилось зробити. Перше, ця версія `Rational` міксує трейт  `Ordered`. На відміну від трейтів, що ви бачили дотепер, `Ordered` вимагає від вас вказати _параметр типу_, коли ви міксуєте його. Параметри типів не обговорюються в деталях до Глави 19, але поки все що вам треба знати, це що коли ви міксуєте клас з `Ordered`, насправді ви міксуєте `Ordered[C]`, де `C` є класом, елементи якого ми порівнюємо. В цьому випадку `Rational` міксується з `Ordered[Rational]`.

Друга річ, що вам треба зрбити, це визначити метод `compare` для порівняння двох об'єктів. Цей метод буде порівнювати отримувача, `this`, з об'єктом, переданим як аргумент до метода. Він має повертати ціле число, що буде нуль, якщо об'єкти однакові, від'ємне, якщо отримувач менший за аргумент, та додатнє, якщо отримувач більший за аргумент.

В цьому випадку, метод порівняння в `Rational` використовує формулу, базовану на конвертації дрібу до загального займенника, та потім віднімання отриманих чисельників. Маючи цей міксін та визначення `compare`, тепер клас `Rational` має всі чотири методи порівняння:
[source,scala]
----
scala> val half = new Rational(1, 2)
half: Rational = 1/2

scala> val third = new Rational(1, 3)
third: Rational = 1/3

scala> half < third
res5: Boolean = false

scala> half > third
res6: Boolean = true
----
Кожного разу, коли ви реалізуєте клас, що впорядкований згідно деякого порівняння, ви маєте міксувати його з трейтом `Ordered`. Якщо ви зробите це, ви запровадите користувачів класа багатим набором методів порівняння.

Зважайте, що трейт `Ordered` не визначає метод `equals` за вас, оскільки він не може цього зробити. Проблема в тому, що реалізація `equals` в термінах `compare` вимагає перевірки типу переданого об'єкту, та завдяки затиранню типів, сам по собі `Ordered` не може зробити цю перевірку. Таким чином, вам треба самому визначити `equals`, навіть якщо ви наслідуєте `Ordered`. Ви знайдете як це робити в Главі 30.

Повний трейт `Ordered`, мінус коментарі та дещо для сумісності, виглядає так:
[source,scala]
----
trait Ordered[T] {
  def compare(that: T): Int

  def <(that: T): Boolean = (this compare that) < 0
  def >(that: T): Boolean = (this compare that) > 0
  def <=(that: T): Boolean = (this compare that) <= 0
  def >=(that: T): Boolean = (this compare that) >= 0
}
----
Не дуже турбуйтесь щодо `T` та `[T]`. Тут `T` є параметром типу, як описано в деталях в Главі 19. Для розуміння трейту `Ordered` просто думайте про нього, як про "той самий тип, що і отримувач". Потім ви можете бачити, що цей трейт визначає один абстрактний метод, `compare`, що, як очікується, буде порівнювати отримувач (`this`) з іншим об'єктом того самого типу, що і отримувач (`that`). Маючи цей метод, `Ordered` може провадити суцільні визначення для `<`, `>`, `<=` та `>=`.

12.5 Трейти як накладувані модифікації
--------------------------------------
Тепер ви бачили одне головне затосування трейтів: перетворення тонких інтерфейсів в багаті. Тепер ми звернемось до другого головного застосування: провадити накладувані модифікації для класів. Трейти дозволяють _модифікувати_ методи класів, і вони роблять це в такий спосіб, що дозволяє вам накладати ці модифікації одне на одне.

Як приклад, розглянемо накладання модифікацій для церги з цілих чисел. Черга буде мати дві операції: `put`, що покладає цілі в чергу, та `get`, що вибирає їх звідси. Черги побудовані як перший-увійшов перший-вийшов, так що `get` повинен повертати цілі в тому ж порядку, в якому вони були покладені `put` в чергу.

Маючи клас, що реалізує таку чергу, ви можете визначити трейти для виконання модифікацій, як такі:

* Doubling: подвоює всі цілі, що поставлені в чергу
* Incrementing: збільшує всі цілі, що поставлені в чергу
* Filtering: відфільтровує від'ємні цілі з черги

Ці три трейти представляють модифікації, оскільки вони модифікують поведінку класу підлеглої черги, скоріше, ніж самому визначати повний клас черги. Ці три також можна накладувати один на одний. Ви можете обрати любі з ціх трьох, зміксувати їх в клас, та отримати новий клас, який матиме всі модифікації, що ви обрали.

Абстрактний клас `IntQueue` показаний на Лістингу 12.6. `IntQueue` має метод `put`, що додає нові цілі до черги, та метод `get`, що видлаяє та повертає їх. Базова реалізація `IntQueue`, що використовує `ArrayBuffer`, показана в Лістингу 12.7.
[source,scala]
----
abstract class IntQueue {
  def get(): Int
  def put(x: Int)
}
----
Лістинг 12.6 - Абстрактний клас `IntQueue`.

[source,scala]
----
import scala.collection.mutable.ArrayBuffer

class BasicIntQueue extends IntQueue {
  private val buf = new ArrayBuffer[Int]
  def get() = buf.remove(0)
  def put(x: Int) = { buf += x }
}
----
Лістинг 12.7 - `BasicIntQueue` реалізований з допомогою `ArrayBuffer`.

Клас `BasicIntQueue` має приватне поле, що містить буферний масив. Метод `get` видаляє входження з одного кінця буфера, тоді як метод `put` додаєж елементи з іншого кінця. Ось як ця реалізація виглядає, коли ви використовуєте її:
[source,scala]
----
scala> val queue = new BasicIntQueue
queue: BasicIntQueue = BasicIntQueue@23164256

scala> queue.put(10)
scala> queue.put(20)
scala> queue.get()
res9: Int = 10

scala> queue.get()
res10: Int = 20
----
Доки все добре. Тепер поглянемо на використання трейтів для модифікації цієї поведінки. Лістинг 12.8 показує трейт, що подвоює цілі, по мірі того, як воні покладаються в чергу. Трейт `Doubling` має дві цікаві речі, що відбуваються. Перша це те, що він декларує суперклас `IntQueue`. Ця декларація означає, що трейт може бути міксований в клас, що також розширює `IntQueue`. Таким чином, ви можете міксувати `Doubling` в `BasicIntQueue`, але не в `Rational`.
[source,scala]
----
trait Doubling extends IntQueue {
  abstract override def put(x: Int) = { super.put(2 * x) }
}
----
Лістинг 12.8 - Трейт накладуваної модифікації `Doubling`.

Друга цікава річ в тому, що трейт має супер виклик на методі, що визначений як абстрактний. Такі виклики нелегальні для звичайних класів, оскільки вони напевне будуть схиблювати під час виконання. Однак для трейта такий виклик насправді може бути успішним. Оскільки супер виклики в трейті динамічно зв'язані, супер виклик в трейті `Doubling` буде робити до тих пір, доки трейт міксований після іншого трейта або класа, що надає суцільне визначення методу.

Цей механізм часто потрібний для трейтів, коли реалізуються накладувані модифікації. Щоб сказати компілятору, що ви робите це навмисно, ви маєте позначити такі методи як `abstract override`. Ця комбінація модифікаторів дозволена тільки для членів трейтів, не класів, і це означає, що трейт має бути зміксований в деякий клас, що має суцільне визначення розглядуваного метода.

З таким простим трейтом можливі багато речей! Ось як виглядає використання цього трейта:
[source,scala]
----
scala> class MyQueue extends BasicIntQueue with Doubling
defined class MyQueue

scala> val queue = new MyQueue
queue: MyQueue = MyQueue@44bbf788

scala> queue.put(10)

scala> queue.get()
res12: Int = 20
----
В першому рядку цієї сессії інтерпретатора ми визначаємо клас `MyQueue`,що розширює `BasicIntQueueand` з міксованим `Doubling`. Потім ми покладаємо `10` в чергу, але оскільки був доміксований `Doubling`, `10` було подвоєне. Коли ви отримаєте ціле з черги, це буде 20.

Зауважте, що `MyQueue` не визначає новий код. Він просто ідентифікує клас та міксує трейт. В цій ситуації ви можете просто надати `BasicIntQueue with Doubling` напряму до `new`, замість визначення іменованого класу. Це буде виглядати як показано в Лістингу 12.9:
[source,scala]
----
scala> val queue = new BasicIntQueue with Doubling
queue: BasicIntQueue with Doubling = $anon$1@141f05bf

scala> queue.put(10)

scala> queue.get()
res14: Int = 20
----
Лістинг 12.9 - Міксування трейту при створенні екземпляру за допомогою `new`.

Щоб побачити, як накладати модифікації, нам треба визначити інша два трейта модифікації, `Incrementing` та `Filtering`. Реалізації ціх трейтів показані в Лістингу 12.10:
[source,scala]
----
trait Incrementing extends IntQueue {
  abstract override def put(x: Int) = { super.put(x + 1) }
}

trait Filtering extends IntQueue {
  abstract override def put(x: Int) = {
    if (x >= 0) super.put(x)
  }
}
----
Лістинг 12.10 - Накладувані модифікації в вигляді трейтів `Incrementing` та `Filtering`.

Маючи ці модифікації ви можете тепер обирати, які саме ви бажаєте застосувати для певної черги. Наприклад, ось черга, що одначасно фільтрує від'ємні числа та додає одиницю до всіх чисел, які вона містить:
[source,scala]
----
scala> val queue = (new BasicIntQueue
with Incrementing with Filtering)
queue: BasicIntQueue with Incrementing with Filtering...

scala> queue.put(-1); queue.put(0); queue.put(1)

scala> queue.get()
res16: Int = 1

scala> queue.get()
res17: Int = 2
----
Порядок міксінів важливий.footnote:[Коли трейт заміксований в клас, ви можете альтернативно називати його міксін.] Точні правила надаються в наступному розділі, але грубо кажучи, трейти, що стоять більш зправа, набувають чинності перші. Коли ви викликаєте метод або клас на міксіні, метод в трейті, що правіший, буде викликаний першим. Якщо метод визиває `super`, він викликає наступний трейт, що лівіше, і так далі. В попередньому прикладі `Filtering` `put` викликається першим, так що він для початку видаляє від'ємні цілі. `Incrementing` `put` викликається другим, так що він додає одиницю до цілих, що залишились.

Якщо ви вмінити порядок, цілі спочатку будуть збільшені, та потім цілі, що все ще від'ємні, будуть відкинуті:
[source,scala]
----
scala> val queue = (new BasicIntQueue
           with Filtering with Incrementing)
queue: BasicIntQueue with Filtering with Incrementing...

scala> queue.put(-1); queue.put(0); queue.put(1)

scala> queue.get()
res19: Int = 0

scala> queue.get()
res20: Int = 1

scala> queue.get()
res21: Int = 2
----
Загалом, код, що написаний в такому стилі дає вам добрі можливості щодо гнучкості. Ви можете визначити шістнадцять різних класів, міксуючи ці три трейти в різних комбінаціях на порядках. Це багато гнучкості для невеликого обсягу коду, так що ви маєте тримати очі відкритими в пошуках можливостей втілити в коді накладувані модифікації.

12.6 Чому не множинне наслідування?
-----------------------------------
Трейти є шляхом наслідувати від багатьох класо-подібних конструкцій, але вони відрізняються в важливий спосіб від множинного наслідування, що присутнє в інших мовах. Одна різниця є особливо важливою: інтерпретація `super`. З множинним наслідуванням метод, що викликається через `super` може бути викликаний саме там, де відбувається виклик. З трейтами викликаний метод визначається через лінеарізацію класів та трейтів, зміксованих в клас. Ця різниця дозволяє накладання модифікацій, описану в попередньому розділі.

Перед тим, як поглянути на лінеарізацію, ми витратимо момент, та розглянемо, як накладати модифікації в мові з традиційним множинним наслідуванням. Уявімо наступний код, але на цей раз інтерпретований як множинне наслідування замість міксування трейтів:
[source,scala]
----
// Множинне наслідування як експерімент
val q = new BasicIntQueue with Incrementing with Doubling
q.put(42) // який put має бути викликаний?
----
Перше питання: який метод `put` буде викликаний, коли робиться цей виклик? Можливо, правило буде таке, що останній суперклас перемагає, в якому випадку буде викликаний `Doubling`. `Doubling` подвоїть свій аргумент, та викличе `super.put`, і це вже буде кінець. Інкрементація не відбудеться! Так само, якщо правило буде таке, що перший суперклас перемагає, отримана черга буде збільшувати цілі, але не подвоювати їх. Так що жодний порядок не буде робити.

Ви можете також прокрутити таку можливість: дозволити програмістам вказати, який метод суперкласу вони мають на увазі, коли кажуть `super`. Наприклад, уявімо наступний Scala-подібний код, в якому `super` явно викликається на обох, `Incrementing` та `Doubling`:
[source,scala]
----
// Експерименти з множинним наслідуванням
trait MyQueue extends BasicIntQueue
    with Incrementing with Doubling {
  def put(x: Int) = {
    Incrementing.super.put(x) // (Несправжня Scala)
    Doubling.super.put(x)
  }
}
----
Цей підхід дає нам нові проблеми (балакучість цього підходу є найменьшою з його проблем). Що відбудеться, це те, що метод `put` базового класу буде викликано двічі, перший раз для збільшеного значення, та ще раз для подвоєного значення, але жодного разу для збільшеного та подвоєного значення.

Просто не існує гарного рішення цієї проблеми з використанням множинного наслідування. Вам доведеться переробити код в інший спосіб. Для контрасту, рішення з трейтами в Scala є прямолінійним. Ви просто міксуєте `Incrementing` та `Doubling`, та спеціальне трактування super в трейтах Scala робить всю іншу роботу. Тут дещо чітко відрізняється від традиційного множинного наслідування, але що? Як ми натякали перед цім, відповідь є лінеарізація. Коли ми створюємо примірник класу за допомогою `new`, Scala бере клас та всі його унаслідувані класи та трейти, та шакує їх в єдиний, лінійний порядок. Тоді,якщо ви викликаєте `super` в одному з ціх класів, викликаний метод є наступним в черзі. Якщо всі методи, крім останнього, викликають `super`, чистим результатом буде накладання поведінки.

Точний порядок лінеарізації описаний в специфікації мови. Він трохи заскладний, але головна річ, що вам треба знати, це що при любій лінеаризації клас клас завжди лінеаризується перед усіма своїми суперкласами та доміксованими трейтами. Таким чином, коли ви пишете метод, що викликає `super`, цей метод напевне модифікує поведінку суперкласів і зміксованих трейтів, і іншого шляху немає.

NOTE: Залишок цього розділу описує деталі лінеаризації. Ви можете безпечно пропустити залишок цього розділу, якщо ви не зацікавлені розуміти ці деталі просто зараз.

Головні властивості лінеаризації Scala проілючтровані на наступному прикладі: скажімо, ви маєте клас `Cat`, що наслідує від суперкласа `Animal`, та двох супертрейтів, `Furry` та `FourLegged`. `FourLegged`, в свою чергу, розширює трейт `HasLegs`:
[source,scala]
----
class Animal
trait Furry extends Animal
trait HasLegs extends Animal
trait FourLegged extends HasLegs
class Cat extends Animal with Furry with FourLegged
----
Ієрархія наслідування та лінеаризація класу Cat показана на Малюнку 12.1. Наслідування використовує традиційну UML нотацію:footnote:[Rumbaugh, et. al., The Unified Modeling Language Reference Manual. [Rum04\]] стрілки з білими трикутними наконечниками означають наслідування, стрілки вказують на супертипи. Стрілки з темнішими, не трикутними наконечниками позначають лінеаризацію. Темніші стрілки вказують в напрямку, в якому будуть розрішуватись виклики `super`.

Малюнок 12.1 - Ієрархія наслідування і лінеарізація класу Cat.

Лінеаризація `Cat` обчислюється яз кінця в начало наступним чином. Остання частина лінеаризації `Cat` є лінеаризація його суперкласу `Animal`. Ця лінеаризація копіюється без всяких змін. (Лінеаризація кожного з ціх типів показана в Таблиці 12.) Оскільки  `Animal` явно не розширює суперклас, або не міксує якийсь трейт, він по замовчанню розширює `AnyRef`, що розширює `Any`. Таким чином лінеаризація `Animal` виглядає так:

Друга з кінця частина є лінеаризація першого міксіна, трейта `Furry`, але всі класи, що вже знаходяться в лінеаризації `Animal` тепер відкидаються, так що кожний клас з'являється тільки один раз в лінеаризації `Cat`. Результат такий:

За цім слідує лінеаризація `FourLegged`, де знову любі класи, що вже були скопійовані в лінеаризації суперкласів або першого міксіну відкидаються:

Нарешті, перший клас в лінеаризації `Cat` є сам `Cat`:

Коли кожний з ціх класів та трейтів викликає метод через `super`, викликається реалізація, що буде першою реалізацією зправа в лінеаризації.

[caption="Таблиця 12.1 "]
.Лінеарізація типів в ієрархії Cat
[cols="1,5",options="header"]
|===
^| Тип ^| Лінеаризація
>| Animal | Animal, AnyRef, Any
>| Furry  | Furry, Animal, AnyRef, Any
>| FourLegged |FourLegged, HasLegs, Animal, AnyRef, Any
>| HasLegs | HasLegs, Animal, AnyRef, Any
>| Cat | Cat, FourLegged, HasLegs, Furry, Animal, AnyRef, Any
|===

12.7 Чи використовувати трейти?
-------------------------------
Коли ви реалізуєте повторно використовувану колекцію поведінок, ви повинні прийняти рішення, чи ви бажаєте використати трейт або абстрактний клас. Немає надійного правила, але цей розділ містить декілька настанов, які треба зважити.

_Якщо поведінка не буде використовуватись повторно_, тоді робіть суцільний клас. Кінець кінцем це не повторно використовувана поведінка.

_Якщо вона може бути використана в декількох непов'язаних класах_, зробіть трейт. Тільки трейти можуть бути зміксовані в різні частини ієрархії класів.

_Якщо ви бажаєте наслідувати від поведінки в Java коді_, використовуйте абстрактний клас. Оскільки трейти з кодом не мають близького Java аналогу, як правило незручно наслідувати від трейта в Java класі. В той же час, наслідувати від Scala класу є точно таким же, як наслідування від Java класу. Як одне виключення, трейт Scala з тільки одними абстрактними членами транслюється напряму в Java інтерфейс, так що ви можете вільно визначати такі трейти, навіть якщо очікуєте, що Java код буде наслідувати від них. Дивіться Розділ 31 щодо додаткової інформації по роботі з Java та Scala разом.

_Якщо ви плануєте розповсюджувати це в компільованій формі_, та ви очікуєте, що зовнішні групи будуть писати класи з наслідуванням від вашого коду, ви можете трохи ухилитись, використовуючи абстрактний клас. Проблема в тому, що коли трейт отримує або втрачає член, любі класи, що наслідують від нього, мають бути перекомпільовані, навіть якщо вони не змінились. Якщо зовнішні клієнти будуть тільки викликати поведінку, замість наслідувати від неї, тоді використання трейтів є гарним.

_Якщо ви все ще не знаєте_, навіть після розляду питань вище, тоді починайте створивши трейт. Ви завжди можете поміняти це пізніше, і, загалом, трейт тримає більше опцій відкритими.

12.8 Висновок
-------------
Ця глава показала вам як роблять трейти, та як використовувати їх в декількох загальних ідіомах. Ви побачили, як трейти подібні до множинного наслідування. Але, оскілкьи трейти інтерпретують `super` з використанням лінеаризації, вони одночасно уникають деяких складнощей традиційного множинного наслідування, та дозволяють вам накладати поведінку. Ви також бачили трейт `Ordered`, та навчились, як писати ваші власні збагачуючі трейти.

Тепер, коли ви побачили всі ці грані, має сенс відступити назад, та зробити ще один погляд на трейти як на ціле. Трейти не тільки просто підтримують ідіоми, описані в цій главі; вони є фундаментальною одиницею коду, що повторно використовується через інтерфейс. Ось чому багато досвідчених Scala програмістів починають з трейтів, коли вони знаходяться на ранішній стадії реалізації. Кожний трейт може містити меньше ніж цілу концепцію, а тільки фрагмент концепції. По мірі застигання розробки фрагменти можуть бути скомбіновані в більш цілісні концеації через міксування трейтів.
