include::headers.adoc[]

Глава 17
--------

Робота з іншими колекціями
==========================

Scala має багату бібліотеку колекцій. Ця глава дає вам тур по найбільш загально уживаних типах колекцій та операціях, показуючи тільки частини, які ви будете використовувати найбільш часто. Глава 24 провадить більш повний тур по тому, що доступно, та Глава 25 покаже, як конструкції композиції Scala використовуються для провадження такого багатого API.

17.1 Послідовності
------------------
Типи послідовностей дозволяють вам робити з групами даних, впорядкованих один за одним. Оскільки елементи впорядковані, ви можете запросити перший елемент, другий елемент, 103й елемент, і так далі. В цій главі ми дамо вам короткий тур по найбільш важливим послідовностям.

Списки
~~~~~~
Можливо, найбільш важливий тип послідовністі, про який треба знати, це клас `List`, незмінний пов'язаний список, описаний в деталях в попередній главі. Списки підтримують швидке додавання та видалення елементів з початку списку, але вони не провадять швидкого доступу до довільних індексів, оскільки реалізація має лінійно ітерувати вздовж всього списку.

Ця комбінація можливостей може виглядати дивною, але вони б'ють в яблучко, та гарно роблять з багатьма алгоритмами. Швидке додавання та видалення перших елементів означає, що порівняння шаблонів також робить гарно, як описано в Главі 15. Незмінність списків допомагає вам розробляти коректні, ефективні алгоритми, тому що вам ніколи не треба робити копії зі списків.

Ось короткий приклад, що показує, як ініціалізувати список, та отримати доступ до його голови та хвоста:
[source,scala]
----
scala> val colors = List("red", "blue", "green")
colors: List[String] = List(red, blue, green)

scala> colors.head
res0: String = red

scala> colors.tail
res1: List[String] = List(blue, green)
---- 
Щоб нагадати собі про списки, дивіться Крок 8 в Главі 3. Ви можете знайти деталі використання списків в Главі 16. Списки також обговорюються в Главі 22, що провадить погляд на те, як списки реалізовані в Scala.

Масиви
~~~~~~
Масиви дозволяють вам зберігати послідовність елементів, та ефективно отримувати доступ до елемента в довільній позиції, або отримуючи, або оновлюючі елемент, рахуючи від нульового індексу. Ось як ви створюєте масив, розмір якого ви знаєте, але для якого ви досі не знаєте значень елементів:
[source,scala]
----
scala> val fiveInts = new Array[Int](5)
fiveInts: Array[Int] = Array(0, 0, 0, 0, 0)
----
Ось як ви ініціалізуєте масив, коли ви знаєте значення елементів:
[source,scala]
----
scala> val fiveToOne = Array(5, 4, 3, 2, 1)
fiveToOne: Array[Int] = Array(5, 4, 3, 2, 1)
----
Як зазначалось раніше, масиви мають доступ в Scala, розташовуючи індекс в дужки, не в прямокутні дужки, як в Java. Ось приклад обох, доступу та зміни елемента масива:
[source,scala]
----
scala> fiveInts(0) = fiveToOne(4)

scala> fiveInts
res3: Array[Int] = Array(1, 0, 0, 0, 0)
----
Масиви Scala представлені в той самий спосіб, що і масиви Java. Так що ви можете без проблем використовувати існуючі методи Java, що повертають масиви.footnote:[Різниця в варіантності масивів Scala та Java — тобто, коли `Array[String]` є субтипом `Array[AnyRef]` — це буде розглядатись в Розділі 19.3.]

Ви мали бачити масиви в дії багато раз в попередніх главах. Основи в Кроці в Главі 3. Декіклька прикладів ітерування по елементах масивів за допомогою вираза `for` показані в Розділі 7.3. Масиви також яскраво фігурують в бібліотеці двомірних розташувань в Главі 10.

Буфери списків
~~~~~~~~~~~~~~
Клас `List` провадить швидкий доступ до голови списку, але не до кінця. Таким чином, коли вам треба побудувати список через додавання в кінець, розгляньте побудування списку навпаки, додаючи елементи до начала. Коли ви скінчите, викличте `reverse`, щоб отримати елементи в порядку, що вам потрібен.

Інша альтернатива, що уникає операції `reverse`, це використання `ListBuffer`. `ListBuffer` є змінним об'єктом (що міститься в пакунку `scala.collection.mutable`), що може допомогти вам побудувати списки більш ефективно, коли вам треба дописувати в кінець. `ListBuffer` провадить сталий час виконання операцій додавання з обох кінців. Ви додаєте елементи за допомогою оператора `+=`, та ставите на початок за допомогою оператора `+=:`. Коли ви завершуєте побудову, ви можете отримати `List` через виклик `toList` на `ListBuffer`. Ось приклад:
[source,scala]
----
scala> import scala.collection.mutable.ListBuffer
import scala.collection.mutable.ListBuffer

scala> val buf = new ListBuffer[Int]
buf: scala.collection.mutable.ListBuffer[Int] = ListBuffer()

scala> buf += 1
res4: buf.type = ListBuffer(1)

scala> buf += 2
res5: buf.type = ListBuffer(1, 2)

scala> buf
res6: scala.collection.mutable.ListBuffer[Int] =
ListBuffer(1, 2)

scala> 3 +=: buf
res7: buf.type = ListBuffer(3, 1, 2)

scala> buf.toList
res8: List[Int] = List(3, 1, 2)
----
Інша причина використовувати `ListBuffer` замість `List` є запобігання потенційному переповненню стека. Якщо ви можете будувати список в бажаному порядку, додаючи спереду, але потрібний рекурсивний алгоритм не має хвостової рекурсії, замість цього ви можете використовувати вираз `for` або цикл `while` разом з `ListBuffer`. Ви побачите, як `ListBuffer` буде використаний в цей спосіб в Розділі 22.2.

Буфери масивів
~~~~~~~~~~~~~~
`ArrayBuffer` подібний до масиву, за виключенням того, що ви можете додавати елементи з початку та з кінця послідовності. Доступні всі операції з масивами `Array`, хоча вони трохі повільніші, через прошарок обгортки в реалізації. Нові операції додавання та видалення мають сталий час в середньому, але часом потребують лінійного часу, бо реалізація потребує розміщувати новий масив, щоб зберігати вміст буфера.

Щоб використовувати `ArrayBuffer`, ви маєте спочатку імпортувати його з пакунку змінних колекцій:
[source,scala]
----
scala> import scala.collection.mutable.ArrayBuffer
import scala.collection.mutable.ArrayBuffer
----
Коли ви створюєте `ArrayBuffer`, ви маєте вказати параметр типу, але ви не маєте вказувати довжину. `ArrayBuffer` буде підлаштовувати розміщений простір автоматично, по мірі необхідності:
[source,scala]
----
scala> val buf = new ArrayBuffer[Int]()
buf: scala.collection.mutable.ArrayBuffer[Int] =
ArrayBuffer()
----
Ви можете додавати до `ArrayBuffer` з використанням метода `+=`:
[source,scala]
----
scala> buf += 12
res9: buf.type = ArrayBuffer(12)

scala> buf += 15
res10: buf.type = ArrayBuffer(12, 15)

scala> buf
res11: scala.collection.mutable.ArrayBuffer[Int] =
ArrayBuffer(12, 15)
----
Доступні всі методи нормальних масивів. Наприклад, ви можете запитати в `ArrayBuffer` його довжину, або ви можете отримати елемент по його індексу:
[source,scala]
----
scala> buf.length
res12: Int = 2

scala> buf(0)
res13: Int = 12
----
Рядки (через `StringOps`)
~~~~~~~~~~~~~~~~~~~~~~~~~
Ще одна послідовність, про яку треба знати, це `StringOps`, що реалізує багато методів послідовностей. Оскільки `Predef` має неявне перетворення від `String` до `StringOps`, ви можете трактувати любий рядок як послідовність. Ось приклад:
[source,scala]
----
scala> def hasUpperCase(s: String) = s.exists(_.isUpper)
hasUpperCase: (s: String)Boolean

scala> hasUpperCase("Robert Frost")
res14: Boolean = true

scala> hasUpperCase("e e cummings")
res15: Boolean = false
----
В цьому прикладі метод `exists` викликається на рядку на ім'я `s` в тілі методу `hasUpperCase`. Оскільки в самому класі String немає декларованого метода на ім'я `exists`, компілятор Scala буде неявно конвертувати `s` до `StringOps`, що має такий метод. Метод `exists` трактує рядок як послідовність символів, та буде повертати `true`, якщо любий з символів в верхньому реєстрі:[Код, наданий в Главі 1, презентує подібний приклад.]

17.2 Множини та мапи
--------------------
Ви вже бачили основи множин та мап в попередніх главах, починаючи з Кроку 10 в Главі 3. В цьому розділі ми маємо намір краще зрозуміти їх використання, та покажемо вам ще декілька прикладів.

Як вже зазначалось, бібліотека колекцій Scala пропонує обоє, змінні та незмінні версії множин та мап. Ієрархія для множин показана на Малюнку 3.2, і ієрархія для мап на Малюнку 3.3. Як показують ці діаграми, прості імена `Set` та `Map` використовуються трьома трейтами кожний, що знаходяться в різних пакунках.

По замовчанню, коли ви пишете `Set` або `Map`, ви отримаєте незмінний об'єкт. Якщо ви бажаєте змінний варіант, вам треба зробити явний імпорт. Scala дає вам простіший доступ до незмінних варіантів, як м'яке заохочення обирати їх, ніж їх змінні двійники. Простий доступ провадиться через об'єкт `Predef`, що неявно імпортується в кожний джерельний файл Scala. Лістинг 17.1 показує відповідні визначення:
[source,scala]
----
object Predef {
  type Map[A, +B] = collection.immutable.Map[A, B]
  type Set[A] = collection.immutable.Set[A]
  val Map = collection.immutable.Map
  val Set = collection.immutable.Set
  // ...
}
----
Лістинг 17.1 - Визначення по замовчанню для мап на множин в `Predef`.

Ключове слово `type` використовується в `Predef` для визначення `Set` та `Map`, як псевдонимів для довших, повністю кваліфікованих імен незмінних трейтів множин та мап.footnote:[Ключове слово `type` буде пояснено більш детально в Розділі 20.6.] Змінні `val` на ім'я  `Set` та `Map` ініціалізовані для посилань на об'єкти синглтони для незмінних `Set` та `Map`. Так що `Map` те саме, що `Predef.Map`, що визначений бути тим самий, що і `scala.collection.immutable.Map`. Це дотримується так само для типу `Map`, та об'єкта `Map`.

Якщо ви бажаєте використовувати обоє, змінні та незмінні множини та мапи в тому самому джерельному файлі, один підхід є імпортувати ім'я пакунку, що містить змінні варіанти:
[source,scala]
----
scala> import scala.collection.mutable
import scala.collection.mutable
----
Ви можете продовжувати посилатись на незмінні множини як `Set`, як і раніше, але тепер можете посилатись на змінну множину як на `mutable.Set`. Ось приклад:
[source,scala]
----
scala> val mutaSet = mutable.Set(1, 2, 3)
mutaSet: scala.collection.mutable.Set[Int] = Set(1, 2, 3)
----
Використання множин
~~~~~~~~~~~~~~~~~~~
Ключева характеристика множин в тому, що вони будуть гарантувати щонайбільше одне входження об'єкту, в терміних `==`, що буде міститись в множині в кожний момент часу. Як приклад, ми будемо використовувати множину для підрахунку кількості різних слів в рядку.

Метод `split` на `String` може розділити рядок на слова, якщо ви вкажете проміжки та символи пунктуації в якості роздільників слів. Регулярний вираз `"[ !,.]+"` буде достатнім: він вказує, що рядок має бути розділений в кожному місці, де є один або більше проміжків та/або символів пунктуації.
[source,scala]
----
scala> val text = "See Spot run. Run, Spot. Run!"
text: String = See Spot run. Run, Spot. Run!

scala> val wordsArray = text.split("[ !,.]+")
wordsArray: Array[String]
= Array(See, Spot, run, Run, Spot, Run)
----
Щоб підрахувати різні слова, ви можете конвертувати їх в однаковий реєстр, та додати їх до множини. Оскільки множини виключають дублікати, кожне окреме слово буде з'являтись в множині рівно один раз.

Перше, ви можете створити порожню множину, використовуючи порожній метод, впроваджений об'єктом компанйоном `Set`:
[source,scala]
----
scala> val words = mutable.Set.empty[String]
words: scala.collection.mutable.Set[String] = Set()
----
Потім просто ітеруєте по словах за допомогою `for` виразу, конвертуєте кожне слово в нижній реєстр, та додаваєте його до змінної множини оператором `+=`:
[source,scala]
----
scala> for (word <- wordsArray)
words += word.toLowerCase

scala> words
res17: scala.collection.mutable.Set[String] =
Set(see, run, spot)
----
Таким чином, текст містив рівно три відмінні слова: `spot`, `run`, та `see`. Найбільш загально використовувані методи для обох, змінних та незмінних множин, показані в Таблиці 17.1.

[caption="Таблиця 17.1 "]
.Базові операції для множин
[cols="1,2",options="header"]
|===
^| Що таке ^| Що робить
|`val nums = Set(1, 2, 3)`|Створює незмінну множину (`nums.toString returnsSet(1, 2, 3)`)
|`nums + 5`|Додає елемент (повертає `Set(1, 2, 3, 5)`)
|`nums - 3`|Видаляє елемент (повертає `Set(1, 2)`)
|`nums ++ List(5, 6)`|Додає декілька елементві (повертає `Set(1, 2, 3, 5, 6)`)
|`nums -- List(1, 2)`|Видаляє декілька елементів (повертає `Set(3)`)
|`nums & Set(1, 3, 5, 7)`|Робить перетин двох множин (повертає `Set(1, 3)`)
|`nums.size`|Повертає розмір множини (повертає `3`)
|`nums.contains(3)`|Перевіряє входження (повертає `true`)
|`import scala.collection.mutable`|Робить змінні колекції простими для доступу
|`val words = mutable.Set.empty[String]`|Створює порожню змінну множину (`words.toString` повертає `Set()`)
|`words += "the"`|Додає елемент (`words.toString` повертає `Set(the)`)
|`words -= "the"`|Видаляє елемент, якщо він існує (`words.toString` повертає `Set()`)
|`words ++= List("do", "re", "mi")`|Додає декілька елементів (`words.toString` повертає `Set(do, re, mi)`)
|`words --= List("do", "re")`|Видаляє декілька елементів (`words.toString` повертає `Set(mi)`)
|`words.clear`|Видаляє всі елементи (`words.toString` повертає `Set()`)
|===

Використання мап
~~~~~~~~~~~~~~~~
Мапи дозволяють асоціювати значення з кожним елементом множини. Використання мапи виглядає подібним до використання масива, за винятком того, що замість індексування цілими числами, рахуючи від `0`, ви можете використовувати любий різновид ключів. Якщо ви імпортуєте ім'я зі змінного пакунку, ви можете створити порожню змінну мапу, ось так:
[source,scala]
----
scala> val map = mutable.Map.empty[String, Int]
map: scala.collection.mutable.Map[String,Int] = Map()
----
Зауважте, що коли ви створюєте мапу, ви маєте задати два типи. Перший тип для ключів мапи, та другий для значень. В цьому випадку ключі є рядками, та значення є цілими. Встановлення значень для мапи виглядає подібно для встановлення елементів в масиві:
[source,scala]
----
scala> map("hello") = 1

scala> map("there") = 2

scala> map
res20: scala.collection.mutable.Map[String,Int] =
    Map(hello -> 1, there -> 2)
----
Подібно до цього, читання мапи подібне до читання масиву:
[source,scala]
----
scala> map("hello")
res21: Int = 1
----
Складаючи все це разом, ось метод, що підраховує число раз, скільки разів кожне слово страпляється в рядку:
[source,scala]
----
scala> def countWords(text: String) = {
          val counts = mutable.Map.empty[String, Int]
          for (rawWord <- text.split("[ ,!.]+")) {
            val word = rawWord.toLowerCase
            val oldCount =
              if (counts.contains(word)) counts(word)
              else 0
            counts += (word -> (oldCount + 1))
          }
          counts
        }

countWords: (text:
String)scala.collection.mutable.Map[String,Int]

scala> countWords("See Spot run! Run, Spot. Run!")
res22: scala.collection.mutable.Map[String,Int] =
    Map(spot -> 2, see -> 1, run -> 3)
----
Маючи ці підрахунки, ви можете бачити, що цей текст каже більше про біг, та меньше про бачення.

Спосіб, як робить цей код, в тому, що змінна мапа на ім'я `counts` відзеркалює кожне слово на кількість раз, скількі воно трапляється в тексті. Для кожного слова в тексті спочатку шукається старий лічильник, що збільшується на одиницю, та потім зберігається назад в `counts`. Зауважте використання `contains` для перевірки, чи слово вже відоме, чи ні. Якщо `counts.contains(word)` не є `true`, тоді слово ще невідоме, та для лічильника використовується нуль.

Багато з загально уживаних методів, на обох, змінних та незмінних мап, показані в Таблиці Table 17.2.

[caption="Таблиця 17.2 "]
.Загальні операції для мап
[cols="1,2",options="header"]
|===
^| Що таке ^| Що робить

|`val nums = Map("i" -> 1, "ii" -> 2)`
|Створює незмінну мапу (`nums.toString` повертає `Map(i -> 1, ii -
> 2))`

|`nums + ("vi" -> 6)`
|Додає елемент (повертає `Map(i -> 1, ii -> 2, vi -> 6)`)

|`nums - "ii"`|Видаляє елемент (повертає `Map(i -> 1)`)

|`nums ++ List("iii" -> 3, "v" -> 5)`
|Додає декілька елементів (повертає `Map(i -> 1, ii -> 2, iii -> 3, v -> 5)`)

|`nums -- List("i", "ii")`
|Видаляє декілька елементів (повертає `Map()`)

|`nums.size`|Повертає розмір мапи (повертає `2`)
|`nums.contains("ii")`|Перевіряє входження (повертає `true`)
|`nums("ii")`|Отримує значення вказаного ключа (повертає `2`)

|`nums.keys`
|Повертає ключі (повертає `Iterable` по рядках `"i"` та `"ii"`)

|`nums.keySet`|Повертає ключі як множину (повертає `Set(i, ii)`)

|`nums.values`
|Повертає значення (повертає `Iterable` по цілим `1` та `2`)

|`nums.isEmpty`
|Визначає, чи мапа порожня (повертає `false`)

|`import scala.collection.mutable`|Спрощує досутп до змінних колекцій

|`val words = mutable.Map.empty[String, Int]`
|Створює порожню змінну мапу

|`words += ("one" -> 1)`
|Додає елемент мапи з `"one"` до `1` (`words.toString` повертає `Map(one -> 1)`)

|`words -= "one"`
|Видаляє елемент мапи, якщо він існує (`words.toString` повертає `Map()`)

|`words ++= List("one" -> 1, "two" -> 2, "three" -> 3)`
|Додає декілька елементів мапи (`words.toString` повертає `Map(one -
> 1, two -> 2, three -> 3)`)

|`words --= List("one", "two")`
|Видаляє декілька об'єктів (`words.toString` повертає `Map(three -> 3)`)
|===

Множини та мапи по замовчанню
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Для більшості застосувань реалізації змінних та незмінних множин та мап, запроваджені фабриками `Set()`, `scala.collection.mutable.Map()`, тощо, скоріше будуть достатніми. Реалізації, проваджені ціми фабриками, використовують алгоритм швидкого пошуку, який звичайно задіє хеш таблицю, так що вони можуть швико вирішити, є або ні об'єкт в колекції.

Наприклад, метод фабрики `scala.collection.mutable.Set()` повертає  `scala.collection.mutable.HashSet`, що внутрішньо використовує хеш таблицю. Подібно, фабрика `scala.collection.mutable.Map()` повертає `scala.collection.mutable.HashMap`.

Історія для незмінних множин та мап трохи складніша. Наприклад, клас, що повертається методом фабрики `scala.collection.immutable.Set()`, залежить від того, як багато елементів ви передасте йому, як показано в Таблиці 17.3. Для множин, меньших за п'ять елементів, існують окремі класи, ексклюзивно призначені для множин кожного окремого розміру, що використовуються для максимальної продуктивності. Однак, коли ви запитуєте множину, що має п'ять або більше елементів, метод фабрики буде повертати реалізацію, що використовує хеш дерева.

Подібно до цього, метод фабрики `scala.collection.immutable.Map()` буде повертати інший клас, в залежності від того, як багато пар ключ-значення ви передасте йому, як показано в Таблиці 17.4. Так само, як з множинами, для незмінних мап з меньше ніж п'ятьма елементами виділяється окремий клас, ексклюзивно призначений для мап окремого розміру, що використовується для максимальної продуктивності. Однак, коли мапа має п'ять або більше пар ключ-значення, буде використаний незмінний `HashMap`.

Реалізація незмінних класів по замовчанню, показаних в Таблиці 17.3 та 17.4, роблять разом для надання вам максимальної продуктивності. Наприклад, якщо ви додасте елемент до `EmptySet`, він поверне `Set1`. Якщо ви додасте елемент до `Set1`, він буде повертати `Set2`. Якщо ви потім видалите елемент з `Set2`, ви отримаєте новий `Set1`.

[caption="Таблиця 17.3 "]
.Реалізації незмінних множин по замовчанню
[cols="1,6",options="header"]
|===
^|Число елементів ^|Реалізація
^|0|`scala.collection.immutable.EmptySet`
^|1|`scala.collection.immutable.Set1`
^|2|`scala.collection.immutable.Set2`
^|3|`scala.collection.immutable.Set3`
^|4|`scala.collection.immutable.Set4`
^|>=5|`scala.collection.immutable.HashSet`
|===

[caption="Таблиця 17.4 "]
.Реалізації незмінних мап по замовчанню
[cols="1,6",options="header"]
|===
^|Число елементів ^|Реалізація
^|0|`scala.collection.immutable.EmptyMap`
^|1|`scala.collection.immutable.Map1`
^|2|`scala.collection.immutable.Map2`
^|3|`scala.collection.immutable.Map3`
^|4|`scala.collection.immutable.Map4`
^|>=5|`scala.collection.immutable.HashMap`
|===

Впорядковані множини та мапи
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Часом вам може знадобитись множина або мапа, чий ітератор повертає елементи в певному порядку. Для ціх цілей бібліотека колекцій Scala провадить трейти `SortedSet` та `SortedMap`. Ці трейти реалізовані класами `TreeSet` та `TreeMap`, що викорисотвують дерева _червоне-чорне_ для зберігання елементів (в випадку `TreeSet`) або ключів (в випадку `TreeMap`) впорядкованими. Порядок визначається трейтом `Ordered`, що або зміксований в тип множини чи тип ключа мапи, або має до нього неявне перетворення. Ці класи мають тільки незмінні варіанти. Ось деякі приклади `TreeSet`:
[source,scala]
----
scala> import scala.collection.immutable.TreeSet
import scala.collection.immutable.TreeSet

scala> val ts = TreeSet(9, 3, 1, 8, 0, 2, 7, 4, 6, 5)
ts: scala.collection.immutable.TreeSet[Int] =
    TreeSet(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)

scala> val cs = TreeSet('f', 'u', 'n')
cs: scala.collection.immutable.TreeSet[Char] =
    TreeSet(f, n, u)
----
Та ось декілька прикладів `TreeMap`:
[source,scala]
----
scala> import scala.collection.immutable.TreeMap
import scala.collection.immutable.TreeMap

scala> var tm = TreeMap(3 -> 'x', 1 -> 'x', 4 -> 'x')
tm: scala.collection.immutable.TreeMap[Int,Char] =
    Map(1 -> x, 3 -> x, 4 -> x)

scala> tm += (2 -> 'x')

scala> tm
res30: scala.collection.immutable.TreeMap[Int,Char] =
    Map(1 -> x, 2 -> x, 3 -> x, 4 -> x)
----
17.3 Вибір між змінними та незмінними колекціями
------------------------------------------------
Для деяких пробелем змінні колекції роблять краще, тоді як для інших незмінні колекції роблять краще. Коли є сумніви, краще почати з незмінної колекції, та потім змінити її, якщо буде потреба, оскількі незмінні колекції легші для розуміння, ніж змінні.

Також може бути вартим іноді іти в зворотньому напрямку. Якщо ви знайдете якійсь код, що використовує змінні колекції, та стає складним для розуміння, поміркуйте, чи не допоможе зміна деяких з колекцій на незмінні альтернативи. Зокрема, якщо ви турбуєтесь щодо створення копій змінних колекцій тільки в вірних місцях, або думаєте про те, хто "володіє" або "містить" змінну колекцію, розгляньте перехід деяких колекцій на їх незмінних двійників.

Крім того, що про них легше розмірковувати, незмінні колекції можуть зазвичай зберігатись більш компактно, ніж змінні, якщо кількість елементів, що зберігається в колекції, невелика. Наприклад, примірник порожньої змінної мапи в її представленні за замовчанням  `HashMap`, займає приблизно 80 байт, та на 16 ще додаються для кожного елемента, що додається. Порожня незмінна `Map` є єдиним об'єктом, що поділяється між всіма посиланнями, так що посилання на неї коштує рівно стільки, скільки саме поле вказівника.

Ще більше, бібліотека колекцій Scala наразі зберігає незмінні мапи до чотирьох елементів як єдиний об'єкт, що типово займає від 16 до 40 байтів, в залежності від числа елементів, що зберігаються в колекції.footnote:["Єдиний об'єкт" є примірник `Set1` до `Set4`, або `Map1` до `Map4`, як показано в Таблиці 17.3 та 17.4.] Так що для малих мап та множин незмінні версії значно більш компактні, ніж змінні. Беручи до уваги, що багато колекцій є малими, перехід на незмінні варіанти може привнести важливі збереження простору та переваги продуктивності.

Щоб спростити перехід від незмінних до змінних колекцій, та навпаки, Scala провадить деякий синтаксичний цукор. Навіть зважаючи, що незмінні множини та мапи не підтримують дійсний метод `+=`, Scala дає корисну альтернативну інтерпретацію до `+=`. Кожного разу, коли ви пишете `a += b`, і `a` не підтримує метод з ім'ям `+=`, Scala спробує інтерпретувати це як `a = a + b`.

Наприклад, незмінні множини не підтримують оператор `+=`:
[source,scala]
----
scala> val people = Set("Nancy", "Jane")
people: scala.collection.immutable.Set[String] =
    Set(Nancy, Jane)

scala> people += "Bob"
<console>:14: error: value += is not a member of
scala.collection.immutable.Set[String]
              people += "Bob"
                     ^
----                     
Однак, якщо ви декларуєте `people` як `var`, замість `val`, тоді колекція може бути "оновлена" за допомогою оператора `+=`, навіть якщо вона незмінна. Спочатку буде створена нова колекція, та потім `people` буде переприсвоєне, щоб посилатись на нову колекцію:
[source,scala]
----
scala> var people = Set("Nancy", "Jane")
people: scala.collection.immutable.Set[String] =
    Set(Nancy, Jane)

scala> people += "Bob"

scala> people
res34: scala.collection.immutable.Set[String] =
    Set(Nancy, Jane, Bob)
----
Після цієї серії тверджень, змінна `people` посилається на нову незмінну множину, що містить доданий рядок, `"Bob"`. Та сама ідея застосовується до любого метода, що завершується на `=`, не тільки до метода `+=`. Ось той самий синтаксис, використаний з оператором `-=`, що видаляє елемент з множини, та до оператора `++=`, що додає колекцію елементів до множини:
[source,scala]
----
scala> people -= "Jane"

scala> people ++= List("Tom", "Harry")

scala> people
res37: scala.collection.immutable.Set[String] =
  Set(Nancy, Bob, Tom, Harry)
----
Щоб подивитись, як це може бути корисне, знову розглянемо наступний приклад `Map` з Розділу 1.1:
[source,scala]
----
var capital = Map("US" -> "Washington", "France" -> "Paris")
capital += ("Japan" -> "Tokyo")
println(capital("France"))
----
Цей код використовує незмінні колекції. Якщо ви бажаєте спробувати використання змінних колекцій замість цього, все що треба, це імпортувати змінну версію `Map`, таким чином перекриваючи імпорт по замовчанню незмінної `Map`:
[source,scala]
----
import scala.collection.mutable.Map // єдина потрібна зміна!
var capital = Map("US" -> "Washington", "France" -> "Paris")
capital += ("Japan" -> "Tokyo")
println(capital("France"))
----
Не всі приклади так само прості для конвертації, але особлива трактовка методів, що закінчується на знак рівності, часто зменшує кількість коду, що потребує змін.

До ручі, цей синтаксичний підхід робить з любим типом значення, не тільки для колекцій. Наприклад, ось як він робить, використаний для чисел з плаваючою крапкою:
[source,scala]
----
scala> var roughlyPi = 3.0
roughlyPi: Double = 3.0

scala> roughlyPi += 0.1

scala> roughlyPi += 0.04

scala> roughlyPi
res40: Double = 3.14
----
Ефект цього розширення подібний до операторів присвоєння Java (`+=`, `-=`, `*=`, тощо), але він більш загальний, бо кожний оператор, що закінчується на `=`, може бути конвертований.

17.4 Ініціалізація колекцій
---------------------------
Як ви вже бачили до цього, найбільш загальний спосіб створити та ініціалізувати колекцію є передати початкові елементи до метода фабрики на об'єкті компанйоні обраної колекції. Ви просто покладаєте елементи в дужки після імені об'єкта компанйона, та компілятор Scala буде трансформувати його на виклик метода `apply` на цьому об'єкті компанйоні:
[source,scala]
----
scala> List(1, 2, 3)
res41: List[Int] = List(1, 2, 3)

scala> Set('a', 'b', 'c')
res42: scala.collection.immutable.Set[Char] = Set(a, b, c)

scala> import scala.collection.mutable
import scala.collection.mutable

scala> mutable.Map("hi" -> 2, "there" -> 5)
res43: scala.collection.mutable.Map[String,Int] = 
    Map(hi -> 2, there -> 5)

scala> Array(1.0, 2.0, 3.0)
res44: Array[Double] = Array(1.0, 2.0, 3.0)
----
Хоча більш часто ви можете дозволити компілятору Scala виводити тип елементів колекції від елементів, що ви передаєте до його методу фабрики, іноді ви можете бажати створити колекцію, але вказати інший тип, ніж той, що буде обирати компілятор. Це особливо важливо для змінних колекцій. Ось приклад:
[source,scala]
----
scala> import scala.collection.mutable
import scala.collection.mutable

scala> val stuff = mutable.Set(42)
stuff: scala.collection.mutable.Set[Int] = Set(42)

scala> stuff += "abracadabra"
<console>:16: error: type mismatch;
found   : String("abracadabra")
required: Int
            stuff += "abracadabra"
            ^
----            
Тут проблема в тому, що `stuff` отримав тип елементу `Int`. Якщо ви бажаєте, щоб тип елементу був `Any`, вам треба сказати це явно, поклавши тип елементу в прямокутні дужки, як тут:
[source,scala]
----
scala> val stuff = mutable.Set[Any](42)
stuff: scala.collection.mutable.Set[Any] = Set(42)
----
Інша особлива ситуація виникає, коли ви бажаєте ініціалізувати колекцію за допомогою іншої колекції. Наприклад, уявімо, що ви маєте список, але ви бажаєте мати `TreeSet`, що містить елементи з цього списку. Ось список:
[source,scala]
----
scala> val colors = List("blue", "yellow", "red", "green")
colors: List[String] = List(blue, yellow, red, green)
----
Ви не можете передати список `colors` до метода фабрики для `TreeSet`:
[source,scala]
----
scala> import scala.collection.immutable.TreeSet
import scala.collection.immutable.TreeSet

scala> val treeSet = TreeSet(colors)
<console>:16: error: No implicit Ordering defined for
List[String].
       val treeSet = TreeSet(colors)
                            ^
----                            
Замість цього вам треба створити порожній `TreeSet[String]`, та додати до нього елементи списку за допомогою оператора `TreeSet` `++`:
[source,scala]
----
scala> val treeSet = TreeSet[String]() ++ colors
treeSet: scala.collection.immutable.TreeSet[String] =
    TreeSet(blue, green, red, yellow)
----
Конвертація до масиву або списку
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
З іншого боку, якщо вам треба ініціалізувати список або масив з іншої колекції, це досить прямолінійно. Як ви бачили до цього, щоб ініціалізувати новий список з іншої колекції, просто виконайте на цій колекції метод `toList`:
[source,scala]
----
scala> treeSet.toList
res50: List[String] = List(blue, green, red, yellow)
----
Або, якщо вам треба масив, викличте `toArray`:
[source,scala]
----
scala> treeSet.toArray
res51: Array[String] = Array(blue, green, red, yellow)
----
Зауважте, що хоча оригінальний список `colors` не був впорядкований, елементи в списку, спродукованому через виклик `toList` на `TreeSet`, ідуть в алфавітному порядку. Коли ви викликаєте `toList` або `toArray` на колекції, порядок елементів в отриманому списку або масиві буде той самий, що і порядок елементів, спродукований ітератором, отриманим через виклик `elements` на цій колекції. Оскільки ітератор `TreeSet[String]` буде продукувати рядкі в алфавітному порядку, ці рядкі будуть з'являтись в алфавітному порядку в списку, отриманому від визову `toList` на цьому `TreeSet`.

Однак майте на увазі, що перетворення між списками та масивами звичайно потребує копіювання всіх елементів в колекції, і, таким чином, можуть бути повільними для великих колекцій. Хоча іноді вам треба зробити це через існуюче API. Більше того, багато колекцій мають лише декілька елементів, і в цьому випадку існує лише мала втрата швидкості.

Перетворення між змінними та незмінними множинами або мапами
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Інша ситуація, що часом постає, є потреба конвертувати змінну множину або мапу до незмінної, або _vice versa_. Щоб досягти цього, ви можете використати прийом, показаний на попередній сторінці, для ініціалізації `TreeSet` елементами списку. Створіть колекцію нового типу, використовуючи метод `empty`, та потім додайте нові елементи, використовуючи або `++`, або `++=`, що відповідає до типу цільової колекції. Ось як ви конвертуєте незмінний `TreeSet` з попереднього прикладу до змінної множини, та назад до незмінної:
[source,scala]
----
scala> import scala.collection.mutable
import scala.collection.mutable

scala> treeSet
res52: scala.collection.immutable.TreeSet[String] =
    TreeSet(blue, green, red, yellow)

scala> val mutaSet = mutable.Set.empty ++= treeSet
mutaSet: scala.collection.mutable.Set[String] =
    Set(red, blue, green, yellow)

scala> val immutaSet = Set.empty ++ mutaSet
immutaSet: scala.collection.immutable.Set[String] =
    Set(red, blue, green, yellow)
----
Ви можете використовувати той самий прийом для конвертації змінних та незмінних мап:
[source,scala]
----
scala> val muta = mutable.Map("i" -> 1, "ii" -> 2)
muta: scala.collection.mutable.Map[String,Int] =
    Map(ii -> 2,i -> 1)

scala> val immu = Map.empty ++ muta
immu: scala.collection.immutable.Map[String,Int] =
    Map(ii -> 2, i -> 1)
----
17.5 Тапли
----------
Як описане в Кроці 9 в Главі 3, типл комбінує фіксоване число елементів разом, так що вони можуть бути передані будь-куди як ціле. На відміну від масиву або списка, тапл може зберігати об'єкти різних типів. Ось приклад тапла, що містить ціле, рядок та консоль:
[source,scala]
----
(1, "hello", Console)
----
Тапли вберігають вам від нудьги визначати прості класи даних. Навіть зважаючи, що визначення класу вже просте, воно все ще потребує мінімальних зусиль, що іноді на до чого. Тапли вберігають вас від зусиль обирати ім'я файлу, обирати поле видимості, в якому треба визначити клас, та обрати імена для членів класу. Якщо ваш клас просто містить ціле та рядок, не додасться ясності, якщо ви визначите клас на ім'я `AnIntegerAndAString`.

Оскільки тапли можуть комбінувати об'єкти різних типів, тапли не наслідують від `Traversable`. Якщо ви бажаєте згруаувати рівно одне ціле і один рядок, тоді вам треба тапл, не `List` або `Array`.

Загальне застосування таплів є повернення декількох значень з метода. Наприклад, ось метод, що знаходить найдовше слово в колекції, що також повертає індекс:
[source,scala]
----
def longestWord(words: Array[String]) = {
  var word = words(0)
  var idx = 0
  for (i <- 1 until words.length)
    if (words(i).length > word.length) {
      word = words(i)
      idx = i
  }
  (word, idx)
}
----
Ось приклад, що використовує цей метод:
[source,scala]
----
scala> val longest =
         longestWord("The quick brown fox".split(" "))
longest: (String, Int) = (quick,1)
----
Функція `longestWord` обчислює два елементи: `word`, найдовше слово в масиві, та `idx`, індекс цього слова. Щоб утримувати речі простими, функція вважає, що в списку є хоча б одне слово, і він вирішує спірні питання, обираючи слово, що іде раніше в списку. Коли функція обирає, яке слово та індекс повертати, вона повертає обоє з них разом, використовуючи синтаксис тапла `(word, idx)`. Щоб отримати доступ до елементів в таплі, ви можете використати метод `_1` для доступу до першого елементу, `_2` для доступу до другого, і так далі:
[source,scala]
----
scala> longest._1
res53: String = quick

scala> longest._2
res54: Int = 1
----
Додатково, ви можете присвоїти кожний елемент тапла до власної змінної,footnote:[Насправді, цей синтаксис є особливим випадком порівняння шаблонів, як описано в деталях в Розділі 15.7.] ось так: 
[source,scala]
----
scala> val (word, idx) = longest
word: String = quick
idx: Int = 1

scala> word
res55: String = quick
----
Доречі, якщо ви відкинете дужки, ви отримаєте інший варіант:
[source,scala]
----
scala> val word, idx = longest
word: (String, Int) = (quick,1)
idx: (String, Int) = (quick,1)
----
Цей синтаксис дає _множинні визначення_ того самого виразу. Кожна змінна ініціалізована власним обчисленням виразу в правій стороні. Те, що в даному випадку цей вираз обчислюється до тапла, не має значення. Обоє змінні ініціалізуються таплом, як цілим. Дивіться Главу 18 для деяких прикладів, де множинні визначення є зручними.

В якості попередження, тапли загалом дуже прості в використанні. Тапли чудові, коли ви комбінуєте дані, що не мають значення, крім "якесь A та якесь B." Однак, коли комбінація має якесь значення, або ви бажаєте додати якісь методи до комбінації, краще піти далі, та створити клас. Наприклад, не використовуйте 3-місний тапл для комбінації місяця, дня та року. Створіть клас `Date`. Це зробить ваші наміри явними, що одночасно прояснює код для людей, та дає компілятору та мові можливість допомогти вам відловлювати помилки.

17.6 Висновок
-------------
Ця глава надала огляд бібліотеки колекцій Scala, та найбільш важливі класи та трейти в ній. З цією основою ви маєте бути в змозі робити ефективно зі Scala колекціями, та знати, куди дивитись в Scaladoc, якщо вам треба більше інформації. Для більш детальної інформації щодо Scala колекцій, дивіться далі, в Главі 24 та Главі 25. До того часу, в наступній главі ми перенесемо нашу увагу від бібліотеки Scala назад на мову, та обговоримо підтримку Scala для змінних об'єктів.

