include::headers.adoc[]

Додаток A
---------

Скрипти Scala на Unix та Windows
================================

Якщо ви на деякому різновиді Unix, ви можете виконувати скрипти Scala як скрипт оболонки, поставивши нагорі файла директиву "ша банг". Наприклад, наберіть таке в файлі на ім'я `helloarg`:
[source,bash]
----
#!/bin/sh
exec scala "$0" "$@"
!#
// Скажи hello першому аргументу
println("Hello, " + args(0) + "!")
----
Перше `#!/bin/sh` має бути на самому першому рядку в файлі. Коли ви встановите дозвіл на виконання:
[source,bash]
----
$ chmod +x helloarg
----
Ви можете виконувати Scala скрипт як скрипт оболонки просто сказавши:
[source,bash]
----
$ ./helloarg globe
----

Якщо ви на Windows, ви можете досягти того самого ефекту, назвавши файл `helloarg.bat`, та поклавши це нагорі вашого скрипта:
::#!
@echo off
call scala %0 %*
goto :eof
::!#

Глосарій
========

_**алгебраїчний тип даних**_ Тип, визначений через провадження декількох альтетрнатив, кожна з яких іде зі своїм власним конструктором. Віз зазвичай іде зі способом декомпозиції типу через співпадіння шаблонів. Концепція знайдена в мовах специфікації та функціональних мовах програмування. Алгебраїчні типи даних можуть бути емульовані в Scala через кейс класи.

_**альтернатива**_ Гілка виразу `match`. Вона має форму `case pattern => expression`. Інше ім'я для альтернативи є _випадок_. 

_**анотація**_ Анотація з'являється в джерельному коді, та прив'язана до деякої частини синтаксису. Анотації обробляються комп'ютером, так що ви можете використовувати їх для ефективного додавання розширень до Scala.

_**анонімний клас**_ Анонімний клас є синтетичний субклас, згенерований компілятором Scala з виразу `new`, в якому за ім'ям класу або трейту ідуть фігурні дужки. Фігурні дужки містять тіло анонімного класу, що може бути порожнім. Однак якщо ім'я, на яке посилається `new`, посилається на трейт або клас, що містить абстрактні члени, це має бути зроблене суцільним в фігурних дужках, що визначають тіло анонімного субкласу.

_**анонімна функція**_ Інша назва для функціонального літералу.

_**аргумент**_ Коли викликається функція, аргумент передається для кожного параметра функції. Параметр є змінна, що посилається на аргумент. Аргумент є об'єктом, переданим під час виклику. На додаток, застосування можуть приймати аргументи (командного рядка), що виглядають як `Array[String]`, переданий до метода `main` об'єкта синглтона.

_**без посилань**_ Дивіться _недоступний_.

_**безпараметерна функція**_ Функція, що не приймає параметрів, та визначена без жодних порожніх дужок. Виклики безпараметерних функцій не може надавати дужки. Це підтримує принцип уніформного доступу, що дозволяє замінити `def` на `val`, без вимог до зміни клієнтського коду.

_**блок**_ Один або більше виразів та декларацій, оточених фігурними дужками. Коли блок обчислюється, всі його вирази та декларації обробляються по порядку, та потім блок повертає значення останнього виразу або своє власне значення. Блоки загально використовуються як тіла функцій, для виразів, циклів `while`, та в усіх інишх місцях, де ви бажаєте згрупіювати декілька твердженя разом. Більш формально, блок це конструкція інкапсуляції, для якої ви можете бачити тільки побічні ефекти або значення результату. Фігурні дужки, в яких ви визначаєте клас або об'єкт, таким чином, не формують блок, оскільки поля та методи (що визначені в ціх фігурних дужках) видимі ззовні. Такі фігурні дужки формують _шаблон_.

_**варіантність**_ Параметр типу класу або трейту може бути відмічений анотацією варіантності, як коваріантний (+) або контрваріантний (-). Так анотації варіантності вказують, як субтипізація робить для класів або трейтів. Наприклад, дженерік клас `List` є коваріантним по своєму парметру типа, так що `List[String]` є субтипом `List[Any]`. По замовчанню, тобто при відсутності анотацій + або -, тип параметрів є _неваріантним_.

_**вільна змінна**_ _Вільна змінна_ в виразі є змінна, що використовується в виразі, але не визначається в виразі. Наприклад, в виразі функціонального літерала `(x: Int) => (x, y)` використовуються обидві змінні, `x` та `y`, але тільки `y` є вільною змінною, оскільки вона не визначена всередині виразу.

_**видача**_ Вираз може _видавати_ результат. Ключове слово `yield` позначає результат для виразу `for`.

_**визначення**_ _Визначити_ дещо в програмі Scala означає надати ім'я та реалізацію. Ви можете визначити класи, трейти, об'єкти синглтони, поля, методи, локальні функції, локальні змінні, тощо. Оскільки визначення завжди включає деякий різновид реалізації, абстрактні члени _декларовані_, але не визначені.

_**виклик**_ Ви можете викликати метод, функцію або замикання на аргументах, означаючи, що її тіло буде виконане з заданими аргументами.

_**вираз**_ Любий фрагмент Scala коду, що дає результат. Ви також можете сказати, що вираз обчислюється до результату, або має результуюче _значення_.

_**вираз генератора**_ _Вираз генератора_ генерує послідовність значень в виразі `for`. Наприклад, в `for(i <- 1 to 10)`, вираз генератора є `1 to 10`.

_**генератор**_ _Генератор_ визначає іменовану `val`, та присвоює їй набір значень в виразі `for`. Наприклад, в `for(i <- 1 to 10)`, генератор є `i <- 1 to 10`. Значення зправа від `<-` є вираз генератора.

_**декларація**_ Ви можете _декларувати_ абстрактне поле, метод або тип, що надає сутності ім'я, але не реалізацію. Ключова різниця між декларацією та визначенням в тому, що визначення встановлює реалізацію для іменованої сутності, тоді як декларація - ні.

_**дженерік клас**_ Клас, що приймає параметри типу. Наприклад, оскільки `scala.List` приймає параметр типу, `scala.List` є дженерік класом.

_**дженерік трейт**_ Трейт, що приймає параметри типу. Наприклад, оскільки трейт `scala.collection.Set` приймає параметр типу, він є дженерік трейтом.

_**додатковий конструктор**_ Додаткові конструктори визначаються в фігурних дужках визначення класа, що виглядає як визначення методів з ім'ям `this`, але без типу повернення.

_**допоміжна функція**_ Функція, чиє призначення є провадити сервіс до одної або декількох функцій. Допоміжні функції часто реалізовані як локальні функції.

_**допоміжний метод**_ Допоміжна функція, що є членом класу. Допоміжні методи часто є приватними.

_**еквівалентність**_ Коли використовується без кваліфікації, еквівалентність є відношення, виражене `==`. Дивіться також _еквівалентність посилань_.

_**еквівалентність посилань**_ Еквівалентність посилань означає, що два посилання ідентифікують той самий  Java об'єкт. Еквівалентність посилань може бути визначена тільки для типів посилань, через виклик `eq` на `AnyRef`. (В програмах Java еквівалентність посилань може бути визначена з використанням `==` на типах посилань Java.)

_**замикання**_ Функціональний об'єкт, що захоплює вільні змінні, та, як кажуть, "замкнений" на змінних, видимих під час свого створення.

_**застосування**_ Ви можете застосувати метод, функцію або замикання до аргументів, що означає, що ви викликаєте їх на ціх аргументах.

_**затінення**_ Нова декларація локальної змінної затінює таку з тим же ім'ям в оточуючому полі зору.

_**захисник шаблону**_ В виразі `match` це альтернатива, захисник шаблону може слідувати за шаблоном. Наприклад, в `case x if x % 2 == 0 => x + 1`, захисник шаблону є `if x % 2 == 0`. Випадок з захисником шаблону буде обраною тільки якщо співпадає шаблон, та захисник шаблону видає `true`.

_**змінна**_ Іменована сутність, що посилається на об'єкт. Змінна є або `val`, або `var`. Обоє, `val` та `var` мають бути ініціалізовані при визначенні, але тільки `var` потім можуть бути переприсвоєні, щоб посилатись на інший об'єкт.

_**значення**_ Результат любого обчислення або виразу в Scala є значення, та в Scala кожне значення є об'єктом. Термін "значення" в основному означає образ об'єкта в пам'яті (в купі JVM або в стеку).

_**імперативний стиль**_ Імперативний стиль програмування підкреслює уважне ставлення до послідовності операцій, так, щоб їх ефект відбувався в вірному порядку. Стиль характеризується ітераціями в циклі, змінами даних на місці, та методами з побічними ефектами. Це домінуюча парадигма таких мов, як C, C++, C# та Java, та контрастує з _функціональним стилем_.

_**інваріант**_ Інваріант використовується в два способи. Це може означати властивість, що завжди має бути `true`, коли структура даних гарно-сформована. Наприклад, це інваріант для впорядкованого бінарного дерева, що кожний вузол впорядкований перед своїм правим підвузлом, якщо той існує. Інваріант також іноді використовується як синонім до неваріантності: "клас `Array` є інваріантним по своєму параметру типу".

_**ініціалізація**_ Коли змінна визначається в джерельному коді Scala, ви маєте ініціалізувати її значенням об'єкту.

_**карування**_ Спосіб записати функцію з декількома списками параметрів. Наприклад, `def f(x: Int)(y: Int)` є карована функція з двома списками параметрів. Карована функція застосовується передачею декількох списків аргументів, як `f(3)(4)`. Однак, також можливо написати часткове застосування карованої функції, як `f(3)`.

_**клас**_ Визначається ключовим словом `class`, клас може бути або абстрактним, або суцільним, та може бути параметризований типами та значеннями при створенні примірника. В виразі `new Array[String](2)` клас, примірник якого створюється, є `Array`, і тип значення, що утворюється, є `Array[String]`. Клас, що приймає параметри типів називається _конструктором типів_. Також можна сказати, що тип має свій клас: наприклад, клас типу `Array[String]` є `Array`.

_**клас компанйон**_ Клас, що поділяє те саме ім'я з об'єктом синглтоном, визначеним в тому ж джерельному файлі. Клас є класом компанйоном синглтон об'єкта.

_**коваріантність**_ _Коваріантна_ анотація може бути застосована до параметру типу класа або трейта, через покладання знаку плюс (+) перед параметром типу. Клас або трейт потім утворює субтипи коваріантно — в тому самому напрямку — до анотованого параметром типу. Наприклад, `List` є коваріантним в своєму параметрі типу, так що `List[String]` є субтипом `List[Any]`.

_**конструктор типу**_ Клас або трейт, що приймає параметри типу.

_**контрваріантність**_ _Контрваріантна_ анотація може бути застосована до параметру типу класу або трейту, через покладання знаку мінус (-) перед параметром типу. Клас або трейт потім утворює субтипи контрваріантно — в протилежному напрямку — до анотованого типом параметру. Наприклад, `Function1` є контрваріантною в своєму першому параметрі, так що `Function1[Any, Any]` є субтипом `Function1[String, Any]`.

_**літерал**_ `1`, `"One"`, та `(x: Int) => x + 1` є прикладами літералів. Літерал є скороченням для опису об'єкта, коли скоровення в точності відображує структуру створюваного об'єкту.

_**локальна змінна**_ Локальна змінна є `val` або `var` визначена в блоці. Хоча подібні до локальних змінних, параметри функцій не посилаються як на локальні змінні, але просто як на параметри або "змінні", без "локальні".

_**локальна функція**_ Локальна функція є `def`, визначений в блоці. Для контрасту, `def`, визначена як слен класу, трейту або об'єкту синглтону називається методом.

_**мета-програмування**_ Мета-програмування програмного забезпечення є програми, які на вході також мають програми. Компіляттори є мета-програмами, як і інструменти, як scaladoc. Програми мета-програмування потрібні для робити будь що за допомогою анотацій.

_**метод**_ Метод є функція, що є членом днякого класу, трейту або об'єкта синглтона.

_**метод без параметрів**_ Метод _без параметрів_ є функція без параметрів, що є членом класу, трейта або об'єкта синглтона.

_**міксін**_ Міксін є назвою трейта, коли він застосований в міксін композиції. Іншими словами, в `trait Hat`, `Hat` є просто трейтом, але в `new Cat extends AnyRef with Hat`, `Hat` може бути названий міксіном. Коли використовується як дієслово, "mix in" є двома словами. Наприклад, ви можете міксувати трейти в класи або інші трейти.

_**міксін композиція**_ Процес міксування трейтів в класи або інші трейти. Міксін композиція відрізняється від традиційного множинного наслідування, в тому, що тип посилання `super` невідомий в точці визначення трейта, але скоріше визначається поновій кожного разу, коли трейт міксується в клас або інший трейт.

_**множинне визначення**_ Той самий вираз може бути присвоєний в декількох визначеннях, якщо ви використовуєте синтаксис `val v1, v2, v3 = exp`.

_**модифікатор**_ Ключове слово, що кваліфікує визначення класу, трейта, поля або метода, в деякий спосіб. Наприклад, модифікатор `private` вказує що клас, трейт, поле або метод буде визначений, як приватний.

_**напів-структуровані дані**_ Дані XML є напів структурованими. Вони більш структуровані, ніж суцільно бінарний файл, або текстовий файл, але вони не мають повної структури, як структури даних в мовах програмування.

_**неваріантність**_ Параметр типу класу або трейта по замовчанню є неваріантним. При цьому клас або трейт не утворює субтип при зміні параметрів. Наприклад, оскільки клас `Array` є неваріантним по своєму параметру типа, `Array[String]` не є ні субтипом, ані супертипом `Array[Any]`.

_**недосяжні значення**_ На рівні Scala об'єкти можуть стати недосяжні, та в цій точці пам'ять, що вони займають, повертається в рантайм. Недосяжність не обов'язково означає _без посилань_. Типи посилань (примірники `AnyRef`) реалізовані як об'єкти, що розташовуються в купі JVM. Коли примірник типу посилання стає недосяжний, він дійсно стає без посилань, і стає предметом збирача сміття. Типи значень (примірники `AnyVal`) реалізовані одночасно як примітивні типи значень, або примірники типів огорток Java (таких як `java.lang.Integer`), що розташовуються в купі. Примірники типів значень можуть бути боксовані (перетворені з примітивних значень до об'єкту огортки) та розбоксовані (перетворені з об'єкта огортки на примітивне значення) на протязі життєвого циклу змінних, що посилаються на значення. Якщо примірник типу значення наразі представлено як об'єкт огортки в купі JVM, і він стає недосяжним, він також стає без посилань, та доступний для збору сміття. Але якщо тип значення наразі представлений як примітивне значення, та стає недосяжним, тоді він не втрачає посилань, оскільки він не існує як об'єкт в купі JVM, щонайменьше в цій точці часу. Рантайм може повернути пам'ять, зайняту недосяжними об'єктами, але якщо, наприклад, `Int`, реалізований під час виконання як примітив  Java `int`, що займає деяку пам'ять у фреймі стеку, тоді пам'ять для цього об'єкту "відновлюється", коли фрейм стеку виштовхується при завершенні метода. Пам'ять для типів посилань, такі як String, може бути відновлена збирачем сміття JVM, після того, як вони стали недосяжними.

_**незмінний**_ Об'єкт є _незмінним_, якщо його значення не може бути зміненим після його створення в жодний спосіб, видимий для клієнтів. Об'єкти можуть бути або не бути змінними.

_**об'єкт компанйон**_ Об'єкт синглтон, що поділяє те саме ім'я з класом, визначеним в тому самому джерельному файлі. Компанйон об'єкти та класи мають доступ до приватних членів один одного. На додаток, любі неявні перетворення, визначені в компанйон об'єкті, будуть в полі зору будь-де, де використовується клас.

_**об'єкт синглтон**_ Об'єкт, визначений за допомогою ключового слова `object`. Кожний об'єкт синглтон має один, і тільки один примірник. Об'єкт синглтон, що поділяє ім'я з класом, та визначений в тому самому джерельному файлі, що і клас, є об'єктом компанйоном цього класу. Клас є його класом компанйоном. Об'єкт синглтон, що не має класа компанйона, є _окремим об'єктом_.

_**обмеження типу**_ Деякі анотації є обмеженнями типу, що означає, що вони додають межі, або обмеження на значення, які включає тип. Наприклад, `@positive` може бути обмеженням типу на типі `Int`, обмежуючи тип  32-бітних цілих до додатніх значень. Обмеження тиаів не перевіряються стандартним компілятором Scala, та замість цього мають бути перевірені зовнішінім інструментом, або плагіном компілятора.

_**окремий об'єкт**_ Об'єкт синглтон, що не має класа компанйона. 

_**операція**_ В Scala, кожна _операція_ є викликом метода. Методи можуть бути викликані в операторній нотації, як `b + 2`, та в цій нотації `+` є оператором.

_**охоплення `for`**_ Інша назва для _виразу `for_`.

_**параметр**_ Функції можуть мати нуль або більше параметрів. Кожний параметр має ім'я та тип. Різниця між параметрами та аргументами в тому, що аргументи посилаються на дійсні передані об'єкти, коли функція викликається. Параметри є змінними, що посилаються на ці передані аргументи. 

_**параметр за-значенням**_ Параметр, що _не_ позначений `=>` перед типом параметру, як в `(x: Int)`. Аргумент, що відповідає параметру за-значенням, обчислюється перед викликом метода. Параметри за-значенням відрізняються від параметрів _за-ім'ям_.

_**параметр за-ім'ям**_ Парметр, що позначений `=>` перед типом параметра, як в `(x: => Int)`. Аргумент, що відповідає параметру за ім'ям, обчислюється не перед викликом метода, але кожного разу, коли на параметр є посилання _за ім'ям_ в методі. Якщо параметр не є параметром за-ім'ям, він є _за-значенням_.

_**параметр типу**_ Параметр дженерік класу або дженерік методу, що має бути заповнений типом. Наприклад, клас `List` визначений як `class List[T] { ...`, та метод `identity`, член об'єкта `Predef`, визначений як `def identity[T](x:T) = x`. T в обох випадках є параметром типу.

_**параметричне поле**_ Поле, визначене як параметр класу.

_**переприсвоєння**_ Змінна може бути, або не бути переприсвоюваною. `var` повторно присвоюється, тоді як `val` - ні.

_**первинний конструктор**_ Головний конструктор класу, що викликає конструктор суперкласу, якщо це потрібно, ініціалізує поля переданими значеннями, та виконує високорівневий код, визначений між фігурними дужками класу. Поля ініціалізовані тільки для значень параметрів, не переданих до конструктора суперкласів, за винятком таких, що не використовуються в тілі класу, і, таким чином, можуть бути "оптимізовані" геть.

_**першокласна функція**_ Scala підтримує _першокласні функції_, що означає, що ви можете виразити функції в синтаксисі _функціональних літералів_, тобто, `(x: Int) => x + 1`, і ці функції можуть представлені об'єктами, що називаються _функціональними значеннями_.

_**підстановочний тип**_ Підстановочний тип включає посилання на змінні типів, що наразі невідомі. Наприклад, `Array[_]` є підстановочним типом. Це масив, де елемент типу повністю невідомий.

_**повернення**_ Функція в програмі Scala повертає значення. Ви можете назвати це значення результатом функції. Ви також можете сказати, що результатом функції є значення. Результат кожної функції в Scala є об'єкт.

_**повідомлення**_ Актори комунікують один з одним через надсилання один одному повідомлень. Надсилання повідомлення не перериває те, що робить отримувач. Отримувач може зачекати, доки він скінчить свою поточну активність, та їх інваріанти будуть дотримуватись.

_**посилається**_ Змінна в роблячій програмі Scala завжди посилається на деякий об'єкт. Навіть якщо змінній присвоєне `null`, вона концептуально посилається на об'єкт `Null`. Під час виконання об'єкт може бути реалізований як Java об'єкт або значення примітивного типу, але Scala дозволяє програмістам думати на вищому рівні абстракції щодо їх кода, як вони уявляють виконання. Також дивіться _посилання_.

_**посилання**_ Посилання в абстракціях Java є вказівник, що унікально ідентифікує об'єкт, що знаходиться на купі JVM. Тип посилання змінних містить посилання на об'єкти, оскільки типи посилання (примірники `AnyRef`) реалізовані як Java об'єкти, що зберігаються на купі JVM. Для контрасту, змінні типу значення можуть іноді містити посилання (на боксований тип огортки), та іноді ні (коли об'єкт представлений як примітивне значення). Кажучи загалом, змінна Scala посилається на об'єкт. Термін "посилається" більш абстрактний, ніж "містить посилання". Якщо змінна є типу `scala.Int` наразі представлена як примітивне значення Java `int`, тоді змінна все ще посилається на об'єкт `Int`, але посилання не задіяне.

_**предикат**_ Предикат є функцією з типом результату `Boolean`.

_**прив'язана змінна**_ Прив'язана змінна в виразі є змінна, що є одночасно визначена та використана в виразі. Наприклад, в виразі функціонального літерала `(x: Int) => (x, y)`, використовуються обоє змінні, `x` та `y`, але тільки `x` прив'язана, оскільки вона визначається в виразі як `Int`, і є єдиним аргументом функції, визначеній цім виразом.

_**примірник**_ Примірник, або примірник класу, є об'єктом, концепцією, що існує тільки під час виконання.

_**принцип уніформного доступу**_ Принцип уніформного доступу стверджує, що змінні та функції без параметрів повинні отримувати доступ за однаковим синтаксисом. Scala підтримує цей принцип, не дозволяючи ставити дужки в місці виклику функцій без параметрів. Як результат, визначення функції без параметрів може бути змінена на `val`, або навпаки, без впливу на код клієнта.

_**присвоєння**_ Ви можете присвоїти об'єкт до змінної. Після цього змінна буде посилатись на об'єкт.

_**прозорість посилання**_ Властивість функцій, що незалежні від тимчасового контексту, та не мають побічних ефектів. Для певного вводу виклик прозорої до посилання функції може бути замінене не її результат, без зміни семантики програми.

_**процедура**_  _Процедура_ є функція, результат якої `Unit`, і яка, таким чином, виконується виключно для її побічних ефектів.

_**прямий субклас**_ Клас є _прямим субкласом_ свого прямого суперкласу.

_**прямий суперклас**_ Клас, від якого клас або трейт напрму походить, найближчий клас вище в його ієрархії наслідування. Якщо клас `Parent` споминається в опціональному твердженні `extends` класу `Child`, тоді `Parent` є прямим суперкласом `Child`. Якщо трейт вказується в твердженні `extends` `Child`, прямий суперклас трейту є прямим суперкласом `Child`. Якщо `Child` не має твердження `extends`, тоді `AnyRef` є прямим суперкласом `Child`. Якщо прямий суперклас класу приймає параметри типу, наприклад, `class Child extends Parent[String]`, прямий суперклас `Child`  все ще `Parent`, не `Parent[String]`. З іншого боку, `Parent[String]` буде прямим супертипом `Child`. Дивіться _супертип_ щодо більшої дискусії про різницю між класами і типами.

_**рантайм**_  Середовище виконання Java Virtual Machine, або JVM, що виконує Scala програму. Рантайм охоплює обоє, віртуальну машину, як визначено в Java Virtual Machine Specification, та бібліотеки рантайму Java API і стандартного Scala API. Фраза _run time_ (з проміжком між `run` та `time`) означає саме час, коли виконується програма, та контрастує з часом компіляції.

_**рантайм тип**_ Тип об'єкта під час виконання. Для контрасту, _статичний тип_ є типом виразу під час компіляції. Більшість типів рантайму просто звичайні типи, без параметрів типу. Наприклад, рантайм типу `"Hi"` є `String`, та рантайм тип `(x: Int) => x + 1` є `Function1`. Рантайм типи можуть бути перевірені за допомогою `isInstanceOf`.

_**результат**_ Вираз в програмі Scala дає результат. Результат кожного виразу в Scala є об'єктом.

_**рекурсивність**_ Функція є рекурсивною, якщо вона викликає сама себе.

_**селектор**_ Значення, що буде порівнюватись в виразі `match`. Наприклад, в `s match { case _ => }`, селектор є `s`.

_**серіалізація**_ Ви можете серіалізувати об'єкт в потік байтів, що потім може бути збережений або переданий по мережі. Ви можете пізніше де-серіалізувати потік байтів, навіть на іншому комп'ютері, та отримати об'єкт, що той самий, що і оригінальний серіалізований об'єкт.

_**сигнатура**_ Сигнатура є скороченням від _сигнатури типів_.

_**сигнатура типу**_ Сигнатура типу метода складається з імені, числа, порядку, та типів його параметрів, якщо такі є, та його результуючого типу. Тип сигнатури класу, трейта, або об'єкта синглтона складається з його імені, типу сигнатур всіх його членів та конструкторів, та його задекларованих відношень наслідування та міксінів.

_**синтетичний клас**_ Синтетичний клас є згенерований автоматично компілятором, скоріше, ніж бути написаним руками програміста.

_**скрипт**_ Файл, що містить високорівневі визначення та твердження, що може бути виконаний напряму за допомогою `scala`, без явної компіляції. Скрип має завершувати виразом, не визначенням.

_**статичний тип**_ Дивіться _тип_.

_**створення примірнику**_ Створити примірник класу означає створити новий об'єкт з класу, дія, що відбувається тільки під час виконання.

_**субклас**_ Клас є субкласом для всіх своїх суперкласів та супертрейтів.

_**субтип**_ Компілятор буде дозволяти любий з субтипів типу використовуваться як замінник, коли вимагається використання типу. Для класів та трейтів, що не приймають параметрів типу, відношення субтипів відзеркалює відношення субкласів. Наприклад, якщо клас `Cat` є субкласом абстрактного класу `Animal`, та жодний не приймає параметрів типу, тип `Cat` є субтипом `Animal`. Подібно до цього, якщо трейт `Apple` є субтрейтом трейту `Fruit`, та жодний не приймає параметрів, тип `Apple` є субтипом типу `Fruit`. Однак для класів та трейтів, що приймають параметри типу, в гру вступає варіантність. Наприклад, оскільки абстрактний клас `List` декларований коваріантним по своєму єдиному параметру типа (тобто, `List` декларований як `List[+A]`), `List[Cat]` є субтипом `List[Animal]`, та `List[Apple]` є субтипом `List[Fruit]`. Ці відношення субтипів існують навіть не зважаючи на те, що клас кожного з ціх типів є `List`. Для контрасту, оскільки `Set` не декларований як коваріантний по своєму параметру типа (тобто, `Set` декларований як `Set[A]` без знака плюс), `Set[Cat]` не є субтипом `Set[Animal]`. Субтип повинен коректно реалізувати контракти супертипів, так що тут застосовуюється Принцип Заміни Ліскова, але компілятор тільки перевіряє цю властивість на рівні перевірки типів.

_**субтрейт**_ Трейт є субтрейтом для всіх своїх супертрейтів.

_**суперклас**_ Суперкласу класу включають всі прямі суперкласи, прямі суперкласи ціх суперкласів, і так далі, аж до `Any`.

_**супертип**_ Тип є супертипом всіх своїх субтипів.

_**супертрейт**_ Супертрейти класу або трейтів, якщо такі є, включають всі трейти, напряму зміксовані в клас або трейт любого зі своїх суперкласів, плюс любі супертрейти ціх трейтів.

_**твердження**_ Вираз, визначення або імпорт, тобто речі, що можуть іти в шаблоні або блоці в джерельному коді Scala.

_**тип**_ Кожна змінна та вираз в програмі Scala має тип, що відомий під час компіляції. Тип обмежує можливі значення, на які може посилатись змінна, або яке може продукувати вираз під час виконання. Змінна або тип виразу також може посилатись на статичний тип, якщо треба відрізняти його від типу об'єкту під час виконання. Іншими словами, "тип" сам по собі означає статичний тип. Тип відрізняється від класу, бо клас, що приймає параметри типу, може конструювати багато типів. Наприклад, `List` є класом, але не типом. `List[T]` є типом з вільним параметром типу. `List[Int]` та `List[String]` також є типами (так звані заземлені типи, бо не мають вільних параметрів типів). Тип може мати "клас" або "трейт." Наприклад, клас типу `List[Int]` є `List`. Трейт типу `Set[String]` є `Set`.

_**тип значення**_ Тип значення є любим субкласом `AnyVal`, такий як `Int`, `Double`, або `Unit`. Цей термін має значення на рівні джерельного коду Scala. Під час виконання примірники значень типів, що відповідають до примітивних типів Java, можуть бути реалізовані в термінах значень примітивних типів або примірників класів огорток, таких як `java.lang.Integer`. Під час життєвого циклу примірника рантайм може трансформувати тип між примітивним типом та огорткою (тобто, боксувати та розбоксувати змінну).

_**тип посилання**_ Тип посилання є субкласом `AnyRef`. Примірники типу посилання під час виконання знаходяться в купі JVM.

_**тип результату**_ Тип результату метода є тип значення, що є результатом виклику метода. (В Java, ця концепція називається _типом повернення_.)

_**тип `self`**_  _Тип `self`_ трейта є удаваний тип `this`, отримувача, що буде використовуватись в цьому трейті. Любий суцільний клас, що міксує трейт, має переконатись, що цей тип відповідає до типу трейта `self`. Найбільш загальне використання типів `self` є для поділення великих класів на декілька трейтів, як описано в Главі 29.

_**трейт**_ Трейт, що визначений за допомогою ключового слова `trait`, подібний до абстрактного класу, що не може приймати жодних значень параметрів, та може бути "заміксований" в класи або інші трейти через процес, відомий як міксін композиція. Коли клас міксується в клас або трейт, він називається міксіном. Трейт може бути параметризований одним або більше типами. Коли трейт параметризований типами, він створює тип. Наприклад, `Set` ґ трейтом, що приймає один параметр типу, тоді як `Set[Int]` є типом. Також кажуть, що `Set` є "трейтом типу" `Set[Int]`.

_**удосконалення типу**_ Тип, сформований через надання базовому типу декількох членів в фігурних дужках. Члени в фігурних дужках удосконалюють типи, що присутні в базовому типі. Наприклад, тип "animal that eats grass" є `Animal { type SuitableFood = Grass }`. 

_**фільтр, або вираз фільтру**_ `if`, за яким слідує логічний виразв виразі `for`. В `for(i <- 1 to 10; if i % 2 == 0)` фільтр є `if i % 2 == 0`. Значення зправа від `if` є виразом фільтра.

_**фільтруючий вираз**_ Фільтруючий вираз, або вираз фільтру, є логічний вираз, що слідує за `if` в виразі `for`. В `for(i <- 1 to 10; if i % 2 == 0)` вираз фільтру є "i % 2 == 0".

_**функціональне значення**_ Об'єкт функції, що може бути викликаний так само, як люба інша функція. Клас функціонального значення розширює один з трейтів `FunctionN` (тобто, `Function0`, `Function1`) з пакунку `scala`, та and isusually expressed in source code via function literal syntax. A function value is "invoked" when its apply method is called. A function value that captures free variables is a _closure_.

_**функціональний літерал**_ Функція без імені в джерельному коді Scala, задана за допомогою синтаксису функціонального літералу. Наприклад, `(x: Int, y: Int) => x + y`.

_**функція**_ _Функція_ може бути _викликана_ зі списком аргументів, щоб спродукувати результат. Функція має список параметрів, тіло, та тип результата. Функції, що є членами класу, трейта або об'єкта синглтона, називаються _методами_. Функції, визначені в інших функціях, називаються _локальними функціями_. Функції, тип результата яких є `Unit` називаються _процедурами_. Анонімні функції в джерельному коді називаються _функціональними літералами_. Під час виконання функціональні літерали стають примірниками об'єктів, що називаються _функціональними значеннями_.

_**функціональний стиль**_ _Функціональний стиль_ програмування наголошує на функціях та обчисленні результатів, та не робить наголос на порядку, в якому трапляються оператори. Стиль характеризується передачею функціональних значень в циклічні методи, незмінними даними, методами без побічних ефектів. Це домінантна парадигма таких мов, як Haskell та Erlang, та контастує з _імперативним стилем_.

_**хвостова рекурсія**_ Функція має хвостову рекурсію, якщо єдине місце, де вона викликає сама себе - це остання операція функції.

_**цільова типізація**_ Цільова типізація є формою виводу типів, що приймає до уваги очікуваний тип. Наприклад, в `nums.filter((x) => x > 0)`, компілятор Scala виводить тип `x` як тип елементів `nums`, оскільки метод `filter` викликає функцію на кожному елементі `nums`.

_**частково застосована функція**_ Функція, що використовується в виразі, та в якій відсутні деякі з його аргументів. Наприклад, якщо функція `f` має тип `Int => Int => Int`, тоді `f` та `f(1)` є частково застосовані функції.

_**член**_ Член це любий іменований елемент шаблона класу, трейта або об'єкта синглтона. Член може бути доступний через ім'я власника, крапку, та просте ім'я члену. Наприклад, високорівневі поля та методи, визначені в класі, є членами цього класу. Трейт, визначений в класі, є членом оточуючого класу. Тип, визначений за допомогою ключового слова `type` в класі, є членом цього класу. Клас є членом пакунку, в якому він визначений. Для контрасту, локальна змінна або локальна функція не є членом свого оточуючого блока.

_**шаблон класа**_ Шаблон є тілом визначення класу, трейта, або об'єкта синглтона. Він визначає тип сигнатури, поведінки та початковий стан класу, трейта або об'єкта.

_**шаблон порівняння**_ В виразі `match` альтернативі, шаблон слідує за кожним ключовим словом `case` та стоїть перед або захисником шаблона, або перед символом `=>`.

_**шляхо-залежний тип**_ Тип, як `swiss.cow.Food`. Частина `swiss.cow` є шляхом, що формує посилання на об'єкт. Значення типу чутлива до шляху, що ви використовуєте для доступа до нього. Наприклад, типи `swiss.cow.Food` та `fish.Food` є різними типами.

_**JVM**_ JVM є Java Virtual Machine, або рантайм, середовище виконання, що містить програму, що виконується Scala програма.

