include::headers.adoc[]

Про авторів
-----------

Martin Odersky є створювачем мови Scala. Він є професором EPFL в Лозані, Швейцарія, та засновником Typesafe, Inc. Він робить з програмними мовами та системами, більш точно над темами, як скомбінувати об'єктно-орієнтовне та функціональне програмування. З 2001го року він зконцентрований на розробці, реалізації та покращенні Scala. До цього він зазнав впливу розробки Java в якості спів-розробника дженериків Java, та як оригінальний автор поточного референсного компілятора javac. Він є товаришем ACM.

Lex Spoon є софтверний інженер в Semmle, Ltd. Він робив над Scala протягом двох років в якості пост-докторської практики в EPFL. Він отримав доктоорську ступінь в  Georgia Tech, де він робив над статистичним аналізом динамічних мов. На додаток до Scala він допомагав розробляти широку ріноманітність програмних мов, включаючи динамічну мову Smalltalk, наукову мову X10, та логічну мову, що живить Semmle. Він та його жінка живуть в Атланті з двома котами та чихуахуа.

Bill Venners є президентом Artima, Inc., видавник веб сайту Artima Developer (www.artima.com), та співзасновник Escalate Software, LLC. Він автор книги Inside the Java Virtual Machine, програміст-орієнтовного дослідження архитектури Java платформи та її нутрощів. Його популярні колонки в журналі JavaWorld торкаються нутрощів Java, об'єктно-орієнтовної розробки та Jini. Будучи активний в спільноті Jini Community з її створення, Bill лідирує в проекті Jini Community ServiceUI, чиє ServiceUI API стало де-факто стандартним способом асоціювати користувацькій інтерфейс з Jini сервісами. Bill також ведучий розробник та дизайнер ScalaTest, відкритого інструменту тестування для Scala та Java розробників.