include::header.adoc[]

[quote,Bertrand Russell]
Любов розумна, ненависть глупа. В цьому світі, що стає більш і більш тісно пов'язаним, ми маємо навчитись поважати один одного, ми маємо змиритись з фактом, що деякі люди кажуть речі, які нам не до вподоби. Ми зможемо жити разом тільки в цей спосіб. Але якщо ми зібрались жити разом, та не помирати разом, ми маємо навчитись деякій мірі благодійності та деякій мірі терпимості, що абсолютно необхідна для продовження життя на цій планеті.

Про цю книгу
------------

Ця книга для типового розробника Scala, можливо з Java бекграундом, який одночасно скептичний та зацікавлений в парадігмі Функціонального програмування (FP). Ця книга підкріплює кожну комцепцію практичними прикладами, включаючи написання веб застосування.

Ця книга використовує Scalaz 7.2, найбільш популярну, стабільну, обгрунтовану та всебічну ферсію фреймворка функціонального програмування для Scala.

Ця книжка розроблена для читання від обкладинки до обкладинки, в представленому порядку, з відпочинком між главами. Ранішні глави захочують стилі кодування, які ми потім дискредитуємо: подібно то того, як ми вчимо теорію гравітації Ньютона в дитинстві, та прогресуємо до Рімана / Ейнштейна / Максевела, якщо ми стаємо студентами-фізиками.

Комп'ютер не потрібен для просування, але вивчення джерельного коду `Scalaz` вітається. Деякі з найбільш складних шматків коду доступні з джерельним кодом книги, і ті, хто бажає практичних вправ, заохочуються до (пере-)реалізації `Scalaz` (та коду прикладів), використовуючи часткові описи, представлені в цій книзі.

Ми рекомендуємо `The Red Book` в якості подальшого читання. Вона навчає як писати FP бібліотеки на Scala, походячи з первинних прикладів.

Copyleft Зауваження
-------------------
Ця книга є Libre, та слідує філософії Free Software: ви можете використовувати цю книгу як побажаєте, джерело доступне, та ви можете розповсюджувати цю книгу, або ви можете розповсюджувати вашу власну версію. Це означає, що ви можете друкувати її, робити фотокопії, надсилати електронною поштою, завантажувати на веб сайти, змінювати її, отримувати з неї гроші, змішувати її, видаляти частини та малювати на її сторінках.

Ця книга є Copyleft: якщо ви змінити цю книгу та розповсюдите вашу версію, ви також маєте надати це право вашим отримувачам.

Ця книга використовує ліцензію Creative Commons Attribution ShareAlike 4.0 International (CC BY-SA 4.0).

Всі оригінальні шматки коду в цій книзі окремо ліцінзійовані CC0, ви можете використовувати їх без обмежень. Експерти від `Scalaz` та пов'язаних бібліотек підтримують свої ліензії, що повністю відтворені в додатку.

Застосування-приклад `drone-dynamic-agents` розповсюджується на умовах GPLv3: тільки частини з цієї книги доступні без обмежень.

Подяки
------
Diego Esteban Alonso Blas, Raúl Raja Martínez та Peter Neyens з 47 degrees, Rúnar Bjarnason, Tony Morris, John de Goes та Edward Kmett отримують подяки за допомогу в поясненні принципів FP. Kenji Yoshida та Jason Zaugg за те, що були головними авторами Scalaz, та Paul Chiusano / Miles Sabin за виправлення критичної вади в компіляторі Scala (SI-2712).

Дякую читачам, що надсилали зауваження до ранішніх чернеток цього тексту.

Деякий матеріал був зокрема корисний для моєго власного розуміння концепцій цієї книги. Подяка Juan Manuel Serrano за `All Roads Lead to Lambda`, Pere Villega за `On Free Monads`, Dick Wall та Josh Suereth за `For: What is it Good For?`, Erik Bakker за `Options in Futures, how to unsuck them`, Noel Markham за `ADTs for the Win!`, Sukant Hajra за `Classy Monad Transformers`, Luka Jacobowitz за `Optimizing Tagless Final`, Vincent Marquez за `Index your State`, Gabriel Gonzalez за `The Continuation Monad`, та Yi Lin Wei / Zainab Ali за їх туторіали на зустрічах `Hack The Tower`.

Корисні душі, хто терпляче пояснював мені речі: Merlin Göttlinger, Edmund Noble, Fabio Labella, Adelbert Chang, Michael Pilquist, Paul Snively, Daniel Spiewak, Stephen Compall, Brian McKenna, Ryan Delucchi, Pedro Rodriguez, Emily Pillmore, Aaron Vargo, Tomas Mikula, Jean-Baptiste Giraudeau, Itamar Ravid, Ross A. Baker, Alexander Konovalov, Harrison Houghton, Alexandre Archambault, Christopher Davenport, Jose Cardona, Isaac Elliott.

Передумови
==========
Щоб налаштувати проект, що використовує бібліотеки, представлені в цій книзі, використовуйте останню версію Scala з вімкненими FP-специфічними можливостями (в `build.sbt`):

[source,scala]
----
  scalaVersion in ThisBuild := "2.12.6"
  scalacOptions in ThisBuild ++= Seq(
    "-language:_",
    "-Ypartial-unification",
    "-Xfatal-warnings"
  )
  
  libraryDependencies ++= Seq(
    "com.github.mpilquist" %% "simulacrum"     % "0.13.0",
    "org.scalaz"           %% "scalaz-core"    % "7.2.26"
  )
  
  addCompilerPlugin("org.spire-math" %% "kind-projector" % "0.9.7")
  addCompilerPlugin("org.scalamacros" % "paradise" % "2.1.1" cross CrossVersion.full)
----

Щоб утримувати шматки коду короткими ми будемо уникати розділу імпорту. Коли не сказане інакше, вважається що всі фрагменти мають наступні імпорти:

[source,scala]
----
  import scalaz._, Scalaz._
  import simulacrum._
----
