include::headers.adoc[]


[quote,Bertrand Russell]
Любов розумна, ненависть глупа. В цьому світі, що стає більш і більш тісно пов'язаним, ми маємо навчитись поважати один одного, ми маємо змиритись з фактом, що деякі люди кажуть речі, які нам не до вподоби. Ми зможемо жити разом тільки в цей спосіб. Але якщо ми зібрались жити разом, та не помирати разом, ми маємо навчитись деякій мірі благодійності та деякій мірі терпимості, що абсолютно необхідна для продовження життя на цій планеті.

Про цю книгу
------------

Ця книга для типового розробника Scala, можливо з Java бекграундом, який одночасно скептичний та зацікавлений в парадігмі Функціонального програмування (FP). Ця книга підкріплює кожну комцепцію практичними прикладами, включаючи написання веб застосування.

Ця книга використовує Scalaz 7.2, найбільш популярну, стабільну, обгрунтовану та всебічну ферсію фреймворка функціонального програмування для Scala.

Ця книжка розроблена для читання від обкладинки до обкладинки, в представленому порядку, з відпочинком між главами. Ранішні глави захочують стилі кодування, які ми потім дискредитуємо: подібно то того, як ми вчимо теорію гравітації Ньютона в дитинстві, та прогресуємо до Рімана / Ейнштейна / Максевела, якщо ми стаємо студентами-фізиками.

A computer is not necessary to follow along, but studying the Scalaz source code is encouraged. Some of the more complex code snippets are available with the book’s source code and those who want practical exercises are encouraged to (re-)implement Scalaz (and the example application) using the partial descriptions presented in this book.

We also recommend The Red Book as further reading. It teaches how to write an FP library in Scala from first principles.

Copyleft Notice
---------------
This book is Libre and follows the philosophy of Free Software: you can use this book as you like, the source is available you can redistribute this book and you can distribute your own version. That means you can print it, photocopy it, e-mail it, upload it to websites, change it, translate it, charge for it, remix it, delete bits, and draw all over it.

This book is Copyleft: if you change the book and distribute your own version, you must also pass these freedoms to its recipients.

This book uses the Creative Commons Attribution ShareAlike 4.0 International (CC BY-SA 4.0) license.

All original code snippets in this book are separately CC0 licensed, you may use them without restriction. Excerpts from Scalaz and related libraries maintain their license, reproduced in full in the appendix.

The example application drone-dynamic-agents is distributed under the terms of the GPLv3: only the snippets in this book are available without restriction.

Thanks
------
Diego Esteban Alonso Blas, Raúl Raja Martínez and Peter Neyens of 47 degrees, Rúnar Bjarnason, Tony Morris, John de Goes and Edward Kmett for their help explaining the principles of FP. Kenji Yoshida and Jason Zaugg for being the main authors of Scalaz, and Paul Chiusano / Miles Sabin for fixing a critical bug in the Scala compiler (SI-2712).

Thanks to the readers who gave feedback on early drafts of this text.

Some material was particularly helpful for my own understanding of the concepts that are in this book. Thanks to Juan Manuel Serrano for All Roads Lead to Lambda, Pere Villega for On Free Monads, Dick Wall and Josh Suereth for For: What is it Good For?, Erik Bakker for Options in Futures, how to unsuck them, Noel Markham for ADTs for the Win!, Sukant Hajra for Classy Monad Transformers, Luka Jacobowitz for Optimizing Tagless Final, Vincent Marquez for Index your State, Gabriel Gonzalez for The Continuation Monad, and Yi Lin Wei / Zainab Ali for their tutorials at Hack The Tower meetups.

The helpul souls who patiently explained things to me: Merlin Göttlinger, Edmund Noble, Fabio Labella, Adelbert Chang, Michael Pilquist, Paul Snively, Daniel Spiewak, Stephen Compall, Brian McKenna, Ryan Delucchi, Pedro Rodriguez, Emily Pillmore, Aaron Vargo, Tomas Mikula, Jean-Baptiste Giraudeau, Itamar Ravid, Ross A. Baker, Alexander Konovalov, Harrison Houghton, Alexandre Archambault, Christopher Davenport, Jose Cardona, Isaac Elliott.

Practicalities
To set up a project that uses the libraries presented in this book, use a recent version of Scala with FP-specific features enabled (e.g. in build.sbt):

  scalaVersion in ThisBuild := "2.12.6"
  scalacOptions in ThisBuild ++= Seq(
    "-language:_",
    "-Ypartial-unification",
    "-Xfatal-warnings"
  )
  
  libraryDependencies ++= Seq(
    "com.github.mpilquist" %% "simulacrum"     % "0.13.0",
    "org.scalaz"           %% "scalaz-core"    % "7.2.26"
  )
  
  addCompilerPlugin("org.spire-math" %% "kind-projector" % "0.9.7")
  addCompilerPlugin("org.scalamacros" % "paradise" % "2.1.1" cross CrossVersion.full)
In order to keep our snippets short, we will omit the import section. Unless told otherwise, assume that all snippets have the following imports:

  import scalaz._, Scalaz._
  import simulacrum._
