include::header.adoc[]

1. Вступ
========

Людським інстинктом є виступати скептиком до нових парадигм. Щоб надати деяку перспективу який далекий шлях ми пройшли, та зміни, що ми сприйняли щодо JVM, давайте почнемо зі швидкого нагадування останніх 20 років.

Java 1.2 ввела Collections API, дозволивши нам писати методи, що абстрагувались на змінних колекціях. Це було корисно для написання алгоритмів загального призначення, та стало фундаментальним каменем нашого коду.

Але була проблема, ми мали виконувати приведення часу виконання:

[source,scala]
----
  public String first(Collection collection) {
    return (String)(collection.get(0));
  }
----
У відповідь розробники визначили прикладні об'єкти в своїй бізнес логиці, що ефективно буди Колекціями Речей, а Collection API стало деталлю реалізації.

В 2005 Java 5 ввела дженеріки, дозволяючи нам визначати `Collection<Thing>`, абстрагуючись над контейнером та його елементами. Дженеріки змінили те, як ми пишемо на Java.

Автор компілятора дженеріків Java, Martin Odersky, потім створив  Scala з суворішою системою типів, незмінними даними та множинним наслідуванням. Це дало зплав об'єктно-орієнтовного (OOP) та функціонального програмування (FP).

Для більшості розробників FP означає використання незмінних даних наскільки це можливо, але змінний стан все ще є потрібним злом, яке треба ізолювати та керувати, наприклад за допомогою акторів Akka або синхронізованих класів. Цей стиль FP призводить до простиших програм, що простіше розпаралелити та розповсюдити, покращення порівняно з  Java. Але це тільки подряпина поверні переваг FP, як ми з'ясуємо в цій книзі.

Scala також привносить `Future`, роблячи простим написання асинхронних застосувань. Але коли `Future` стає типом повернення, все має бути переписаним, щоб досягти цього, включаючи тести, що тепер є предметом до довільних таймаутів.

Ми маємо проблему, подібну до Java 1.0: немає способу абстрагуватись над виконанням, майже так само, як ми не мали шляху абстрагуватись над колекціями.

1.1 Абстрагування над виконанням
--------------------------------

Скажімо, ви бажаєте взаємодіяти з користувачем через інтерфейс командного рядка. Ми можемо читати що друкує користувач, та ми можете писати їм повідомлення.

[source,scala]
----
  trait TerminalSync {
    def read(): String
    def write(t: String): Unit
  }
  
  trait TerminalAsync {
    def read(): Future[String]
    def write(t: String): Future[Unit]
  }
----
Як ми пишемо уніфікований код, що робить щось таке просте, як відлуння користувацького вводу синхронно або асинхронно, в залежності від рантайм реалізації?

Ви можете написати синхронну версію, та огорнути її в `Future`, але тепер ми маємо турбуватись про те, який пул потоків треба задіяти для цієї роботи, або ми можемо зробити `Await.result` на `Future`, та ввести блокування потоків. В жодному разі це безліч шаблонного коду, та ми фундаментально маємо справу з різними API, що не є уніфікованими.

Ми можемо віришити цю проблему, як Java 1.2, з загальним предком, використовуючи можливості типів вищих порядків (higher kinded types, HKT) Scala.

Higher Kinded Types дозволяють нам використовувати конструктор типу в наших параметрах типів, що виглядає як `C[_]`. Це спосіб сказати, що чим би не було `C`, воно має приймати параметр типу. Наприклад:

[source,scala]
----
  trait Foo[C[_]] {
    def create(i: Int): C[Int]
  }
----
`List` є конструктором типу, оскільки він приймає тип (як `Int`), та конструює тип (`List[Int]`). Ми можемо реалізувати `Foo` використовуючи `List`:

[source,scala]
----
  object FooList extends Foo[List] {
    def create(i: Int): List[Int] = List(i)
  }
----
Ми можемо реалізувати `Foo` для будь-чого з діркою в параметрах типу, як `Either[String, _]`. Нажаль, це трохи незграбно, і ми маємо створювати псевдоними типів, щоб оманою змусити компілятор прийняти його:

[source,scala]
----
  type EitherString[T] = Either[String, T]
----
Псевдоними типів не визначають нові типи, вони є простою підстановкою, та не провадять додаткової безпеки типів. Компілятор замінює `EitherString[T]` на `Either[String, T]` будь-де. Цей прийом може використовуватись для омани компілятора для сприйняття типів з однією діркою, коли він би інакше думав що їх дві, як коли ми реалізуємо `Foo` через `EitherString`:
[source,scala]
----
  object FooEitherString extends Foo[EitherString] {
    def create(i: Int): Either[String, Int] = Right(i)
  }
----
Альтернитивно, плагін проектора типів дозволяє нам уникати псевдонимівтипів, та використовувати синтаксис `?`, щоб сказати компілятору, де є дірка типу:
[source,scala]
----
  object FooEitherString extends Foo[Either[String, ?]] {
    def create(i: Int): Either[String, Int] = Right(i)
  }
----
Нарешті, є один збочений трюк, що ми можемо використати, коли ми бажаємо ігнорувати конструктор типу. Визначте псевдонім типу як еквівалентний до його параметру:
[source,scala]
----
  type Id[T] = T
----
Перед тим як продовжити, зрозумійте, що `Id[Int]` є та сама річ, що і `Int`, через підстановку `Int` в `T`. Оскільки `Id` є валідний конструктор типів, ми можемо використовувати `Id` в реалізації `Foo`:
[source,scala]
----
  object FooId extends Foo[Id] {
    def create(i: Int): Int = i
  }
----
Ми бажаємо визначити `Terminal` для конструктора типів `C[_]`. Через визначення `Now` для конструювання його параметру типів (як `Id`), ми можемо реалізувати загальний інтерфейс для синхронних та асинхронних терміналів:
[source,scala]
----
  trait Terminal[C[_]] {
    def read: C[String]
    def write(t: String): C[Unit]
  }
  
  type Now[X] = X
  
  object TerminalSync extends Terminal[Now] {
    def read: String = ???
    def write(t: String): Unit = ???
  }
  
  object TerminalAsync extends Terminal[Future] {
    def read: Future[String] = ???
    def write(t: String): Future[Unit] = ???
  }
----
Ми можемо мислити `C` як `Context`, оскільки ми кажемо “в контексті виконання `Now`” або “в `Future`”.

Але ми нічого не знаємо про C, і ми не можемо нічого робити з `C[String]`. Що нам треба є різновид оточення виконання, що дозволяє нам викликати метод, що повертає `C[T]`, та потім бути в змозі робить щось з `T`, включаючи виклик іншого метода на `Terminal`. Нам також треба спосіб огорнути значення, як `C[_]`. Ця сигнатура робить гарно:
[source,scala]
----
  trait Execution[C[_]] {
    def chain[A, B](c: C[A])(f: A => C[B]): C[B]
    def create[B](b: B): C[B]
  }
----
дозволяючи нам писати:
[source,scala]
----
  def echo[C[_]](t: Terminal[C], e: Execution[C]): C[String] =
    e.chain(t.read) { in: String =>
      e.chain(t.write(in)) { _: Unit =>
        e.create(in)
      }
    }
----
Тепер ми можемо поділити реалізацію `echo` між синхронними та асинхронними шляхами. Ви можете написати мок реалізацію `Terminal[Now]`, та використовувати його в наших тестах без жодних таймаутів.

Реалізації `Execution[Now]` та `Execution[Future]` повторно використовуються загальними методами, як `echo`.

Але код для `echo` жахливий!

Можливості неявних класів мови Scala надають `C` деякі методи. Ми будемо називати ці методи `flatMap` та `map` з причин, що за мить стануть яснішими. Кожний метод приймає неявний `Execution[C]`, але це нічого більше, ніж `flatMap` та `map`, що ми використовували для `Seq`, `Option` та `Future`:
[source,scala]
----
  object Execution {
    implicit class Ops[A, C[_]](c: C[A]) {
      def flatMap[B](f: A => C[B])(implicit e: Execution[C]): C[B] =
            e.chain(c)(f)
      def map[B](f: A => B)(implicit e: Execution[C]): C[B] =
            e.chain(c)(f andThen e.create)
    }
  }
  
  def echo[C[_]](implicit t: Terminal[C], e: Execution[C]): C[String] =
    t.read.flatMap { in: String =>
      t.write(in).map { _: Unit =>
        in
      }
    }
----
Тепер ми можемо розкрити, чому ми використовували `flatMap` як ім'я метода: воно дозволяє нам використовувати розширений `for`, що є тільки синтаксичним цукром над вкладеними `flatMap` та `map`.
[source,scala]
----
  def echo[C[_]](implicit t: Terminal[C], e: Execution[C]): C[String] =
    for {
      in <- t.read
       _ <- t.write(in)
    } yield in
----
Наш `Execution` має ту саму сигнатуру, що і трейт в `Scalaz` з назвою `Monad`, за винятком що `chain` є `bind`, та `create` є `pure`. Ми кажемо, що `C` є монадичним, коли доступне неявне `Monad[C]`. На додаток `Scalaz` має псевдоним типу `Id`.

Висновок такий: якщо ми пишемо методи, що оперують з монадичними типами, тоді ми можемо записати послідовний код, що абстрагується над контектстом виконання. Тут ми показали абстрагування над синхронним та асинхронним виконанням, але це може бути також для більш суворої обробки помилок (де `C[_]` є `Either[Error, _])`, керування доступом до мінливого стану, виконання I/O, або аудиту сессії.

1.2 Чисто функціональне прогрумування
-------------------------------------
Функціональне програмування є актом написання програм з чистих функцій. Чисті функції мають три властивості:

Повні: повертають значення для кожного можливого вводу
Детерміністичні: повертають те саме значення для того самого вводу
Безгрішні: немає (прямої) взаємодії зі світом або станом програми.

Разом ці властивості надають нам безпрецендентну здатність продумувати код. Наприклад, вхідні значення простіше ізолювати за допомогою повноти, кешування можливе коли функції детерміністичні, та взаємодію зі світом простіше контролювати та тестувати, коли функції безгрішні.

Різновид речей, що порушують ці принципи, є побічні ефекти: прямо отримуючи доступ або змінюючи змінний стан (тобто, маючи `var` в класі або використовуючи старий нечистий API), комунікація з зовнішними ресурсами (як файли або мережевий пошук), або закидання та перехоплення виключень.

Ми пишемо чисті функції уникаючи виключень, та взаємодіючи зі світом через безпечний контекст виконання `F[_]`.

В попередньому розділі ми абстрагувались над виконанням, та визначили  `echo[Id]` та `echo[Future]`. Ми могли обгрунтовано очікувати, що виклик любого `echo` не буде виконувати жодних побічних ефектів, оскільки вони чисті. Однак якщо ми використовуємо `Future` або `Id` як контекст виконання, наше застосування почне слухати на `stdin`:
[source,scala]
----
  val futureEcho: Future[String] = echo[Future]
----
Ми зруйнували чистоту, та більше не пишемо FP код: `futureEcho` є результатом виконання `echo` один раз. `Future` поєднує визначення програми з її інтерпретацією (її виконанням). Як результат, застосування, побудовані на `Future`, складно промислювати.

Вираз посилково прозорий, якщо він може бути замінений відповідним значенням без зміни поведінки програми.

Чисті функції посилково прозорі, дозволяючи гарно використовувати код, опитимізувати продуктивність, розуміти та контролювати програму.

Нечисті функції не є посилково прозорими. Ми не можемо замінити `echo[Future]` на значення, таке як `val futureEcho`, оскільки бридкий користувач може надрукувати дещо інше іншого разу.

Ми можемо визначити простий безпечний контекст виконання `F[_]`:
[source,scala]
----
  final class IO[A](val interpret: () => A) {
    def map[B](f: A => B): IO[B] = IO(f(interpret()))
    def flatMap[B](f: A => IO[B]): IO[B] = IO(f(interpret()).interpret())
  }
  object IO {
    def apply[A](a: =>A): IO[A] = new IO(() => a)
  }
----
що ліниво обчислює голову. `IO` є просто структурою даних, що посилається (потенційно) на нечистий код, та насправді нічого не виконує. Ми можемо реалізувати `Terminal[IO]`:
[source,scala]
----
  object TerminalIO extends Terminal[IO] {
    def read: IO[String]           = IO { io.StdIn.readLine }
    def write(t: String): IO[Unit] = IO { println(t) }
  }
----
та викликати `echo[IO]` щоб повернути значення:
[source,scala]
----
  val delayed: IO[String] = echo[IO]
----
Ця `val delayed` може використовуватись повторно, але це тільки визначення роботи, що була зроблена. Ми можемо відобразити `String` та скласти додаткові програми, майже так само, як ми могли робити  `map` на `Future`. `IO` честний з нами в тому, що ми залежимо від деякої взаємодії зі світом, але не шкодить нам щодо доступу до виводу від цієї взаємодії.

Нечистий код всередині `IO` обчислюється тільки коли ми `.interpret()` значення, що є нечистою дією:
[source,scala]
----
  delayed.interpret()
----
Застосування, складене з `IO` програм, інтерпретується тільки раз, в методі `main`, що також називається кінцем світу.

В цій книзі ми розширимо концепції, введені в цій главі, та покажемо, як писати керовані, чисті функції, що досягають наших бізнес цілей.
