include::header.adoc[]

2. Розширення for
=================

Розширення `for` в Scala є ідеальною абстракцією для послідовних програм, що взаємодіють зі світом. Оскільки ми будемо багато використовувати його, ми ще раз вивчимо принципи `for`, та як `Scalaz` може допомогти нам писати чистіший код.

Ця глава не намагається писати чисті програми, ці прийоми також стосуються не-FP коду.

2.1 Синтаксичний цукор
----------------------
В Scala `for` є простим правилом переписування, що також називається синтаксичним цукром, що не має жодної контекстуальної інформації.

Щоб побачити, що робить `for` розширення ми використаємо можливість _show and reify_ в `REPL` для друку того, як виглядає код після виведення типів.
[source,scala]
----
  scala> import scala.reflect.runtime.universe._
  scala> val a, b, c = Option(1)
  scala> show { reify {
           for { i <- a ; j <- b ; k <- c } yield (i + j + k)
         } }
  
  res:
  $read.a.flatMap(
    ((i) => $read.b.flatMap(
      ((j) => $read.c.map(
        ((k) => i.$plus(j).$plus(k)))))))
----
Є багато шуму через додатковий цукор (як `+` переписане як `$plus`, тощо). ми будемо пропускати `show` та `reify` для краткості, коли рядок `REPL` виглядає як `reify>`, та вручну підчищатимемо згенерований код, так щоб він не ставав відволікаючим.
[source,scala]
----
  reify> for { i <- a ; j <- b ; k <- c } yield (i + j + k)
  
  a.flatMap {
    i => b.flatMap {
      j => c.map {
        k => i + j + k }}}
----
Правило великого пальця: для кожного `<-` (що називається генератором) є вкладеним викликом `flatMap`, з фінальним генератором `map`, що містить тіло `yield`.

2.1.1 Присвоєння
----------------
Ми можемо присвоїти значення інлайн, як `ij = i + j` (ключове слово  `val` не потрібне).
[source,scala]
----
  reify> for {
           i <- a
           j <- b
           ij = i + j
           k <- c
         } yield (ij + k)
  
  a.flatMap {
    i => b.map { j => (j, i + j) }.flatMap {
      case (j, ij) => c.map {
        k => ij + k }}}
----
`map` по `b` вводить `ij`, що  `flat-mapped` разом з `j`, потім отримується фінальний `map` для коду в `yield`.

Нажаль, ми не можемо присвоювати перед жодним генератором. Існує запит на цю можливість мови, але вона не була реалізована: https://github.com/scala/bug/issues/907
[source,scala]
----
  scala> for {
           initial = getDefault
           i <- a
         } yield initial + i
  <console>:1: error: '<-' expected but '=' found.
----
Ми можемо обійти це обмеження через визначення `val` зовні `for`:
[source,scala]
----
  scala> val initial = getDefault
  scala> for { i <- a } yield initial + i
or create an Option out of the initial assignment

  scala> for {
           initial <- Option(getDefault)
           i <- a
         } yield initial + i
----
`val` не має присвоювати одне значення, воно має бути будь-чим, що робить як `case` в співставленні шаблонів `match`.
[source,scala]
----
  scala> val (first, second) = ("hello", "world")
  first: String = hello
  second: String = world
  
  scala> val list: List[Int] = ...
  scala> val head :: tail = list
  head: Int = 1
  tail: List[Int] = List(2, 3)
----
Те саме вірне в узагальнених `for`:
[source,scala]
----
  scala> val maybe = Option(("hello", "world"))
  scala> for {
           entry <- maybe
           (first, _) = entry
         } yield first
  res: Some(hello)
----
Але будьте пильними, не втратьте жодного випадку, або буде виключення часу виконання (збій повноти).
[source,scala]
----
  scala> val a :: tail = list
  caught scala.MatchError: List()
----
2.1.2 Фільтр
------------
Можливо покласти твердження `if` після генератора, щоб фільтрувати значення по предикату:
[source,scala]
----
  reify> for {
           i  <- a
           j  <- b
           if i > j
           k  <- c
         } yield (i + j + k)
  
  a.flatMap {
    i => b.withFilter {
      j => i > j }.flatMap {
        j => c.map {
          k => i + j + k }}}
----
 Старіші версії Scala використовували `filter`, але `Traversable.filter` створює нові колекції для кожного предиката, так що була введена більш продуктивна альтернатива, `withFilter`. Ми можемо випадково вімкнути `withFilter`, надавши інформацію типу, що інтерпретується як порівняння шаблону.
[source,scala]
----
  reify> for { i: Int <- a } yield i
  
  a.withFilter {
    case i: Int => true
    case _      => false
  }.map { case i: Int => i }
----
Як і присвоювання, генератор може використовувати порівняння шаблонів в лівій частині. Але не відміну від присвоєння (або закидається  `MatchError` по збою), генератори фільтровані, та не схиблять під час виконання. Однак існує неефективне подвійне порівняння шаблону.

Плагін компілятора `better-monadic-for` продукує альтернативне, краще децукрування, ніж компілятор Scala. Цей приклад інтерпретується так:
[source,scala]
----
  reify> for { i: Int <- a } yield i
  
  a.map { (i: Int) => i}
----
замість неефективного подвійного співпадіння (в кращому випадку) та тихої фільтрації під час виконання (в гіршому випадку). Дуже рекомендуємо.

2.1.3 Foreach
-------------
Нарешті, якщо немає `yield`, компілятор буде використовувати `foreach` замість `flatMap`, що корисне тільки для побічних ефектів.
[source,scala]
----
  reify> for { i <- a ; j <- b } println(s"$i $j")
  
  a.foreach { i => b.foreach { j => println(s"$i $j") } }
----
2.1.4 Підсумок
--------------
Повний набір методів, підтримуваний розширеним `for`, не поділяють загальний супер тип; кожний згенерований фрагмент компілюється окремо. Якщо це був би трейт, він мав би виглядати так:
[source,scala]
----
  trait ForComprehensible[C[_]] {
    def map[A, B](f: A => B): C[B]
    def flatMap[A, B](f: A => C[B]): C[B]
    def withFilter[A](p: A => Boolean): C[A]
    def foreach[A](f: A => Unit): Unit
  }
----
Якщо контекст (`C[_]`) розширеного `for` не провадить свої власні  `map` та `flatMap`, не все втрачено. Якщо для `T` доступний неявний `scalaz.Bind[T]`, він буде провадити `map` та `flatMap`.

Це часто дивує розробників, коли інлан обчислення `Future` в розширеному `for` не виконуються паралельно:
[source,scala]
----
  import scala.concurrent._
  import ExecutionContext.Implicits.global
  
  for {
    i <- Future { expensiveCalc() }
    j <- Future { anotherExpensiveCalc() }
  } yield (i + j)
----
Це тому, що `flatMap` відгалужує `anotherExpensiveCalc` прямо після `expensiveCalc`. Щоб переконатись, що два обчислення розпочались паралельно, почніть їх за межами розширеного for.
[source,scala]
----
  val a = Future { expensiveCalc() }
  val b = Future { anotherExpensiveCalc() }
  for { i <- a ; j <- b } yield (i + j)
----
`for` розширення фундаментально для визначення послідовних програм. Ми покажемо далеко кращий спосіб визначення паралельних обчислень в наступній главі. Підсумок: не використовуйте `Future`.

2.2 Нещасливий шлях
-------------------
Дотепер ми дивились тільки на правила переписування, не на те, що відбувається в `map` та `flatMap`. Розглянемо, що трапляється, коли контекст вирішує, що він не може продовжувати далі.

В прикладі `Option` `yield` викликається тільки коли всі `i`,`j`,`k` є визначеними.
[source,scala]
----
  for {
    i <- a
    j <- b
    k <- c
  } yield (i + j + k)
----
Якщо любий з `a`,`b`,`c` є `None`, розширення скоротить шлях з `None`, але він не скаже нам, що пішло не так.

Існує багато функцій в природі, що приймають параметри `Option`, але насправді потребують всі параметри для існування. Альтернативою до закидання виключення часу виконання є використання розширеного `for`, що дає нам повноту (значення повернення для кожного вводу):
[source,scala]
----
  def namedThings(
    someName  : Option[String],
    someNumber: Option[Int]
  ): Option[String] = for {
    name   <- someName
    number <- someNumber
  } yield s"$number ${name}s"
----
але це балакуче, відволікаюче та поганий стиль. Якщо функція потребує кожного вводу, то вона має зробити це явним, покладаючи відповідальність мати справу з опціональними параметрами на викликаючу сторону.
[source,scala]
----
  def namedThings(name: String, num: Int) = s"$num ${name}s"
----
Якщо ми використовуємо `Either`, тоді `Left` призведе розширене `for` на короткий шлях з додатковою інформацією, значно краще, ніж `Option` для повідомлення про помилку:
[source,scala]
----
  scala> val a = Right(1)
  scala> val b = Right(2)
  scala> val c: Either[String, Int] = Left("sorry, no c")
  scala> for { i <- a ; j <- b ; k <- c } yield (i + j + k)
  
  Left(sorry, no c)
----
І нарешті давайте подивимось, що станеться з `Future` що схибила:
[source,scala]
----
  scala> import scala.concurrent._
  scala> import ExecutionContext.Implicits.global
  scala> for {
           i <- Future.failed[Int](new Throwable)
           j <- Future { println("hello") ; 1 }
         } yield (i + j)
  scala> Await.result(f, duration.Duration.Inf)
  caught java.lang.Throwable
[source,scala]
----
`Future`, що друкує на терміналі, ніколи не викликається, оскільки, як `Option` та `Either`, розширений `for` обчислює скорочено.

Коротке обчислення для нещасливих шляхів є загальною та важливою темою. Розширений `for` не може виразити очищення ресурсів: немає способу зробити `try / finally`. Це добре, в FP це покладає ясну власність відповідальності для відновлення після несподіваних помилок та очистку ресурсів на контекст (що загалом є `Monad`, як ми побачимо пізніше), а не бізнес логіка.

2.3 Гімнастика
--------------
Хоча це просто переписати простий послідовний код як розширений `for`, іноді ми бажаємо зробити дещо, що вимагає розумових вправ. Цей розділ збирає деякі практичні приклади, та як мати з ними справу.

2.3.1 Логіка відкату
~~~~~~~~~~~~~~~~~~~~
Скажімо, ми викликаємо метод, що повертає `Option`. Якщо він неуспішний, ми бажаємо відкатитись до іншого методу (і так далі і далі), як при використанні кешу:
[source,scala]
----
  def getFromRedis(s: String): Option[String]
  def getFromSql(s: String): Option[String]
  
  getFromRedis(key) orElse getFromSql(key)
----
Якщо ми робимо це для асинхронної версії того самого API:
[source,scala]
----
  def getFromRedis(s: String): Future[Option[String]]
  def getFromSql(s: String): Future[Option[String]]
[source,scala]
----
тоді ми маємо бути уважними, щоб не зробити ту додаткову роботу, оскільки
[source,scala]
----
  for {
    cache <- getFromRedis(key)
    sql   <- getFromSql(key)
  } yield cache orElse sql
----
виконає обидва запити. Ми можемо зробити порівняння на першому результаті, але тип невірний:
[source,scala]
----
  for {
    cache <- getFromRedis(key)
    res   <- cache match {
               case Some(_) => cache !!! невірний тип !!!
               case None    => getFromSql(key)
             }
  } yield res
[source,scala]
----
Ми маємо створити `Future` з `cache`:
[source,scala]
----
  for {
    cache <- getFromRedis(key)
    res   <- cache match {
               case Some(_) => Future.successful(cache)
               case None    => getFromSql(key)
             }
  } yield res
----
`Future.successful` створює новий `Future`, майже так само, як конструктор `Option` або `List`.

2.3.2 Ранішній вихід
~~~~~~~~~~~~~~~~~~~~
Скажімо, ми маємо деяку умову, що повинна рано виходити з успішним значенням.

Якщо ви бажаєте вийти рано з помилкою, це стандартна практика в OOP закинути виключення:
[source,scala]
----
  def getA: Int = ...
  
  val a = getA
  require(a > 0, s"$a must be positive")
  a * 10
----
що може бути переписане асинхронно:
[source,scala]
----
  def getA: Future[Int] = ...
  def error(msg: String): Future[Nothing] =
    Future.failed(new RuntimeException(msg))
  
  for {
    a <- getA
    b <- if (a <= 0) error(s"$a must be positive")
         else Future.successful(a)
  } yield b * 10
----
Але якщо ми бажаємо вийти рано з успішним значенням, простий синхронний код:

  def getB: Int = ...
  
  val a = getA
  if (a <= 0) 0
  else a * getB
----
транслюється у вкладений розширений `for`, коли наші залежності є асинхронними:
[source,scala]
----
  def getB: Future[Int] = ...
  
  for {
    a <- getA
    c <- if (a <= 0) Future.successful(0)
         else for { b <- getB } yield a * b
  } yield c
----
Якщо існує неявний `Monad[T]` для `T[_]` (тобто `T` є монадичний), тоді `Scalaz` дозволяє нам створити `T[A]` зі значення `a: A` через виклик `a.pure[T]`.

`Scalaz` провадить `Monad[Future]`, та `.pure[Future]` викликає  `Future.successful`. Крім того, що `pure` трохи коротший для друку, це загальна концепція, що робить за межами `Future`, і таким чином є рекомендованою.
[source,scala]
----
  for {
    a <- getA
    c <- if (a <= 0) 0.pure[Future]
         else for { b <- getB } yield a * b
  } yield c
----
2.4 Незрозумілість
------------------
Контекст, де ми розширюємо `for`, має залишатись тим самим: ми не можемо змішувати контексти.
[source,scala]
----
  scala> def option: Option[Int] = ...
  scala> def future: Future[Int] = ...
  scala> for {
           a <- option
           b <- future
         } yield a * b
  <console>:23: error: type mismatch;
   found   : Future[Int]
   required: Option[?]
           b <- future
                ^
----
Ніщо не допоможе нам змішати довільні контексти в розширенні `for`, оскількі значення цього не дуже визначене.

Але якщо ми маємо вкладені контексти, і наміри звичайно очевидні, компілятор все ще не може прийняти наш код.
[source,scala]
----
  scala> def getA: Future[Option[Int]] = ...
  scala> def getB: Future[Option[Int]] = ...
  scala> for {
           a <- getA
           b <- getB
         } yield a * b
                   ^
  <console>:30: error: value * is not a member of Option[Int]
----
Тут ми бажаємо, щоб `for` потурбувався про зовнішній контекст, та дав нам написати наш код на внутрішньому `Option`. Приховування зовнішнього контексту є саме те, що робить трансформер монад, та `Scalaz` провадить реалізації для `Option` та `Either` на ім'я `OptionT` та `EitherT`, відповідно.

Зовнішній контекст може бути будь-чим, що нормально робить в `for` розширеннях, але воно має залишатись на всьому протязі.

Ми створили `OptionT` для кожного виклику метода. Це змінює контекст `for` з `Future[Option[_]]` до `OptionT[Future, _]`.
[source,scala]
----
  scala> val result = for {
           a <- OptionT(getA)
           b <- OptionT(getB)
         } yield a * b
  result: OptionT[Future, Int] = OptionT(Future(<not completed>))
----
`.run` повертає нам оригінальний контекст:
[source,scala]
----
  scala> result.run
  res: Future[Option[Int]] = Future(<not completed>)
----
Трансформатор монад також дозволяє нам міксувати виклики `Future[Option[_]]` за допомогою методів, що просто повертають звичайний  `Future` через `.liftM[OptionT]` (провадиться `scalaz`):
[source,scala]
----
  scala> def getC: Future[Int] = ...
  scala> val result = for {
           a <- OptionT(getA)
           b <- OptionT(getB)
           c <- getC.liftM[OptionT]
         } yield a * b / c
  result: OptionT[Future, Int] = OptionT(Future(<not completed>))
----
та ми міксуємо з методами, що повертають звичайні `Option`, огортаючи їх в `Future.successful` (`.pure[Future]`), за яким слідує `OptionT`:
[source,scala]
----
  scala> def getD: Option[Int] = ...
  scala> val result = for {
           a <- OptionT(getA)
           b <- OptionT(getB)
           c <- getC.liftM[OptionT]
           d <- OptionT(getD.pure[Future])
         } yield (a * b) / (c * d)
  result: OptionT[Future, Int] = OptionT(Future(<not completed>))
----
Це знову безлад, але це краще, ніж вручну вкладений `flatMap` та `map`. Ми можемо очистити його за допомогою DSL, що обробить всі потрібні перетворення в `OptionT[Future, _]`:
[source,scala]
----
  def liftFutureOption[A](f: Future[Option[A]]) = OptionT(f)
  def liftFuture[A](f: Future[A]) = f.liftM[OptionT]
  def liftOption[A](o: Option[A]) = OptionT(o.pure[Future])
  def lift[A](a: A)               = liftOption(Option(a))
----
в комбінації з оператором `|>`, що застосовує функцію зправа до значення зліва, щоб візуально відділити логіку від трансформацій:
[source,scala]
----
  scala> val result = for {
           a <- getA       |> liftFutureOption
           b <- getB       |> liftFutureOption
           c <- getC       |> liftFuture
           d <- getD       |> liftOption
           e <- 10         |> lift
         } yield e * (a * b) / (c * d)
  result: OptionT[Future, Int] = OptionT(Future(<not completed>))
----
`|>` часто називають оператором дрозда, завдяки його несподіваної подоби до цікавої пташки. Ті, кому не до вподоби символічні оператори, може використовувати псевдоним `.into`.

Цей підхід також робить для `Either` (та інших) в якості внутрішнього контексту, але їх методи ліфтингу більш складні, і потребують параметрів. `Scalaz` провадить монадні трансформери для більшості своїх власних типів, так що має сенс перевірити, чи достіпний один з них.
