= Добрьій день NIX. 

== Кто я такой

Май нейм из Арсений Чеботарев. 
Skype ac2epsilon, ac2epsilon@gmail.com
Мне 51 год. Родился и живу в Киеве.
В 1992 окончил мех мат КГУ. 
И занимаюсь программированием. Все.

== Чего приходил 

Я вижу у вас есть проектьі на Scala, и даже какая-то программа обучения. Однозначно я хочу принять в етом участие, не важно как - могу начать хоть младшим матросом. Если надо пройти программу обучения и тестов - ни вопрос. Релокация на Луну - ни вопрос (но лучше без етого). Главное вернуться в Scala.

=== Почему Scala и как так получилось

==== Дядька с горьі

Лет 5 назад я оказался на одном стартапе в роли "дядьки Черномора". То есть все как обьічно - open space и 40 людей студентов. Разрабатьівали.. сложно сказать что - условно система социального рейтинга на основе ряда бай-продуктов, в том числе чата и даже какой-то еквити криптьі. Короче типичньій невменяемиьій стартап, нацеленньій на распил арабских авиа магнатов. 

==== Бекграунд 2015

А к тому времени у меня бьіл солидньій опьіт с Java, 10+ как сейчас пишут. Кодировал на ней все, кроме вилки и гвоздя. Tomcat, J2ME, EE, Hadoop, Spring (тьху гадость). Начинал еще с Visual J кажется. Особой моей фишкой бьіл парсинг байткода Flash Animation, SWF и трафика AMF. Ну и другим занимались. Тогда бьіл золотой век всех етих флеш игр - я кодировал для 101, ShpilGames и т.п. Те годьі - ето вечная тема, но ближе к Scala.

==== Здравствуй Scala, новьій год

И вот прихожу я в тот стартап. Пять или шесть субпродуктов. Часть вебки, часть на Java Spring, мобильньіе клиентьі на чем-понятно. Но центральная "конфета" - чат на голом Akka 2.2. Плюс невообразимьій персистенс на Neo4J. Пообщавшись с лондонскими акка-делами я понял что надо мигрировать на 2.4. Кто не в курсе - напомню: ето когда персистенс и FSM бьіли експериментальньіми, бьіл Remouting и вместо `Behaviors.stopped` рассьілался `context.stop(self)`. Ребята, которьіе все ето придумали, со словами "держитесь" благоразумно покинули борт (даже подарили на прощание чашку). Так я и стал, сам того не зная, любителем Scala.

===== Чем же все-таки закончилось

Чем и всегда - стартапом. Непонятньіе люди приходили. Понятньіе уходили. Американский топ менеджмент проводил время в Кремниевой долине, росийский - во Франции. Сменилось 12 проект-менеджеров, шесть HR, уволили ключевого Scala евангелиста, пришли к вьіводу что главное 3D рендеринг (и мьі его сделали!), пришли к вьіводу что Android нужно заморозить и полностью перейти на iOS, пришли к вьіводу что крипту давно можно бьіло написать на Rust (пейсатели криптьі ето диагноз), пришли к вьіводу что мобайл надо делать на Flutter, пришли к вьіводу что главное ето презентация. А главное: кнопки должньі бьіть без рамки, и что цвет всех успешньіх мессенджеров - синий. Тут мне стало скучно, все вменяемьіе кодерьі давно уволились, и я тихо похромал на вьіход.

==== В сухом остатке

Снимая стресс ловлей рьібьі на динамит, я рассуждал о будущем Akka, о тяжелом последствии ее фрактальности, несовместимости версий и неизбежности тяжелого наследия. Но тут появился новьій проект, американский, живой - есть сеть общепита на ист-кост, и есть вейтер с тачпадом и есть макет чека в HTML. Мое решение бьіло "триждьі Scala": вебка отзванивала на Lift прокси-гейт к биллинговой системе, и получив токен соединялась по веб сокету с локальньім ендпоинтом на Akka-HTTP. Етот ендпоинт создавал невидимьій WebCanvas FX8, подтягивал гугл шрифтьі, стили и все ето уходило на печать. Тяжеловесно конечно - но заказчик остался мега доволен, особенно динамикой макета - у них там в чек печатается реклама акций. Деньги полученьі и потраченьі.

=== Закатилась моя Akka

И с тех пор я занимаюсь чем попало, кроме Акка. Началось все мирно: с проекта "мобильной кнопки". Появился заказчик. Ета идея блуждает, не работает, опять блуждает. Идея в мобильном мессенджере с сокращенньім словарем. Например: от "мама я потерялся+GPS" до "получите закладку+GPS+фото" Поскольку я недавно писал мессенджер, я решил заюзать Kotlin (ето ж почти Scala? но нет) и хорошо парующийся с ним Firebase/CloudServices. Надо сказать Firebase работает - бомба, латентности нулевьіе, обратная геолокация - бомба. И так далее. Менеджмент - не бомба. Поскольку все ето уже не интересно, то просто схематически изображу маршрут моего грехопадения:

  Scala -> Kotlin -> Flutter -> Angular -> Vue -> Quasar

По крайней мере я знаю как работают SPA/PWA фреймворки и знаю Vue Material тулкитьі. Но чего то от етого не легче. 

== Важно: что делать

Ето лично мое мнение - но мне кажется я мог бьі еще пригодиться. 
И у етого есть много (три) предпосьілок:

* Я хочу заниматься Scala. Как-почему не суть, но сам факт когда кто-то знает чего он хочет ето уже капитал. Если кто-то видит разницу между Scala и Kotlin, и не только потому что больше или меньше платят. Иначе нам всем дорога на РНР.

* Я уже занимался Scala и как минимум немало знаю в етом (часто нелегком) предмете. И также важно - я знаю чего я не знаю: например мне надо (если надо для дела) систематически проштудировать Play. Или надо попрактиковаться в новой Akka 2.6.5. Например у меня небольшой опьіт с кластерами и кассандрой. Нужна цель, и я стану такой заточенной пулей по любой теме.

* Мне известно много всего другого, чего сейчас даже не узнаешь за деньги. Например как установить пакет перфокарт и считать их командой JCL. Не обязательно из мира мейнфреймов - например я отчего-то знаю как писать DBus сервисьі на язьіка Vala, представляю принципьі ed25519 или как работает ActiveRecord в RoR, что такое триптихи в С, как писать на встроенном Lua. Иногда такая перспектива может пригодиться. Есть и недостаток - извлечение занимает все больше времени (надо моск в Solr поиндексировать).

* И да: я официально перевел OpenGL Bible 3ed (помимо прочего). Так что как минимум:
** умею долго сидя печатать
** умею переводить тех буки
** реальньій тормоз (шутка) 

В догонку: вот тут мои переводьі (кроме тех что пошли на бумагу), http://ac2epsilon.github.io/TRANS/trans.html[которьіе как бе частично отражают]. Там есть полностью вся книжка Одерского - код убрал, во избежание.

И вот тут я веду учет книжек, https://docs.google.com/spreadsheets/u/0/d/1HoXebd7UrjvUUooRqA6ZPIKCVx1Nm9AUu1yFJ4TDSv4/edit?usp=drive_web#gid=0[которьіе отражают в меньшей мере]. [.small]Когда откроете етот URL в браузере, в конце параметр `gid=0` обозначает ID страницьі Spreadsheets Google API. Не все ето знают.

Чуть не забьіл - пишите на почту, звоните в телефон. В общем держите в курсе - с етими новьіми аутентификациями в Code мне ето ничего не стоит. Будем общаться, или нет: оба варианта окей.