include::header.adoc[]

== Життєвий цикл актора

=== Інформація про модуль

Щоб використовувати Akka Actors, додайте таку залежність у свій проект:

[source,scala]
----
libraryDependencies += "com.typesafe.akka" %% "akka-actor-typed" % "2.6.5"
----

=== Вступ

Актор - це ресурс зі станом, який потрібно явно розпочати і зупинити.

Важливо зазначити, що актори не зупиняються автоматично, коли на них більше немає посилань, кожен створений Актор також повинен явно знищуватися. Єдине спрощення полягає в тому, що зупинка батьківського Актора також буде рекурсивно зупиняти всіх дочірніх Акторів, яких створив цей батько. Усі актори також автоматично зупиняються, коли вимикається `ActorSystem`.

Примітка. ActorSystem - це важка структура, яка буде виділяти нитки, тому створіть по одній на логічну програму. Зазвичай одна система акторів на один процес JVM.

=== Створення акторів

Актор може створити або нерестити довільну кількість дитячих акторів, які, в свою чергу, можуть породити своїх дітей, тим самим формуючи ієрархію акторів. `ActorSystem` формує ієрархію, і може бути лише один корінний актор, актор на вершині ієрархії `ActorSystem`. Життєвий цикл дитини-актора пов'язаний з батьком - дитина може зупинити себе або зупинити її в будь-який час, але вона ніколи не може пережити свого батька.

===== ActorContext

Доступ до ActorContext можна отримати для багатьох цілей, таких як:

* Створення дитячіх акторів та нагляд
* Нагляд інших акторів на отримання події `Terminated(otherActor)`, якщо нагляданий актор назавжди зупиниться
* Ведення журналів
* Створення адаптерів повідомлень
* Взаємодія запит-відповідь (`ask`) з іншим актором
* Доступ до свого `ActorRef` `self`

Якщо поведінка потребує використання `ActorContext`, наприклад, для продукування дітей-акторів або використання `context.self`, це можна отримати, обернувши конструкцію `Behaviors.setup`:

[source,scala]
----
object HelloWorldMain {

  final case class SayHello(name: String)

  def apply(): Behavior[SayHello] =
    Behaviors.setup { context =>
      val greeter = context.spawn(HelloWorld(), "greeter")

      Behaviors.receiveMessage { message =>
        val replyTo = context.spawn(HelloWorldBot(max = 3), message.name)
        greeter ! HelloWorld.Greet(message.name, replyTo)
        Behaviors.same
      }
    }

}
----

=== Безпека нитки ActorContext

Багато методів у `ActorContext` не є безпечними для потоків, і тому:

* Не можна отримувати доступ до потоків із зворотнього виклику `scala.concurrent.Future`
* Не може ділитися між кількома акторами
* Потрібно використовувати лише у звичайній нитці обробки повідомлень актора

=== Актор-охоронець

Актор верхнього рівня, який також називають актором-охоронцем користувача, створюється разом з `ActorSystem`. Повідомлення, що надсилаються до акторської системи, спрямовуються на головного актора. Основний актор визначається поведінкою, що використовується для створення `ActorSystem`, названої `HelloWorldMain` у наведеному нижче прикладі:

[source,scala]
----
val system: ActorSystem[HelloWorldMain.SayHello] =
  ActorSystem(HelloWorldMain(), "hello")

system ! HelloWorldMain.SayHello("World")
system ! HelloWorldMain.SayHello("Akka")
----

Для дуже простих додатків опікун може містити фактичну логіку програми та обробляти повідомлення. Як тільки програма звертається до декількох проблем, опікун повинен замість цього лише завантажувати програму, відгалужувати різні підсистеми як дітей, та контролювати їх життєвий цикл.

Коли актор-охоронець зупиниться, це зупинить `ActorSystem`.

Коли робиться виклик `ActorSystem.terminate`, процес скоординованого відключення зупинить акторів і служби у визначеному порядку.

=== Створення дітей

Дитячі актори створюються і починаються `ActorContext` `spawn` . У наведеному нижче прикладі, коли запускається кореневий актор, він породжує дочірнього актора, описаного поведінкою `HelloWorld`. Крім того, коли кореневий актор отримує повідомлення `Start`, він створює дочірній актор, визначени поведінкою `HelloWorldBot`:

[source,scala]
----
object HelloWorldMain {

  final case class SayHello(name: String)

  def apply(): Behavior[SayHello] =
    Behaviors.setup { context =>
      val greeter = context.spawn(HelloWorld(), "greeter")

      Behaviors.receiveMessage { message =>
        val replyTo = context.spawn(HelloWorldBot(max = 3), message.name)
        greeter ! HelloWorld.Greet(message.name, replyTo)
        Behaviors.same
      }
    }

}
----

Щоб вказати диспетчера під час створення актора, використовуйте `DispatcherSelector`. Якщо не вказано, актор використовуватиме диспетчер за замовчуванням, детальну інформацію див. У https://doc.akka.io/docs/akka/current/typed/dispatchers.html#default-dispatcher[диспетчері за замовчуванням].

[source,scala]
----
def apply(): Behavior[SayHello] =
  Behaviors.setup { context =>
    val dispatcherPath = "akka.actor.default-blocking-io-dispatcher"

    val props = DispatcherSelector.fromConfig(dispatcherPath)
    val greeter = context.spawn(HelloWorld(), "greeter", props)

    Behaviors.receiveMessage { message =>
      val replyTo = context.spawn(HelloWorldBot(max = 3), message.name)

      greeter ! HelloWorld.Greet(message.name, replyTo)
      Behaviors.same
    }
  }
----

Зверніться до акторів, щоб ознайомитися з вищезазначеними прикладами.

=== SpawnProtocol

Актор-опікун повинен відповідати за ініціалізацію завдань та створення початкових акторів програми, але іноді ви можете породжувати нових акторів із зовнішньої сторони актора-опікуна. Наприклад, створення одного актора на кожний запит HTTP.

Це не важко реалізувати у вашій поведінці, але оскільки це загальний шаблон, існує попередньо визначений протокол повідомлення та реалізація поведінки для цього. Він може бути використаний як актор-охоронець системи `ActorSystem`, можливо, поєднаний з `Behaviors.setup`, щоб розпочати деякі початкові завдання чи акторів. Потім дочірніх акторів можна запустити ззовні, через `tell` або `ask` `SpawnProtocol.Spawn` до посилання на актора системи. Використання запиту аналогічно тому, як `ActorSystem.actorOf` може використовуватися в класичних акторах з тією різницею, що повертається `Future` `ActorRef`.

Поведінку опікуна можна визначити як:

[source,scala]
----
import akka.actor.typed.Behavior
import akka.actor.typed.SpawnProtocol
import akka.actor.typed.scaladsl.Behaviors
import akka.actor.typed.scaladsl.LoggerOps

object HelloWorldMain {
  def apply(): Behavior[SpawnProtocol.Command] =
    Behaviors.setup { context =>
      // Запуск початкових завдань
      // context.spawn(...)

      SpawnProtocol()
    }
}
----

і ActorSystem можна створити з такою основною поведінкою і попросити породити інших суб'єктів:

[source,scala]
----
import akka.actor.typed.ActorRef
import akka.actor.typed.ActorSystem
import akka.actor.typed.Props
import akka.util.Timeout


implicit val system: ActorSystem[SpawnProtocol.Command] =
  ActorSystem(HelloWorldMain(), "hello")

// треба в неявному полі для ask (?)
import akka.actor.typed.scaladsl.AskPattern._
implicit val ec: ExecutionContext = system.executionContext
implicit val timeout: Timeout = Timeout(3.seconds)

val greeter: Future[ActorRef[HelloWorld.Greet]] =
  system.ask(SpawnProtocol.Spawn(behavior = HelloWorld(), name = "greeter", props = Props.empty, _))

val greetedBehavior = Behaviors.receive[HelloWorld.Greeted] { (context, message) =>
  context.log.info2("Greeting for {} from {}", message.whom, message.from)
  Behaviors.stopped
}

val greetedReplyTo: Future[ActorRef[HelloWorld.Greeted]] =
  system.ask(SpawnProtocol.Spawn(greetedBehavior, name = "", props = Props.empty, _))

for (greeterRef <- greeter; replyToRef <- greetedReplyTo) {
  greeterRef ! HelloWorld.Greet("Akka", replyToRef)
}
----

SpawnProtocol також можна використовувати в інших місцях в ієрархії акторів. Не обов’язково бути актором-кореневим опікуном.

Спосіб пошуку працюючих акторів описаний у відкритті Актора.

=== Зупинка акторів

Актор може зупинити себе, повернувши `Behaviors.stopped` як наступну поведінку.

Дитячого актора можна змусити зупинитись після того, як він закінчить обробляти своє поточне повідомлення, використовуючи метод зупинки `stop` `ActorContext` від батьківського актора. Тільки дитячі актори можуть бути зупинені таким чином.

Усі діти будуть зупинені, коли їх батька зупинено.

Коли актор зупиняється, він отримує сигнал `PostStop`, який можна використовувати для очищення ресурсів. Функція зворотного виклику може бути визначена як параметр `Behaviors.stopped` для обробки сигналу `PostStop` при витонченій зупинці. Це дозволяє застосовувати різні дії, коли виконання різко зупиняється.

Ось ілюструючий приклад:

[source,scala]
----
import akka.actor.typed.Behavior
import akka.actor.typed.scaladsl.Behaviors
import akka.actor.typed.{ ActorSystem, PostStop }

object MasterControlProgram {
  sealed trait Command
  final case class SpawnJob(name: String) extends Command
  case object GracefulShutdown extends Command

  // Визначена операція зачистки
  def cleanup(log: Logger): Unit = log.info("Cleaning up!")

  def apply(): Behavior[Command] = {
    Behaviors
      .receive[Command] { (context, message) =>
        message match {
          case SpawnJob(jobName) =>
            context.log.info("Spawning job {}!", jobName)
            context.spawn(Job(jobName), name = jobName)
            Behaviors.same
          case GracefulShutdown =>
            context.log.info("Initiating graceful shutdown...")
            // м'яка зупинка перед фінальною зупинкою
            // поведінка очистки передана як параметр до Actor.stopped
            Behaviors.stopped { () =>
              cleanup(context.system.log)
            }
        }
      }
      .receiveSignal {
        case (context, PostStop) =>
          context.log.info("Master Control Program stopped")
          Behaviors.same
      }
  }
}

object Job {
  sealed trait Command

  def apply(name: String): Behavior[Command] = {
    Behaviors.receiveSignal[Command] {
      case (context, PostStop) =>
        context.log.info("Worker {} stopped", name)
        Behaviors.same
    }
  }
}

import MasterControlProgram._

val system: ActorSystem[Command] 
    = ActorSystem(MasterControlProgram(), "B7700")

system ! SpawnJob("a")
system ! SpawnJob("b")

Thread.sleep(100)

// м'яка зупинка системи
system ! GracefulShutdown

Thread.sleep(100)

Await.result(system.whenTerminated, 3.seconds)
----

Під час очищення ресурсів від `PostStop` слід також розглянути можливість виконання того ж самого для сигналу `PreRestart`, який випромінюється при перезапуску актора. Зауважте, що `PostStop` не видається для перезавантаження.

=== Спостереження за акторами

Для того, щоб отримувати повідомлення про припинення дії іншого актора (тобто припиняється постійно, а не тимчасової несправності та перезавантаження), актор може спостерігати іншого актора. Він отримає сигнал `Terminated` після припинення (див. Припинення акторів) актора під наглядом.

[source,scala]
----
object MasterControlProgram {
  sealed trait Command
  final case class SpawnJob(name: String) extends Command

  def apply(): Behavior[Command] = {
    Behaviors
      .receive[Command] { (context, message) =>
        message match {
          case SpawnJob(jobName) =>
            context.log.info("Spawning job {}!", jobName)
            val job = context.spawn(Job(jobName), name = jobName)
            context.watch(job)
            Behaviors.same
        }
      }
      .receiveSignal {
        case (context, Terminated(ref)) =>
          context.log.info("Job stopped: {}", ref.path.name)
          Behaviors.same
      }
  }
}
----

Альтернативою для `watch` є `watchWith`, що дозволяє вказати користувальницьке повідомлення замість `Terminated`. Цьом часто надається перевага, ніж використанню `watch` та сигналу `Terminated`, оскільки в повідомлення може бути включена додаткова інформація, яка може бути використана пізніше при його отриманні.

Аналогічний приклад, як вище, але використовуючи `watchWith` та відповіді на початковий запитувач, коли робота закінчена.

[source,scala]
----
object MasterControlProgram {
  sealed trait Command
  final case class SpawnJob(name: String, replyToWhenDone: ActorRef[JobDone]) extends Command
  final case class JobDone(name: String)
  private final case class JobTerminated(name: String, replyToWhenDone: ActorRef[JobDone]) extends Command

  def apply(): Behavior[Command] = {
    Behaviors.receive { (context, message) =>
      message match {
        case SpawnJob(jobName, replyToWhenDone) =>
          context.log.info("Spawning job {}!", jobName)
          val job = context.spawn(Job(jobName), name = jobName)
          context.watchWith(job, JobTerminated(jobName, replyToWhenDone))
          Behaviors.same
        case JobTerminated(jobName, replyToWhenDone) =>
          context.log.info("Job stopped: {}", jobName)
          replyToWhenDone ! JobDone(jobName)
          Behaviors.same
      }
    }
  }
}
----

Зверніть увагу, як `replyToWhenDone` включається до повідомлення `watchWith`, а потім використовується пізніше при отриманні повідомлення `JobTerminated`.

Спостерігаємим актором може бути будь-який `ActorRef`, не обов’язково бути дочірним актором, як у наведеному вище прикладі.

Слід зазначити, що `terminated` повідомлення формується незалежно від порядку, в якому відбувається реєстрація та припинення. Зокрема, спостерігаючий актор отримає повідомлення про припинення, навіть якщо спостерігаючий актор вже був припинений на момент реєстрації.

Реєстрація кілька разів не обов'язково призводить до створення декількох повідомлень, але немає гарантії, що буде отримано лише одне саме таке повідомлення: якщо припинення переглянутого актора генерувало та ставило в чергу повідомлення, а інша реєстрація робиться до того, як це повідомлення було дійсно оброблене, тоді друге повідомлення буде в черзі, тому що реєстрація для моніторингу вже закінченого актора призводить до негайного генерування повідомлення `terminated`.

Можливо також скасувати реєстрацію за переглядання жвавості іншого актора, використовуючи `context.unwatch(target)`. Це працює, навіть якщо повідомлення `terminated` вже зафіксовано у поштовій скриньці; після виклику `unatch` жодне припинене повідомлення для цього актора більше не буде оброблятися.

Повідомлення `terminated` також надсилається, коли спостерігаючий актор знаходиться на вузлі, видаленому з кластеру.