include::header.adoc[]

= Arsenii Chebotarov, 51

== Career Summary:

* 30+ of Work Years

* ~20 Fulltimes

* ~50 Projects

* Rare Skill List

== Skills

=== Programming Languages, Technologies 
in order of practical expirience

==== Java 

10+ of hands-on experience in architecting and builing, testing Java applications. Most involved techs in use are: Tomcat, JSP, JEE, Hadoop, FX, J2Me, Android. Strong knowledge of OOP, Java Patterns and Good Practices. 

==== Scala

Two closed Scala projects in Scala/Akka stack. Firm understanding of Functional Programming, Patterns in Scala. 

==== Kotlin

Two closed Kotlin (mobile) projects on Android/Firebase stack. Some knowledge of Android+Kotlin. 

==== JS/TS

Through usage of JS in numerous places. Also some expirience in SPA/PWA with Vue and Quasar.  

==== Databases, SQL

* Ocasional usage of raw SQL with no specifics
* Some Java projects with Hibernate as backend
* Casual Redis, BerkeleyDB usage
* Raw Hadoop, Pig Map/Reduce experience.

==== Others 

Following languages was used in commercial development at least once: Python, Lua, PHP, Ruby, PERL, C/C++, VBA, Pascal.


== Last 

== Education

Kyiv State University, 1992