iclude::header.adoc[]n

== Java IO Monad. Реальність чи вигадка

Vladimir Shiryaev
Jan 7 · 7 min read

== Монади? Знову?

Стільки написано та розказано про монади, що вони є, чому вони є та які форми вони мають в наших улюблених мовах програмування. То чому я намагаюся знову підняти цю довгоносну тему? А може, я пропустив потяг? Звичайно, про це та трохи більше ми поговоримо в наступних розділах. Але наразі довірте мені, що цю тему можна обговорити з інших сторін або сміливо закривайте цю статтю, якщо ви мені не вірите.

Якщо ви все ще продовжуєте читати, то давайте, як у звичайних старих статтях, спочатку поверніться до початку і згадайте, що таке монада. Ну і, звичайно, всі знають, що монада - це моноїд у категорії ендофунктерів, і нічого більше сказати не можна. Але якщо ви не такий знавець теорії категорій, як я (я, звичайно, не експерт), то для вас монада є по суті абстракцією відсутності значення, іншими словами, це поле, яке може або зберігати значення або зберігати його відсутність, що дозволяє нам складати обчислення цього значення.

Будь-яка реалізація монади повинна мати дві операції.

Операція зв’язування, яка дозволяє нам перетворити значення всередині однієї монади в іншу монаду.

[source,java]
----
<B> Monad<B> flatMap(function: Function<A, Monad<B>>)
----

And the return operation that allows us to get the monad from the value.
І операція повернення, яка дозволяє нам отримати монаду від значення.

[source,Java]
----
<A> Monad<A> apply(value: A)
----

Також ці дві операції повинні відповідати наступним 3 законам монади `(М)`

===== закон лівої ідентичності:
[source,java]
----
M.aplly(x).flatMap(f).equals(f.apply(x))
----

===== закон правої ідентичності:
[source,java]
----
M.flatMap(M::apply).equals(M)
----

===== закон асоціативності:

[source,java]
----
M.flatMap(f).flatMap(g).equals(M.flatMap(x -> f.apply(x).flatMap(g))
----

Маючи ці операції та закони щодо них, ми можемо сміливо будувати ланцюги лінивих обчислень, поки не захочемо отримати (або не отримати) значення всередині нашого поля.

=== Введення в IO

`IO Monad`, як ви, напевно, розумієте під назвою, також є монадою, але чому `IO`? Ви маєте рацію, вона інкапсулює такі операції вводу/виводу, як реєстрація, читання та запис операцій з консолі або, можливо, дії з базою даних. Але чи так важливо їх інкапсулювати? Що ж, так вийшло, що всі ці цікаві речі щодо роботи із зовнішнім світом створюють побічні ефекти у функціях та методах, які роблять їх нереференційно-прозорими, а значить, вони нечисті, подивіться на приклад.

Припустимо, у нас є деяка функція, яка збільшує зовнішню змінну у своєму тілі.

[source,java]
----
int externalVariable = 0;
int addAndIncrementExtVar(int a, int b) {
   final var result = a + b;
   externalVariable += 1;
   return result;
}
----

Тоді наступні два випадки не будуть еквівалентними та порушать референтну прозорість і засвідчать, що наш метод нечистий.

У першому випадку ми збільшуємо зовнішню змінну двічі

[source,java]
----
var sum = addAndIncrementExtVar(1, 1) + addAndIncrementExtVar(1, 1);
----

і у другому випадку ми збільшуємо змінну лише один раз.

[source,scala]
----
var value = addAndIncrementExtVar(1, 1);
var sum = value + value;
----

Тут нам потрібна монада вводу-виводу - ми можемо обернути виклик методу з потенційним побічним ефектом всередині, тим самим зробивши цей метод виклику лінивим. Що це нам дасть? Перш за все, ми гарантуємо, що виклики методу, які ми будемо викликати ланцюгом, що буде використовувати наш `IO Monad`, будуть референтно прозорими, а всі методи з побічними ефектами виконуватимуться лише на вимогу, але не до цього.

У деяких мовах, таких як Scala і Kotlin, є бібліотеки, які реалізують `IO Monad` (`cats`, `scalaz` та `arrow`, відповідно) і мають додаткові утиліти для роботи з нею.

== Реалізація Java

Гаразд, давайте все це зробимо разом і спробуємо реалізувати `IO Monad` в Java. По-перше, нам потрібно висловити виклик методу з побічним ефектом (ми називаємо це просто «ефектом»). Висловимо наш ефект як інтерфейс єдиного абстрактного методу (SAM інтерфейс) - його метод поверне нам деяке значення виконання ефекту. А оскільки інтерфейс функціональний, ми можемо описати наші ефекти як лямбда-вирази.

[source,java]
----
public interface Effect<T> {
    T run();
}
----

Гаразд, тому ми з’ясували, що наша монада - це коробка, давайте спробуємо вкласти свій ефект всередину.

[source,java]
----
public class IO<A> {
    private final Effect<A> effect;
    private IO(Effect<A> effect) {
        this.effect = effect;
    }
}
----

І ми також повинні додати метод, який зробить наш ящик корисним.

[source,java]
----
public A unsafeRun() {
    return effect.run();
}
----

Тепер давайте реалізуємо наші дві операції, які визначають монаду.

Спочатку ми реалізуємо операцію зв’язування.

[source,java]
----
public <B> IO<B> flatMap( Function< A, IO<B>> function) {
    return IO.apply(() -> function.apply(effect.run()).unsafeRun());
}
----

Далі ми здійснимо операцію, за допомогою якої зможемо огорнути свій ефект всередині монади.

[source,java]
----
public static <T> IO<T> apply(Effect<T> effect) {
    return new IO<>(effect);
}
----

Ми також можемо легко реалізувати метод `map`, тому що він може бути представлений у вигляді комбінації двох інших операцій: `flatMap` та `apply`.

[source,java]
----
public <B> IO<B> map(Function<A, B> function){
    return this.flatMap(result -> IO.apply(() -> function.apply(result)));
}
----

Ну все добре, IO монада готова !!!

О, почекайте хвилинку, а як щодо методів, що повертають особливий тип `void`? Таке твердження, як `System.out.println ();` не повертає реальний тип, який поширюється від `Object`. Хоча Java має тип `java.lang.Void` для позначення типу, який може повернути метод, ми не можемо його використовувати самостійно, оскільки його неможливо створити. Тут ми стикаємося з мовним обмеженням, оскільки інтуїтивно зрозуміло, що нормально очікувати, що аргумент функції, такої як `Function <T, Void>`, повинен приймати посилання методу, як `System.out::println`, але, на жаль, це так не буде працювати. Гаразд, давайте скористаємося місцевим поліморфізмом в Java, використовуючи перевантаження метод і припустимо, що `Consumer <T>` еквівалентний `Function<T, Void>`. Потім, дотримуючись наших припущень, я пропоную реалізувати метод `map` для такого випадку.

[source,java]
----
public IO<Void> map(Consumer<A> function) {
     return this.flatMap(result -> IO.apply(() -> {
         function.accept(result);
         //We can’t instantiate Void, hence we can return null only
         return null;
     }));
}
----

І тепер ми можемо витончено описати наші обчислення.

[source,java]
----
IO.apply(() -> “abc”)
   .map(String::toUpperCase)
   .map(System.out::println);
----

На жаль, знову пішло не так, оскільки згідно з специфікацією мови Java, Java SE 13 Edition у розділі 15.12.2.1. “Визначення потенційно застосовні методи” та абзац про використання лямбда-виразів як аргументів, де очікується тип споживача `Consumer <T>`, допустимо використовувати лямбда типу типу `Function <T, R>`. Тобто без явного виведення типу лямбда компілятор не зможе зрозуміти, який метод ми хочемо викликати, і нам доведеться зробити код більш багатослівним і незграбним.

[source,java]
----
IO.apply(() -> “abc”)
   .map(((Function<String, String>) String::toUpperCase)
   .map((Consumer<String>) System.out::println));
----

Тому ми не можемо елегантно впоратися з цією ситуацією. Ну, тоді вам доведеться перейменувати наш бідний метод на щось інше, я пропоную назвати його `mapToVoid`, щоб явно вказати, що `effect` нічого не повертає.

До речі, неможливо довести 3 закони в контексті IO монади в Java. Тому що ми не можемо порівняти два моноїда IO, перш ніж назвати на них метод `unsafeRun`. Ви можете поверхово перевірити ці закони, порівнюючи значення, отримані від виклику `unsafeRun` від кожної IO монади.

== Використання

Тепер, коли ми нарешті закінчилися з реалізацією, розглянемо її використання.
Найпопулярніший приклад - робота з консоллю.

[source,scala]
----
IO.apply(() -> “What is your name friend?”)
    .mapToVoid(System.out::println)
    .map(ignored -> System.console().readLine())
    .map(name -> String.format(“Hello %s!”, name))
    .mapToVoid(System.out::println);
----

Якщо ми запустимо цей фрагмент у нашому головному методі `main`, то, звичайно, ми нічого не отримаємо в результаті. Тому що наш ланцюг виконується на вимогу.

Гаразд, додайте `unsafeRun` до кінця ланцюга і запустіть його ще раз.

Працює! І тепер, коли наші ефекти загорнені в IO Monad, кожен наш крок (за винятком `unsafeRun`) у ланцюжку є чистим виразом, тому що ми завжди отримуємо результат, який ми очікували, а як щодо референтної прозорості?

Ніяких сюрпризів. Тоді наступні два випадки будуть рівнозначними

У першому випадку ми збільшуємо зовнішню змінну двічі

[source,scala]
----
var sum = IO.apply(() -> addAndIncrementExtVar(1, 1))
            .map(x -> x + addAndIncrementExtVar(1, 1))
            .unsafeRun();
----

У другому випадку ми збільшуємо зовнішню змінну також двічі!

[source,scala]
----
final var value = IO.apply(() -> addAndIncrementExtVar(1, 1));
var sum = value.flatMap(x -> value.map(y -> x + y))
               .unsafeRun();
----

І як бонус, ми можемо додати безпечний спосіб отримати значення від монади IO

[source,scala]
----
public Either<Exception, A> safeRun() {
     try {
         return Either.right(unsafeRun());
     } catch (Exception ex) {
         return Either.left(ex);
     }
}
----

`Either` це лише структура даних, яка зберігає значення або виняток, але не обидва одразу.

=== Плюси і мінуси

Тепер поговоримо про плюси і мінуси IO Monad на Java:

==== PROS:

* Композиція. Ми можемо скомпонувати наші обчислення
* Чистота. Сама монада IO, звичайно, не робить наші нечисті функції чистими, але інкапсулює їх як "рецепт" ефекту всередині монади і робить IO монаду чистою структурою.
* Всеосяжність. Використовуючи монаду IO, ми можемо створити методи, які дають результат для будь-якого введення
* Референційна прозорість
* Лінь. Відкладаємо наші побічні ефекти на стільки, скільки ми можемо

==== CONS:

* На відміну від мов, де тип `Void` (або його аналог `Unit`) є реальним типом і має реальний екземпляр, у Java ви повинні додати методи, без яких ви могли б обійтися, і тому реалізація IO Monad у Java є більш багатослівною, ніж , наприклад, у Scala
* Підтримка спільноти - вона, відверто кажучи, слабка. Я міг знайти лише пару прикладів здійснення монади IO на Java і майже жодних статей, що пояснювали б, що це таке. Звичайно, я вважаю, що це не мінус, і нам просто потрібно зробити громаду більш обізнаною.
* Немає бібліотек, які реалізують функціональність IO настільки потужно, як і в інших мовах JVM (Давайте напишемо їх!)

=== Висновок

Щоб закруглити це коротко, я скажу лише кілька слів. Ми можемо ненавидіти Java, скільки хочемо, але все ж є простір для впровадження нових підходів та методів. Звичайно, залежить від вас, чи використовувати їх на Java або використовувати мову, більш підходящу для цього.