
=== Морфізм в теорії категорій. 

Морфізм - це перетвоерння, що зберігає структуру, з однієї математичної структури на іншу, того ж типу. Термін дещо _перевантажений_ і позначає різні речі: функції в теорії множин, лінійні трансформації в алгебрі, групові гомоморфізми в теорії груп, тощо. 

В теорії категорій морфізм є відношенням об'єктів одної категорії на об'єкти тієї самої категорії, з дотриманням асоциативності операцій. Зазвичай об'єкти є множинами, а відношення є функцією відображення зі збереженням структури. 

=== Категорії.

Категорії складаються з двох класів, _об'єктів та морфізмів_. Морфізми позначаються стрілкою на діаграмах і в формулах, f : X → Y, і скорочено читаються _arrow_. Морфізми мають при собі двомісну операцію _композиції_ (суперпозиції), що складає разом ефект двох морфізмів. Композиція задовільняє двом аксіомам: 

* Ідентичності: для кожного об'єкта існує ідентичний морфізм idX : X → X, і для кожного f : A → B ми матимемо idB ∘ f = f = f ∘ idA.
* Асоциативності: h ∘ (g ∘ f) = (h ∘ g) ∘ f. 

 Для суцільних категорій на базі множин морфізм ідентичності просто функція ідентичності, а композиція є проста композиція функцій. 