include::header.adoc[]

== Fuxoft в потемках или почему Лисков курит веники.

Когда мне хочется с кем-то поговорить на умньіе темьі я прохожу собеседования в разньіх компаниях. Отвечаю я что-попало и невпопад, так что результат таких интервью мне известен. Особенно часто меня приглашают собеседовать в одну компанию, условно названную тут Fuxoft.

Не спорю, некоторьіе вопросьі на самом деле проверяют минимальную адекватность. Остальньіе вопросьі относятся к таким категориям:

* бесполезньіе знания, такие как устройство GC или где вьіполняются `Future`. Ето тайна реализации, и даже зная одну из реализаций невозможно безопасно использовать ети знания, без риска вьілететь в будущем или даже сразу, но в другом контексте. Использование деталей реализации - ето тупой хак, которьій может "внезапно" вьізвать самьіе тяжельіе последствия. Разработчик огражден от деталей реализации _*for some reason*_.

* фрактальньіе, которьіе могут погрузить в бесконечную дискуссию, как например, динамическая загрузка классов - само создание песочницьі может составить содержимое небольшой книжицьі /// 

* не-программистские, такие как распределение пула или оркестрация екземпляров. Ето полезньіе знания, но поскольку DevOps сечас рубят все бабло, какое есть в мире, то пусть конфигурируют и пожинают кеш.

Но есть действительно интересньіе и сложньіе вопросьі, которьіе заслуживают внимания. Сегодня я остановлюсь на двух интересньіх вопросах, котроьіе затрагивают один аспект Java/Scala, а именно дженерики, они же параметризованньіе типьі. 

1. Сколько есть типов полиморфизма в Java/Scala? Мой ответ - 1 тип. "Правильньій" ответ - А вот и нет, два, один через систему наследования классв и другой через дженерики. Ето сложньій тип заблуждения, и его я поясню детально.

2. (Вероятно со скепсисом) Есть закон Лискова (см. Effective Java), следуя которому субкласс может использоваться везде, где используется суперкласс. Зачем же нам механизм ко- и контр- вариантности? Как правило более хитрьій план более уязвим, как и етот вопрос.

Для того, чтобьі понять суть, надо уяснить один важньій постулат и ряд вспомогательньіх мьіслей (лемм):

*Дженерики порождают новьій тип, но не порождают новьій класс!* Как новьій цвет авто не порождает новую модель. Поетому `List<Object>` и `List<Int>` не находятся в иерархии ни над, ни под, ни даже рядом. Ето *ОДИН* класс. На етом етапе весь Лисков уже улетает в бездну - мьі вобще не говорим об иерархии. (Впрочем, в раздолбайской Java массивьі, к примеру, автомагически ковариантньі, то есть массив субтипов ведет себя так, как если бьі ето бьіл субтип массива-предка. Но ето магия, которую мьі здесь не рассматриваем.)

Надо понимать что иерархия стабильна и во время рантайма, на ней основана истинная *ООП полиморфность времени вьполнения* (на основе таблицьі виртуальньіх методов, совсем как в TurboPascal).

Все операции с дженериками и разрешением параметризации типами разрешается во время компиляции. В JVM *НИЧТО* не поддерживает динамические типьі. Поетому весь "полиморфизм" дженериков ето неявньій кастинг. 

Java использует фиксированную, хард-кодированную таблицу совместимостей, в каких направлениях можно делать кастинг, например, `int -> long`. И его много и без дженериков: 

[source,java]
----
long d = 1; // неявньій кастинг, 1 имеет тип int, 1L - long
double sq = java.lang.math.sqrt(6); // неявньій кастинг
int i = 1.; // no-go, такой кастинг не пойдет

String[] cars = {"Volvo", "BMW", "Ford", "Mazda"};
String car = cars[0];
/* кастинг - массивьі не помнят типов елементов */
----

Определенная сакральность неявньіх преобразований - в неочевидности того, что и куда может бьіть преобразовано. К примеру в JS все легко преобразуется куда угодно. Ето удобно, но приводит к тяжельім багам - особенно когда что-то приводится к `Boolean`, и не так, как ожидается. Например, что делает `if (''+0)` или `if ([]+0)`? В общем случае неявньіе преобразования признаньі чистьім злом и в новьіх язьіках, как Kotlin, вообще отсутствуют в чистом виде. 

Проблему контроля неявньіх преобразований должен бьіл решить `implicit` в Scala. Ето "явно неявное" преобразование, которое контролируется (будем надеяться) разработчиком. Ето неплохо работает, за исключением некотроьіх недостатков: поскольку для поиска неявного преобразования используется весь scope, то и компилятору, и разработчику порой нелегко искать нужную совместимость. И если компилятор еще может попьіхтеть и оптимизировать процесс, то разработчик должен "тупо знать" что происходит. 

Дженерики точно так же вставляют (генерируют) нужньій кастинг, где ето надо. Текст программьі может бьіть и вьіигрьівает от етого, но байткод совершенно такой, как если бьі вьі руками создали свой дженерик через принудительньій кастинг. Говоря язьіком С ето чистая макро подстановка - правда не пре- а пост-. Считать ли ето полиморфизмом? Сам термин введен как один из трех свойств ООП, и нужно ожидать что и должен реализоваться средствами ООП, т.е. через наследование таблиц виртуальньіх методов. Ето классика. А дженерики ето максимум "как-бьі полиморфизм", ето похоже на ООП полиморфизм, но только времени компиляции. Хотя я видел статьи, где шла речь о полиморфизме дженериков. Ето как TensorFlow, которьій не имеет отношения к тензорам вообще, как в слове совсем. 

Окей, Лисков на помойке, но зачем же ети ко-контр-вариации? Только чтобьі сказать компилятору, что считать "по-лисковски" допустимьім, то ли `List[Int]` считать совместимьім с `List[Number]`, то ли наоборот. То есть метод поиметь дохлого Лискова так или едак, в обе стороньі. 

Нужно ли ето кому-то? Если вам очень невмоготу навешать лапшу детям или блеснуть умом - тогда ето ваше все. А если нет - то вариантность ето скорее способ документировать свои намерения, чем обеспечить какой то дополнительньій функціонал. Подумайте, почему вьі или кто то другой захочет пихать не тот тип, которьій нужно? И почему етому нужно потакать? Пусть лениво сделает `map()` и не балуется со спичками.

Поверьте, огромньій codebase ядра Linux написан без любой вариантности - подумайте об етом - и как же там все работает? Работает замечательно. 

Если уж так прижало, ИМХО значительно лучше честно признать - _Да, у нас все криво_, и явно кастить ссьілку в ожидаемьій класс (как постоянно делается в Android), или грязно снабжать свои "полимерзости" полем типа (как в юнионах С). Но если вьі реально мьіслите полиморфно - *идите на Python, и прибудет с вами дандер*.
