*help.txt*	Nvim

= VIM - основний файл довідки

Переміщення: використовуйте клавіші курсору або "h", щоб перейти ліворуч, "j" йти вниз, "k" йти вгору, "l" йти праворуч

Закрити вікно: ":q <Enter>".

Вийти з Vim: ": qa! <Enter>" (обережно, всі зміни будуть втрачені!).

Перейти до теми: Помістіть курсов на тег (e.g. |bars|) і натисніть CTRL-].
   За допомогою миші - двічі клацніть лівою кнопкою |bars|.
 
Отримати специфічну допомогу:  Можливо перейте куди ви бажаєте, надавши аргумент до команди |:help|. Поставьте щось зпереду щоб вказати контекст:  *help-context*

|=====
| ЩО | Префікс | Команда
| Команда  нормального режиму || :help x
| Команда візуального режиму | v_ | :help v_u
| Команда режиму вставки | i_ | :help i_<Esc>
| Команда командного рядка | : | :help :quit
| Редагування командного рядка | c_ | :help c_<Del>
| Аргумент команди Vim | - | :help -r
| Опція	| '' | :help 'textwidth'
| Регулярний вираз | / | :help /[
|=====

Дивіться |help-summary| для більшої кількості контекстів та пояснень.

Пошук допомоги: Наберіть ":help word", потім CTRL-D щоб знайти допомогу де зустрічається  "word". Або використовуйте ":helpgrep word". |:helpgrep|

Для початку пройдіть 20ти хвилинний курс для базових команд, подивіться |vimtutor|. Прочитайте мануал з початку до кінця: |usr_01.txt|

Vim означає for Vi IMproved. Більшість в Vim була зроблена Bram Moolenaar, але тільки за допомоги багатьох інших. Дивіться |credits|.


== ОСНОВИ:

|quickref|	Огляд найбільш загальних команд для використання
|tutor|		20ти хвилинний тренувальний курс для початківців

= Завітайте до VIM Tutor

Vim дуже потужний редактор, що має багато команд, дуже багато щоб пояснити в такому туторіалі як цей. Цей туторіал розроблений пояснити досить команд, щоб ви були в змозі легко використовувати Vim як багатоцільовий редактор. ВАЖЛИВО пам'ятати, що цей редактор налаштований для навчання через використання. Це означає, що вам треба робити вправи щоб добре навчатись. Якщо ви будете лише читати текст, ви скоро забудете що було найважливішим. Поки переконайтесь,що в вас не включений CapsLock і натисніть клавішу `j`{normal} досить раз, щоб Урок 0 повністю опинився на екрані.

== Урок 0

NOTE: Команди в цьому уроці будуть модифікувати текст, але зміни не збережуться. Не турбуйтесь втратити речі; Просто пам'ятайте, що натиснувши [<Esc>](<Esc>), і потім [u](u) відкатить ваші останні зміни.

Цей туторіал інтерактивний, і вам треба знати декілька речей. Натискання [<Enter>](<Enter>) на підсвіченому тексті, [як цей](holy-grail) буде переносити вас до відповідного розділу допомоги (маємл надію), і натискання K над любим словом також буде намагатись зробити це.

Іноді ви будете потребувати модифікувати текстовий файл як цей. Коли ви зробите зміни коректно, знак ✗ зліва зміниться на ✓. Я уявляю ви вже бачите, яким милим може бути Vim ;)

Іншого разу ви отримаєте підказку виконати команду (я поясню це пізніше):
~~~ cmd
    :help <Enter>
~~~
або натиснути послідовність клавіш
~~~ normal
    <Esc>0f<Space>d3wP$P
~~~

Текст, оточений в < > (як `<Enter>`) описує клавішу для натискання, а не сам текст. Тепер перейдіть до наступного уроку, не забуваючи натискати `j` для прокручування.

===  Урок 1.1: Переміщення курсора

** Щоб перемістити курсор натискайте `h`, `j`, `k`, `l` . **

         ↑
         k          Підказка: `h` зліва і рухає вліво
     ← h   l →                `l` зправа і рухає вправо
         j                    `j` виглядає як стрілка вниз (сумнівно)
         ↓

  1. Перемістіть курсор по екрану, доки не відчуєте себе комфортно.

  2. Натискайте `j`{normal} доки не спрацює повтор. 
     Тепер ви знаєте як перейти до наступного уроку.

  3. Використовуючи клавішу вниз, перейдіть до Уроку 1.2.

NOTE: Якщо ви будь-коли непевні щодо того, що ви дпукуєте, натисніть <Esc> для повернення в режим Normal. Потім знову наберіть команду.

NOTE: Клавіші курсору також мають робити. Але використання hjkl дасть вам змогу просуватись значно швидше, як тільки ви це усвідомите. Справді.

=== Урок 1.2: ВИХІД З VIM 

NOTE: Перед виконанням подальших кроків спочатку прочитайте урок до кінця !!

  1. Натисніть кнопку <Esc> (щоб переконатись що ви в Нормальному режимі[Normal mode](Normal-mode).

  2. Наберіть:

    `:q!<Enter>`

    Ви вийдете з редактору, ВІДКИДАЮЧИ ВСІ ЗМІНИ, які ви зробили. 

  3. Відкрийте vim та поверніться сюди, виконавши команду, що завела вас в цей тутор. Це має бути:

     :Tutor <Enter>

  4. Якщо ви запам'ятали ці кроки і почуваєтесь впевнено, виконайте кроки з 1 до 3, щоб вийти і знову війти в редактор.

NOTE: q!<Enter> відкине всі зміни, що ви зробили. За декілька уроків ви навчитесь зберігати зміни в файлі.

  5. Перемістіть курсор вниз до Уроку 1.3.

=== Урок 1.3: РЕДАГУВАННЯ ТЕКСТУ - ВИДАЛЕННЯ

** Натисніть `x` для видалення символа під курсором. **

  1. Перемістіть курсор на рядок нижче позначений --->.

  2. Щоб виправити помилки, перемістіть курсор до символів, що треба видалити. 

  3. Натисніть x для видалення зайвого символу.

  4. Повторіть кроки 2-4, доки речення не стане коректним.

The cow jumped over the moon.

NOTE: По мірі просування цім тутором не намагайтесь запам'ятовувати, навчайтесь через використання.

=== Урок 1.4: РЕДАГУВАННЯ ТЕКСТУ - ВСТАВКА

** Натисніть `i` для вставки тексту. **

  1. Перемістіть курсор на перший рядок за поміченим --->.

  2. Щоб зробити перший рядок таким самим, як другий, пересуньте курсор на перший символ ПІСЛЯ того де має бути вставлений текст.

  3. Натисніть `i` і введить потрібні зміни.

  4. Після виправлення кожної помилки натискайте `<Esc>` для повернення в Normal mode.
     Повторіть кроки 2-4 для виправлення речення.

There is some text missing from this line.
There is some text missing from this line.

Коли ви призвичаєтесь вставляти текст, переходьте до Уроку 1.5.

=== Урок 1.5: РЕДАГУВАННЯ ТЕКСТУ - ДОДАВАННЯ

** Натисніть `A` для додавання тексту.

  1. Перемістіть курсор на перший рядок, помічений --->.
     Не має різниці, на який символ вказує курсор в цьому рядку.

  2. Натисніть [A] в друкуйте потрібні додавання до цього рядка.

  3. Коли текст буде додано, натисніть <Esc> для повернення в Normal mode.

  4. Перейдіть в другий рядок, відмічений ---> і повторіть кроки 2 і 3 для корекції цього речення. 

There is some text missing from this line.
There is some text missing from this line.
There is also some text missing here.
There is also some text missing here.

  5. Коли ви впевнено додаєте текст, переходьте до Уроку 1.6.

=== Урок 1.6: РЕДАГУВАННЯ ФАЙЛА 

** Використовуйте `:wq` для збереження файлу та виходу.

Перед виконанням подальших кроків дочитайте урок до кінця.

  1. Вийдіть з vim як ви робили раніше за допомогою `:q!` або запустіть інший термінал і зробіть там наступне.  

  2. В оболонці введять команду:
~~~ sh
     $ vim tutor
~~~
     'vim' це команда для запуску редактора Vim, 'tutor' ім'я файла, який ви бажаєте редагувати. Використовуйте файл, що можете змінити.

  3. Вставляйте і видаляйте текст, як ви вивчили в попередніх уроках. 

  4. Збережіть файл, який ви змінили, та вийдіть з Vim:
~~~ cmd
     :wq
~~~

     Зауважте, що вам потрібно додати <Enter> для виконання команди.

  5. Якщо ви вийшли з тутора на кроці 1, знову війдіть і переходьте до підсумка першого заняття.

  6. Після того, як ви прочитали та зрозуміли кроки переходьте до дій і виконайте їх.

=== Урок 1 ПІДСУМОК 1. 

1. Курсор рухається з використанням або стрілок, або клавіш hjkl.

2. Щоб запустити vim з оболонки введіть sh $ vim FILENAME

3. Щоб вийти з Vim: `<Esc>` `:q!` `<Enter>` для відкидання змін, або `:wq` для збереження змін.

4. Для видалення символу під курсором натисніть `x`

5. Для вставляння або додавання тексту до рядка:
     `i` вставити текст `<Esc>`
     `A` додати текст в кінець `<Esc>`

NOTE: Натискання `<Esc>` переведе вас в нормальний режим, або відмінить небажану і частково завершену команду.

=== Урок 2.1: КОМАНДИ ВИДАЛЕННЯ

** Надрукуйте `dw`для видалення слова. **

** Надрукуйте `d$` щоб видалити до кінця рядка. **

Somebody typed the end of this line twice. 

# Lesson 2.3: ON OPERATORS AND MOTIONS

Багато команд, що змінюють текст, створені як оператор+рух.
Для видалення перша літера має бути d, а далі we$ для видалення слова, слова з проміжком або рядка. Окреме натискання однієї з ціх літер без дії просто перемістить курсор у вказану позицію.

# Урок 2.4: Використання лічильників

Завдання числа перед переміщенням або дією діє як множник. Тобто 2w або 3e переміщує курсор на вказане число слів. Відповідно, вказавши d2w або 2dw можна отримати бажаний результат.

Зважаючи на постійне видалення рядків в коді програм видалення рядка зроблене просто dd.

# Урок 2.7: КОМАНДА ВІДКАТУ 
Для відкату натисніть u або U для відкату всього рядка.  
 
# Lesson 2 SUMMARY

  1. To delete from the cursor up to the next word type:    `dw`{normal}
  2. To delete from the cursor to the end of a line type:   `d$`{normal}
  3. To delete a whole line type:                           `dd`{normal}
  4. To repeat a motion prepend it with a number:           `2w`{normal}

  5. The format for a change command is:
               operator   [number]   motion
     where:
       operator -   is what to do, such as [d](d) for delete
       [number] -   is an optional count to repeat the motion
       motion   -   moves over the text to operate on, such as:
                        [w](w) (word),
                        [$]($) (to the end of line), etc.

  6. To move to the start of the line use a zero: [0](0)

  7. To undo previous actions, type:            `u`{normal}  (lowercase u)
     To undo all the changes on a line, type:   `U`{normal}  (capital U)
     To undo the undo's, type:                  `<Ctrl-r>`{normal}

# Lesson 3.1: THE PUT COMMAND

** Type `p`{normal} to put previously deleted text after the cursor. **

  1. Move the cursor to the first ---> line below.

  2. Type `dd`{normal} to delete the line and store it in a Vim register.

  3. Move the cursor to the c) line, ABOVE where the deleted line should go.

  4. Type `p`{normal} to put the line below the cursor.

  5. Repeat steps 2 through 4 to put all the lines in correct order.

d) Can you learn too?
b) Violets are blue,
c) Intelligence is learned,
a) Roses are red,

# Lesson 3.2: THE REPLACE COMMAND

** Type `rx`{normal} to replace the character at the cursor with x. **

  1. Move the cursor to the first line below marked --->.

  2. Move the cursor so that it is on top of the first error.

  3. Type `r`{normal} and then the character which should be there.

  4. Repeat steps 2 and 3 until the first line is equal to the second one.

Whan this lime was tuoed in, someone presswd some wrojg keys!
When this line was typed in, someone pressed some wrong keys!

  5. Now move on to Lesson 3.3.

NOTE: Remember that you should be learning by doing, not memorization.

# Lesson 3.3: THE CHANGE OPERATOR

** To change until the end of a word, type `ce`{normal}. **

  1. Move the cursor to the first line below marked --->.

  2. Place the cursor on the "u" in "lubw".

  3. Type `ce`{normal} and the correct word (in this case, type "ine" ).

  4. Press `<Esc>`{normal} and move to the next character that needs to be changed.

  5. Repeat steps 3 and 4 until the first sentence is the same as the second.

This lubw has a few wptfd that mrrf changing usf the change operator.
This line has a few words that need changing using the change operator.

Notice that [c](c)e deletes the word and places you in Insert mode.

# Lesson 3.4: MORE CHANGES USING `c`{normal}

** The change operator is used with the same motions as delete. **

  1. The change operator works in the same way as delete. The format is:

         c    [number]   motion

  2. The motions are the same, such as `w`{normal} (word) and `$`{normal} (end of line).

  3. Move to the first line below marked --->.

  4. Move the cursor to the first error.

  5. Type `c$`{normal} and type the rest of the line like the second and press `<Esc>`{normal}.

The end of this line needs some help to make it like the second.
The end of this line needs to be corrected using the `c$`{normal} command.

NOTE: You can use the Backspace key to correct mistakes while typing.

# Lesson 3 SUMMARY

  1. To put back text that has just been deleted, type [p](p). This puts the
     deleted text AFTER the cursor (if a line was deleted it will go on the
     line below the cursor).

  2. To replace the character under the cursor, type [r](r) and then the
     character you want to have there.

  3. The [change operator](c) allows you to change from the cursor to where the
     motion takes you. Type `ce`{normal} to change from the cursor to the end of
     the word, `c$`{normal} to change to the end of a line.

  4. The format for change is:

     c   [number]   motion

Now go on to the next lesson.

# Lesson 4.1: CURSOR LOCATION AND FILE STATUS

** Type `<Ctrl-g>`{normal} to show your location in the file and the file status.
 Type `G`{normal} to move to a line in the file. **

NOTE: Read this entire lesson before executing any of the steps!!

  1. Hold down the `<Ctrl>`{normal} key and press `g`{normal}. We call this `<Ctrl-g>`{normal}.
     A message will appear at the bottom of the page with the filename and the
     position in the file. Remember the line number for Step 3.

NOTE: You may see the cursor position in the lower right corner of the screen
      This happens when the ['ruler']('ruler') option is set (see `:help 'ruler'`{vim} ).

  2. Press [G](G) to move you to the bottom of the file.
     Type [gg](gg) to move you to the start of the file.

  3. Type the number of the line you were on and then `G`{normal}. This will
     return you to the line you were on when you first pressed `<Ctrl-g>`{normal}.

  4. If you feel confident to do this, execute steps 1 through 3.

# Lesson 4.2: THE SEARCH COMMAND

** Type `/`{normal} followed by a phrase to search for the phrase. **

  1. In Normal mode type the `/`{normal} character. Notice that it and the cursor
     appear at the bottom of the screen as with the `:`{normal} command.

  2. Now type 'errroor' `<Enter>`{normal}. This is the word you want to search for.

  3. To search for the same phrase again, simply type [n](n).
     To search for the same phrase in the opposite direction, type [N](N).

  4. To search for a phrase in the backward direction, use [?](?) instead of `/`{normal}.

  5. To go back to where you came from press `<Ctrl-o>`{normal} (keep `<Ctrl>`{normal} pressed down while
     pressing the letter `o`{normal}). Repeat to go back further. `<Ctrl-i>`{normal} goes forward.

"errroor" is not the way to spell error; errroor is an error.

NOTE: When the search reaches the end of the file it will continue at the
      start, unless the ['wrapscan']('wrapscan') option has been reset.

# Lesson 4.3: MATCHING PARENTHESES SEARCH

** Type `%`{normal} to find a matching ),], or }. **

  1. Place the cursor on any (, [, or { in the line below marked --->.

  2. Now type the [%](%) character.

  3. The cursor will move to the matching parenthesis or bracket.

  4. Type `%`{normal} to move the cursor to the other matching bracket.

  5. Move the cursor to another (,),[,],{ or } and see what `%`{normal} does.

This ( is a test line with ('s, ['s ] and {'s } in it. ))

NOTE: This is very useful in debugging a program with unmatched parentheses!

# Lesson 4.4: THE SUBSTITUTE COMMAND

** Type `:s/old/new/g` to substitute "new" for "old". **

  1. Move the cursor to the line below marked --->.

  2. Type
~~~ cmd
    :s/thee/the/
~~~

    NOTE that the [:s](:s) command only changed the first occurrence of "thee" in the line.

  3. Now type
~~~ cmd
     :s/thee/the/g
~~~

     Adding the g [flag](:s_flags) means to substitute globally in the line, change
     all occurrences of "thee" in the line.

Usually thee best time to see thee flowers is in thee spring.

  4. To change every occurrence of a character string between two lines, type
~~~ cmd
     :#,#s/old/new/g
~~~
     where #,# are the line numbers of the range of lines where the substitution is to be done.

     Type
~~~ cmd
     :%s/old/new/g
~~~
     to change every occurrence in the whole file.

     Type
~~~ cmd
     :%s/old/new/gc
~~~
     to find every occurrence in the whole file, with a prompt whether to substitute or not.

# Lesson 4 SUMMARY

  1. `<Ctrl-g>`{normal}     displays your location in the file and the file status.
             `G`{normal}    moves to the end of the file.
     number  `G`{normal}    moves to that line number.
            `gg`{normal}    moves to the first line.

  2. Typing `/`{normal} followed by a phrase searches FORWARD for the phrase.
     Typing `?`{normal} followed by a phrase searches BACKWARD for the phrase.
     After a search type `n`{normal} to find the next occurrence in the same direction
                      or `N`{normal} to search in the opposite direction.
     `<Ctrl-o>`{normal} takes you back to older positions, `<Ctrl-i>`{normal} to newer positions.

  3. Typing `%`{normal} while the cursor is on a (,),[,],{, or } goes to its match.

  4. To substitute new for the first old in a line type
~~~ cmd
        :s/old/new
~~~
     To substitute new for all 'old's on a line type
~~~ cmd
        :s/old/new/g
~~~
     To substitute phrases between two line #'s type
~~~ cmd
        :#,#s/old/new/g
~~~
     To substitute all occurrences in the file type
~~~ cmd
        :%s/old/new/g
~~~
     To ask for confirmation each time add 'c'
~~~ cmd
        :%s/old/new/gc
~~~

# Lesson 5.1: HOW TO EXECUTE AN EXTERNAL COMMAND

** Type `:!`{vim} followed by an external command to execute that command. **

  1. Type the familiar command `:`{normal} to set the cursor at the bottom of the
     screen. This allows you to enter a command-line command.

  2. Now type the [!](!cmd) (exclamation point) character. This allows you to
     execute any external shell command.

  3. As an example type "ls" following the "!" and then hit `<Enter>`{normal}. This
     will show you a listing of your directory, just as if you were at the
     shell prompt.

NOTE: It is possible to execute any external command this way, also with
      arguments.

NOTE: All `:`{vim} commands must be finished by hitting `<Enter>`{normal}.
      From here on we will not always mention it.

# Lesson 5.2: MORE ON WRITING FILES

** To save the changes made to the text, type `:w`{vim} FILENAME. **

  1. Type `:!ls`{vim} to get a listing of your directory.
     You already know you must hit `<Enter>`{normal} after this.

  2. Choose a filename that does not exist yet, such as TEST.

  3. Now type:
~~~ cmd
        :w TEST
~~~
    (where TEST is the filename you chose.)

  4. This saves the whole file (the Vim Tutor) under the name TEST.
     To verify this, type `:!ls`{vim} again to see your directory.

NOTE: If you were to exit Vim and start it again with `nvim TEST`, the file
      would be an exact copy of the tutor when you saved it.

  5. Now remove the file by typing:
~~~ cmd
        :!rm TEST
~~~

# Lesson 5.3: SELECTING TEXT TO WRITE

** To save part of the file, type `v`{normal} motion `:w FILENAME`{vim}. **

  1. Move the cursor to this line.

  2. Press [v](v) and move the cursor to the fifth item below. Notice that the
     text is highlighted.

  3. Press the `:`{normal} character. At the bottom of the screen

        :'<,'>

    will appear.

  4. Type

        `:w TEST`{vim}

     where TEST is a filename that does not exist yet. Verify that you see

        `:'<,'>w TEST`{vim}

     before you press `<Enter>`{normal}.

  5. Vim will write the selected lines to the file TEST. Use `:!ls`{vim} to see it.
     Do not remove it yet! We will use it in the next lesson.

NOTE: Pressing [v](v) starts [Visual selection](visual-mode). You can move
      the cursor around to make the selection bigger or smaller. Then you can
      use an operator to do something with the text. For example, `d`{normal} deletes
      the text.

# Lesson 5.4: RETRIEVING AND MERGING FILES

** To insert the contents of a file, type `:r FILENAME`{vim}. **

  1. Place the cursor just above this line.

NOTE:  After executing Step 2 you will see text from Lesson 5.3. Then move
       DOWN to see this lesson again.

  2. Now retrieve your TEST file using the command

        `:r TEST`{vim}

     where TEST is the name of the file you used.
     The file you retrieve is placed below the cursor line.

  3. To verify that a file was retrieved, cursor back and notice that there
     are now two copies of Lesson 5.3, the original and the file version.

NOTE: You can also read the output of an external command. For example,

        `:r !ls`{vim}

      reads the output of the `ls` command and puts it below the cursor.

# Lesson 5 SUMMARY

  1. [:!command](:!cmd) executes an external command.

     Some useful examples are:
     `:!ls`{vim}              -  shows a directory listing
     `:!rm FILENAME`{vim}     -  removes file FILENAME

  2. [:w](:w) FILENAME             writes the current Vim file to disk with
                                   name FILENAME.

  3. [v](v)  motion  :w FILENAME   saves the Visually selected lines in file
                                   FILENAME.

  4. [:r](:r) FILENAME             retrieves disk file FILENAME and puts it
                                   below the cursor position.

  5. [:r !dir](:r!)                reads the output of the dir command and
                                   puts it below the cursor position.

# Lesson 6.1: THE OPEN COMMAND

** Type `o`{normal} to open a line below the cursor and place you in Insert mode. **

  1. Move the cursor to the line below marked --->.

  2. Type the lowercase letter `o`{normal} to [open](o) up a line BELOW the cursor and place
     you in Insert mode.

  3. Now type some text and press `<Esc>`{normal} to exit Insert mode.

After typing `o`{normal} the cursor is placed on the open line in Insert mode.

  4. To open up a line ABOVE the cursor, simply type a [capital O](O), rather
     than a lowercase `o`{normal}. Try this on the line below.

Open up a line above this by typing O while the cursor is on this line.

# Lesson 6.2: THE APPEND COMMAND

** Type `a`{normal} to insert text AFTER the cursor. **

  1. Move the cursor to the start of the line below marked --->.

  2. Press `e`{normal} until the cursor is on the end of "li".

  3. Type the lowercase letter `a`{normal} to [append](a) text AFTER the cursor.

  4. Complete the word like the line below it. Press `<Esc>`{normal} to exit Insert
     mode.

  5. Use `e`{normal} to move to the next incomplete word and repeat steps 3 and 4.

This li will allow you to pract appendi text to a line.
This line will allow you to practice appending text to a line.

NOTE: [a](a), [i](i) and [A](A) all go to the same Insert mode, the only difference is where
      the characters are inserted.

# Lesson 6.3: ANOTHER WAY TO REPLACE

** Type a capital `R`{normal} to replace more than one character. **

  1. Move the cursor to the first line below marked --->. Move the cursor to
     the beginning of the first "xxx".

  2. Now press `R`{normal} ([capital R](R)) and type the number below it in the second line, so that it
     replaces the "xxx".

  3. Press `<Esc>`{normal} to leave [Replace mode](mode-replace). Notice that the rest of the line
     remains unmodified.

  4. Repeat the steps to replace the remaining "xxx".

Adding 123 to xxx gives you xxx.
Adding 123 to 456 gives you 579.

NOTE: Replace mode is like Insert mode, but every typed character deletes an
      existing character.

# Lesson 6.4: COPY AND PASTE TEXT

** Use the `y`{normal} operator to copy text and `p`{normal} to paste it. **

  1. Go to the line marked with ---> below and place the cursor after "a)".

  2. Start Visual mode with `v`{normal} and move the cursor to just before "first".

  3. Type `y`{normal} to [yank](yank) (copy) the highlighted text.

  4. Move the cursor to the end of the next line: `j$`{normal}

  5. Type `p`{normal} to [put](put) (paste) the text.

  6. Press `a`{normal} and then type "second". Press `<Esc>`{normal} to leave Insert mode.

  7. Use Visual mode to select " item.", yank it with `y`{normal}, move to the end of
     the next line with `j$`{normal} and put the text there with `p`{normal}.

a) This is the first item.
    b)

NOTE: you can also use `y`{normal} as an operator; `yw`{normal} yanks one word.

# Lesson 6.5: SET OPTION

** Set an option so a search or substitute ignores case. **

  1. Search for 'ignore' by entering: `/ignore`
     Repeat several times by pressing `n`{normal}.

  2. Set the 'ic' (Ignore case) option by entering:
~~~ cmd
        :set ic
~~~
  3. Now search for 'ignore' again by pressing `n`{normal}.
     Notice that Ignore and IGNORE are now also found.

  4. Set the 'hlsearch' and 'incsearch' options:
~~~ cmd
        :set hls is
~~~
  5. Now type the search command again and see what happens: /ignore <Enter>

  6. To disable ignoring case enter:
~~~ cmd
        :set noic
~~~
  7. To toggle the value of a setting, prepend it with "inv":
~~~ cmd
        :set invic
~~~
NOTE: To remove the highlighting of matches enter:
~~~ cmd
        :nohlsearch
~~~
NOTE: If you want to ignore case for just one search command, use [\c](/\c)
      in the phrase: /ignore\c <Enter>

# Lesson 6 SUMMARY

  1. Type `o`{normal} to open a line BELOW the cursor and start Insert mode.
     Type `O`{normal} to open a line ABOVE the cursor.

  2. Type `a`{normal} to insert text AFTER the cursor.
     Type `A`{normal} to insert text after the end of the line.

  3. The `e`{normal} command moves to the end of a word.

  4. The `y`{normal} operator yanks (copies) text, `p`{normal} puts (pastes) it.

  5. Typing a capital `R`{normal} enters Replace mode until `<Esc>`{normal} is pressed.

  6. Typing "[:set](:set) xxx" sets the option "xxx". Some options are:

        'ic' 'ignorecase'   ignore upper/lower case when searching
        'is' 'incsearch'    show partial matches for a search phrase
        'hls' 'hlsearch'    highlight all matching phrases

     You can either use the long or the short option name.

  7. Prepend "no" to switch an option off:
~~~ cmd
        :set noic
~~~
  8. Prepend "inv" to toggle an option:
~~~ cmd
        :set invic
~~~

# Lesson 7.1: GETTING HELP

** Use the on-line help system. **

Vim has a comprehensive on-line help system. To get started, try one of
these three:
    - press the `<HELP>`{normal} key (if you have one)
    - press the `<F1>`{normal} key (if you have one)
    - type
        `:help`{vim}

Read the text in the help window to find out how the help works.
Type `<Ctrl-w><Ctrl-w>`{normal} to jump from one window to another.
Type `:q`{vim} to close the help window.

You can find help on just about any subject, by giving an argument to the
":help" command. Try these (don't forget pressing <Enter>):
~~~ cmd
    :help w
    :help c_CTRL-D
    :help insert-index
    :help user-manual
~~~
# Lesson 7.2: CREATE A STARTUP SCRIPT

** Enable Vim features. **

Vim has many more features than Vi, but most of them are disabled by
default. To start using more features you have to create a "vimrc" file.

  1. Start editing the "vimrc" file. This depends on your system:
    `:e ~/.config/nvim/init.vim`{vim} for Unix-like systems

  2. Now read the example "vimrc" file contents:
    `:r $VIMRUNTIME/vimrc_example.vim`{vim}

  3. Write the file with:
    `:w`{vim}

  The next time you start Vim it will use syntax highlighting.
  You can add all your preferred settings to this "vimrc" file.
  For more information type `:help vimrc-intro`{vim}.

# Lesson 7.3: COMPLETION

** Command line completion with `<Ctrl-d>`{normal} and `<Tab>`{normal}. **

  1. Look what files exist in the directory: `:!ls`{vim}

  2. Type the start of a command: `:e`{vim}

  3. Press `<Ctrl-d>`{normal} and Vim will show a list of commands that start with "e".

  4. Press `<Tab>`{normal} and Vim will complete the command name to ":edit".

  5. Now add a space and the start of an existing file name: `:edit FIL`{vim}

  6. Press `<Tab>`{normal}. Vim will complete the name (if it is unique).

NOTE: Completion works for many commands. It is especially useful for `:help`{vim}.

# Lesson 7 SUMMARY

  1. Type `:help`{vim}
     or press `<F1>`{normal} or `<Help>`{normal} to open a help window.

  2. Type `:help TOPIC`{vim} to find help on TOPIC.

  3. Type `<Ctrl-w><Ctrl-w>`{normal} to jump to another window

  4. Type `:q`{vim} to close the help window

  5. Create a vimrc startup script to keep your preferred settings.

  6. While in command mode, press `<Ctrl-d>`{normal} to see possible completions.
     Press `<Tab>`{normal} to use one completion.

# CONCLUSION

This was intended to give a brief overview of the Vim editor, just enough to
allow you to use the editor fairly easily. It is far from complete as Vim has
many many more commands. Consult the help often.

There are many resources online to learn more about vim. Here's a bunch of them:

- *Learn Vim Progressively*: http://yannesposito.com/Scratch/en/blog/Learn-Vim-Progressively/
- *Learning Vim in 2014*: http://benmccormick.org/learning-vim-in-2014/
- *Vimcasts*: http://vimcasts.org/
- *Vim Video-Tutorials by Derek Wyatt*: http://derekwyatt.org/vim/tutorials/
- *Learn Vimscript the Hard Way*: http://learnvimscriptthehardway.stevelosh.com/
- *7 Habits of Effective Text Editing*: http://www.moolenaar.net/habits.html
- *vim-galore*: https://github.com/mhinz/vim-galore

If you prefer a book, *Practical Vim* by Drew Neil is recommended often (the sequel, *Modern
Vim*, includes material specific to nvim).

This tutorial was written by Michael C. Pierce and Robert K. Ware, Colorado
School of Mines using ideas supplied by Charles Smith, Colorado State
University. E-mail: bware@mines.colorado.edu.

Modified for Vim by Bram Moolenaar.
Modified for vim-tutor-mode by Felipe Morales.
|copying|	Щодо копірайтів
|iccf|		Допомога бідним дітям Уганди
|sponsor|	Снонсування розробки Vim, як стати зареєстрованим користувачем
|www|		Vim у всесвітній мережі
|bugs|		Куди надсилати повідомлення про помилки

== ІНСТРУКЦІЯ КОРИСТУВАЧА: ці файли пояснюють, як досягти цілей редагування.

|usr_toc.txt|	Зміст

=== Починаючи роботу

|usr_01.txt|  Щодо інструкцій
|usr_02.txt|  Перші кроки в Vim
|usr_03.txt|  Переміщення курсора
|usr_04.txt|  Малі зміни
|usr_05.txt|  Налаштування
|usr_06.txt|  Використання підсвітки синтаксису
|usr_07.txt|  Редагування більше одного файлу
|usr_08.txt|  Розділення вікон
|usr_09.txt|  Використання GUI
|usr_10.txt|  Великі зміни
|usr_11.txt|  Відновлення після збою
|usr_12.txt|  Хитрі трюки

=== Ефективне редагування 

|usr_20.txt|  Щвидкий набір команд
|usr_21.txt|  Перейти і повернутись
|usr_22.txt|  Пошук файлу для редагування
|usr_23.txt|  Редагування інших файлів
|usr_24.txt|  Швидка вставка
|usr_25.txt|  Редагування форматованого тексту
|usr_26.txt|  Повторення
|usr_27.txt|  Пошук команд та шаблонів
|usr_28.txt|  Згортання
|usr_29.txt|  Пересування програмою
|usr_30.txt|  Редагування програм
|usr_31.txt|  Використання GUI
|usr_32.txt|  Дерево відкатів

=== Налаштування Vim 

|usr_40.txt|  Створення нових команд
|usr_41.txt|  Написання скриптів Vim
|usr_42.txt|  Додавання нових меню
|usr_43.txt|  ВИкористання типів файлів
|usr_44.txt|  Ваше власне розфарбування синтаксису
|usr_45.txt|  Вибір вашої мови


== ІНСТРУКЦІЯ: Ці файли пояснюють кожну деталь Vim.	*reference_toc*

=== Головні теми

|intro.txt|	загальний вступ до Vim; нотація файлів допомоги
|help.txt	огляд і швидке посилання (цей файл)
|helphelp.txt|	про використання файлів допомоги
|index.txt|	алфавітний покажчик всіх команд
|help-tags|	всі тегі, на які ви можете перейти (індекс тегів)
|tips.txt|	різні підказки з використання Vim
|message.txt|	(помилки) повідомлення та пояснення Жччч
|develop.txt|   Розробка Nvim	
|debug.txt|	Зневадження самого Nvim
|uganda.txt|	умови розповсюдження Vim і що вам робити з вашими грошима

=== Базове редагування

|starting.txt|	starting Vim, Vim command arguments, initialisation
|editing.txt|	editing and writing files
|motion.txt|	commands for moving around
|scroll.txt|	scrolling the text in the window
|insert.txt|	Insert and Replace mode
|change.txt|	deleting and replacing text
|undo.txt|	Undo and Redo
|repeat.txt|	repeating commands, Vim scripts and debugging
|visual.txt|	using the Visual mode (selecting a text area)
|various.txt|	various remaining commands
|recover.txt|	recovering from a crash

=== Складне редагування

|cmdline.txt|	Command-line editing
|options.txt|	description of all options
|pattern.txt|	regexp patterns and search commands
|map.txt|	key mapping and abbreviations
|tagsrch.txt|	tags and special searches
|windows.txt|	commands for using multiple windows and buffers
|tabpage.txt|	commands for using multiple tab pages
|spell.txt|	spell checking
|diff.txt|	working with two to four versions of the same file
|autocmd.txt|	automatically executing commands on an event
|eval.txt|	expression evaluation, conditional commands
|fold.txt|	hide (fold) ranges of lines
|lua.txt|	Lua API

=== Особливі випадки

|print.txt|	printing
|remote.txt|	using Vim as a server or client

=== Підтримка мов програмування

|indent.txt|	automatic indenting for C and other languages
|lsp.txt|         Language Server Protocol (LSP)
|syntax.txt|	syntax highlighting
|filetype.txt|	settings done specifically for a type of file
|quickfix.txt|	commands for a quick edit-compile-fix cycle
|ft_ada.txt|	Ada (the programming language) support
|ft_rust.txt|	Filetype plugin for Rust
|ft_sql.txt|	about the SQL filetype plugin

=== Підтримка мов

|digraph.txt|	list of available digraphs
|mbyte.txt|	multi-byte text support
|mlang.txt|	non-English language support
|rileft.txt|	right-to-left editing mode
|arabic.txt|	Arabic language support and editing
|hebrew.txt|	Hebrew language support and editing
|russian.txt|	Russian language support and editing

=== GUI

|gui.txt|	Graphical User Interface (GUI)

=== Інтерфейс

|if_cscop.txt|	using Cscope with Vim
|if_pyth.txt|	Python interface
|if_ruby.txt|	Ruby interface
|sign.txt|	debugging signs

=== Версії 
|vim_diff.txt|	Main differences between Nvim and Vim
|vi_diff.txt|	Main differences between Vim and Vi

						*standard-plugin-list*
== Стандартні плагіни 
 
|pi_gzip.txt|      Reading and writing compressed files
|pi_health.txt|    Healthcheck framework
|pi_matchit.txt|   Extended |%| matching
|pi_msgpack.txt|   msgpack utilities
|pi_netrw.txt|     Reading and writing files over a network
|pi_paren.txt|     Highlight matching parens
|pi_spec.txt|      Filetype plugin to work with rpm spec files
|pi_tar.txt|       Tar file explorer
|pi_zip.txt|       Zip archive explorer


LOCAL ADDITIONS:				*local-additions*

------------------------------------------------------------------------------

*bars*		Bars example

Тепер, коли ви перестрибнули сюди по CTRL-] або двічи мишею, ви можете використати CTRL-T, CTRL-O, g<RightMouse>, або <C-RightMouse> щоб повернутись звідки прийшли.

Зауважте, що тегі оточені символами |, але коли ввімкнена підсвітка, ці символи приховані. Це спрощує читання команд.

В жодному разі, ви можете використовувати CTRL-] на любому слові, навіть коли воно не в |, і Vim буде намагатись знайти допомогу по ньому. Особливо це стосується опцій в лапках, як 'hlsearch'.
