== Підверджую: Так. 
1. Мене звуть Арсеній Чеботарьов, мені 51 рік. 
2. Я хочу розробляти фронт-енди за допомогою Vue!
3. І - так: я можу це робити.

=== Посилання
* Моя спешил https://proofcoding.firebaseapp.com/[портфолія для Vue]
* Моє резюме можна [побачити _здєсь_]
* Мою читанку можна https://docs.google.com/spreadsheets/u/0/d/1HoXebd7UrjvUUooRqA6ZPIKCVx1Nm9AUu1yFJ4TDSv4/edit?usp=drive_web#gid=0[почитати туть]
* Мої http://ac2epsilon.github.io/TRANS/trans.html[переклади українською] 

=== Звідки Vue, чому не React?
Звісно є деяка історія. Одна пітерська компанія, з якою я співпрацюю більше 15 років, замовила в 2019му році певне _mobile-first_ застосування. Спочатку розглядався варіант Flutter/Dart, але там все було заважке (або ми чогось не зрозуміли). Нашукали Quasar, PWA і всьо цьо. Почали копати і швидко натрапили на Vue. Клондайк щастя. Якщо б не ці косоокі Vue пацики, я б скоріше присів на Angular, бо люблю Гуглів. 

=== Навички і досвід
Коротко кажучи: присутні. До біса присутні. 30+ років в індустрії, біля 50+ проектів, біля 20+ фултаймів. Деякі дійшли до продакшина, деяки живі і дотепер. 

=== Фішка - флешка
Більшість життя я працював програмістом. Фулл-стек фріленсером. Хоча не оминав і офіси . Моя фішка була поєднання Java і Flash Animation. І все про це: класика (BlazeDS), Flex, парсинг та генерація SWF байткоду, аналіз AMF трафіку. Навіть був доволі успішний проект на Open Laszlo з бекендом на Google App Engine. Золоті часи пов'язані з розквітом Flash геймерства в соц мережах, зокрема ВКонтакті. Кожну гру треба було "садити" на стіну через API. Також співпрацював з глобальним паблішером Spil Games, 101.ru та відомою українською компанією Deep Shadow. Робота в цій сфері досить люта (це фулстек, бейбі), але гроші надходили як крига на Тітанік. Це тривало близько 15 років - в нульових і десятих.

==== Цікавий факт
В 2000 році, перебуваючи в Іспанії, я вигадав SPA. Так, є свідки. Код на PERL будував JSON, і невеликий скрипт генерував цілий каталог керамічної плитки на боці клієнта. Нагано лідер. 

=== Запаморочення від успіхів
Не секрет, що успіхи спочатку тонізують, але швидко викликають ейфорію. Саме через це я декілька разів відкривав фопи. Від банального ремонту ПК і небанальних комп'ютерних курсів - до досить вдалої спроби накрити районнитй центр ві-фі. Що в цьому чудове - це спілкування з сотнями людей. Вдячних людей. Це просто свято! Але по касі - воно того не варте. Нажаль. Не в мене. Не тут.

=== Java - here, there, everywhere. І не тільки
Як іржавий фриленсер я брався за все що горить. Від JavaME і до Hadoop - доречі обоє проекти виконані на ять і стрільнули, принаймні в технічній частині. Менеджери все врешті решт спаскудили, але воно чудово робило. І гроші отримані - я профі. Навіть є проекти на Lua і.. скажімо Limbo. Чому ні. І знову дехто в нулях, а дехто навіть у в'язниці. Але гроші отримані, так буває.

=== Функціональний через велике F
З часом, як звичайно буває, всьому прийшов епічний кінець: ВК гейми вщухли, Flash скукожився. Java остогидла в своїй Spring DI передбачуваності. Але тут 

=== Burnout
Після вивчення Haskell мене обійняла туга: бек-енди виродилися до RESTful ендпоінтів. ML/DL звелося до підстановки параметрів в Keras. Akka забилася в Lagom.

=== Дурні питання
* Не я застарий для офісної роботи з молоддю? - Зовсім ні. Зазвичай пік старості приходить приблизно на 25 років. Потім людина всихає, або молодшає.
* Як у мене з алкоголем/наркотиками? - Чудово. Без них краще. Але з ними також чудово. 
* Що з дисципліною? - Якщо робота цікава, то жодних проблем. Якщо ні - також жодних. В мене ні.
* На яку платню націлений? - Ситуація така: завдяки факту що це мій перший комерційний досвід з Vue, платня може бути довільною. Саме так. Звичайно якщо вона буде зовсім нудна, то стане нецікаво. 