include::header.adoc[]

== day 1

=== typeclasses 101 

_Learn You a Haskell for Great Good_ каже:

----
Типоклас є різновидом інтерфейсу, що описує деяку поведінку. Якщо тип є частиною типокласу, це означає, що він підтримує та реалізує поведінку, яку описує типоклас.
----

_Scalaz_ каже:

----
Він провадить чисто функціональні структури даних до компонентів зі стандартної бібліотеки Scala. Він визначає набір функціональних классів типів (`Functor`, `Monad`) , та відповідні примірники для великої кількості структур даних.
----

Давайте подивимось, чи я зможу вивчити Scalaz, навчаючи мене Haskell.

=== sbt 

Ось `build.sbt` для тестування Scalaz 7.1.0:

[source,scala]
----
scalaVersion := "2.11.2"

val scalazVersion = "7.1.0"

libraryDependencies ++= Seq(
  "org.scalaz" %% "scalaz-core" % scalazVersion,
  "org.scalaz" %% "scalaz-effect" % scalazVersion,
  "org.scalaz" %% "scalaz-typelevel" % scalazVersion,
  "org.scalaz" %% "scalaz-scalacheck-binding" % scalazVersion % "test"
)

scalacOptions += "-feature"

initialCommands in console := "import scalaz._, Scalaz._"
----

Все що вам тепер треба зробити, це відкрити REPL використовуючи sbt 0.13.0:

[source,bash]
----
$ sbt console
...
[info] downloading http://repo1.maven.org/maven2/org/scalaz/scalaz-core_2.10/7.0.5/scalaz-core_2.10-7.0.5.jar ...
import scalaz._
import Scalaz._
Welcome to Scala version 2.10.3 (Java HotSpot(TM) 64-Bit Server VM, Java 1.6.0_51).
Type in expressions to have them evaluated.
Type :help for more information.

scala>
----

Також існує API документація, згенерована для Scalaz 7.1.0.

=== Equal 

LYAHFGG: `Eq` використовується для типів, що підтримують перевірку на еквівалентність. Він реалізує члени-функції `==` та `/=`.

Еквівалент Scalaz типокласа `Eq` має назву `Equal`:

[source,scala]
----
scala> 1 === 1
res0: Boolean = true

scala> 1 === "foo"
<console>:14: error: could not find implicit value for parameter F0: scalaz.Equal[Object]
              1 === "foo"
              ^

scala> 1 == "foo"
<console>:14: warning: comparing values of types Int and String using `==' will always yield false
              1 == "foo"
                ^
res2: Boolean = false

scala> 1.some =/= 2.some
res3: Boolean = true

scala> 1 assert_=== 2
java.lang.RuntimeException: 1 ≠ 2
----

Замість стандартного `==`, `Equal` дозволяє синтаксис `===`, `=/=`, та `assert_===` через декларування метода `equal`. Головна різниця в тому, що `===` не пройде компіляцію, якщо ви спробуєте порівняти `Int` та `String`.

Note: В мене в оригіналі було `/==` замість `=/=`, але Eiríkr Åsheim вказав мені на це:

----
⛭ esoterik ⛭
@d6
 @eed3si9n хей, читав твої туторіали зі scalaz. тобі треба заохочувати людей використовувати `=/=` та не `/==`, оскільки останнє має поганий преоритет.

7
6:54 AM - Sep 6, 2012
Twitter Ads info and privacy
See ⛭ esoterik ⛭'s other Tweets
----

Звичайно оператори порівняння, як `!=`, мають вищий рівень преоритету, ніж `&&`, всі літери, тощо. Через особливе правило преоритетів правило `/==` розпізнається як оператор присвоювання, оскільки він завершується на `=`, але не починається з `=`, що відкидає його донизу таблиці преоритетів:

[source,scala]
----
scala> 1 != 2 && false
res4: Boolean = false

scala> 1 /== 2 && false
<console>:14: error: value && is not a member of Int
              1 /== 2 && false
                      ^

scala> 1 =/= 2 && false
res6: Boolean = false
----

=== Order 

LYAHFGG: `Ord` призначений для типів, що мають впорядкування. `Ord` покриває всі стандартні функції порівняння, такі як `>`, `<`, `>=` та `<=`.

Еквівалент Scalaz до типокласу `Ord` є `Order`:

[source,scala]
----
scala> 1 > 2.0
res8: Boolean = false

scala> 1 gt 2.0
<console>:14: error: could not find implicit value for parameter F0: scalaz.Order[Any]
              1 gt 2.0
              ^

scala> 1.0 ?|? 2.0
res10: scalaz.Ordering = LT

scala> 1.0 max 2.0
res11: Double = 2.0
----

`Order` дозволяє синтаксис `?|?`, що повератє `Ordering`: `LT`, `GT`, та `EQ`. Він також дозволяє оператори `lt`, `gt`, `lte`, `gte`, `min`, та `max`, декларуючи метод `order`. Подібно до `Equal`, порівняння `Int` та `Double` завалить порівняння.

=== Show 

LYAHFGG: Члени `Show` можуть бути представлені як рядки.

Еквівалент Scalaz для типокласу `Show` є `Show`:

[source,scala]
----
scala> 3.show
res14: scalaz.Cord = 3

scala> 3.shows
res15: String = 3

scala> "hello".println
"hello"
----

`Cord` є чисто функціональна структура даних для потенційно довгих  `Strings`.

=== Read 

LYAHFGG: `Read` є в деякому сенсі протилежний типоклас для `Show`. Функція `read` приймає рядок, та повертає тип, який є членом `Read`.

Я не знайшов еквівалент Scalaz для цього типокласу.

=== Enum 

LYAHFGG: Члени `Enum` є послідовно впорядковані типи — вони можуть бути перелічені. Головна перевага типокласу `Enum` в тому, що ми можемо використовувати його типи в диапазонах списків. Вони також мають попередній та наступний елемент, які ви можете отримати за допомогою функцій `succ` та `pred`.

Еквівалент Scalaz для типокласу `Enum` є `Enum`:

[source,scala]
----
scala> 'a' to 'e'
res30: scala.collection.immutable.NumericRange.Inclusive[Char] = NumericRange(a, b, c, d, e)

scala> 'a' |-> 'e'
res31: List[Char] = List(a, b, c, d, e)

scala> 3 |=> 5
res32: scalaz.EphemeralStream[Int] = scalaz.EphemeralStreamFunctions$$anon$4@6a61c7b6

scala> 'B'.succ
res33: Char = C
----

Замість стандартного `to`, `Enum` дозволяє `|->`, що повертає `List` через декларацію методів `pred` та `succ` поверх типокласу `Order`. Також є кіпа інших операторів, що він визначає, як `-+-`, `---`, `from`, `fromStep`, `pred`, `predx`, `succ`, `succx`, `|-->`, `|->`, `|==>`, та `|=>`. Виглядає що всі вони присвячені ходінню взад-вперед, та повертають диапазони.

=== Bounded 

LYAHFGG: Члени `Bounded` мають верхню та нижню межу.

Еквівалент Scalaz для `Bounded`, здається, знову буде `Enum`.

[source,scala]
----
scala> implicitly[Enum[Char]].min
res43: Option[Char] = Some(?)

scala> implicitly[Enum[Char]].max
res44: Option[Char] = Some( )

scala> implicitly[Enum[Double]].max
res45: Option[Double] = Some(1.7976931348623157E308)

scala> implicitly[Enum[Int]].min
res46: Option[Int] = Some(-2147483648)

scala> implicitly[Enum[(Boolean, Int, Char)]].max
<console>:14: error: could not find implicit value for parameter e: scalaz.Enum[(Boolean, Int, Char)]
              implicitly[Enum[(Boolean, Int, Char)]].max
                        ^
----

Примірник типокласу `Enum` повертає `Option[T]` для `max` значень.

=== Num 

LYAHFGG: `Num` є числовий типоклас. Його члени мають властивість бути в змозі поводитись як числа.

Я не знайшов еквівалентів Scalaz для `Num`, `Floating`, та `Integral`.

== Типокласи 102 

Тепер я збираюсь перестрибнути до Глави 8, Створення ваших власних типокласів (Глава 7, якщо в вас є книжка), оскільки глави посередині здебільшого присвячені синтаксису Haskell.

==== Тип даних для світла світлофора

[source,haskell]
---- 
data TrafficLight = Red | Yellow | Green
----

В Scala це буде:

[source,scala]
----
scala> :paste
// Entering paste mode (ctrl-D to finish)

sealed trait TrafficLight
case object Red extends TrafficLight
case object Yellow extends TrafficLight
case object Green extends TrafficLight
----

Тепер давайте визначимо примірник для `Equal`.

[source,scala]
----
scala> implicit val TrafficLightEqual: Equal[TrafficLight] = Equal.equal(_ == _)
TrafficLightEqual: scalaz.Equal[TrafficLight] = scalaz.Equal$$anon$7@2457733b
----

Чи можу я використати його?

[source,scala]
----
scala> Red === Yellow
<console>:18: error: could not find implicit value for parameter F0: scalaz.Equal[Product with Serializable with TrafficLight]
              Red === Yellow
----

Вочевідь `Equal[TrafficLight]` не був обраний, оскільки `Equal` має неваріантну субтипізацію: `Equal[F]`. Якщо я перевторю `TrafficLight` на кейс клас, тоді `Red` та `Yellow` будуть мати той самий тип, але тоді я втрачу тісне співпадіння шаблонів від закоркованого #fail.

[source,scala]
----
scala> :paste
// Entering paste mode (ctrl-D to finish)

case class TrafficLight(name: String)
val red = TrafficLight("red")
val yellow = TrafficLight("yellow")
val green = TrafficLight("green")
implicit val TrafficLightEqual: Equal[TrafficLight] = Equal.equal(_ == _)
red === yellow

// Exiting paste mode, now interpreting.

defined class TrafficLight
red: TrafficLight = TrafficLight(red)
yellow: TrafficLight = TrafficLight(yellow)
green: TrafficLight = TrafficLight(green)
TrafficLightEqual: scalaz.Equal[TrafficLight] = scalaz.Equal\$\$anon$7@42988fee
res3: Boolean = false
----

=== Типоклас Yes-No
 
Давайте подивимось, чи ми можемо створити наш власний справжній типоклас в стилі Scalaz. За тим винятком, що я додам свій нахил до нього щодо домовленості іменування. Scalaz називає три або чотири різні речі з використанням імені типокласу, як `Show`, `show`, та  `show`, що трохи бентежить.

Мені подобається ставити префікс `Can` до імені типокласу, позичивши його з `CanBuildFrom`, і іменувати його методи як слово + `s`, позичаючи від `sjson`/`sbinary`. Оскільки `yesno` не має багато сенсу, давайте назвемо його `truthy`. Проміжна ціль отримати `1.truthy` що повертає `true`. Мінусом є те, що додаткове `s` додається, якщо ми бажаємо використати примірники типокласу як функції, як `CanTruthy[Int].truthys(1)`.

[source,scala]
----
scala> :paste
// Entering paste mode (ctrl-D to finish)

trait CanTruthy[A] { self =>
  /** @return true, if `a` is truthy. */
  def truthys(a: A): Boolean
}
object CanTruthy {
  def apply[A](implicit ev: CanTruthy[A]): CanTruthy[A] = ev
  def truthys[A](f: A => Boolean): CanTruthy[A] = new CanTruthy[A] {
    def truthys(a: A): Boolean = f(a)
  }
}
trait CanTruthyOps[A] {
  def self: A
  implicit def F: CanTruthy[A]
  final def truthy: Boolean = F.truthys(self)
}
object ToCanIsTruthyOps {
  implicit def toCanIsTruthyOps[A](v: A)(implicit ev: CanTruthy[A]) =
    new CanTruthyOps[A] {
      def self = v
      implicit def F: CanTruthy[A] = ev
    }
}

// Exiting paste mode, now interpreting.

defined trait CanTruthy
defined module CanTruthy
defined trait CanTruthyOps
defined module ToCanIsTruthyOps

scala> import ToCanIsTruthyOps._
import ToCanIsTruthyOps._
----

Ось як ми можемо визначити примірники типокласу для `Int`:

[source,scala]
----
scala> implicit val intCanTruthy: CanTruthy[Int] = CanTruthy.truthys({
         case 0 => false
         case _ => true
       })
intCanTruthy: CanTruthy[Int] = CanTruthy$$anon$1@71780051

scala> 10.truthy
res6: Boolean = true
Next is for List[A]:

scala> implicit def listCanTruthy[A]: CanTruthy[List[A]] = CanTruthy.truthys({
         case Nil => false
         case _   => true  
       })
listCanTruthy: [A]=> CanTruthy[List[A]]

scala> List("foo").truthy
res7: Boolean = true

scala> Nil.truthy
<console>:23: error: could not find implicit value for parameter ev: CanTruthy[scala.collection.immutable.Nil.type]
              Nil.truthy
----

Здається, нам треба розглядати `Nil` особливо, через неваріантність.

[source,scala]
----
scala> implicit val nilCanTruthy: CanTruthy[scala.collection.immutable.Nil.type] = CanTruthy.truthys(_ => false)
nilCanTruthy: CanTruthy[collection.immutable.Nil.type] = CanTruthy$$anon$1@1e5f0fd7

scala> Nil.truthy
res8: Boolean = false
----

Та для `Boolean` використовувати `identity`:

[source,scala]
----
scala> implicit val booleanCanTruthy: CanTruthy[Boolean] = CanTruthy.truthys(identity)
booleanCanTruthy: CanTruthy[Boolean] = CanTruthy$$anon$1@334b4cb

scala> false.truthy
res11: Boolean = false
----

Використовуючи типоклас `CanTruthy` давайте визначимо `truthyIf` як LYAHFGG:

Тепер давайте зробимо функцію, що копіює твердження `if`, але що робитиме зі значеннями `YesNo`.

Щоб відкласти обчислення переданих аргументів ми можемо використати передачу-по-імені:

[source,scala]
----
scala> :paste
// Entering paste mode (ctrl-D to finish)

def truthyIf[A: CanTruthy, B, C](cond: A)(ifyes: => B)(ifno: => C) =
  if (cond.truthy) ifyes
  else ifno

// Exiting paste mode, now interpreting.

truthyIf: [A, B, C](cond: A)(ifyes: => B)(ifno: => C)(implicit evidence$1: CanTruthy[A])Any
Here’s how we can use it:

scala> truthyIf (Nil) {"YEAH!"} {"NO!"}
res12: Any = NO!

scala> truthyIf (2 :: 3 :: 4 :: Nil) {"YEAH!"} {"NO!"}
res13: Any = YEAH!

scala> truthyIf (true) {"YEAH!"} {"NO!"}
res14: Any = YEAH!
----

Пізніше ми візьмемо його звідси.
