:ascii-ids:
:doctype: book
:source-highlighter: pygments
:icons: font

== Модулі JavaScript

Тепер модулі JavaScript підтримуються у всіх основних браузерах!

Ця стаття пояснює, як користуватися модулями JS, як відповідально їх розгортати та як працює команда Chrome, щоб зробити модулі ще кращими в майбутньому.

=== Що таке модулі JS?

Модулі JS (також відомі як "модулі ES" або "модулі ECMAScript") - це головна нова функція, а точніше - сукупність нових функцій. Можливо, ви раніше використовували систему модулів JavaScript в юзерленді. Можливо, ви використовували https://nodejs.org/docs/latest-v10.x/api/modules.html[CommonJS], як у Node.js, або, можливо, https://github.com/amdjs/amdjs-api/blob/master/AMD.md[AMD], або, можливо, щось інше. Усі ці модульні системи мають одне спільне: вони дозволяють імпортувати та експортувати речі.

Тепер JavaScript має стандартизований синтаксис саме для цього. У межах модуля ви можете використовувати ключове слово `export` для експорту майже будь-що. Ви можете експортувати `const`, функцію або будь-яку іншу змінну прив'язки чи декларації. Просто встановіть заявку змінної або декларацію за допомогою `export`:

[source,js]
----
// 📁 lib.mjs
export const repeat = (string) => `${string} ${string}`;
export function shout(string) {
  return `${string.toUpperCase()}!`;
}
----

Потім можна використовувати ключове слово `import` для імпорту модуля з іншого модуля. Тут ми імпортуємо функцію `repeat` та `shout` з модуля `lib` та використовуємо його в нашому головному модулі `main`:

[source,js]
----
// 📁 main.mjs
import {repeat, shout} from './lib.mjs';
repeat('hello');
// → 'hello hello'
shout('Modules in action');
// → 'MODULES IN ACTION!'
----

Ви також можете експортувати значення за замовчуванням з модуля:

[source,js]
----
// 📁 lib.mjs
export default function(string) {
  return `${string.toUpperCase()}!`;
}
----

Такий експорт за замовчуванням можна імпортувати, використовуючи будь-яке ім’я:

[source,js]
----
// 📁 main.mjs
import shout from './lib.mjs';
//     ^^^^^
----

Модулі трохи відрізняються від класичних сценаріїв:

* Модулі за замовчуванням вмикають https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode[strict mode].

* Синтаксис коментарів у стилі HTML не підтримується в модулях, хоча він працює в класичних сценаріях.

[source,js]
----
// Не використовуйте синтаксис коментарів у стилі HTML у JavaScript!
const x = 42; <!-- TODO: Rename x to y.
// Замість цього використовуйте звичайний однорядковий коментар:
const x = 42; // TODO: Rename x to y.
----

* Модулі мають лексичну область вищого рівня. Це означає, що, наприклад, виконання `var foo = 42;` всередині модуля не створює глобальну змінну з назвою `foo`, доступну через `window.foo` у браузері, хоча це було б так у класичному сценарії.

* Аналогічно, `this` в модулях не відноситься до глобального `this`, а натомість `undefined`. (Використовуйте `globalThis`, якщо вам потрібен доступ до глобального `this`.)

* Новий синтаксис статичного `import` та `export` доступний лише в модулях - він не працює в класичних сценаріях.

* `await` верхнього рівня доступне в модулях, але не в класичних сценаріях. Крім того, `await` не може бути використаний як ім'я змінної в будь-якому місці модуля, хоча змінні в класичних сценаріях можуть бути названі `await` поза функціями `async`.

Через ці відмінності той самий код JavaScript може поводитись по-різному, коли трактується як модуль vs. класичного сценарію. Таким чином, середовище виконання JavaScript повинен знати, які сценарії є модулями.

=== Використання JS-модулів у браузері

В веб ви можете вказати браузерам, щоб вони розглядали елемент `<script>` як модуль, встановивши атрибут `type` в `module`.

[source,html]
----
<script type="module" src="main.mjs"></script>
<script nomodule src="fallback.js"></script>
----

Браузери, які розуміють `type = 'module'` ігнорують сценарії з атрибутом `nomodule`. Це означає, що ви можете обслуговувати на основі модулів браузерам, що підтримують модулі, одночасно надаючи фолбек для інших браузерів. Можливість зробити цю відмінність дивовижна, хоча б тільки для продуктивності! Подумайте про це: лише сучасні браузери підтримують модулі. Якщо браузер розуміє ваш код модуля, він також підтримує функції, які були перед модулями, такі як функції стрілок або `async-await`. Вам більше не доведеться транпілювати ці можливості в пакети своїх модулів! Ви можете обслуговувати менші та значною мірою необроблені навантаження на основі модулів сучасним браузерам. Лише застарілі веб-переглядачі отримують навантаження `nomodule`.

Оскільки модулі відкладені за замовчуванням, ви можете також завантажити сценарій `nomodule` відкладеним чином:

[source,js]
----
<script type="module" src="main.mjs"></script>
<script nomodule defer src="fallback.js"></script>
----

==== Відмінності між модулями та класичними сценаріями, в залежності від браузера

Як ви тепер знаєте, модулі відрізняються від класичних сценаріїв. Окрім відмінностей платформи-агностики, які ми описали вище, є деякі відмінності, характерні для браузерів.

Наприклад, модулі оцінюються лише один раз, тоді як класичні сценарії оцінюються так багато разів, доки ви додаєте їх у DOM.

[source,scala]
----
<script src="classic.js"></script>
<script src="classic.js"></script>
<!-- classic.js executes multiple times. -->

<script type="module" src="module.mjs"></script>
<script type="module" src="module.mjs"></script>
<script type="module">import './module.mjs';</script>
<!-- module.mjs executes only once. -->
----

Крім того, скрипти модулів та їх залежності підтягуються із CORS. Це означає, що будь-які сценарії модулів перехресного походження повинні обслуговуватися з відповідними заголовками, такими як `Access-Control-Allow-Origin: *`. Це не стосується класичних сценаріїв.

Інша відмінність стосується атрибута `async`, який спричиняє завантаження скрипту без блокування HTML-аналізатора (як `defer`), за винятком того, що він також виконує сценарій якнайшвидше, без гарантованого впорядкування та не чекаючи завершення розбору HTML. Атрибут `async` не працює для вбудованих класичних сценаріїв, але він працює для інлайн `<script type = "module">`.

==== Примітка про розширення файлів

Можливо, ви помітили, що ми використовуємо розширення файлу `.mjs` для модулів. В Інтернеті розширення файлу насправді не має значення, якщо файл подається з JavaScript MIME типом `text/javascript`. Веб-переглядач знає, що це модуль через атрибут типу для елемента сценарію.

Проте ми рекомендуємо використовувати розширення `.mjs` для модулів з двох причин:

1. Під час розробки розширення `.mjs` дає вам та всім, хто дивиться на ваш проект, сигнал, що файл є модулем на відміну від класичного сценарію (це не завжди можливо сказати, просто подивившись на код). Як вже казалося раніше, модулі трактуються інакше, ніж класичні сценарії, тому різниця надзвичайно важлива!

2. Це гарантує, що ваш файл буде проаналізований як модуль середовищем виконання, таким як Node.js і d8, і інструментами побудови, як Babel. Хоча кожне з цих середовищ та інструментів має власні способи, за допомогою конфігурації інтерпретувати файли з іншими розширеннями як модулі, розширення `.mjs` є крос-сумісним способом забезпечення того, що файли трактуються як модулі.

Примітка. Для розгортання `.mjs` в Інтернеті ваш веб-сервер повинен бути налаштований на подачу файлів із цим розширенням за допомогою відповідного заголовка `Content-Type: text/javascript`, як згадувалося вище. Крім того, ви можете налаштувати свій редактор для обробки `.mjs` файлів як `.js` файлів, щоб отримати підсвічування синтаксису. Більшість сучасних редакторів вже роблять це за замовчуванням.

==== Специфікатори модуля

Під час імпорту модулів рядок, що визначає розташування модуля, називається "специфікатором модуля" або "специфікатором імпорту". У нашому попередньому прикладі специфікатором модуля є `"./lib.mjs"`:

[source,js]
----
import {shout} from './lib.mjs';
//                  ^^^^^^^^^^^
----

Деякі обмеження стосуються специфікаторів модулів у браузерах. Так звані “голі” специфікатори модулів наразі не підтримуються. Це обмеження визначено, щоб у майбутньому браузери могли дозволити завантажувачам окремих модулів надавати особливого значення голим специфікаторам модулів, ось так:

[source,js]
----
// Не підтримується (поки що):
import {shout} from 'jquery';
import {shout} from 'lib.mjs';
import {shout} from 'modules/lib.mjs';
----

З іншого боку, підтримуються такі варіанти:

[source,js]
----
// Підтримується:
import {shout} from './lib.mjs';
import {shout} from '../lib.mjs';
import {shout} from '/modules/lib.mjs';
import {shout} from 'https://simple.example/modules/lib.mjs';
----

Наразі специфікаторами модуля повинні бути повні URL-адреси або відносні URL-адреси, що починаються з `/`, `./` або `../`.

==== Модулі відкладені за замовчуванням

Класичний `<script>` блокує HTML-аналізатор за замовчуванням. Ви можете обійти блокування, додавши атрибут `defer`, що забезпечує завантаження сценарію паралельно з розбором HTML.

image::async-defer.svg[]

Сценарії модулів відкладаються за замовчуванням. Тому немає необхідності додавати `defer` до тегів `<script type = "module">`! Завантаження основного модуля відбувається не тільки паралельно з розбором HTML, те саме стосується всіх модулів залежності!

=== Інші функції модуля

==== Динамічний import()
Поки ми використовували лише статичний `import`. За допомогою статичного `import` перед завантаженням основного коду потрібно завантажити та виконати весь граф модуля. Іноді ви не хочете завантажувати модуль заздалегідь, а на вимогу, лише коли це потрібно - наприклад, коли користувач натискає посилання чи кнопку. Це покращує початкові показники часу завантаження. Динамічний `import()` робить це можливим!

[source,js]
----
<script type="module">
  (async () => {
    const moduleSpecifier = './lib.mjs';
    const {repeat, shout} = await import(moduleSpecifier);
    repeat('hello');
    // → 'hello hello'
    shout('Dynamic import in action');
    // → 'DYNAMIC IMPORT IN ACTION!'
  })();
</script>
----

На відміну від статичного `import`, динамічний `import()` може використовуватися в звичайних сценаріях. Це простий спосіб поступово почати використовувати модулі в існуючій кодовій базі. Детальніше дивіться в https://v8.dev/features/dynamic-import[нашій статті] про динамічний `import()`.

Примітка: `webpack` має власну версію `import()`, яка хитро розбиває імпортований модуль на власний фрагмент, окремо від основного пакету.

==== import.meta

Ще одна нова функція, пов'язана з модулем, - `import.meta`, яка дає метадані про поточний модуль. Точні метадані, які ви отримуєте, не визначені як частина ECMAScript; це залежить від хост середовища. У браузері ви можете отримати інші метадані, ніж, наприклад, у Node.js.

Ось приклад `import.meta` в Інтернеті. За замовчуванням зображення завантажуються відносно поточної URL-адреси в документах HTML. `import.meta.url` дозволяє замість цього завантажити зображення відносно поточного модуля.

[source,js]
----
function loadThumbnail(relativePath) {
  const url = new URL(relativePath, import.meta.url);
  const image = new Image();
  image.src = url;
  return image;
}

const thumbnail = loadThumbnail('../img/thumbnail.png');
container.append(thumbnail);
----

=== Рекомендації щодо продуктивності

=== Продовжуйте групувати

За допомогою модулів стає можливим розробляти веб-сайти без використання таких пакетів, як webpack, Rollup або Parcel. Добре напряму використовувати вбудовані модулі JS в наступних сценаріях:

* під час локальної розробки
* у виробництві для невеликих веб-додатків із загальною кількістю менше ніж 100 модулів та із відносно неглибоким деревом залежності (тобто максимальною глибиною менше 5)

Однак, як ми з'ясували під час аналізу вузьких місць конвеєра завантаження Chrome, під час завантаження модульної бібліотеки, що складається з ~ 300 модулів, ефективність завантаження запакованих додатків краща, ніж незапакованих.

image::renderer-main-thread-time-breakdown.svg[]
Однією з причин цього є те, що синтаксис статичного імпорту/експорту є статистично проаналізованим, і це може допомогти інструментам пакування оптимізувати ваш код, усуваючи невикористаний експорт. Статичний імпорт та експорт - це не просто синтаксис; вони є критичною частиною інструментарію!

Наша загальна рекомендація - продовжувати використовувати пакувальники до розгортання модулів у виробництві. Певним чином, пакування - це оптимізаця, подібна до мінімізації вашого коду: це призводить до вигоди в  продуктивності, оскільки ви в кінцевому рахунку доставляєте менше коду. Пакування має той же ефект! Продовжуйте пакувати.

Як завжди, функція https://developers.google.com/web/updates/2017/04/devtools-release-notes#coverage[DevTools Code Coverage] може допомогти вам визначити, чи ви не штовхаєте користувачам непотрібний код. Ми також рекомендуємо використовувати https://developers.google.com/web/fundamentals/performance/webpack/use-long-term-caching#lazy-loading[розбиття коду] для поділу пакетів та для відстрочення завантаження критичних сценаріїв, що не належать до першого значення.

==== Компроміс пакування vs. доставка неспакованих модулів

Як зазвичай у веб-розробці, все є компромісом. Доставка модулів, що не є пакетом, може знизити продуктивність початкового завантаження (холодний кеш), але фактично може покращити ефективність завантаження для наступних відвідувань (теплий кеш) порівняно з доставкою одного пакета без розбиття коду. Для кодової бази на 200 КБ зміна одного дрібно-нарізаного модуля і наявність цього єдиного завантаження з сервера для наступних відвідувань набагато краще, ніж необхідність повторного отримання всього пакету.

Якщо ви більше переймаєтесь досвідом відвідувачів із теплими кешами, ніж продуктивністю першого відвідування та маєте сайт із менш ніж декількома сотнями роздрібнених модулів, ви можете поекспериментувати з доставкою нерозділених модулів, виміряти вплив на продуктивність як для холодних, так і для теплих завантажень, а потім прийміть рішення, продиктоване даними!

Інженери браузерів наполегливо працюють над підвищенням продуктивності модулів прямо-з-коробки. З часом ми очікуємо, що доставка роз'єднаних модулів стане можливою у більшості ситуацій.

==== Використовуйте дрібні модулі

Візміть за звичку писати свій код за допомогою маленьких дрібих модулів. Під час розробки, як правило, краще мати лише кілька експортів в модулі, ніж вручну поєднувати багато експортів в один файл.

Розглянемо модуль з іменем `./util.mjs`, який експортує три функції з назвою `drop`, `pluck` та `zip`:

[source,js]
----
export function drop() { /* … */ }
export function pluck() { /* … */ }
export function zip() { /* … */ }
----

Якщо ваша база коду дійсно потребує функціональності планку, ви, ймовірно, імпортуєте її наступним чином:

[source,js]
----
import {pluck} from './util.mjs';
----

У цьому випадку браузер (без кроку пакування часу збірки) все одно матиме необхідність завантаження, розбору та компіляції всього модуля ./util.mjs, хоча йому потрібен лише один експорт. Це марнотратство!

Якщо `pluck` не ділиться жодним кодом із `drop` та `zip`, краще перенести його до власного дрібного модуля, наприклад `./pluck.mjs`.

[source,js]
----
export function pluck() { /* … */ }
----

Тоді ми можемо імпортувати `pluck` без накладних витрат на `drop` та `zip`:

[source,js]
----
import {pluck} from './pluck.mjs';
----

Примітка. Тут ви можете використовувати `default` експорт замість названого експорту, залежно від ваших особистих переваг.

Це не тільки забезпечує збереження вашого вихідного коду красивим та простим, але також зменшує потребу в усуненні мертвого коду, що виконується пакувальниками. Якщо один з модулів у вашому вихідному дереві не використовується, він ніколи не імпортується, і тому браузер ніколи не завантажує його. Модулі, які використовувались, можуть індивідуально кешуватись браузером. (Інфраструктура для того, щоб це сталося, вже закладена у V8, і зараз триває робота над її включенням також і в Chrome.)

Використання невеликих дрібних модулів допомагає підготувати вашу кодову базу до майбутнього, де можливо буде існувати природне рішення для пакування.

==== Перед-завантажені модулі

Ви можете додатково оптимізувати доставку модулів, використовуючи `<link rel =" modulepreload ">`. Таким чином, браузери можуть передзавантажувати та навіть попередньо збирати та попередньо компілювати модулі та їх залежності.

[source,html]
----
<link rel="modulepreload" href="lib.mjs">
<link rel="modulepreload" href="main.mjs">
<script type="module" src="main.mjs"></script>
<script nomodule src="fallback.js"></script>
----

Це особливо важливо для більших дерев залежностей. Без `rel = "modulepreload"`, веб-переглядачу потрібно виконати кілька запитів HTTP, щоб визначити повне дерево залежності. Однак якщо ви оголосите повний список залежних скриптів модуля за допомогою `rel = "modulepreload"`, браузеру не доведеться виявляти ці залежності поступово.

==== Використовуйте HTTP/2

Використання HTTP/2, де це можливо, завжди є хорошою порадою щодо продуктивності, якщо тільки для його підтримки мультиплексування. За допомогою мультиплексування HTTP/2 одночасно можуть бути в польоті кілька запитів і відповідей, що вигідно для завантаження дерев модулів.

Команда Chrome дослідила, чи може інша функція HTTP/2, зокрема протокол server push HTTP/2, бути практичним рішенням для розгортання високомодульованих додатків. На жаль, HTTP/2-серверний push непростий для правильного використання, а реалізація веб-серверів та браузерів на даний момент не оптимізована довипадків використання високомодульованих  веб-додатків. Наприклад, важко штовхати лише ресурси, які користувач ще не кеширував. І вирішити це, передаючи на сервер весь стан кешу буде ризиком для конфіденційності.

Тож без сумніву, продовжуйте користуватися HTTP/2! Тільки майте на увазі, що server push в HTTP/2 - це, на жаль, не є срібною кулею.

=== Веб-сприйняття модулів JS

Модулі JS повільно набувають прийняття в Інтернеті. Наші лічильники використання показують, що 0,08% усіх завантажень сторінок в даний час використовують `<script type = "module">`. Зауважте, що це число виключає інші точки введення, такі як динамічний `import()` або `worklets`.

=== Що далі для модулів JS?
Команда Chrome працює над покращенням досвіду розробки модулів JS різними способами. Давайте обговоримо деякі з них.

==== Більш швидкий і детермінований алгоритм роздільної здатності модуля

Ми запропонували змінити алгоритм роздільної здатності модуля, який вирішив брак швидкості та детермінізму. Новий алгоритм тепер доступний як в специфікації HTML, так і в специфікації ECMAScript і реалізований в Chrome 63. Очікуйте, що це вдосконалення незабаром з’явиться в інших браузерах!

Новий алгоритм набагато ефективніший та швидший. Обчислювальна складність старого алгоритму була квадратичною, тобто 𝒪 (n²), за розміром графіка залежності, і це була реалізація Chrome на той час. Новий алгоритм лінійний, тобто 𝒪 (n).

Більше того, новий алгоритм детерміновано повідомляє про помилки роздільної здатності. Маючи граф, що містить декілька помилок, різні запуски старого алгоритму можуть повідомляти про різні помилки, що несуть відповідальність за вихід з ладу. Це ускладнювало налагодження. Новий алгоритм гарантовано щоразу повідомляє про ту саму помилку.

==== Ворклети та веб-працівники

Зараз Chrome реалізує ворклети, які дозволяють веб-розробникам налаштовувати жорстко закодовану логіку в "низькорівневих частинах" веб-браузерів. За допомогою ворклетів веб-розробники можуть подати модуль JS в конвеєр рендерингу або в конвеєр обробки аудіо (і, можливо, більше конвеєрів у майбутньому!).

Chrome 65 підтримує PaintWorklet (API CSS Paint), щоб контролювати, як малюється елемент DOM.

[source,js]
----
const result = await css.paintWorklet.addModule('paint-worklet.mjs');
----

Chrome 66 підтримує AudioWorklet, що дозволяє контролювати обробку аудіо за допомогою власного коду. Ця ж версія Chrome запустила OriginTrial для AnimationWorklet, що дозволяє створювати пов'язані з прокруткою та інші високопродуктивні процедурні анімації.

Нарешті, LayoutWorklet (API CSS Layout) тепер реалізований у Chrome 67.

Ми працюємо над тим, щоб додати підтримку використання модулів JS з спеціалізованими веб-працівниками в Chrome. Ви вже можете спробувати цю функцію, якщо ввімкнено функцію `chrome: // flags / # enable-експериментально-веб-платформа '.

[source,js]
----
const worker = new Worker('worker.mjs', { type: 'module' });
----

Незабаром відбудеться підтримка модулів JS для спільних робітників та сервісних робітників:

[source,js]
----
const worker = new SharedWorker('worker.mjs', { type: 'module' });
const registration = await navigator.serviceWorker.register('worker.mjs', { type: 'module' });
----

==== Мапи імпорту

У Node.js/npm звичайно імпортувати JS-модулі за їх "ім'ям пакета". Наприклад:

[source,js]
----
import moment from 'moment';
import {pluck} from 'lodash-es';
----

Наразі за специфікацією HTML такі "голі специфікатори імпорту" закидають виключення. Наша пропозиція про мапи імпорту дозволяє такому коду працювати в Інтернеті, в тому числі і у виробничих додатках. Мапа імпорту - це ресурс JSON, який допомагає браузеру перетворювати голі специфікатори імпорту в повні URL-адреси.

Мапи імпорту все ще знаходяться на стадії пропозиції. Хоча ми багато роздумували над тим, як вони вирішують різні випадки використання, ми все ще спілкуємося із спільнотою і ще не написали повну специфікацію. Відгуки вітаються!

==== Веб-пакування: природні пакети

Зараз команда завантаження Chrome вивчає природний формат веб-упаковки як новий спосіб розповсюдження веб-додатків. Основними особливостями веб-упаковки є:

Підписані обміни HTTP, які дозволяють браузеру довіряти, що одна пара запит/відповідь HTTP була створена за походженням, на яке вона заявляє; Пакетні обміни HTTP, тобто сукупність обмінів, кожна з яких може бути підписана або без підпису, з деякими метаданими, що описують, як інтерпретувати пакет в цілому.

У поєднанні такий формат веб-упаковки дозволить надійно вбудувати декілька ресурсів одного походження в єдину відповідь HTTP GET.

Існуючі інструменти для поєднання, такі як webpack, Rollup або Parcel, в даний час видають єдиний пакет JavaScript, в якому втрачається семантика оригінальних окремих модулів та активів. За допомогою нативних пакетів веб-переглядачі можуть розпакувати ресурси до їх первісного вигляду. Спрощено, ви можете уявити пакетну HTTP-біржу як набір ресурсів, доступ до яких можна отримати в будь-якому порядку за допомогою змісту (маніфесту), і де вміщені ресурси можуть бути ефективно збережені та марковані відповідно до їх відносної важливості, зберігаючи поняття окремих файлів. Через це нативні пакети можуть покращити досвід налагодження. Переглядаючи об’єкти в DevTools, браузери можуть чітко визначати оригінальний модуль, не потребуючи складних мап похідного код.

Прозорість нативного формату пакетів відкриває різні можливості оптимізації. Наприклад, якщо веб-переглядач вже має частину локального пакету, кешованого на локальному рівні, він може повідомити про це веб-серверу, а потім завантажити лише відсутні частини.

Chrome вже підтримує частину пропозиції (SignedExchanges), але сам формат пакету, а також його застосування до високомодульованих додатків ще знаходяться в дослідницькій фазі. Ваш відгук дуже вітається в репозиторії або електронною поштою `loading-dev@chromium.org`!

==== Багатошаровий API

Доставка нових функцій та веб-API вимагає постійних витрат на обслуговування та підчас виконання - кожна нова функція забруднює простір імен браузера, збільшує витрати на запуск та представляє нову поверхню для впровадження помилок у всій базі коду. Багатошарові API - це спроба впровадити та надсилати API більш високого рівня у веб-браузери більш масштабованим способом. Модулі JS - це ключова технологія для багатошарових API:

* Оскільки модулі імпортуються явно, вимагаючи, щоб багатошарові API піддавалися впливу модулів, гарантує розробникам плату лише за багатошарові API, які вони використовують.
* Оскільки завантаження модулів налаштовується, багатошарові API можуть мати вбудований механізм автоматичного завантаження поліфілів у браузерах, які не підтримують багатошарові API.

Деталі того, як модулі та багатошарові API працюють разом, все ще розробляються, але поточна пропозиція виглядає приблизно так:

[source,js]
----
<script
  type="module"
  src="std:virtual-scroller|https://example.com/virtual-scroller.mjs"
></script>
----

Елемент `<script>` завантажує API віртуального скролера або з вбудованого набору браузера багатошарового API (`std: virtual-scroller`), або з резервної URL-адреси, що вказує на поліфіл. Цей API може робити все, що можна зробити JS-модулі у веб-браузерах. Одним із прикладів може бути визначення користувальницького елемента `<virtual-scroller>`, щоб наступний HTML поступово покращувався за бажанням:

[source,js]
----
<virtual-scroller>
  <!-- Content goes here. -->
</virtual-scroller>
----
