:ascii-ids:
:doctype: book
:source-highlighter: pygments
:icons: font

== JavaScript Promises: вступ
Jake Archibald
Human boy working on web standards at Google

Розробники, підготуйтеся до ключового моменту в історії веб-розробки.

_Починається барабанний дріб_

- Обіцянки нарешті надійшли до JavaScript!

_Вибухають феєрверхи, зверху дощить блискучий папір, натовп стає несамовитим_

У цей момент ви потрапляєте в одну з таких категорій:

* Люди підбадьорюють вас, але ви не впевнені, у чому вся суєта. Можливо, ви навіть не впевнені, що таке «обіцянка». Ви би знизали плечима, але вага блискучого паперу важить на ваших плечах. Якщо так, не хвилюйтеся з цього приводу, мені знадобилися віки, щоб розібратися, чому я повинен дбати про ці речі. Ви, мабуть, хочете почати на початку.
* Ви рубаєте кулаком повітря! Настав ваш час, так? Ви раніше використовували ці Promise, але вас турбує факт, що всі реалізації мають трохи інший API. Який API для офіційної версії JavaScript? Ви, мабуть, хочете почати з термінології.
* Ви про це вже знали і насміхаєтесь над тими, хто стрибає вгору і вниз, ніби це для них новина. Знайдіть хвилину, щоб поласувати своєю перевагою, а потім направляйтеся прямо до посилання API.

=== Що це за метушня?

JavaScript є однопоточним, тобто два біти скрипту не можуть працювати одночасно; вони повинні виконуватись один за одним. У веб-переглядачах JavaScript поділяє потік із завантаженням інших речей, що відрізняються від браузера до браузера. Але зазвичай JavaScript знаходиться в тій самій черзі, що і малювання, оновлення стилів та обробка дій користувача (наприклад, виділення тексту та взаємодія з елементами управління формами). Активність в одній з цих речей затримує інші.

Як притаманно людині, ви багатопоточні. Ви можете друкувати декількома пальцями, можете вести машину і підтримувати розмову одночасно. Єдина функція блокування, з якою ми вимушені мати справу, - це чхання, де всю поточну активність потрібно призупинити на час чихання. Це дуже дратує, особливо коли ви їдете та намагаєтесь вести розмову. Ви не хочете писати код, що чихає.

Ви, ймовірно, використовували події та зворотні виклики, щоб уникнути цього. Ось події:

[source,js]
----
var img1 = document.querySelector('.img-1');

img1.addEventListener('load', function() {
  // завантажено зображення
});

img1.addEventListener('error', function() {
  // ачч, все зламано
});
----

Це зовсім не чхає. Ми отримуємо зображення, додаємо пару слухачів, потім JavaScript може припинити виконання, поки не викликається один із цих слухачів.

На жаль, у наведеному вище прикладі можливо, що події відбувалися ще до того, як ми почали їх слухати, тому нам потрібно обійти це, використовуючи властивість зображень `"complete"`:

[source,scala]
----
var img1 = document.querySelector('.img-1');

function loaded() {
  // завантажено зображення
}

if (img1.complete) {
  loaded();
}
else {
  img1.addEventListener('load', loaded);
}

img1.addEventListener('error', function() {
  // ачч, все зламано
});
----

Це не відловлює зображення, які мали помилку, перш ніж ми отримали можливість їх слухати; на жаль, DOM не дає нам способу це зробити. Крім того, це завантаження одного зображення. Речі стають ще складнішими, якщо ми хочемо знати, коли завантажився набір зображень.

=== Події - це не завжди найкращий спосіб

Events are great for things that can happen multiple times on the same object—keyup, touchstart etc. With those events you don't really care about what happened before you attached the listener. But when it comes to async success/failure, ideally you want something like this:
Події чудово підходять для речей, які можуть відбуватися багаторазово на одному об’єкті - клавіатурі, сенсорній панелі і т.п. З тими подіями вам не дуже важливо, що сталося до того, як ви приєднали слухача. Але якщо мова йде про асинхронні успіх/невдачу, в ідеалі вам потрібно щось подібне:

[source,scala]
----
img1.callThisIfLoadedOrWhenLoaded(function() {
  // завантажене
}).orIfFailedCallThis(function() {
  // не вдалося
});

// та потім...
whenAllTheseHaveLoaded([img1, img2]).callThis(function() {
  // всі завантажені
}).orIfSomeFailedCallThis(function() {
  // одна або декілька помилок
});
----

Це те, що роблять обіцянки, але з кращим назвами. Якщо в елементах HTML зображень був би метод `"ready"`, який повернув обіцянку, ми могли б зробити це:

[source,scala]
----
img1.ready().then(function() {
  // завантажене
}, function() {
  // не вдалося
});

// та потім...
Promise.all([img1.ready(), img2.ready()]).then(function() {
  // всі завантажені
}, function() {
  // одна або декілька помилок
});
----

Загалом, обіцянки схожі на слухачів подій, за винятком:

* Обіцянка може вдатися або провалитися лише один раз. Вона не може досягти успіху чи невдачі двічі, а також не може перейти від успіху до невдачі чи навпаки.
* Якщо обіцянка вдалася або не вдалася, і ви пізніше додасте зворотний виклик успіху/невдачі, буде викликано правильний зворотний виклик, навіть якщо подія відбулася раніше.

Це надзвичайно корисно для асинхронних успіху/невдачі, оскільки вас менше цікавить точний час, коли щось стало доступним, і більше зацікавлені в реакції на результат.

=== Термінологія обіцянок

Домен Денікола вибірково прочитав першу чернетку цієї статті і оцінив мене на "двійку" з термінології. Він помістив мене під варту, змусив 100 разів копіювати _States and Fates_ і написав занепокоєний лист моїм батькам. Незважаючи на це, у мене все ще багато мішанини в термінології, але ось основи:

Обіцянка може бути:

* виконана - дія, що стосується обіцянки, вдалася
* відхилена - дії, пов'язані з обіцянкою, не вдалися
* підвішена - ще не виконана або відхилена
* визначена - виконана або відхилена

Специфікація також використовує термін _thenable_ для опису об'єкта, який є подібним до обіцянок, оскільки він має метод `then`. Цей термін нагадує мені про екс-менеджера з футболу Англії Террі Венаблеса, тому я буду використовувати його якомога менше.

=== Обіцянки з'являються у JavaScript!

Обіцяння вже деякий час існують у формі бібліотек, таких як:

* Q
* when
* WinJS
* RSVP.js

Вищезазначені та обіцянки JavaScript поділяють загальну, стандартизовану поведінку під назвою `Promises/A+`. Якщо ви користувач `jQuery`, у них є щось подібне під назвою `Deferred`. Однак `Deferred` не сумісні з `Promise/A+`, що робить їх трохи відмінними та менш корисними, тому будьте обережні. `jQuery` також має тип `Promise`, але це лише підмножина `Deferred`, і має ті самі проблеми.

Хоча впровадження обіцянок дотримується стандартизованої поведінки, їх загальний API відрізняється. Обіцяння JavaScript схожі в API для RSVP.js. Ось як ви створюєте обіцянку:

[source,scala]
----
var promise = new Promise(function(resolve, reject) {
  // робити щось, можливо, async, потім…

  if (/* все вийшло успішно */) {
    resolve("Все робить!");
  }
  else {
    reject(Error("Воно поламалось"));
  }
});
----

Конструктор обіцянок приймає один аргумент, зворотний виклик з двома параметрами, `resolve` та `reject`. Зробіть щось із зворотного виклику, можливо, асинхроннно, потім викликаємо `resolve`, якщо все спрацювало, інакше викликається `reject`.

Як `throw` в звичайному старому JavaScript, відхиляти з об'єктом `Error` прийнято, але не потрібно. Перевага об'єктів `Error` полягає в тому, що вони захоплюють слід стека, роблячи інструменти налагодження більш корисними.

Ось як ви використовуєте цю обіцянку:

[source,scala]
----
promise.then(function(result) {
  console.log(result); // "Все робить!"
}, function(err) {
  console.log(err); // Error: "Воно поламалось"
});
----

`then()` бере два аргументи, зворотний виклик для успішної справи та інший для випадку відмови. Обидва є необов’язковими, тому ви можете додати зворотний виклик лише у випадку успіху чи відмови.

Обіцянки JavaScript почалися в DOM як `Future`, перейменовані на `Promise` і нарешті перейшли в JavaScript. Наявність їх у JavaScript, а не в DOM - це чудово, оскільки вони будуть доступні в контекстах JS, що не є браузером, таких як Node.js (чи вони використовуватимуть їх у своїх основних API-інтерфейсах - це інше питання).

Хоча вони є функцією JavaScript, DOM не боїться ними користуватися. Насправді всі нові API DOM з асинхронними методами успіху/відмови будуть використовувати обіцянки. Це відбувається вже з управлінням квотами, подіями завантаження шрифтів, ServiceWorker, веб-MIDI, потоками Streams тощо.

=== Підтримка веб-переглядачів та поліфілл

Сьогодні вже є реалізація обіцянок у браузерах.

Що стосується Chrome 32, Opera 19, Firefox 29, Safari 8 та Microsoft Edge, обіцянки включені за замовчуванням.

Щоб довести браузери, яким не вистачає повної реалізації обіцянок, до відповідності специфікації, або додати обіцянки до інших браузерів та Node.js, використовуйте поліфілл (2k gzipped).

=== Сумісність з іншими бібліотеками

API обіцянок JavaScript буде ставитись до будь-чого з методом `then()` як до обіцянки (або _thenable_ мовою обіцяльників). Тому якщо ви використовуєте бібліотеку, яка повертає обіцянку Q, це добре, це буде добре грати з новим JavaScript обіцянки.

Хоча, як я вже згадував, `Deferred` з jQuery дещо... безпораді. На щастя, ви можете привести їх в стандартні обіцянки, що варто зробити якнайшвидше:

[source,scala]
----
var jsPromise = Promise.resolve($.ajax('/whatever.json'))
----

Тут `$.ajax` з jQuery повертає `Deferred`. Оскільки у нього є метод `then()`, `Promise.resolve()` може перетворити його в обіцянку JavaScript. Однак іноді `Deferred` передають кілька аргументів своїм зворотним викликам, наприклад:

[source,scala]
----
var jqDeferred = $.ajax('/whatever.json');

jqDeferred.then(function(response, statusText, xhrObj) {
  // ...
}, function(xhrObj, textStatus, err) {
  // ...
})
----

Тоді як обіцянка JS буде ігнорувати всі, крім першого:

[source,scala]
----
jsPromise.then(function(response) {
  // ...
}, function(xhrObj) {
  // ...
})
----

На щастя, це зазвичай те, чого ви хочете, або принаймні надає вам доступ до того, що ви хочете. Також майте на увазі, що jQuery не дотримується умов передачі об'єктів `Error` у відхилення.

=== Складний код асинхронізації спростився

Гаразд, давайте закодируємо деякі речі. Скажімо, ми хочемо:

1. Запустити спінер, щоб вказати на хід завантаження
2. Отримати JSON для оповідання, яке дає нам назву, та URL кожної глави
3. Додати заголовок на сторінку
4. Підтягувати кожну главу
5. Додати оповідання на сторінку
6. Зупинити спінер

... але також повідомити користувачеві, якщо щось пішло не так по дорозі. Ми також хочемо зупинити спінер на цьому етапі також, інакше він буде продовжувати крутитися, запаморочитися і врізатися в якийсь інший інтерфейс користувача.

Звичайно, ви б не використовували JavaScript, щоб доставити оповідання, в вигляді HTML це робитиме швидше. Але ця схема є досить поширеною при роботі з API: Кілька підтягувань даних, а потім дещо зробіти, коли все буде зроблено.

Для початку давайте розберемося з отриманням даних з мережі:

=== Обіцяннки XMLHttpRequest

Старі API будуть оновлені, щоб використовувати обіцянки, якщо це можливо в зворотно сумісний спосіб. `XMLHttpRequest` є головним кандидатом, але поки давайте напишемо просту функцію, щоб зробити запит `GET`:

[source,scala]
----
function get(url) {
  // Повернути нову обіцянку.
  return new Promise(function(resolve, reject) {
    // Зробіть звичайні речі XHR
    var req = new XMLHttpRequest();
    req.open('GET', url);

    req.onload = function() {
      // Це визивається по 404 тощо
      // тому перевірити стан
      if (req.status == 200) {
        // Розв’яжіть обіцянку текстом відповіді
        resolve(req.response);
      }
      else {
        // В іншому випадку відхиліть з текстом статусу
        // що, сподіваємось, буде значущою помилкою
        reject(Error(req.statusText));
      }
    };

    // Обробка мережевих помилок
    req.onerror = function() {
      reject(Error("Network Error"));
    };

    // Зробити запит
    req.send();
  });
}
----

Тепер скористаємося цим:

[source,scala]
----
get('story.json').then(function(response) {
  console.log("Success!", response);
}, function(error) {
  console.error("Failed!", error);
})
----

Тепер ми можемо робити запити HTTP, не вводячи `XMLHttpRequest` вручну, що чудово, тому що чим менше мені доведеться бачити надихаючий верблюжий реєстр `XMLHttpRequest`, тим щасливішим буде моє життя.

=== Зціплення

`then()` не є кінцем історії, ви можете зв'язати ланцюги `then` разом, щоб перетворити значення або виконувати додаткові дії асинхронізації одна за одною.

==== Перетворення значень

Ви можете перетворити значення, просто повернувши нове значення:

[source,scala]
----
var promise = new Promise(function(resolve, reject) {
  resolve(1);
});

promise.then(function(val) {
  console.log(val); // 1
  return val + 2;
}).then(function(val) {
  console.log(val); // 3
})
----

В якості практичного прикладу повернемося до:

[source,scala]
----
get('story.json').then(function(response) {
  console.log("Success!", response);
})
----

Відповідь - JSON, але зараз ми отримуємо це як звичайний текст. Ми могли б змінити нашу функцію `get`, щоб використовувати тип відповіді JSON, але ми також могли вирішити її в області обіцянок:

[source,scala]
----
get('story.json').then(function(response) {
  return JSON.parse(response);
}).then(function(response) {
  console.log("Yey JSON!", response);
})
----

Оскільки `JSON.parse()` приймає один аргумент і повертає перетворене значення, ми можемо зробити скорочення:

[source,scala]
----
get('story.json').then(JSON.parse).then(function(response) {
  console.log("Yey JSON!", response);
})
----

Насправді ми могли б зробити функцію `getJSON()` дуже легко:

[source,scala]
----
function getJSON(url) {
  return get(url).then(JSON.parse);
}
----

`getJSON()` все ще повертає обіцянку, яка отримує URL, а потім розбирає відповідь як JSON.

=== Черги асинхронних дій

Ви також можете зв'язати ланцюги для виконання послідовних асинхронних дій.

Коли ви повертаєте щось із зворотного виклика `then()`, це трохи магія. Якщо ви повернете значення, наступне `then()` викликається з цим значенням. Однак якщо ви повернете щось подібне до обіцянки, наступне `then()` чекає на ній, і його викликають лише тоді, коли ця обіцянка набере чинності (успішно/неуспішно). Наприклад:

[source,scala]
----
getJSON('story.json').then(function(story) {
  return getJSON(story.chapterUrls[0]);
}).then(function(chapter1) {
  console.log("Got chapter 1!", chapter1);
})
----

Тут ми робимо `async` запит до `story.json`, який дає нам набір URL-адрес для запиту, тоді ми запитуємо першу з них. Ось коли обіцянки дійсно починають видрізнятись від простих моделей зворотного виклику.

Ви навіть можете зробити метод швидкого доступу, щоб отримати всі глави:

[source,scala]
----
var storyPromise;

function getChapter(i) {
  storyPromise = storyPromise || getJSON('story.json');

  return storyPromise.then(function(story) {
    return getJSON(story.chapterUrls[i]);
  })
}

// і використовувати його просто:
getChapter(0).then(function(chapter) {
  console.log(chapter);
  return getChapter(1);
}).then(function(chapter) {
  console.log(chapter);
})
----

Ми не завантажуємо `story.json` до виклику `getChapter`, але наступного разу, коли викликається `getChapter`, ми повторно використовуємо обіцянку оповідання, тому `story.json` отримується лише один раз. Yay Promises!

=== Обробка помилок

Як ми бачили раніше, `then()` бере два аргументи: один для `success`, один на `failure` (або виконати і відкинути, мовою обіцянки):

[source,scala]
----
get('story.json').then(function(response) {
  console.log("Success!", response);
}, function(error) {
  console.log("Failed!", error);
})
----

Ви також можете використовувати `catch()`:

[source,scala]
----
get('story.json').then(function(response) {
  console.log("Success!", response);
}).catch(function(error) {
  console.log("Failed!", error);
})
----

У `catch()` немає нічого особливого, це лише цукор для `then(undefined, func)`, але він легше читається. Зауважимо, що два наведені вище приклади коду не поводяться однаково, останній еквівалентний:

[source,scala]
----
get('story.json').then(function(response) {
  console.log("Success!", response);
}).then(undefined, function(error) {
  console.log("Failed!", error);
})
----

Різниця тонка, але надзвичайно корисна. Відхилення обіцянок пропускають вперед до наступного `then()` з викликом відхилення (або `catch()`, оскільки це рівнозначно). В `then(func1, func2)` будуть визиватись `func1` або `func2`, ніколи не обидва. Але з `then(func1).catch(func2)` будуть викликані обидва, якщо `func1` відмовить, оскільки вони є окремими кроками в ланцюзі. Візьміть наступне:

[source,scala]
----
asyncThing1().then(function() {
  return asyncThing2();
}).then(function() {
  return asyncThing3();
}).catch(function(err) {
  return asyncRecovery1();
}).then(function() {
  return asyncThing4();
}, function(err) {
  return asyncRecovery2();
}).catch(function(err) {
  console.log("Don't worry about it");
}).then(function() {
  console.log("All done!");
})
----

Потік вище дуже схожий на звичайний JavaScript `try/catch`: помилки, які трапляються в межах `try`, негайно переходять до блоку `catch()`. Ось наведене вище як блок-схема (тому що я люблю блок-схеми):

Дотримуйтесь синіх ліній для обіцянок, які виконуються, або червоних для тих, що відхилені.

=== Винятки та обіцянки JavaScript

Відхилення трапляються, коли обіцянку явно відхилено, але також неявно, якщо помилка передається у зворотному виклику конструктора:

[source,scala]
----
var jsonPromise = new Promise(function(resolve, reject) {
  // JSON.parse видає помилку, якщо ви подаєте
  // недійсний JSON, тому це неявно відхиляє:
  resolve(JSON.parse("This ain't JSON"));
});

jsonPromise.then(function(data) {
  // Цього ніколи не буває:
  console.log("It worked!", data);
}).catch(function(err) {
  // Натомість це відбувається:
  console.log("It failed!", err);
})
----

Це означає, що корисно виконувати всі роботи, пов'язані з обіцянками, всередині зворотного виклику конструктора обіцянок, тому помилки автоматично потрапляють і стають відхиленнями.

Те саме стосується помилок, закинутих у зворотні виклики `then()`.

[source,scala]
----
get('/').then(JSON.parse).then(function() {
  // Це ніколи не відбувається, '/' - це HTML-сторінка, а не JSON
  // це закидає JSON.parse
  console.log("It worked!", data);
}).catch(function(err) {
  // Натомість відбувається  це:
  console.log("It failed!", err);
})
----

=== Обробка помилок на практиці

За допомогою нашої розповіді та розділів ми можемо використовувати `catch` для відображення помилки для користувача:

[source,scala]
----
getJSON('story.json').then(function(story) {
  return getJSON(story.chapterUrls[0]);
}).then(function(chapter1) {
  addHtmlToPage(chapter1.html);
}).catch(function() {
  addTextToPage("Failed to show chapter");
}).then(function() {
  document.querySelector('.spinner').style.display = 'none';
})
----


Якщо витягнути `story.chapterUrls[0]` не вдасться (наприклад, `http 500` або користувач в автономному режимі), він буде пропускати всі наступні зворотні виклики успіху, що включає в себе той, який є в `getJSON()`, який намагається проаналізувати відповідь як JSON, а також пропустить зворотний виклик, який додає `chapter1.html` на сторінку. Замість цього він переходить на зворотний виклик `catch`. Як результат, на сторінку буде додане `"Failed to show chapter"`, якщо будь-яка з попередніх дій не вдалася.

Як і при `try/catch` JavaScript, помилка перехоплюється, і подальший код продовжується, тому спінер завжди прихований, як ми і хочемо. Вищенаведене стає неблокуючою версією асинхронізації:

[source,scala]
----
try {
  var story = getJSONSync('story.json');
  var chapter1 = getJSONSync(story.chapterUrls[0]);
  addHtmlToPage(chapter1.html);
}
catch (e) {
  addTextToPage("Failed to show chapter");
}
document.querySelector('.spinner').style.display = 'none'
----

Ви можете зробити `catch()` просто для ведення журналу, не відновлюючись від помилки. Для цього просто повторіть помилку. Це можна зробити за допомогою нашого методу `getJSON()`:

[source,scala]
----
function getJSON(url) {
  return get(url).then(JSON.parse).catch(function(err) {
    console.log("getJSON failed for", url, err);
    throw err;
  });
}
----

Отже, нам вдалося отримати одну главу, але ми хочемо їх усіх. Давайте це зробимо.

=== Паралелізм та послідовність: найкраще з обох

Думати асинхронно непросто. Якщо ви намагаєтеся зійти з позначки, спробуйте написати код так, ніби він був синхронним. В цьому випадку:

[source,scala]
----
try {
  var story = getJSONSync('story.json');
  addHtmlToPage(story.heading);

  story.chapterUrls.forEach(function(chapterUrl) {
    var chapter = getJSONSync(chapterUrl);
    addHtmlToPage(chapter.html);
  });

  addTextToPage("All done");
}
catch (err) {
  addTextToPage("Argh, broken: " + err.message);
}

document.querySelector('.spinner').style.display = 'none'
----

==== Спробуємо це

Це працює (див.код)! Але це синхронне і блокує браузер під час завантаження. Щоб зробити цю роботу асинхронною, ми використовуємо `then()` для того, щоб все відбувалося одне за одним.

[source,scala]
----
getJSON('story.json').then(function(story) {
  addHtmlToPage(story.heading);

  // TODO: для кожної URL-адреси в story.chapterUrls, fetch & amp; показ
}).then(function() {
  // І ми все зробили!
  addTextToPage("All done");
}).catch(function(err) {
  // Ловіть будь-яку помилку, яка сталася по дорозі
  addTextToPage("Argh, broken: " + err.message);
}).then(function() {
  // Завжди ховайте спінер
  document.querySelector('.spinner').style.display = 'none';
})
----

Але як ми можемо переглядати URL-адреси глав та отримувати їх у порядку? Це не працює:

[source,scala]
----
story.chapterUrls.forEach(function(chapterUrl) {
    // Підтягнути розділ
  getJSON(chapterUrl).then(function(chapter) {
    // і додайте його на сторінку
    addHtmlToPage(chapter.html);
  });
})
----

`forEach` не обізнаний з асинхроністю, тому наші глави відображатимуться в будь-якому порядку, в якому вони  вони завантажуються, в основному так як написано Pulp Fiction. Це не Pulp Fiction, тож давайте це полагодимо.

=== Створення послідовності

We want to turn our chapterUrls array into a sequence of promises. We can do that using then():
Ми хочемо перетворити наш масив `ChapterUrls` у послідовність обіцянок. Це можна зробити, використовуючи `then()`:

[source,scala]
----
// Почніть з обіцянки, яка завжди вирішується
var sequence = Promise.resolve();

// Переглянемо URL-адреси нашого розділу
story.chapterUrls.forEach(function(chapterUrl) {
  // Додайте ці дії до кінця послідовності
  sequence = sequence.then(function() {
    return getJSON(chapterUrl);
  }).then(function(chapter) {
    addHtmlToPage(chapter.html);
  });
})
----

Це перший раз, коли ми бачили `Promise.resolve()`, який створює обіцянку, яка вирішує будь-яке значення, яке ви надаєте. Якщо ви передасте йому екземпляр `Promise`, він просто поверне його (зверніть увагу: це зміна в специфікації, якої деякі реалізації ще не дотримуються). Якщо ви передаєте йому щось подібне до обіцянок (має метод `then()`), воно створює чистий `Promise`, який виконує/відкидає так само. Якщо ви передасте будь-яке інше значення, наприклад, `Promise.resolve ("Привіт")`, воно створює обіцянку, яка відповідає цьому значенню. Якщо ви визиваєте це без значення, як в коді вище, воно задовільняється `"undefined"`.

Існує також `Promise.reject(val)`, який створює обіцянку, яка відхиляє значення, яке ви надаєте (або `"undefined"`).

Ми можемо виправити наведений вище код за допомогою `array.reduce`:

[source,scala]
----
// Перегляньте URL-адреси нашого розділу
story.chapterUrls.reduce(function(sequence, chapterUrl) {
  // Додайте ці дії до кінця послідовності
  return sequence.then(function() {
    return getJSON(chapterUrl);
  }).then(function(chapter) {
    addHtmlToPage(chapter.html);
  });
}, Promise.resolve())
----

Це робиться так само, як і в попередньому прикладі, але не потрібна окрема `sequence`. Наш зворотний виклик викликається для кожного елемента в масиві. `sequence` - спочатку `Promise.resolve()`, але для решти викликів `sequence` - це те, що ми повернули з попереднього виклика. `array.reduce` дійсно корисний для зведення масиву до єдиного значення, що в цьому випадку є обіцянкою.

Давайте складемо все це разом:

[source,scala]
----
getJSON('story.json').then(function(story) {
  addHtmlToPage(story.heading);

  return story.chapterUrls.reduce(function(sequence, chapterUrl) {
    // Once the last chapter's promise is done…
    return sequence.then(function() {
      // …fetch the next chapter
      return getJSON(chapterUrl);
    }).then(function(chapter) {
      // and add it to the page
      addHtmlToPage(chapter.html);
    });
  }, Promise.resolve());
}).then(function() {
  // And we're all done!
  addTextToPage("All done");
}).catch(function(err) {
  // Catch any error that happened along the way
  addTextToPage("Argh, broken: " + err.message);
}).then(function() {
  // Always hide the spinner
  document.querySelector('.spinner').style.display = 'none';
})
----

І ось у нас вона (див.код), повністю асинхронна версія версії синхронізації. Але ми можемо зробити краще. Наразі наша сторінка завантажується так:

Браузери досить добре завантажують кілька речей одночасно, тому ми втрачаємо продуктивність, завантажуючи глави одна за одною. Що ми хочемо зробити, це завантажити їх одночасно, а потім обробити їх, коли всі вони прибули. На щастя, для цього є API:

[source,scala]
----
Promise.all(arrayOfPromises).then(function(arrayOfResults) {
  //...
})
----

`Promise.all` приймає масив обіцянок і створює обіцянку, яка виконується, коли всі вони успішно виконані. Ви отримуєте масив результатів (незалежно від виконаних обіцянок) у тому ж порядку, що і обіцянки, які ви виконали.

[source,scala]
----
getJSON('story.json').then(function(story) {
  addHtmlToPage(story.heading);

  // Візьміть масив обіцянок і зачекайте їх усіх
  return Promise.all(
    // Мапа нашого масиву URL-адрес глав
    // на масив обіцянок глави json
    story.chapterUrls.map(getJSON)
  );
}).then(function(chapters) {
  // Тепер ми маємо розділи jsons по порядку! Проведіть цикл ...
  chapters.forEach(function(chapter) {
  // і додати на сторінку
    addHtmlToPage(chapter.html);
  });
  addTextToPage("All done");
}).catch(function(err) {
  // зловити будь-яку помилку, що сталася до цього часу
  addTextToPage("Argh, broken: " + err.message);
}).then(function() {
  document.querySelector('.spinner').style.display = 'none';
})
----

Залежно від з'єднання, це може бути на секунду швидше, ніж завантаження по одному (див.код), і це менше коду, ніж наша перша спроба. Глави можуть завантажуватися в будь-якому порядку, але вони відображаються на екрані в потрібному порядку.

Однак ми можемо вдосконалити сприйняті результати. Коли прийде перша глава, ми повинні додати її на сторінку. Це дозволяє користувачеві почати читати до того, як залишилися інші глави. Коли прийде третій розділ, ми не додамо його до сторінки, оскільки користувач може не зрозуміти, що глава 2 відсутня. Коли прийде друга глава, ми можемо додати глави другу і три і т.д. і т.д.

Для цього ми отримуємо JSON одночасно для всіх наших розділів, а потім створюємо послідовність, щоб додати їх до документа:

[source,scala]
----
getJSON('story.json').then(function(story) {
  addHtmlToPage(story.heading);

// Мапа нашого масиву URL-адрес глав
// на масив обіцянок глав json.
// Це гарантує, що всі вони завантажуються паралельно.
  return story.chapterUrls.map(getJSON)
    .reduce(function(sequence, chapterPromise) {
      // Використовуйте reduce для ланцюга обіцянок разом,
      // додавання вмісту до сторінки для кожної глави
      return sequence.then(function() {
        // Зачекайте, поки все в послідовності,
        // тоді зачекайте, поки ця глава надійде.
        return chapterPromise;
      }).then(function(chapter) {
        addHtmlToPage(chapter.html);
      });
    }, Promise.resolve());
}).then(function() {
  addTextToPage("All done");
}).catch(function(err) {
  // зловити будь-яку помилку, яка сталася по дорозі
  addTextToPage("Argh, broken: " + err.message);
}).then(function() {
  document.querySelector('.spinner').style.display = 'none';
})
----

І ми їдемо (див.код), найкраще з обох! Щоб доставити весь вміст, потрібна однакова кількість часу, але користувач швидше отримує перший шматочок вмісту.

У цьому тривіальному прикладі всі глави надходять приблизно в один і той же час, але користь відображення однієї за одною буде збільшена з більшими, більшими главами.

Зробити вищезазначене за допомогою зворотних викликів або подій у стилі Node.js - це приблизно вдвічі більше коду, але що ще важливіше не так просто прослідкувати. Однак, це не є кінцем історії для обіцянок, коли в поєднанні з іншими функціями ES6 вони стають ще простішими.

=== Бонусний раунд: обіцянки та генератори

Цей наступний біт включає цілу купу нових функцій ES6, але це не те, що вам потрібно зрозуміти, щоб використовувати обіцянки у своєму коді сьогодні. Ставтесь до цього як до трейлеру фільму щодо деяких майбутніх функцій блокбастера.

ES6 також дає нам генератори, які дозволяють функціям виходити в певній точці, наприклад "повернутися", але пізніше відновити з тієї ж точки і стану, наприклад:

[source,scala]
----
function *addGenerator() {
  var i = 0;
  while (true) {
    i += yield i;
  }
}
----

Notice the star before the function name, this makes it a generator. The yield keyword is our return/resume point. We can use it like this:
Помітьте зірку перед назвою функції, це зробить її генератором. Ключове слово `yield` - це наша точка повернення / відновлення. Ми можемо використовувати його так:

[source,scala]
----
var adder = addGenerator();
adder.next().value; // 0
adder.next(5).value; // 5
adder.next(5).value; // 10
adder.next(5).value; // 15
adder.next(50).value; // 65
----

But what does this mean for promises? Well, you can use this return/resume behaviour to write async code that looks like (and is as easy to follow as) synchronous code. Don't worry too much about understanding it line-for-line, but here's a helper function that lets us use yield to wait for promises to settle:
Але що це означає для обіцянок? Ну, ви можете використовувати цю функцію повернення / відновлення для написання асинхронного коду, який виглядає як синхронний (і його так само просто слідувати). Не надто переживайте про розуміння кожного рядка, але ось функція помічника, яка дозволяє нам використовувати врожай, щоб чекати, коли обіцянки вирішаться:

[source,scala]
----
function spawn(generatorFunc) {
  function continuer(verb, arg) {
    var result;
    try {
      result = generator[verb](arg);
    } catch (err) {
      return Promise.reject(err);
    }
    if (result.done) {
      return result.value;
    } else {
      return Promise.resolve(result.value).then(onFulfilled, onRejected);
    }
  }
  var generator = generatorFunc();
  var onFulfilled = continuer.bind(continuer, "next");
  var onRejected = continuer.bind(continuer, "throw");
  return onFulfilled();
}
----

... який я досить сильно підсилив версією дослівного `fromQ`, але пристосований для обіцянок JavaScript. З цим ми можемо взяти наш останній приклад найкращого випадку, змішати його з вантажем нового добра ES6 і перетворити його на:

[source,scala]
----
spawn(function *() {
  try {
    // 'yield' ефективно робить асинхронічне очікування,
    // повертаючи  результат обіцянки
    let story = yield getJSON('story.json');
    addHtmlToPage(story.heading);

    // Мапа нашого масиву URL-адрес глави
    // на масив обіцянок глав json.
    // Це гарантує, що всі вони завантажуються паралельно.
    let chapterPromises = story.chapterUrls.map(getJSON);

    for (let chapterPromise of chapterPromises) {
      // Дочекайтеся готовності кожної глави, а потім додайте її на сторінку
      let chapter = yield chapterPromise;
      addHtmlToPage(chapter.html);
    }

    addTextToPage("All done");
  }
  catch (err) {
    // try/catch просто працює, сюди кидаються відхилені обіцянки
    addTextToPage("Argh, broken: " + err.message);
  }
  document.querySelector('.spinner').style.display = 'none';
})
----

Це працює точно так само, як і раніше, але так набагато простіше читати. Це працює в Chrome і Opera сьогодні (див. Код) і працює в Microsoft Edge, перейшовши до пункту `aabout:flags` та увімкнувши налаштування `Enable experimental JavaScript features`. Це буде включено за замовчуванням у наступній версії.

Це об'єднує багато нового ES6: обіцянки, генератори, `let`, `for-of`. Коли ми даємо обіцянку, помічник `spawn` чекає, коли обіцянка вирішиться, і поверне остаточне значення. Якщо обіцянка відхиляється, `spawn` призводить до того, що наше твердження `yield` кидає виняток, який ми можемо зловити за допомогою звичайного JavaScript `try/catch`. Дивовижно просте асинхронне кодування!

Ця модель є настільки корисною, вона надходить до ES7 у вигляді функції `async`. Це майже так само, як вище, але немає необхідності в методі `spawn`.

=== Посилання на Promise API

Усі методи працюють у Chrome, Opera, Firefox, Microsoft Edge та Safari, якщо не зазначено інше. Поліфайл надає нижче для всіх браузерів.

`Promise.resolve(promise);`	Повертає обіцянку (лише у випадку, якщо `promise.constructor == Promise`)
`Promise.resolve(thenable);` Робить нову обіцянку від thenable. `Thenable` є подібне до обіцянок, наскільки воно має метод `then()`.
`Promise.resolve(obj);`	Створює обіцянку, яка виконує obj. у цій ситуації.
`Promise.reject(obj);` Створює обіцянку, яка відхиляє obj. Для послідовності та налагодження (наприклад, сліди стека), obj повинен бути екземпляром помилки.
`Promise.all(array);`	Створює обіцянку, яка виконується, коли кожен елемент масиву виконується, і відхиляє, якщо (і коли) будь-який елемент відхиляє. Кожен елемент масиву передається `Promise.resolve`, тому масив може бути сумішшю об'єктів, що нагадують обіцянки та інших об'єктів. Значення виконання - це масив (по порядку) значень виконання. Значення відхилення - це перше значення відхилення.
`Promise.race(array);` Створює обіцянку, яка виконується, як тільки будь-який елемент виконується, або відхиляє, як тільки будь-який елемент відхиляє, що б не трапилося спочатку. Примітка: я не переконаний у корисності `Promise.race`; Я вважаю за краще протилежний `Promise.all`, який відхиляє лише, якщо всі елементи відхиляються.

Конструктор

`new Promise(function(resolve, reject) {});`

`resolve(thenable)`
Ваша обіцянка буде виконана/відхилена з результатом thenable

`resolve(obj)`
Ваша обіцянка виконується з obj

`reject(obj)`
Ваша обіцянка відхиляється з `obj`. Для послідовності та налагодження (наприклад, сліди стека), `obj` повинен бути екземпляром помилки. Будь-які помилки, викинуті у зворотний виклик конструктора, будуть неявно передані для `reject()`.

=== Методи екземпляра

`promise.then(onFulfilled, onRejected)`	`onFulfilled` викликається, коли / якщо обіцянка вирішується. `onRejected` викликається, коли/якщо обіцянка відхиляється. Обидва є необов'язковими, якщо будь-який/обидва опущені, наступний `onFulfilled/onRejected` у ланцюзі викликається. Обидва зворотні виклики мають один параметр, значення виконання або причину відхилення. `then()` повертає нову обіцянку, еквівалентну значенню, яке ви повертаєте з програми `onFulfilled/onRejected` після проходження через `Promise.resolve`. Якщо в зворотному виклику видано помилку, повернута обіцянка відхиляється з цією помилкою.

`promis.catch (onRejected)` Цукор для `promise.then(undefined, onRejected)`