Данный текст относится к формату данных и не относится к способу их получения, фреймворкам, языкам программирования, ОС или файловым системам. Также здесь не рассматриваются вопросы этики, эстетики, эффективности или полного или частичного отсутствия целесообразности.

Тем не менее существует референсная реализация, `arscale`, которая в достаточной мере отвечает любым упоминаемым и подразумеваемым критериям. Исходный код этой реализации отвечает на все возможные спорные вопросы.

== Встроенные метаданные - - - - - - - - - этот раздел находится вверху только для удобства читатели и займет свое место после обсуждения

- Метаданные. Каталог с фотографиями может и будет снабжаться файлом метаданных, то есть данными о снимках, таких как место сьемки, данные о авторе, снимаемом объекте.

- Формат. Референсная реализация использует JSON файл с именем `[hex_hash].meta.json`, где  `[hex_hash]` обозначает хеш изображения.

- Первичный ключ. Хеш в имени файлов (в качестве первого элемента имени) является естественным первичным ключем, идентификующим изображение. Все другие "ключи" являются вторичными, неестественными и суррогатными.

- Преоритеты. Мы здесь и в дальнейшем используем встроенные метаданные как единственный источник метаданных. Их отсутствие не является критичной ошибкой, но фолбек к другим вариантам получения метаданных не будет предусмотрен. Внешние клиенты могут использовать внешние хранилища как дополнение или замену встроенным метаданным.

- Расширяемость. Формат метаданных (схема) не является ни фиксированным, ни окончательным. Фактически единственный обязательный элемент это имя специального  формата, снабженное хешем изображения в качестве первого элемента. Все остальное может быть изменено. Изменения вносятся специальным инструментом миграции.

- Первичная миграция. На первичном этапе файлы метеданных генерируются (переносятся из MySQL) специальным компонентом миграции, `metagato`. Это одноразовая ситуация, идеологически предшествующая нарезке изображений. Нарезка будет проверять наличие метаданных в условленном каталоге.

- В обычном режиме метаданные формируются кодом обработки формы ввода изображения. 
== - - - - - - - - - - - - - - -

- Качество. Алгоритм реализует качественное мастабирование, без искажений геометрии, єффекта размытия и с соответствующим поспроцессингом (sharpening).
- Колличество. Алгоритм генерирует пять изображений с индексами от 0 до 4 и условной маркировкой large, medium, small, tiny, nano, в такой последовательности от большего к меньшему. Конкретные размеры описаны в другом месте.
- Базовый размер. Для индекса 0 не выполняется масштабирование и постпроцессинг, остальные действия выполняются как обычно. Размер нулевого изображения игнорируется, и по соглашению устанавливается в 0х0.
- Логотип и копирайт. Определенные изображения (предположительно large и medium) снабжаются наложеным логотипом и информацией об авторе снимка.
- Содержательное выходное имя файла включает: MD5 хеш оригинального файла до любой обработки в виде 32 шестнадцатеричных знаков, имя до трансформации,размер текущего изображения, индекс размера от 0 до 4, условное обозначение размера. Части имени разделяются точкой. Пример корректных имен:

`83b70dfe0aa93d8f2e2355d5a122ee19.orig_0000140001.0x0.0.large.jpeg`

`83b70dfe0aa93d8f2e2355d5a122ee19.orig_0000140001.160x100.3.tiny.jpeg`

- Структура каталогов. Выходные данные хранятся в произвольном общедоступном месте (таком как `/var/local/arscale` ). Из соображений эстетики (которые рассматриваются в другом месте)' файлы организованы в трехуровневую структуру каталогов: `ARSCALE_DIR/[0..3]/[4..7]/[8..31]/` - где числа в [] обозначают фрагменты хеш-кода хранимых файлов. Проще всего проиллюстрировать это на примере:

Файл `83b70dfe0aa93d8f2e2355d5a122ee19.orig_0000140001.0x0.0.large.jpeg` будет расположен в каталоге `/var/local/arscale/83b7/0dfe/0aa93d8f2e2355d5a122ee19` (считая что `ARSCALE_DIR` ссылается на `/var/local/arscale`).

- Сохранение оригинала. После завершения обработки исходный файл перемещается в тот же каталог, что и образованные от него файлы.

Дополнительные условия и анти-гарантии: 

- Предположительно предложенная структура каталогов может и будет использована для хранения дополнительных метаданных. Наличие неизвестных файлов и каталогов не является ошибкой.
- Амбивалентность. Алгоритм не должен (и не будет) использовать "умные", "ленивые", "отложенные" алгоритмы при генерации выходных данных. Это позволит избежать нежелательных состояний, полный список которых приведен в Приложении Б. Пользователь, располагающий оригиналом, сам может принять решение о необходимости повторной генерации. 
