== Exam Topics: ACP-100 Jira Server Administration

Issue Date Exam Validated for Product(s)
06 Apr 2020 Jira Server Enterprise Releases
Exam topics are subject to change. Visit atlassian.com/certification to ensure you have the most up-to-date topics.

== Advanced User Features (5-10% of exam)

=== Given a business requirement, create, translate, critique, and optimize JQL queries.

=== Demonstrate the benefits and best practices for configuring group subscriptions.

=== Describe the results and implications of a bulk change operation.

Иногда возникает необходимость изменить несколько ишью. Для начала вам понадобятся права уровня проекта. Например, для перемещения нескольких ишью операцией *Bulk Move* вам понадобятся *Move Issue* и *Bulk CHange*. Также некоторые действия, как *Change Comment*, могут рассылать почту - отключить это можно в *Administration > System > Mail > Outgoing mail*. Это также отключит уведомления Jira, так что не забудьте включить почту после групповых операций.

Все групповые операции начинаются одинаково: выбирается список ишью с помощью любого из способов поиска, из меню выбирается *Tools > Bulk Change*. Дальше следуют действия, специфические для групповой операции. Например, для *Transition Issues* понадобится выбрать воркфлоу экшин и задать значения для обязательных полей (все зависит от ишью и воркфлоу, которые вы выбрали). Более простые операции, такие как *Delete Issues*, не требуют дополнительных действий. Последний вопрос: хотите ли вы послать уведомления участникам проекта. Когда вы довольны своей транзакцией - завершаете операцию, нажав *Confirm*.

 Другие типы операций - редактирование, установка/сброс вотч и архивирование ишью. Наиболее сложная операция - групповое перемещение. При этом ишью перемещается в другой проект и другой тип ишью. Эта операция имеет ряд ограничений для суб-тасков, основное из которых - субтаск должен сохранить связь с родительским ишью. Имейте в виду, что суб-таск можно превратить в другой тип ишью.

 Describe the pre-requisites for and the results of a CSV import.

== Configuring Global Settings, Layout, Design, and User Communications (5-10% of exam)

=== Modify Jira configuration settings to match the organization's requirements (look and feel, logo, website links in the application navigator, default language).

=== Judge the appropriate content for the system dashboard, user/team dashboards, and filter columns for an organization.


=== Determine appropriate methods for communicating information to users.

=== Determine which global settings to modify to meet provided business requirements (attachment options, issue links, time tracking, subtasks, white list, general configuration).

== Application and Project Access and Permissions (15-25% of Page Two of Three

* Determine the appropriate use of application access, groups, roles and permissions.
 
* Identify and troubleshoot user settings, user profiles and permissions.

* Given a scenario, recommend the appropriate configuration of user and project permissions, roles and group membership.

* Given a scenario, determine the impact of deleting/deactivating a user/group.
 
* Determine if and how issue-level security should be configured in a project.

== General project configuration (10-15% of exam)
 
* Describe the appropriate use of general project settings (key, category etc.).
 
* Determine whether to modify an existing project, and/or create a new
project to meet business requirements.

* Determine whether to use an existing project template, and/or modify
project schemes to meet business requirements.

* Describe the appropriate use of components and versions.
 Determine which project activities should be delegated to the project
administrators.

== Authentication and Security (5-10% of exam)

* Evaluate the appropriate method of authentication and sign-up.

* Determine the appropriate password policy to be applied.

* Assess whether or not Jira is appropriately secured.

== Issue types, fields and screens (10-20% of exam)

* Given a scenario, identify and implement appropriate changes to built-in
fields including statuses, resolutions, priorities, translations, and issue
types.

* Identify the appropriate issue type configurations to satisfy business
requirements.

* Given a scenario, determine the effects of modifying and restructuring
active issue types and schemes.

* Determine the correct configuration of a field, considering field context,
field configuration (scheme) and screens (schemes).

* Troubleshoot the correct configuration of a field, considering field context, field configuration (scheme) and 

== Workflows (5-15% of exam)

* Describe core workflow functionality (triggers, conditions, validators, postfunctions, events, properties) and map workflows to issue types.
 
* Given business requirements, create new workflows and/or implement
appropriate changes to existing workflows and schemes.

* Given a scenario, troubleshoot workflow configurations.

== Setting up Notifications and Email (5-10% of exam)

* Determine an appropriate notification scheme/configuration including
events.
* Troubleshoot a notification scheme/configuration including events.
* Identify and troubleshoot the appropriate configuration of an Incoming Mail
Handler.

== Jira Server Administration (10-15% of exam)

* Recognize the benefits of having production and non-production instances.

* Given a scenario, recommend whether or not to upgrade and determine the
effects of roll-back.

* Evaluate the need for re-indexing following a set of modifications, and
explain the effects of re-indexing.

* Troubleshoot application-level problems with Jira (logging and profiling)
and escalate when appropriate.

* Identify and troubleshoot the appropriate configuration of an outgoing
email server.

* Given a workflow, describe which attributes will and will not be
imported/exported.

* Given a scenario, assess the impact of user directory order and
configuration.

== Administering and Extending Jira (3-10% of exam)

* Compare and contrast the different hosting options of Jira.

* Demonstrate how to appropriately configure issue collectors.

* Demonstrate how to appropriately use the features of the universal plug-in 