:ascii-ids:
:doctype: book
:source-highlighter: pygments
:icons: font

== Service managememnt

=== Знайомтесь з проектом Jira Service Managememnt

Налаштуйте для себе та вашої команди Jira Service Management для використання після входу на сайті Atlassian Cloud. Atlassian Cloud є хостована пропозиція, та дозволяє вам налаштувати ваш власний сайт не встановлюючи нічого. Якщо ви маєте зареєстрований хмарний сайт, переходьте прямо до Що таке Service Project. Якщо ваш адмін вже встановив вас як адміна проекта для існуючого сервісного проекту, перейдіть до Знайомтесь з основними можливостями Jira Service Management. 

==== Що таке Jira Service Management

Jira Service Management є наступною генерацією Jira Service Desk, рішення Atlassian IT Service Management (ITSM), створена для команд швідкісної розробки то взаємодії.

За допомогою Jira Service Management ви легко можете отримувати, відстежувати, керувати, та вирішувати запитивід клієнтів вашої команди. Користувачі можуть надсилати запити по електронній пошті, через налаштовуваний центр допомоги, або вбудований віджет. Jira Service Management спрощує категоризацію сервісних запитів, інцидентів, проблем, та зміни, через організацію та приотеризацію ціх запитів в одному місці, та підтримує команду на шляху до поставлених цілей (або домовленостей щодо рівня послуг).

Jira Service Management побудований на платформі Jira, так що ви натрапите на деякі концепції, загальні для всіх продуктів Atlassian Jira. Це створене для надання IT, розробці, опраціоністам та бізнес командам наближення один до одного, через безліч функцій для швидкої колаборації.

Ось швидкий огляд, що допоможе вам вивчити словник Jira Service Management:

* *Як відбувається робота* _Клієнти_ надсилають свої сервісні _запити_ через API: внутрішні або зовнішні _клієнтські портали_, _вбудований віджет_ або _емейл_.
* *Як роблять команди* Кожна команда може робити над _проектом_, що отримує запити в певній сфері - як от IT, HR, юрисприденція або фінанси. _Шаблони_ є різними типами _проектів_, що налаштовані під певні типи команд - керування сервісами IT тощо. Таким чином кожна команда може мати власний портал, власну реалізацію свого сервісу, і може переправляти роботу до проектів інших команд.
* *Як відстежується робота* _Агенти_ сервісного проекту роблять над _запитами_ клієнтів. Ці _запити_ відстежуються як _питання_ в _черзі_. Прогрес _питання_ встановлюється в _перебігу_, що може містити кроки, як _В прогресі_ або _Потребує затвердження_.
* *Як скоротити роботу* Розкрийте потужність продуктів Atlassian Confluence, щоб налаштувати вашу власну _базу знань_ в вашому проекті. Статті _бази знань_ з'являються на вашому порталі, так що ваші клієнти зможуть допомогти собі, перед тим як звернутись до нас.

Jira Service Management також має численні додаткові функції, що йдуть прямо з коробки для проектів IT сервісу, та можуть бути задіяні для інших проектів.

* *Сучасний менеджмент інцидентів, підсилений Opsgenie* Всі плани Service Management Cloud ідуть з основним керуванням інцидентами, призначенням по дзвінку, повідомленнями, роїнням інцидентів, та іншим - за допомоги Opsgenie, іншого продукта Atlassian. Ці можливості гарно інтегруються з вашим сервісним проектом, даючи відповідним людям бути в курсі критичних повідомлень, надаючи при цьому контекст, потрібний для прийняття дій. Під'єднайте Opsgenie до Jira Software, Bitbucket та Confluence, щоб оркеструвати цілісний, від-і-до, процес вирішення інцидентів, між командами розробки та операцій.
* *Керування змінами для епохи DevOps* Створюйте запити до змін в Jira Service Management допомагає вашим командам робити кращі рішення щодо змін до сервісів, надаючи контекстну інформацію від розробників та інфраструктурних інструментів. Полегшуйте навантаження та працюйте більш ефективно з автоматизованим присвоєнням ризиків змін, поширеними графами затверджень, та інтеграцією з інструментами CI/CD, як Bitbucket Pipelines, Jenkins та CircleCI.
* *Робимо розумніше зі складними діями* Ваші агенти можуть використовувати складні дії та можливості машинного навчання для інтелігентної категорізації, пов'язання або перетворень - та швидкого прийняття рішень.

==== Вхід на сайт Jira Service Management

Перед тим, як створити ваш сайт, ви маєте зареєструватись. Реєстреція на Jira Service Management дає вам семиденний повно функціональний строк для випробувань. Щоб зареєструватись на сайті Jira SErvice Management:

* Перейдіть на link:https://www.atlassian.com/software/jira/service-desk/try[сторінку продукту], який ви бажаєте спробувати.

* Введіть свої дані та оберіть *Agree and Sign Up*.

* Заповніть всі подальші запитання в процесі реєстрації. Створення вашого сайту може зайняти декілька хвилин.

Щоб завершити налаштування вашого сайту створіть ваш перший сервісний проект.

Щоб створити ваш перший проект:

1. На вступному екрані використайте спадаюче меню, щоб обрати, чи ви використовували Jira Software або Jira Service Management до цього.
2. Клацніть Let`s go!
3. Оберіть шаблон проекту для вашого першого сервісного проекту. Не турбуйтесь, ви можете змінити це пізніше. 

Вітаємо! Ви створили ваш перший сервісний проект. Тепер ви можете конфігурувати його за вашими потребами.

=== Що таке сервісний проект?

В Jira Service Management ви можете створювати сервісні проекти, що надають допомогу клієнтам. Ви можете створити декілька сервісних проектів, щоб надати кожній команді підтириски власний сервісний проект. Наприклад, ви можете мати загальний сервіс, сервіс для клієнтів клієнтів, для фінансів, HR, споруд та обладнання, IT або сервіс для юристів.

Клієнти можуть мати доступ до кожного сервісного проекту, до якого ви надасте їм доступ, з їх центру допомоги - онлайн місця для запитів на допомогу.

Перед тим, як ви створите сервісний проект, вам треба обрати для нього шаблон. Після того, як ви підписались на Jira Service Management, вас запитають обрати шаблон для вашого першого сервісного проекту. В залежності від потреб вашої організації, ми запускаємо ваш сервісний проект зі звітами, типами запитів та іншими інструментами. Не хвилюйтесь, це жодним чином не обмежує вас, пізніше ви завжди можете сконфігурувати ваш проект.

Історично існує різниця між сервісними проектами керованими на рівні компанії, та керованими на рівні команди. Наразі документація не вісвітлює цю тему, принаймні не для Cloud.

=== Головні можливості Jira Service Management.
 
Як тільки ви потрапили до вашого сервісного проекту, ви знайдете в ньому кіпу корисних можливостей. 

===== Черги
 
Черги це місце, де ваші агенти працюють з запитами клієнтів. Як адміністратор проекту, ви можете встановити та конфігурувати черги для сортування запитів до потрібних сервісних агентів. Ваші агенти зможуть переглядати та робити з ціма запитами в ваших чергах. 

Клієнтські запити організовані в черги. Черги дозволяють вам швидко переглядати, сортувати та призначати запити по мірі надходження. Вони також надають інформацію високого рівня щодо проблеми, зазвичай підсумок, статус та ім'я клієнта. Черги зазвичай сортуються за Service Level Agreement або цілі для взаємодії з вашою командою підтримки. Годинник на проблемі вказує час, доки не настане наступна ціль для вашої команди.

Ви можете використовувати заздалегідь сконфігуровані черги, або створити власні для вашого проекту. Власна черга дозволяє обрати ім'я черги, визначити, які запити будуть відфільтровані в цю чергу, та які стовбчики будуть з'являтись в черзі. Наприклад, ви можете мати ціль "час до першого реагування". Ваша черга преоритизує запити так, щоб  нагорі в списку опинились найбільш термінові завдання по цій цілі. Таким чином ми можемо сфокусуватись на найбільш важдивих запитах.

Ви можете створити до 50 черг на проект. Якщо ви вийдете за ці межі, розгляньте можливість поєднати черги, або видалити ті, якими ви більше не користуєтесь.

=== Приборні панелі та звіти

Використовуйте звіти для візуалізації трендів в ваших проектах. Адміністратори проектів також можуть встановити власні звіти, щоб знаходити власні тренди, що не відображені в звітах по замовчанню. 

==== Керування панелями та гаджетами

Ваша панель керування є головним екраном, який ви бачите коли заходите в Jira. Ви можете створити декілька панелей з різних проектів, або декілька панелей для одного массивного огляду всієї вашої роботи. 

Ви можете створити персональну панель та додати гаджети, щоб відстежувати призначення та проблеми, над якими ви працюєте. Панелі керування призначені для відображення гаджетів, які допомагають вам організувати ваші проекти, призначення та досягнення на різних діаграммах.

Для перегляду всіх ваших панелей оберіть *Dashboards > View All Dashboards*.

==== Щодо пенелі по замовчанню

Гаджети на панелі по замовченню можуит бути впорядковані та переставлені між правим та лівим стовпчиком. Додаткові гаджети також можуть бути додані, та деякі гаджети можуть бути сконфігуровані. Також можна налаштувати кількість стовпчиків в панелі.

Всі зміни до панелі по замовченням також будуть змінювати панелі для всіх користувачів, що використовують цю панель. Однак гаджети, для яких користувачі не мають прав доступу на перегляд, не будуть відображені. Наприклад, гаджет _Administration_, хоча він і існує в конфігурації гловної панелі по замовчанню, відображується тільки для адмінів.

==== Створення панелі

Ви можете створити та налаштувати вашу панель для відображення потрібної інформації. Тільки адміни Jira можуть налаштовувати системну панель. 

1. Оберіть *Dashboard > Create dashboard.*
2. Назвіть вашу панель та додайте опис, так щоб ваша команда знала як користуватись нею.
3. Заповніть інші поля та натисніть *Save*.

==== Додавання гаджетів до панелі

Щоб завершити налаштування панелі, додайте діаграми, таблиці та інше за допомогою гаджетів. Щоб почати, натисніть *Add gadget* на вашій панелі, і виберіть гаджет з наявних.

Щоб відобразити список проектів на вашій панелі керування, для швидкого доступу, використовуйте гаджет *projects*. Ви можете обрати бачити всі проекти, або вибрати деякі проекти для відображення.

==== Вибір розкладки панелі

Щоб обрати інше розташування гаджетів на вашій сторінці панелі (наприклад, три стовпчика, замість двох):


1. Оберіть *Dashboard > View all dashboards*.
2. Знайдіть та клацніть ім'я панелі, потім натисність *Edit Layout*.
3. Оберіть ваше бажане розташування.

==== Копіювання панелі інструментів

Ви можете створити копію вашої панелі, що ви наразі переглядаєте:

1. Оберіть *Dashboards > View all dashboards*.
2. Знайдіть вашу панель та оберіть *more(...) > Copy dashboard*.
3. Дайте назву вашій панелі і дадайте опис, щоб ваша команда знала як її використовувати. 
4. Заповніть інші поля та натисніть *Save*.

==== Поширення та редагувайня вашої панелі 

Ви можете редагувати деталі вашої панелі, та обмежити або поширити з іншими користувачами, відповідно до встановлених прав. Памʼятайте, що якощо користувач не має прав на гаджет, він його не побачить.

1. Оберіть *Dashboard > View all dashboards*.
2. Знайдіть вашу панель та оберіть *more(...) > Edit and share dashboard*.
3. Відредагуйте властивості та натисніть *Save*.

==== Пошук існуючих або загальних панелей

1. Оберіть *Dashboard > View all dashboards*.
2. Шукайте потрібну панель, набираючи ім'я, або фільтруючи список по *Owner*, *Project* або *Group*.

Кожна загальна панель вказує:

* Поточного власника. Спочатку це користовач, що створив та поширив панель.
* Список правил поділу, за якими надається доступ з боку власника.

*Увага!* Jira шукає точні співпадіння щодо введених вам зразків пошуку. Ви можете використовувати різні оператори для шаблонів та нечіткого співпадіння в ваших запитах. Наприклад:
* оператор нечіткого пошуку допомагає шукати панелі з помилками написання _dashbards~_
* оператор шаблона допомагає знайти панелі, назва яких починаються фразою _dash*_

==== Зірочки на панелях

Якщо ви маєте панель, яку ви використовуєте частіше за інші, ви можете відмітити її зірочкою, так що вона з'явиться в меню *Dashboard* в навігаційній панелі.

1. Оберіть *Dashboards > View all dashboards*.
2. Знайдіть вашу панель та клацніть зірочку поряд з назвою.

==== Встановлення дошки об'яв

Перетворіть панель на дошку на стіну, підключивши ваш комп'ютер до телевізора. Дошка об'яв є гаджет, що діє як інформаційний кіоск, який провадить безпосередній погляд на прогрес проекту та досягнення команди.

Щоб перевести панель на дошку:

1. Оберіть *Dashboards > View all dashboards*.
2. Знайдіть та клацніть назву панелі, що ви хочете відкрити.
3. Клацніть *more(...) > View as wallboard*.

=== Канали

Канали - це різні шляхи, якими клієнти можуть надсилати запити. В каналах ви можете встановлювати та редагувати свій е-мейл, центр допомоги, і канали віджетів. Загалом, власні методи запитів спираються на авторизований REST API.

=== Користувачі та ролі

Користувачі сервісного проекту - це люди, які надсилають запити та роблять над ними. Jira Service Management має _ліцензованих користувачіів_, що потребують ліцензії для взаємодії з сервісним проектом, та _неліцензовані_ користувачі, які можуть мати вільний доступ до сервісного проекту.

Ваш сервісний проект має наступних користувачів:

* *Адміністратори проекту* - ліцензовані користувачі, які встановлюють сервісний проект та користувачів. 
* *Агенти* - ліцензовані користувачі, які роблять над запитами клієнтів, та додають клієнтів до проекту.
* *Клієнти* - неліцензовані користувачі, що надсилають запити до вашого сервісного проекту через портал, е-мейл або віджет.
* *Організації* - группи клієнтів, загальні для кількох проектів.

Вам потрібні різні права доступу для керування різними типвми користувачів. Ці ролі мають такі права:

* *Адміністратори Jira* можуть керувати користувачами та ліцензіями для декількох проектів.
* *Адміністратори проекту* можуть додавати агеньів з інших проектів. Вони також можуть керувати клієнтами і організаціями.
* *Агенти* можуть керувати клієнтами і організаціями.
* *Клієнти* - неліцензовані користувачі, що надсилають запити до вашої команди підтримки через портал, е-мейл або віджет. Jira Service Management конвертує клієнтські запити в питання (_issues_) для ваших агентів. над якими вони мають працювати.

==== Додавання користувачів та як вони надають запити

Надання послуг клієнтам починається з додаванням клієнтів до проекту. Те, як люди стають клієнтами, залежить від прав клієнтів. Для додавання клієнтів перейдіть до *Customers*.

=== Дозволи для вашого сервісного проекту та Jira сайту

Ви можете встановити глобальні дозволи та права проекту для визначення, хто матиме доступ та надсилатиме запити до ваших сервісних проектів. Обоє, адміни Jira та адміни проекта мають роль гратись з правами доступа: 

* Jira адміни керують глобальними правами користувачів, і вирішують, _як саме_ користуачі отримують доступ до сервісного проекту. Вони можуть встановлювать дозволи для всіх проектів сайту Jira Cloud.
* Адміни проекту керують дозволами клієнтів для кожного проекту. Вони мають доступ до:
** хто може переглядати портал
** хто може надсилати запити в сервісний проект 
** з ким клієнти можуть ділитись запитами

Дозволи проекту залежать від глобальних дозволів, що означає, що ви можете мати різні дозволи клієнтів для проекта, в залежності від того, які люди потребують доступу.

*Увага!* Чи ви використовуєте керований-командою проект замість керованого-організацією? Шукайте в документації різницю між ціма випадами.

=== Як глобальні права користувача впливають на права прооекту

Глобальні досводи дозволяють Jira адмінам контролювати таким:
* можуть чи ні клієнти створювати власні аккаунти
* має чи ні користувач увійти в систему, щоб отримати доступ до центру допомоги
* які дозволи проекту може змінювати адмін проекту

В залежності від глобальних налаштувань, обраних Jira адміном, адміни проекту можуть налаштовувати:
* які користувачі отримують до порталу, асоційованого з проектом
* як користувачі можуть можуть поділяти запити, та з ким вони можуть це робити

Далі список посилань підсумовує глобальні дозволи та дозволи проекту.

==== Глобальні дозволи користувача

===== Процедура:

1. *Settings () > Products*
2. *Jira Service Management, Configuration*
3. Розділ *Customer permissions*, див далі
4. Налаштування зберігаються автоматично

Глобальні дозволи можуть бути змінені Jira адмінами, та впливають на права в проекті, що можуть бути змінені адмінами проекта. 

*Чи може клієнт створювати власний аккаунт?* Якщо ні, клієнт має отримати аккаунт від агента або адміна проекту.
*Чи може анонімний клієнт надсилати запити через центр допомоги?* Вмикається No автоматично, якщо аккаунти створюються агентами. 

==== Дозволи користувача проекта

===== Процедура

1. *Project settings > Customer permissions*
2. Зробити налаштування та натиснути *Save*

Дозволи, які ви можете встановити для проекта, залежать від глобальних налаштувань. 

*Хто може надсилати запити через е-мейл або портал?* Доступні три опції -всі або всі з аккаунтами (що доступне якщо користуач може створювати аккаунти), або тільки додані агентами/адмінами.
*Як користувачі можуть шукати один одного та поширювати запити*. Три опції: в організаці, також за е-мейлом, або в проекті та організації.

===== Вплив глобальних прав на права проекта

1. Якщо ввімкнені рестриктивні глобальні налаштування (див вище No-No) надсилати запити через пошту або портал можуть тільки авторизовані користувачі, або навіть тільки додані агентами. Тобто служба для власного ужитку.
2. Якщо глобальні налаштування Yes-No, тобто користувач має зареєструватись, також можна встановити тільки авторизовані користувачі, або навіть тільки додані агентами. Це публічна служба з обмеженням на порталі.
3. Якщо глобальні налаштування Yes-Yes, це відкриває повний відкритий доступ для всіх в мережі. Але адмін проекту все ще може обмежити його до тільки додані агентами. 

=== Налаштування проекту

=== База знань

=== Робочі процеси

Запити, над якими робить ваша команда, проходять путь від створення до завершення. Шлях, по якому ідуть ці питання, називається процесами. Вони можуть включати кроки як _In progress_ або _Needs Approval_.

=== Категоризація запитів клієнтів за типами запитів

Типи запитів є типами, які можливо підіймати в сервісному проекті. Ви можете додати власні типи запитів, крім запитів по замовчанню. Типи запитів можуть бути організовані в групи порталів, так щоб клієнти могли швидко знайти їх.

Кожний тип запитів базується на типі проблеми, та один тип проблеми може слугувати базисом для декількох типів запитів. Наприклад, обоє, _Запит на нове обладнання_ і _Запит на софтвер_ можуть базуватись на єдиному типі проблеми _Придбання_. Це так, тому що типи запитів керують специфічними налаштуваннями, як іменування та налаштування портала, тоді як типи проблем керують фундаментальними налаштуваннями, як процеси та поля.

Якщо ви налаштовуєте типи запитів сервісного проекту перший раз:

* Думайте як ваш клієнт ставитиме запитання. Наприклад, _Придбати новий монітор_ замість _Надіслати запит на придбання обладнання_.
* Розбивайте типи запитів на менші, як _Отримати допомогу з принтером_ або _Отримати допомогу з Wi-Fi_.
* Уникайте специфічної термінології. Наприклад, використовуйте _Мені треба доступ_ ніж _Встановити SSH ключ_.

==== Створення типу запиту

Ваш сервісний проект йде по замовчанню з декількома типами запитів. Також ви можете створити власні - для цього вам треба бути адміністратором проекту.

Щоб створити тип запиту:

1. В сервісному проекті перейдіть до *Project settings > Request types*.
2. Виберіть *Add new request type*.
3. Введіть *Request name*, *Icon*, *Issue type*.
4. Оберіть *Portal group* або залиште чекбокс невибраний, щоб приховати цей тип запитів від вашого порталу.
5. Нажміть *Create*.

Тепер ви можете налаштувати поля та налаштувати статуси процессу.

=== Налаштування стадії затвердження для запиту

==== Що таке затвердження

Деякі запити мають бути затверджені перед тим, як команда зможе робити з ними. Наприклад, менеджер може затвердити відпустку, або IT менеджер може затвердити нові системні аккаунти. Затверджувачі не потребують ліцензії Jira Service Managememnt, щоб затверджувати запити - вони просто мають бути користувачами сервісного проекту.

Ось як затвердження пасує до процесу запиту:

1. Людина надсилає запит через хелп центр або е-мейл.
2. Коли запит переходить до статусу, який потребує затвердження, затверджувач отримує повідомлення що він має підвислі затвердження.
3. В клієнтському хелп центрі затверджувач підтверджує або відхилює запит.
4. Запит переходить до наступного статусу в процессі, і клієнт повідомляється про всі коментарі, додані затверджувачем.

==== Встановлення затвердження

Щоб замовити затвердження для запиту, додайте затвердження до процессу, яким слідує запит:

1. Додайте поле вибір користувача до проекту, щоб визначити, хто може затверджувати. 

===== Процес додавання типу затверджувачів:

1. *Setting > Issues*, *Custom fields > Create custom field*
2. *All > тип* для створення нового власного поля, *Advanced > User Picker (Multiple users) > Next* для власного поля для затверджень.
3. Назвіть поле, натисність *Create*. З'явиться сторінка *Screens*.
4. Натисніть бокс поряд з *Jira Service Project Screeen*. Виберіть *Update*. Нове поле додане в проект.

===== Процес дозволу клієнтам обирати затверджувачів

Якщо ви встановили *Customers can search for other customers within their project or organizations* в налаштуваннях, клієнти можуть обирати затверджувачів через поле вибору користувачів в полі запиту. По замовчанню ваш проект іде з полем Approvers, що може використовуватись для затверждень. 

1. *Project settings > Request types*, вибрати тип запиту.
2. *Edit fields > Add a field*
3. Чекбокс *Approvers*, *Apply*

=== Додайте затвердження в процесс, щоб визначити, коли процесс потребуватиме затвердження. 

Якщо ви додали вибір користувачів до форми запитів, ви можете додати крок затвердження до процессу для цього запиту. Додавання затвердження означає, що ви можете обрати, хто може затверджувати, а також що трапляється, коли затвердження відхилене. Вам треба бути адміном Jira, щоб додавати цей крок. Для додавання процесс має бути асоційованій з відповідними проблемами.

===== Процес додавання кроку затвердження

1. *Project settings > Workflows*, *Edit* *Diagram*
2. Обрати статус, *Add approval*. Має бути два перетворення, до *Approve* та *Decline*. Ви можете додати третє перетворення, щоб агент дозволив перехід то запиту без затвердження. В кінці *Create*.

==== Всановлення списку затвержувачів

Коли встановлюєте затвердження, ви можете встановити список затверджувачів. Ви маєте встановити поле вибору користувачів щоб скористатись цім. На цьому полі зробіть *Actions > Hide*. Введіть користувачів та зробіть *Set*. Вони з'являться в проблемі та будуть повідомлені при нагоді затвердження. Ще раз, це буде доступне лише коли клієнти можуть обирати затверджувача.

=== Автоматизація

=== SLA

=== Додаткові можливості

Якщо ви використовуєте проект IT servace management, ви отримуєте деякі функції по замовчанню. Деякі з них можуть бути додані для інших типів проектів під *Project settings > Features*.

==== Керування сервісними запитами

==== Керування інцидентами

==== Керування проблемами

==== Керування змінами

==== Сервіси 

==== Повідомлення 

==== Планування по-дзвінку