:ascii-ids:
:doctype: book
:source-highlighter: pygments
:icons: font

== Service managememnt

=== Знайомтесь з проектом Jira Service Managememnt

Налаштуйте для себе та вашої команди Jira Service Management для використання після входу на сайті Atlassian Cloud. Atlassian Cloud є хостована пропозиція, та дозволяє вам налаштувати ваш власний сайт не встановлюючи нічого. Якщо ви маєте зареєстрований хмарний сайт, переходьте прямо до Що таке Service Project. Якщо ваш адмін вже встановив вас як адміна проекта для існуючого сервісного проекту, перейдіть до Знайомтесь з основними можливостями Jira Service Management. 

==== Що таке Jira Service Management

Jira Service Management є наступною генерацією Jira Service Desk, рішення Atlassian IT Service Management (ITSM), створена для команд швідкісної розробки то взаємодії.

За допомогою Jira Service Management ви легко можете отримувати, відстежувати, керувати, та вирішувати запитивід клієнтів вашої команди. Користувачі можуть надсилати запити по електронній пошті, через налаштовуваний центр допомоги, або вбудований віджет. Jira Service Management спрощує категоризацію сервісних запитів, інцидентів, проблем, та зміни, через організацію та приотеризацію ціх запитів в одному місці, та підтримує команду на шляху до поставлених цілей (або домовленостей щодо рівня послуг).

Jira Service Management побудований на платформі Jira, так що ви натрапите на деякі концепції, загальні для всіх продуктів Atlassian Jira. Це створене для надання IT, розробці, опраціоністам та бізнес командам наближення один до одного, через безліч функцій для швидкої колаборації.

Ось швидкий огляд, що допоможе вам вивчити словник Jira Service Management:

* *Як відбувається робота* _Клієнти_ надсилають свої сервісні _запити_ через API: внутрішні або зовнішні _клієнтські портали_, _вбудований віджет_ або _емейл_.
* *Як роблять команди* Кожна команда може робити над _проектом_, що отримує запити в певній сфері - як от IT, HR, юрисприденція або фінанси. _Шаблони_ є різними типами _проектів_, що налаштовані під певні типи команд - керування сервісами IT тощо. Таким чином кожна команда може мати власний портал, власну реалізацію свого сервісу, і може переправляти роботу до проектів інших команд.
* *Як відстежується робота* _Агенти_ сервісного проекту роблять над _запитами_ клієнтів. Ці _запити_ відстежуються як _питання_ в _черзі_. Прогрес _питання_ встановлюється в _перебігу_, що може містити кроки, як _В прогресі_ або _Потребує затвердження_.
* *Як скоротити роботу* Розкрийте потужність продуктів Atlassian Confluence, щоб налаштувати вашу власну _базу знань_ в вашому проекті. Статті _бази знань_ з'являються на вашому порталі, так що ваші клієнти зможуть допомогти собі, перед тим як звернутись до нас.

Jira Service Management також має численні додаткові функції, що йдуть прямо з коробки для проектів IT сервісу, та можуть бути задіяні для інших проектів.

* *Сучасний менеджмент інцидентів, підсилений Opsgenie* Всі плани Service Management Cloud ідуть з основним керуванням інцидентами, призначенням по дзвінку, повідомленнями, роїнням інцидентів, та іншим - за допомоги Opsgenie, іншого продукта Atlassian. Ці можливості гарно інтегруються з вашим сервісним проектом, даючи відповідним людям бути в курсі критичних повідомлень, надаючи при цьому контекст, потрібний для прийняття дій. Під'єднайте Opsgenie до Jira Software, Bitbucket та Confluence, щоб оркеструвати цілісний, від-і-до, процес вирішення інцидентів, між командами розробки та операцій.
* *Керування змінами для епохи DevOps* Створюйте запити до змін в Jira Service Management допомагає вашим командам робити кращі рішення щодо змін до сервісів, надаючи контекстну інформацію від розробників та інфраструктурних інструментів. Полегшуйте навантаження та працюйте більш ефективно з автоматизованим присвоєнням ризиків змін, поширеними графами затверджень, та інтеграцією з інструментами CI/CD, як Bitbucket Pipelines, Jenkins та CircleCI.
* *Робимо розумніше зі складними діями* Ваші агенти можуть використовувати складні дії та можливості машинного навчання для інтелігентної категорізації, пов'язання або перетворень - та швидкого прийняття рішень.

==== Вхід на сайт Jira Service Management

Перед тим, як створити ваш сайт, ви маєте зареєструватись. Реєстреція на Jira Service Management дає вам семиденний повно функціональний строк для випробувань. Щоб зареєструватись на сайті Jira SErvice Management:

* Перейдіть на link:https://www.atlassian.com/software/jira/service-desk/try[сторінку продукту], який ви бажаєте спробувати.

* Введіть свої дані та оберіть *Agree and Sign Up*.

* Заповніть всі подальші запитання в процесі реєстрації. Створення вашого сайту може зайняти декілька хвилин.

Щоб завершити налаштування вашого сайту створіть ваш перший сервісний проект.

Щоб створити ваш перший проект:

1. На вступному екрані використайте спадаюче меню, щоб обрати, чи ви використовували Jira Software або Jira Service Managemant до цього.
2. Клацніть Let`s go!
3. Оберіть шаблон проекту для вашого першого сервісного проекту. Не турбуйтесь, ви можете змінити це пізніше. 

Вітаємо! Ви створили ваш перший сервісний проект. Тепер ви можете конфігурувати його за вашими потребами.

=== Що таке сервісний проект?

В Jira Service Management ви можете створювати сервісні проекти, що надають допомогу клієнтам. Ви можете створити декілька сервісних проектів, щоб надати кожній команді підтириски власний сервісний проект. Наприклад, ви можете мати загальний сервіс, сервіс для клієнтів клієнтів, для фінансів, HR, споруд та обладнання, IT або сервіс для юристів.

Клієнти можуть мати доступ до кожного сервісного проекту, до якого ви надасте їм доступ, з їх центру допомоги - онлайн місця для запитів на допомогу.

Перед тим, як ви створите сервісний проект, вам треба обрати для нього шаблон. Після того, як ви підписались на Jira Service Managemant, вас запитають обрати шаблон для вашого першого сервісного проекту. В залежності від потреб вашої організації, ми запускаємо ваш сервісний проект зі звітами, типами запитів та іншими інструментами. Не хвилюйтесь, це жодним чином не обмежує вас, пізніше ви завжди можете сконфігурувати ваш проект.

 Історично існує різниця між сервісними проектами керованими на рівні компанії, та керованими на рівні команди. Нарзі документація не вісвітлює цю тему, принаймні не для Cloud.

 === Головні можливості Jira Service Management.
 
 Як тільки ви потрапили до вашого сервісного проекту, ви знайдете в ньому кіпу корисних можливостей. 

 ===== Черги
 
Черги це місце, де ваші агенти працюють з запитами клієнтів. Як адміністратор проекту, ви можете встановити та конфігурувати черги для сортування запитів до потрібних сервісних агентів. Ваші агенти зможуть переглядати та робити з ціма запитами в ваших чергах. 

Клієнтські запити організовані в черги. Черги дозволяють вам швидко переглядати, сортувати та призначати запити по мірі надходження. Вони також надають інформацію високого рівня щодо проблеми, зазвичай підсумок, статус та ім'я клієнта. Черги зазвичай сортуються за Service Level Agreement або цілі для взаємодії з вашою командою підтримки. Годинник на проблемі вказує час, доки не настане наступна ціль для вашої команди.

Ви можете використовувати заздалегідь сконфігуровані черги, або створити власні для вашого проекту. Власна черга дозволяє обрати ім'я черги, визначити, які запити будуть відфільтровані в цю чергу, та які стовбчики будуть з'являтись в черзі. Наприклад, ви можете мати ціль "час до першого реагування". Ваша черга преоритизує запити так, щоб  нагорі в списку опинились найбільш термінові завдання по цій цілі. Таким чином ми можемо сфокусуватись на найбільш важдивих запитах.

Ви можете створити до 50 черг на проект. Якщо ви вийдете за ці межі, розгляньте можливість поєднати черги, або видалити ті, Якими ви не користуєтесь.



 ==== Приборні панелі та звітами

 Використовуйте звіти для візуалізації трендів в ваших проектах. Адміністратори проектів також можуть встановити власні звіти, щоб знаходити власні тренди, що не відображені в звітах по замовчанню. 

 