:ascii-ids:
:doctype: book
:source-highlighter: pygments
:icons: font

link:https://www.digitalocean.com/community/tutorials/understanding-systemd-units-and-unit-files[Оригінал]

== Розуміння systemd unit та юніт файлів

=== Вступ

Все більше дистрибутиви Linux адаптують, або планують адаптувати, систему ініціалізації `systemd`. Ця потужна програмна сюїта може керувати багатьма аспектами вашого сервера, від сервісів до монтованих пристроїв та системних станів.

В `systemd` юніт посилається на любий ресурс, про який система знає, як з ним поводитись та керувати. Це первинний об'єкт, з яким має справу `systemd`. Ці ресурси визначаються з використанням файлів конфігурації, що мають назву юніт файлів.

В цій настанові ми представимо різні юніти, які може обробляти `systemd`. Ми також розглянемо деякі з багатьох директив, що можуть бути використані в юніт файлах, щоб окреслити спосіб, як ці ресури обробляються в вашій системі.

=== Що вам дають юніти Systemd?

Юніти є об'єктами, якими вміє керувати `systemd`. Це загалом стандартизоване представлення системних ресурсів, що можуть керуватись сюїтою демонів і маніпульовані наданими утілітами.

Юніти деяким чином подібні до сервісів або завдань в інших `init` системах. Однак юніт має значно ширше визначення, тому що вони можуть використовуватись для абстрактних сервісів, мережевих ресурсів, пристроїв, монтованих файлових систем, та ізольованих ресурсних пулів.

Ідеї, що можуть бути представлені в інших `init` системах уніфікованими визначеннями сервісів, можуть бути розбиті на юніт компоненти, відповідно до їх фокусування. Це організує за функцією і дозволяє легко вмикати, вимикати, або розширювати функціональність без модифікації базової поведінки юніта.

Ось деякі можливості, які можна легко реалізувати за допомогою юнітів:

**активація від сокетів*: Сокети, асоційовані з сревісом, поділяються самим демоном, щоб оброблятись окремо. Це надає декілька переваг, таких, як відкладання запуску сервісу до першого доступу до сервісу. Це також дозволяє системі створювати всі сокети раніше, в процесі завантаження, що дозволяє паралельно завантажувати асоційовані сервіси.

**активація від шини*: Юніти також можуть бути активовані на шинному інтерфейсі, що провадить D-Bus. Юніт може бути запущено, коли публікується асоційована шина.

**активація за шляхом*: Юніт може бути запущений за активністю або доступністю за певними шляхами файлової системи. Це використовує `inotify`.

**активація за пристроєм*: Юніти також можуть бути запущені за першої доступності асоційованого пристрою через використання подій udev.

**неявний меппінг залежностей*: Більшість дерева залежностей для юнітів може бути побудоване самим `systemd`. Але ви також можете додати інформацію щодо залежностей та впорядкування, але більшість важкої роботи вже виконані за вас.

**примірники та шаблони*: Шаблонні файли юнітів використовуються для створення декількох примірників того самого загального юніту.

**просте підсилення безпеки*: Юніти можуть реалізувати деякі досить гарні можливості безпеки через додавання простих директив. Наприклад, ви можете вказати відсутність доступу до частини файлової системи, або тільки на читання, обмежити можливості ядра та присвоїти приватний `/tmp` та доступ до мережі.

**дроп-іни та сніпети*: Юніти легко можуть бути розширені додаванням сніпетів, що перекривають частини системного юніт файла. Це спрощує перехід від штатної до власної реалізації юніта.

Є багато інших переваг юнітів `systemd` над елементами інших систем ініціалізації, але це має надати вам ідею тієї потужності, яку можна досягти, залучивши природні директиви конфігурації.

=== Де розташовані файли юнітів

Файли, що визначають, як `systemd` буде обробляти юніт, можуть розташовуватись в багатьох різних місцях, кожне з яких має різні преоритети та наслідки.

Системна копія файлів загалом знаходяться в системній директорії `/lib/systemd/system`. Коли програма встановлює файли юнітів в системі, це місце, де вони розташовуються по замовчанню.

Файли юнітів, що зберігаються тут, здатні запускатись і зупинятись на вимогу протягом сессії. Це буде загальний, штатний юніт файл, часто написаний службою підтримки проекта, і має робити на любій системі, що має `systemd` в своїй стандартній реалізації. Вам не треба редагувати файли в цій директорії. Замість цього ви маєте за потреби перекрити файл іншим юніт файлом в іншій локації, що перекриє цей файл.

Якщо ви бажаєте модифікувати спосіб, в який функціонує юніт, кращою локацією зробити це є директорія `/etc/systemd/system`. Файли юнітів в цій директорії мають перевагу над всіма іншими розташуваннями файлової системи. Якщо вам треба модифікувати системну копію юніт файла, покласти заміну в цей каталог є найбезпечнішим і найбільш гнучким шляхом зробити це.

Якщо ви бажаєте перекрити лише певні директиви системного юніт файла, ви насправді можете використати сніпети юніт файла в субдиректорії. Вони будуть доповнювати або модифікувати директиви в системній копії, дозволяючи вам вказувати тільки опції, які ви бажаєте змінити.

Коректний спосіб зробити це є створити директорію з назвою юніт файла, з доданим `.d` в кінці. Так що для юніта на ім'я `example.service` має бути створена субдиректорія  `example.service.d`. В цій директорії можна використати файл `.conf` для перекриття або розширення атрибутів системного юніт файла.

Також існує локація для рантайм визначень юнітів в `/run/systemd/system`. Юніт файли в цій директорії мають преоритет між файлами `/etc/systemd/system` та `/lib/systemd/system`. Файли з цім розташуванням менш вагомі ніж такі в першому місці, і більш вагомі ніж в останньому.

Сам процес `systemd` використовує це розташування для динамічно створених юніт файлів під час виконання. Ця директорія може бути використана для зміни поведінки системного юніта на протязі сессії. Всі зміни в цій директорії будуть втрачені при перезавантаженні сервера.

=== Типи юнітів

`Systemd` поділяє юніти відповідно до типу ресурса, який вони описують. Простіший спосіб визначити тип юніта є вказати суфікс типу, що додається в кінці імені ресурса. Наступний список описує типи юнітів, доступні в `systemd`:

*.service*: Юніт сервісу описує, як керувати сервісом або застосуванням на сервері. Це включає спосіб запуску та припинення сервісу, за яких умов він має бути автоматично запущений, та інформація про залежності та впорядкування для пов'язаних програм.

*.socket*: Юніт сокета описує мережу або сокет IPC, або FIFO буфер, які `systemd` використовує для сокет активації. Вони завжди мають асоційований файл `.service`, який буде запущено, коли на визначеному сокеті буде помічена активність.

*.device*: Юніт, що описує пристрій, визначений як той, що потребує керування `systemd` через `udev` або файловою системою `sysfs`. Не всі пристрої матимуть файли `.device`. Деякі сценарії, коли може знадобитись юніт `.device`, є впорядкування, монтування та доступ до пристроїв.

*.mount*: Цей юніт визачає точку монтування, що має керуватись `systemd`. Вони мають назви по шляхам монтування, з косими заміненими на мінуси. Елементи в `/etc/fstab` можуть мати юніти, створені автоматично.

*`.automount`*: Юніт `.automount` конфігурує точу монтування, що буде змонтована автоматично. Вони мають називатись як точки монтування, на які вони посилаються, і мати співпадаючий юніт `.mount` для визначення особливостей монтування.

*.swap*: Цей юніт описує простір свопа в системі. Ім'я ціх юнітів повинно відображувати пристрій або шлях до сховища.

*.target*: Таргетний юніт використовується для провадження точок синхронізації для інших юнітів при завантаженні або зміни стану. Вони також можуть використовуватись для приведення системи до нового стану. Інші юніти вказують своє відношення до таргетів, щоб прив'язатись до таргетних операцій.

*.path*: Цей юніт визначає шлях, який може використовуватись для активації за шляхом. По замовчанню буде запущений `.service` з тим самим базовим ім'ям, коли шлях набуде вказаного стану. Це використовує `inotify` для моніторінга шляху.

*.timer*: Юніт визначає таймер, що буде керуватись `systemd`, подібно до `cron` для відкладених та запланованих завдань. Співпадаючий юніт буде запущений, коли спрацює таймер.

*.snapshot*: Юніт `.snapshot` створюється автоматично командою `systemctl snapshot`. Це дозволяє вам відновити поточний стан після внесення змін. Снепшоти не зберігаються між сессіями, і використовуються для відкату тимчасових змін.

*.slice*: Юніт `.slice` асоційований з вузлами Linux Control Group, дозволяючи обмеження або надання ресурсів до любих процессів, асоційованих зі слайсами. Ім'я відображує ієрархічну позицію в дереві `cgroup`. Юніти покладаються в певні слайси по замовчанню, в залежності від їх типу.

*.scope*: Скоуп юніти створюються автоматично `systemd` з інформації, отриманої з шинних інтерфейсів. Вони використовуються для керування наборами системних процессів, що створені ззовні.

Як ви можете бачити, є багато різних юнітів, про які знає `systemd`. Багато з типів юнітів роблять разом для додавання функціональності. Наприклад деякі юніти використовуються для перемикання інших юнітів, і провадять функціональність активації.

Ми в основному сфокусуємось на юнітах `.service` через їх користь і узгодженість, з якою адміністратори мають керувати ціма юнітами.

== Анатомія юніт файла

Внутрішня структура юніт файлів організована як секції. Секції позначаються парами прямокутних дужок “[” та “]”, що оточують ім'я секції. Кожна секція подовжується до початку нової секції, або до кінця файлу.

=== Загальні характеристики юніт файлів

Назви секцій гарно визначені і враховують реєстр. Так що секція `[Unit]` не буде сприйматись коректно, якщо буде записане як `[UNIT]`. Якщо вам треба додати нестандартні розділи, що розбираються деінде крім `systemd`, ви можете додати префікс `X-` до назви секції.

В ціх секціях метадані та поведінка юніта визначаються через використання простих директив в форматі ключ-значення, зі знаком рівності в якості ознаки присвоєння, таким чином:

[source,config]
----
[Section]
Directive1=value
Directive2=value
. . .
----

В випадку перекриття файлів (що розташовані в директорії `unit.type.d`), директиви можуть бути скинуті через присвоєння до них порожнього рядка. Наприклад, системна копія юніт файлу може містити таку директиву:

[source,config]
----
Directive1=default_value
----

`default_value` може бути виключена в файлі перекриття, посилаючись на `Directive1` без значення:

[source,config]
----
Directive1=
----

Загалом, `systemd` дозволяє просту та гнучку конфігурацію. Наприклад, сприймаються декілька булевих виразів (`1`, `yes`, `on`, `true` для ствердження, та `0`, `no`, `off`, `false` для зворотнього). Час може бути інтелігентно розібраний, де значення без одиниць позначають секунди, та декілька форматів підтримуються природно.

=== Директиви секції [Unit]

Перша секція, що трапляється в більшості юніт файлів, є секція `[Unit]`. Вона в основному використовується для визначення метаданих для юніта, та конфігурації відношень юніта з іншими юнітами.

Хоча порядок секцій не має значення для `systemd` при розборі файлу, цей розділ часто розташовується зверху, оскільки він провадить огляд юніту. Деякі загальні директиви, що ви можете побачити в секції `[Unit]`:

**Description=*: Ця директива може бути використана для опису імені та базової функціональності юніта. Вона повертається різними інструментами `systemd`, так що гарно встановити її в дещо стисле, специфічне та інформативне.

**Documentation=*: Ця директива провадить розташування списку URI для документації. Це може бути вбудованими man сторінками, або доступні веб URL. Команда `systemctl status` буде показувати цю інформацію, дозволяючи просте дослідження.

**Requires=*: Ця директива перелічує любі юніти, від яких конче залежить цей юніт. Якщо поточний юніт активується, перелічені тут юніти також мають успішно активізуватись, інакше цей юніт схибить. По замовчанню ці юніти стартують паралельно з поточним юнітом.

**Wants=*: Ця директива подібна до `Requires=`, але менш сувора. `Systemd` буде намагатись запустити любі юніти, перелічені тут, при активації цього юніта. Якщо ці юніти не знайдені або не можуть стартувати, поточний юніт буде продовжувати роботу. Це рекомендований спосіб This is the recommended way to configure most dependency relationships. Again, this implies a parallel activation unless modified by other directives.

**BindsTo=*: Ця директива is similar to `Requires=`, but also causes the current unit to stop when the associated unit terminates.

**Before=*: The units listed in Ця директива will not be started until the current unit is marked as started if they are activated at the same time. This does not imply a dependency relationship and must be used in conjunction with one of the above directives if this is desired.

**After=*: The units listed in Ця директива will be started before starting the current unit. This does not imply a dependency relationship and one must be established through the above directives if this is required.

**Conflicts=*: This can be used to list units that cannot be run at the same time as the current unit. Starting a unit with this relationship will cause the other units to be stopped.

**Condition...=*: There are a number of directives that start with Condition which allow the administrator to test certain conditions prior to starting the unit. This can be used to provide a generic unit file that will only be run when on appropriate systems. If the condition is not met, the unit is gracefully skipped.

**Assert...=*: Similar to the directives that start with Condition, these directives check for different aspects of the running environment to decide whether the unit should activate. However, unlike the Condition directives, a negative result causes a failure with Ця директива.

Using these directives and a handful of others, general information about the unit and its relationship to other units and the operating system can be established.

[Install] Section Directives
On the opposite side of unit file, the last section is often the [Install] section. This section is optional and is used to define the behavior or a unit if it is enabled or disabled. Enabling a unit marks it to be automatically started at boot. In essence, this is accomplished by latching the unit in question onto another unit that is somewhere in the line of units to be started at boot.

Because of this, only units that can be enabled will have this section. The directives within dictate what should happen when the unit is enabled:

WantedBy=: The WantedBy= directive is the most common way to specify how a unit should be enabled. Ця директива allows you to specify a dependency relationship in a similar way to the Wants= directive does in the [Unit] section. The difference is that Ця директива is included in the ancillary unit allowing the primary unit listed to remain relatively clean. When a unit with Ця директива is enabled, a directory will be created within /etc/systemd/system named after the specified unit with .wants appended to the end. Within this, a symbolic link to the current unit will be created, creating the dependency. For instance, if the current unit has WantedBy=multi-user.target, a directory called multi-user.target.wants will be created within /etc/systemd/system (if not already available) and a symbolic link to the current unit will be placed within. Disabling this unit removes the link and removes the dependency relationship.
RequiredBy=: Ця директива is very similar to the WantedBy= directive, but instead specifies a required dependency that will cause the activation to fail if not met. When enabled, a unit with Ця директива will create a directory ending with .requires.
Alias=: Ця директива allows the unit to be enabled under another name as well. Among other uses, this allows multiple providers of a function to be available, so that related units can look for any provider of the common aliased name.
Also=: Ця директива allows units to be enabled or disabled as a set. Supporting units that should always be available when this unit is active can be listed here. They will be managed as a group for installation tasks.
DefaultInstance=: For template units (covered later) which can produce unit instances with unpredictable names, this can be used as a fallback value for the name if an appropriate name is not provided.
Unit-Specific Section Directives
Sandwiched between the previous two sections, you will likely find unit type-specific sections. Most unit types offer directives that only apply to their specific type. These are available within sections named after their type. We will cover those briefly here.

The device, target, snapshot, and scope unit types have no unit-specific directives, and thus have no associated sections for their type.

The [Service] Section
The [Service] section is used to provide configuration that is only applicable for services.

One of the basic things that should be specified within the [Service] section is the Type= of the service. This categorizes services by their process and daemonizing behavior. This is important because it tells systemd how to correctly manage the servie and find out its state.

The Type= directive can be one of the following:

simple: The main process of the service is specified in the start line. This is the default if the Type= and Busname= directives are not set, but the ExecStart= is set. Any communication should be handled outside of the unit through a second unit of the appropriate type (like through a .socket unit if this unit must communicate using sockets).
forking: This service type is used when the service forks a child process, exiting the parent process almost immediately. This tells systemd that the process is still running even though the parent exited.
oneshot: This type indicates that the process will be short-lived and that systemd should wait for the process to exit before continuing on with other units. This is the default Type= and ExecStart= are not set. It is used for one-off tasks.
dbus: This indicates that unit will take a name on the D-Bus bus. When this happens, systemd will continue to process the next unit.
notify: This indicates that the service will issue a notification when it has finished starting up. The systemd process will wait for this to happen before proceeding to other units.
idle: This indicates that the service will not be run until all jobs are dispatched.
Some additional directives may be needed when using certain service types. For instance:

RemainAfterExit=: Ця директива is commonly used with the oneshot type. It indicates that the service should be considered active even after the process exits.
PIDFile=: If the service type is marked as “forking”, Ця директива is used to set the path of the file that should contain the process ID number of the main child that should be monitored.
BusName=: Ця директива should be set to the D-Bus bus name that the service will attempt to acquire when using the “dbus” service type.
NotifyAccess=: This specifies access to the socket that should be used to listen for notifications when the “notify” service type is selected This can be “none”, “main”, or “all. The default, "none”, ignores all status messages. The “main” option will listen to messages from the main process and the “all” option will cause all members of the service’s control group to be processed.
So far, we have discussed some pre-requisite information, but we haven’t actually defined how to manage our services. The directives to do this are:

ExecStart=: This specifies the full path and the arguments of the command to be executed to start the process. This may only be specified once (except for “oneshot” services). If the path to the command is preceded by a dash “-” character, non-zero exit statuses will be accepted without marking the unit activation as failed.
ExecStartPre=: This can be used to provide additional commands that should be executed before the main process is started. This can be used multiple times. Again, commands must specify a full path and they can be preceded by “-” to indicate that the failure of the command will be tolerated.
ExecStartPost=: This has the same exact qualities as ExecStartPre= except that it specifies commands that will be run after the main process is started.
ExecReload=: This optional directive indicates the command necessary to reload the configuration of the service if available.
ExecStop=: This indicates the command needed to stop the service. If this is not given, the process will be killed immediately when the service is stopped.
ExecStopPost=: This can be used to specify commands to execute following the stop command.
RestartSec=: If automatically restarting the service is enabled, this specifies the amount of time to wait before attempting to restart the service.
Restart=: This indicates the circumstances under which systemd will attempt to automatically restart the service. This can be set to values like “always”, “on-success”, “on-failure”, “on-abnormal”, “on-abort”, or “on-watchdog”. These will trigger a restart according to the way that the service was stopped.
TimeoutSec=: This configures the amount of time that systemd will wait when stopping or stopping the service before marking it as failed or forcefully killing it. You can set separate timeouts with TimeoutStartSec= and TimeoutStopSec= as well.
The [Socket] Section
Socket units are very common in systemd configurations because many services implement socket-based activation to provide better parallelization and flexibility. Each socket unit must have a matching service unit that will be activated when the socket receives activity.

By breaking socket control outside of the service itself, sockets can be initialized early and the associated services can often be started in parallel. By default, the socket name will attempt to start the service of the same name upon receiving a connection. When the service is initialized, the socket will be passed to it, allowing it to begin processing any buffered requests.

To specify the actual socket, these directives are common:

ListenStream=: This defines an address for a stream socket which supports sequential, reliable communication. Services that use TCP should use this socket type.
ListenDatagram=: This defines an address for a datagram socket which supports fast, unreliable communication packets. Services that use UDP should set this socket type.
ListenSequentialPacket=: This defines an address for sequential, reliable communication with max length datagrams that preserves message boundaries. This is found most often for Unix sockets.
ListenFIFO: Along with the other listening types, you can also specify a FIFO buffer instead of a socket.
There are more types of listening directives, but the ones above are the most common.

Other characteristics of the sockets can be controlled through additional directives:

Accept=: This determines whether an additional instance of the service will be started for each connection. If set to false (the default), one instance will handle all connections.
SocketUser=: With a Unix socket, specifies the owner of the socket. This will be the root user if left unset.
SocketGroup=: With a Unix socket, specifies the group owner of the socket. This will be the root group if neither this or the above are set. If only the SocketUser= is set, systemd will try to find a matching group.
SocketMode=: For Unix sockets or FIFO buffers, this sets the permissions on the created entity.
Service=: If the service name does not match the .socket name, the service can be specified with Ця директива.
The [Mount] Section
Mount units allow for mount point management from within systemd. Mount points are named after the directory that they control, with a translation algorithm applied.

For example, the leading slash is removed, all other slashes are translated into dashes “-”, and all dashes and unprintable characters are replaced with C-style escape codes. The result of this translation is used as the mount unit name. Mount units will have an implicit dependency on other mounts above it in the hierarchy.

Mount units are often translated directly from `/etc/fstab` files during the boot process. For the unit definitions automatically created and those that you wish to define in a unit file, the following directives are useful:

What=: The absolute path to the resource that needs to be mounted.
Where=: The absolute path of the mount point where the resource should be mounted. This should be the same as the unit file name, except using conventional filesystem notation.
Type=: The filesystem type of the mount.
Options=: Any mount options that need to be applied. This is a comma-separated list.
SloppyOptions=: A boolean that determines whether the mount will fail if there is an unrecognized mount option.
DirectoryMode=: If parent directories need to be created for the mount point, this determines the permission mode of these directories.
TimeoutSec=: Configures the amount of time the system will wait until the mount operation is marked as failed.
The [Automount] Section
This unit allows an associated `.mount` для визначення особливостей монтування As with the .mount unit, these units must be named after the translated mount point’s path.

The [Automount] section is pretty simple, with only the following two options allowed:

Where=: The absolute path of the automount point on the filesystem. This will match the filename except that it uses conventional path notation instead of the translation.
DirectoryMode=: If the automount point or any parent directories need to be created, this will determine the permissions settings of those path components.
The [Swap] Section
Swap units are used to configure swap space on the system. The units must be named after the swap file or the swap device, using the same filesystem translation that was discussed above.

Like the mount options, the swap units can be automatically created from /etc/fstab entries, or can be configured through a dedicated unit file.

The [Swap] section of a unit file can contain the following directives for configuration:

What=: The absolute path to the location of the swap space, whether this is a file or a device.
Priority=: This takes an integer that indicates the priority of the swap being configured.
Options=: Any options that are typically set in the /etc/fstab file can be set with Ця директива instead. A comma-separated list is used.
TimeoutSec=: The amount of time that systemd waits for the swap to be activated before marking the operation as a failure.
The [Path] Section
A path unit defines a filesystem path that systmed can monitor for changes. Another unit must exist that will be be activated when certain activity is detected at the path location. Path activity is determined thorugh inotify events.

The [Path] section of a unit file can contain the following directives:

PathExists=: Ця директива is used to check whether the path in question exists. If it does, the associated unit is activated.
PathExistsGlob=: This is the same as the above, but supports file glob expressions for determining path existence.
PathChanged=: This watches the path location for changes. The associated unit is activated if a change is detected when the watched file is closed.
PathModified=: This watches for changes like the above directive, but it activates on file writes as well as when the file is closed.
DirectoryNotEmpty=: Ця директива allows systemd to activate the associated unit when the directory is no longer empty.
Unit=: This specifies the unit to activate when the path conditions specified above are met. If this is omitted, systemd will look for a `.service` file that shares the same base unit name as this unit.
MakeDirectory=: This determines if systemd will create the directory structure of the path in question prior to watching.
DirectoryMode=: If the above is enabled, this will set the permission mode of any path components that must be created.
The [Timer] Section
Timer units are used to schedule tasks to operate at a specific time or after a certain delay. This unit type replaces or supplements some of the functionality of the cron and at daemons. An associated unit must be provided which will be activated when the timer is reached.

The [Timer] section of a unit file can contain some of the following directives:

OnActiveSec=: Ця директива allows the associated unit to be activated relative to the .timer unit’s activation.
OnBootSec=: Ця директива is used to specify the amount of time after the system is booted when the associated unit should be activated.
OnStartupSec=: Ця директива is similar to the above timer, but in relation to when the systemd process itself was started.
OnUnitActiveSec=: This sets a timer according to when the associated unit was last activated.
OnUnitInactiveSec=: This sets the timer in relation to when the associated unit was last marked as inactive.
OnCalendar=: This allows you to activate the associated unit by specifying an absolute instead of relative to an event.
AccuracySec=: This unit is used to set the level of accuracy with which the timer should be adhered to. By default, the associated unit will be activated within one minute of the timer being reached. The value of Ця директива will determine the upper bounds on the window in which systemd schedules the activation to occur.
Unit=: Ця директива is used to specify the unit that should be activated when the timer elapses. If unset, systemd will look for a .service unit with a name that matches this unit.
Persistent=: If this is set, systemd will trigger the associated unit when the timer becomes active if it would have been triggered during the period in which the timer was inactive.
WakeSystem=: Setting Ця директива allows you to wake a system from suspend if the timer is reached when in that state.
The [Slice] Section
The [Slice] section of a unit file actually does not have any `.slice` асоційований з вузлами Instead, it can contain some resource management directives that are actually available to a number of the units listed above.

Some common directives in the [Slice] section, which may also be used in other units can be found in the systemd.resource-control man page. These are valid in the following unit-specific sections:

[Slice]
[Scope]
[Service]
[Socket]
[Mount]
[Swap]
Creating Instance Units from Template Unit Files
We mentioned earlier in this guide the idea of template unit files being used to create multiple instances of units. In this section, we can go over this concept in more detail.

Template unit files are, in most ways, no different than regular unit files. However, these provide flexibility in configuring units by allowing certain parts of the file to utilize dynamic information that will be available at runtime.

Template and Instance Unit Names
Template unit files can be identified because they contain an @ symbol after the base unit name and before the unit type suffix. A template unit file name may look like this:

example@.service
When an instance is created from a template, an instance identifier is placed between the @ symbol and the period signifying the start of the unit type. For example, the above template unit file could be used to create an instance unit that looks like this:

example@instance1.service
An instance file is usually created as a symbolic link to the template file, with the link name including the instance identifier. In this way, multiple links with unique identifiers can point back to a single template file. When managing an instance unit, systemd will look for a file with the exact instance name you specify on the command line to use. If it cannot find one, it will look for an associated template file.

Template Specifiers
The power of template unit files is mainly seen through its ability to dynamically substitute appropriate information within the unit definition according to the operating environment. This is done by setting the directives in the template file as normal, but replacing certain values or parts of values with variable specifiers.

The following are some of the more common specifiers will be replaced when an instance unit is interpreted with the relevant information:

%n: Anywhere where this appears in a template file, the full resulting unit name will be inserted.
%N: This is the same as the above, but any escaping, such as those present in file path patterns, will be reversed.
%p: This references the unit name prefix. This is the portion of the unit name that comes before the @ symbol.
%P: This is the same as above, but with any escaping reversed.
%i: This references the instance name, which is the identifier following the @ in the instance unit. This is one of the most commonly used specifiers because it will be guaranteed to be dynamic. The use of this identifier encourages the use of configuration significant identifiers. For example, the port that the service will be run at can be used as the instance identifier and the template can use this specifier to set up the port specification.
%I: This specifier is the same as the above, but with any escaping reversed.
%f: This will be replaced with the unescaped instance name or the prefix name, prepended with a /.
%c: This will indicate the control group of the unit, with the standard parent hierarchy of /sys/fs/cgroup/ssytemd/ removed.
%u: The name of the user configured to run the unit.
%U: The same as above, but as a numeric UID instead of name.
%H: The host name of the system that is running the unit.
%%: This is used to insert a literal percentage sign.
By using the above identifiers in a template file, systemd will fill in the correct values when interpreting the template to create an instance unit.

Conclusion
When working with systemd, understanding units and unit files can make administration simple. Unlike many other init systems, you do not have to know a scripting language to interpret the init files used to boot services or the system. The unit files use a fairly simple declarative syntax that allows you to see at a glance the purpose and effects of a unit upon activation.

Breaking functionality such as activation logic into separate units not only allows the internal systemd processes to optimize parallel initialization, it also keeps the configuration rather simple and allows you to modify and restart some units without tearing down and rebuilding their associated connections. Leveraging these abilities can give you more flexibility and power during administration.