include::headers.adoc[]

Часто задавані питання
======================

Маєте запитання щодо Lagom? Ми відібрали приклад часто задаваних питань, та инжче надаємо відповіді на них. Якщо ваше запитання не має відповіді тут, спробуйте ці ресурси:

* https://discuss.lagomframework.com/[*Дискусійний форум Lagom*]
* https://gitter.im/lagom/lagom[*Канал Lagom Gitter*]
* https://stackoverflow.com/questions/tagged/lagom[*Запитання щодо Lagom в Stack Overflow*]

Чи Lagom є відкритий код чи комерційний?
----------------------------------------

Lagom  повністю з відкритим кодом, вільний до використання, та має активну та зростаючу спільноту. Однак ви маєте опцію придбати підписку Lightbend, що провадить технічну підтримку, так само, як і ліцензію на використання Lightbend Enterprise Suite, що включає декілька потужних застосувань для керування, розумного моніторінгу та інструментів корпоративної інтеграції.

Чи Lagom потребує використання Cassandra для збереження?
--------------------------------------------------------
Ні, Lagom підтримує використання або Cassandra, або реляційних баз даних, включаючи MySQL, PostegreSQL, Oracle та H2. Середовище розробки Lagom провадить та використовує Cassandra по замовчанню, бо вона пропонує чудову маштабованість та можливості реплікації. Дивіться більше в https://www.lagomframework.com/documentation/current/java/PersistentEntity.html[Java документації] або https://www.lagomframework.com/documentation/current/scala/PersistentEntity.html[Scala документації].

Чи Lagom потребує використання брокера повідомлень, такого як Kafka?
--------------------------------------------------------------------
Ні, але він дуже корисний для загальних сценаріїв комунікації. Lagom Message Broker API інтегрує Persistent Entities з брокерами повідомлень, такими, як Apache Kafka, щоб запровадити публікацію і підписку на повідомлення між сервісами, з гарантіями доставки щонайменьше-раз. Це дозволяє вам розробляти розподілені та високо-стійкі системи мікросервісів.

Однак якщо ви обираєте не виконувати брокер повідомлень, Message Broker API є повністю опціональним. Ви можете писати Lagom сервіси, що комунікують один з одним напряму, використовуючи HTTP запити, або через надсилаючи дані в потоці через WebSocket.

Дивіться більше в https://www.lagomframework.com/documentation/current/java/MessageBroker.html[Java документації] або https://www.lagomframework.com/documentation/current/scala/MessageBroker.html[Scala документації].

Чи Lagom підтримує брокери повідомлень, крім Kafka?
---------------------------------------------------
Message Broker API був розроблений, щоб бути здатним інтегруватись з альтернативними сервісами брокерів повідомлень. Наразі Lagom включає підтримку тільки для Kafka, але просунуті користувачі можуть написати свої власні реалізації Message Broker API. Майбутні версій Lagom можуть включати нові, офіціально підтримувані реалізації.

Якщо ви зацікавлені в офіційній підтримці нових брокерів, будь ласка перегляньме https://www.lagomframework.com/documentation/current/scala/MessageBroker.html[запит нових можливостей Message Broker API] на GitHub. Ви можете голосувати або коментувати існуючі проблеми, або створити нові.

Чиs Lagom потребує використання джерела подій та CQRS?
------------------------------------------------------
В Lagom сервісі ви можете обробляти стійкість даних в любий спосіб, в який бажаєте, але ми дуже радимо джерела подій та CQRS, та Lagom Persistent Entity API розроблений для підтримки ціх шаблонів. Для сервісів, де ви не бажаєте використовувати джерела подій та CQRS, ви можете використовувати любий клієнт доступу до даних, доти, доки ви будете уважно уникати I/O блокування первинного пулу потоків, що може спричинити проблеми продуктивності та помилки таймаутів.

Lagom провадить утіліти, що можуть бути використані для неблокуючого виконання команд бази даних: `CassandraSession` (https://www.lagomframework.com/documentation/current/java/api/com/lightbend/lagom/javadsl/persistence/cassandra/`CassandraSession`.html[Java]/https://www.lagomframework.com/documentation/current/scala/api/index.html#com.lightbend.lagom.scaladsl.persistence.cassandra.CassandraSession[Scala]), JdbcSession (https://www.lagomframework.com/documentation/current/java/api/com/lightbend/lagom/javadsl/persistence/jdbc/JdbcSession.html[Java]/https://www.lagomframework.com/documentation/current/scala/api/index.html#com.lightbend.lagom.scaladsl.persistence.jdbc.JdbcSession[Scala]), and `JpaSession` (https://www.lagomframework.com/documentation/current/java/api/com/lightbend/lagom/javadsl/persistence/jpa/`JpaSession`.html[Java-only]). Користувачі Scala можуть бути зацікавленв в використанні http://slick.lightbend.com/[Slick] для реляційних баз даних. Проект https://developer.lightbend.com/docs/alpakka/current/[Alpakka] пропонує конектори Akka Streams для різноманітних сховищ даних, що може бути узгоджено використані з обома, Java та Scala різновидами Lagom. Багато не-реляційних баз даних пропонують свої власні, неблокуючі асинхронні клієнти, або офіційно, або через треті сторони.

Дивіться більше в документації Lagom щодо https://www.lagomframework.com/documentation/current/java/ES_CQRS.html[Керування стійкістю даних] та https://www.lagomframework.com/documentation/current/java/ESAdvantage.html[Переваги джерела подій].

Чи можливо використовувати інші методи серіалізації, крім JSON?
---------------------------------------------------------------
Так, Lagom підтримує розширену серіалізацію, абоє для повідомлень, переданих між різними сервісами, та для внутрішніх сервісів та стійких даних, що використовуються в сервісі. JSON підтримується по засовчанню, бо він простий та легкий для розуміння. Сервіси, що вимагають більшої продуктивності або більш компактних даних, можуть використовувати альтернативи, такі як https://developers.google.com/protocol-buffers/[Protocol Buffers], http://avro.apache.org/[Apache Avro], https://github.com/EsotericSoftware/kryo[Kryo], або любу іншу серіалізацію на вибір.

See more in the Lagom documentation on Message Serializers (https://www.lagomframework.com/documentation/current/java/MessageSerializers.html[Java]/https://www.lagomframework.com/documentation/current/scala/MessageSerializers.html[Scala]) and Persistent Entity Serialization (https://www.lagomframework.com/documentation/current/java/Serialization.html[Java]/https://www.lagomframework.com/documentation/current/scala/Serialization.html[Scala]).